### ISSUE TITLE
/ob/cases is not setting the paymentCoin and coinType

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1003]
All cases should include the `paymentCoin`. If the case is for a cryptocurrency listing, the it should also include the `coinType`.

Below is what I'm getting on a case for a crypto listing:

![image](https://user-images.githubusercontent.com/794517/42343098-d97d8526-804c-11e8-8241-fa9e3b6ca63d.png)

**Comment by jjeffryes** [comment]
@tyler-smith can this be closed?

**Comment by tyler-smith** [comment]
Yes.
