### ISSUE TITLE
Order states

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#101]
On the #openbazaar-2_0 Slack channel, @cpacia asks:

```
what do you think about these order states in 2.0:

0. Pending (new order, has not been accepted by the vendor)
1. Confirmed (vendor has accepted the order and is awaiting payment)
2. Funded (buyer has funded the order)
3. Fulfilled (vendor has shipped the order/sent the digital good)
4. Complete (buyer has closed the order, released the funds, sent the rating).
6. Disputed (under active dispute)
7. DisputeResolved (the dispute has been closed by the moderator, waiting for one of the parties to accept the payout)
8. DisputeClosed (the payout transaction has been broadcast, the dispute is over). 
9. Refunded (vendor closed the order and refuned the buyer)
```

My initial thoughts below:
1. This is a critical part of the protocol spec. Can we formalise it (e.g. into an OBIP)?
2. What are the state transitions? We need a state diagram to communicate the full story.
3. There are three parties (buyer, vendor, moderator) involved in an order. Do each of the parties have the exact same set of possible states? Seems unlikely given things are not perfectly symmetric across parties (e.g. see point 4. below).
4. It seems that state synchronisation has not been taken into account. For example, the buyer's order can be in state `Pending` while for the vendor it is in state `Confirmed`. The vendor then needs to communicate the confirmation, leading to the two substates `ConfirmedNotAcknowledged` and `ConfirmedAcknowledged` for the vendor.
5. What happens when an order is under-funded? Don't we need an `UnderFunded` state?
6. What happens when an order is over-funded? Don't we need an `OverFunded` state?
7. I was under the impression that the buyer and vendor can bilaterally decide to use a different moderator. Is that still part of the protocol?
8. I was under the impression that the moderator could split the amount in escrow between buyer and vendor. `DisputeResolved` mentions "waiting for one of the parties". It reads as if there is waiting involved; what are the wait states (e.g. `PayoutWaiting` and `PayoutAccepted`)?
9. Is there any difference between "online" and "offline" orders? For example, in the offline mode, how do the buyer and seller agree on exchange rates?
10. In the offline mode, do buyers have to wait for the seller to come back online before funding the order? That sounds like poor UX.
11. As part of the state transitions, it would be useful to have the automatic timeouts (if any) documented.

**Comment by cpacia** [comment]
These states are mostly just used to communicate to the client the state of the contract. This list isn't really a formal part of the protocol.

**Comment by JustinDrake** [comment]
An alternative implementation of the client (e.g. one by Duo Search) will have to communicate with the reference in an agreed upon way; it's essential for proper communication. As such, the order state diagram is part of the protocol.

What are your thoughts on points 2. onward?

**Comment by JustinDrake** [comment]
Forwarding @tyler-smith comment from Slack:

> I agree that at some point it should be more formalized and that it’s the kind of thing OBIPs are for. I’ll need more time think about the rest of thoughts/questions.
