### ISSUE TITLE
Listing API returns invalid JSON when quoting a field. 

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#102]
The listing POST API is returning the following error:

![image](https://cloud.githubusercontent.com/assets/794517/18109437/1ccd6624-6ec6-11e6-9c2f-7336d98dc8e8.png)

which is invalid JSON because `item` needs to be quoted with single quotes or have its double quotes escaped.

Expected Results:
The API returns valid JSON.

Also, I imagine this may be a scenario happening in other APIs. If so, can it also be addressed there please?

**Comment by cpacia** [comment]
@tyler-smith do you know how to deal with that? That string is an error message from the protobuf library.

**Comment by tyler-smith** [comment]
I think we should consolidate that message generation and do something like
```go
fmt.Fprintf(w, `{"success": false, "reason": "%s"}`, strings.Replace(err.String(), `"`, `\"`, -1))
```

**Comment by rmisio** [comment]
Why wouldn't you encode it in JSON which would handle more cases than just some non-escaped double quotes?

**Comment by tyler-smith** [comment]
Perhaps a better solution is:

```go
type jsonAPIError struct {
  Success bool `json:"success"`
  Reason string `json:"reason"`
}
```

Then render that.
