### ISSUE TITLE
markchatasread API returns 500 error

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1041]
@jjeffryes commented on [Mon Jul 23 2018](https://github.com/OpenBazaar/openbazaar-desktop/issues/1461)

ob/markchatasread is returning a 500 error and 
```
{
    "success": false,
    "reason": "sql: Scan error on column index 0: converting driver.Value type \u003cnil\u003e ('\u003cnil\u003e') to a int: invalid syntax"
}
```

The call appears to be correct, with the right peerID in the call. 

ex: http://localhost:4002/ob/markchatasread/QmcqJmESoxobiSJ4yppRmd4FAfxzgs2UTjBBqwJtjftKbC

**Comment by jjeffryes** [comment]
It looks like the messages are never being marked as read due to this bug, so all conversation messages have read: false.

It also seems to only return the error at the start of a new conversation. Should markchatasread be sent then?

**Comment by cpacia** [comment]
Unable to replicate

**Comment by jjeffryes** [comment]
Did you try it on a new conversation with two nodes that have never talked to each other? That's when I saw it.
