### ISSUE TITLE
Purchases end up in an errored state

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1044]
Twice now I've had a node throw this error when calling ob/purchases:

```
{
    "success": false,
    "reason": "sql: Scan error on column index 12: unsupported Scan, storing driver.Value type \u003cnil\u003e into type *string"
}
```

Once this happens, purchases will always return this error, and the node can't access it's purchases any more.

This happened after a payment was claimed by a vendor on an order from this node (as the buyer), I don't know if that's relevant to this error.

**Comment by tyler-smith** [comment]
After speaking with @jjeffryes this appears to have been the result bugs in migration 9 that have already been fixed, however it revealed that the migration is not including not-null constraints on the new columns like they should. That should be addressed.
