### ISSUE TITLE
Vendor rejected order, reason: Buyer's identity signature on contact failed to verify

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1067]
A few cases have caused a buyer to received the message `Vendor rejected order, reason: Buyer's identity signature on contact failed to verify` from the vendor after a purchase is made. Occurs intermittently.

Two recorded cases so far:
1. https://ob-1.slack.com/archives/C99JD2B7F/p1533183935000107
2. https://openbazaar.slack.com/archives/C02GYCJUZ/p1533559963000379

**Comment by placer14** [comment]
I should mention that I was able to verify this issue independently on a fresh BCH node using master when issue (1) was shared. First and second attempt worked without incident. Third attempt created the problem. Vendor and buyer were online for each other on each attempt.

**Comment by placer14** [comment]
We think this issue may be related to #1074. 🤞

**Comment by cpacia** [comment]
Closing for now. We can reopen if people still have an issue after upgrading.
