### ISSUE TITLE
Unable to use `gencerts`

### ISSUE THREAD

**Issue by lra** [OpenBazaar/openbazaar-go#1079]
Hi,

I'm trying to setup a remote `openbazaar-go` server with SSL enabled.

I generated the certs with `openbazaar-go gencerts --host=<myhost>` but it does not generate a fake CA cert like specified at https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/ssl.md

As I don't have to CA cert to add on my local system, I can't connect my local OB GUI to the remote server with SSL.

Am I missing something obvious? Let me know and I'll update the doc.

Thanks!

**Comment by cpacia** [comment]
Thanks. Will check it out. @tyler-smith you've used this command successfully before correct?

**Comment by cpacia** [comment]
I've had issues connecting to ssl but others have got it to work. I think it's likely an issue of the local environment. I'd like to get the client to accept a cert at some point and it would make this very easy.
