### ISSUE TITLE
No Connection after OB

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1083]
@atmotraxx commented on [Mon Aug 06 2018](https://github.com/OpenBazaar/openbazaar-desktop/issues/1506)

Brief Description: 
Chrome says ERR_NAME_NOT_RESOLVE after (sometimes while) using OB

Operating System:  Windows 10 Home
OpenBazaar version:  2.2.3 / 0.12.2
Hardware: Samsung Laptop (tested on two different machines 32Bit, 64Bit)

Reproducible: 
Always

Steps to reproduce:
1. Open OB2
2. Do something
3. Close OB2

Observed Behavior:
After using OB no more WLAN/LAN DNS resolution: Chrome says ERR_NAME_NOT_RESOLVE
It does not matter if it is a wired connection or wifi(wlan).

Expected Behavior:
All Internet connectivity should be untouched and working

Additonal:
Even after a restart the connection problems are present. My solution is: restart laptop, power off/on router

Kind regards 
Erik

**Comment by placer14** [comment]
@atmotraxx Can I assume you're using the bundled installation and have not customized your configuration in any way? Do you use any firewall infrastructure that you've disabled during your test? Our server shouldn't be doing anything to manipulate your network routing or DNS settings. It's possible something on your network is seeing unusual traffic created by our server and might be employing some "protection" on your computer. Routers and network appliances may also employ these filters or protection. Any of these things ring a bell for you? You might try running your test in a different physical setting (like an internet cafe) to see if the problem persists there.

**Comment by cpacia** [comment]
This happens to me when MDNS is turned on, but we turn it off by default. Have you changed any MDNS settings in the config file?

**Comment by atmotraxx** [comment]
thanks for your replies.
Yes, its the bundled windows installatiobn. i didn't change anything like MDNS.
i figured out that the problems do not occur when using OB through tor. So i'm ok with it. 
But i will check that MDNS an firewall stuff

Keep on gooing OB! I really like the concept!

Kind regards
Erik

**Comment by placer14** [comment]
🍻 Let us know if you'd like to troubleshoot your case further.
