### ISSUE TITLE
transaction_listener.go should should check for nil linkedAddress in input

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1112]
The `input.linkedAddress` may be nil if the send sent from an exotic script and the wallet was unable to parse it. There should be a nil check on the input address which `continue`s at the start of the loop to avoid a panic.

**Comment by cpacia** [comment]
Same for the address in the output side

**Comment by placer14** [comment]
It's likely I introduced this error. Apologies. I added LinkedAddress to a few which were missing them with the assumption that a given InputTransaction would always require one. I'm sure we could isolate a few of those changes if helpful.
