### ISSUE TITLE
Meta File Gets Corrupted

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1120]
Sometimes when updating or installing a node, the meta file becomes corrupted. Once this happens the node is unusable. 

"leveldb/storage: corrupted or incomplete meta file"

I've experienced this a number of times when testing, we have a user reporting it on Reddit now:

https://www.reddit.com/r/OpenBazaar/comments/8g2ao4/openbazaar_20_megathread_post_bugs/e4m67io/

**Comment by placer14** [comment]
We can fix this now with https://github.com/OpenBazaar/leveldb-repair 💪
