### ISSUE TITLE
Migration014.Up: duplicate column name: coin

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1123]
The conditions for creating the error are unclear. Need to triage and isolate the root cause for this issue.

```
13:35:01.047 [NOTICE] [repo/MigrateUp] Migrating repo to version 15
13:35:01.050 [ERROR] [repo/MigrateUp] duplicate column name: coin
duplicate column name: coin
exit status 1
```

source: https://ob-1.slack.com/archives/C9BCUCZ9P/p1534966546000100?thread_ts=1534860707.000100&cid=C9BCUCZ9P

**Comment by dmoonfire** [comment]
I'm not sure if it helps or what else it broke but this got me past the error.

```
sqlite3 mainnet.db .dump > old-mainnet.sql
mv mainnet.db old-mainnet.db
cat old-mainnet.sql  | sed "s@,'BTC'@@" | sed "s@, coin text@@" > new-mainnet.sql
cat new-mainnet.sql | sqlite3 new-mainnet.db
mv new-mainnet.db mainnet.db
```

There were four errors from failed index creation, I could have removed that but it ignored those. After the repo update, I checked and the columns showed back up with 'BTC' entries.

**Comment by placer14** [comment]
This is not occuring very often and may be related to mishandled test data around the time the migration was created. Closing unless we see an abundance of more reports.
