### ISSUE TITLE
Add goimports rule to linter in CI

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1156]
In order to improve the overall quality of the repo, we are enabling the linter within travis but required our code to be made compliant with the lint rules before enabling each ruleset.

See https://github.com/OpenBazaar/openbazaar-go/issues/1169 for steps to enable rules and run linter.

**Comment by tyler-smith** [comment]
This is really easy to do. We'll need a time when inflight changes are minimal to reduce impact of change conflicts.

Test branch with working goimports fixes + linter: https://github.com/OpenBazaar/openbazaar-go/compare/TS_goimports?expand=1
