### ISSUE TITLE
DRY-up jsonapi.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#116]
The file jsonapi.go has a lot of repeated code. For example, the line

> w.Header().Add("Content-Type", "application/json")

appears 33 times in just that file. jsonapi.go needs DRYying up.

**Comment by tyler-smith** [comment]
This is something I want to refactoring using a better router (ideally gocraft/web) when theres time but if it's an issue now feel free to fix it.
