### ISSUE TITLE
Bad form database initialisation

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#117]
In db.go, the initialisation code contains this

```
	if password != "" {
		sqlStmt = "PRAGMA key = '" + password + "';"
	}
```

This means that some passwords can mess up the database, in particular passwords with the character `"`.

**Comment by cpacia** [comment]
So what's the alternative, add a check that disallows passwords with those characters?

**Comment by JustinDrake** [comment]
I don't know the richness of the syntax and the best practices for SQL. (I've never worked with SQL.) My gut feel is that there must be a standard way of dealing with these "SQL injection-like" scenarios without disallowing certain characters. (In JavaScript it's common to use `encodeURIComponent()`.)

**Comment by cpacia** [comment]
Looks like a single quote in the password would need to be replaced with two single quotes.
