### ISSUE TITLE
Migrate wallets config

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1178]
Presumably we're going to be adding backup insight servers to the config? If so we will need to do a migration of the config file to handle that. Even if we are not doing that I believe some of the insight server urls will be changing and will need a migration for that anyway. 

This can be bundled with adding the ethereum config via migration.

**Comment by placer14** [comment]
Closing in favor of https://github.com/OpenBazaar/openbazaar-go/issues/1183
