### ISSUE TITLE
Create a web-relay mode

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1180]
Recently @cpacia created some [great documentation](https://github.com/OpenBazaar/webrelay/blob/master/docs/sending.md) for developers to use the web-relay. The web-relay sever allows nodes to publish their offline messages through them, which is ideal for browser-based and mobile node where this functionality is either too resource intensive or impractical.

For mobile servers, the use of this relay would be advantageous from a UX perspective, as publishing offline messages can take 20+ seconds. Mobile servers would fall back to publishing the offline message directly if the web-relay server went down.

- [ ] What we would like is the ability to enable the use of the web-relay in `openbazaard` with all the settings pre-configured + the DIY backup if the web-relay server is unavailable. 
- [ ] For mobile specifically, we would like to add the option for web-relay mode in `NodeConfig`.

**Comment by cpacia** [comment]
We're going in a different direction with this
