### ISSUE TITLE
Verify unique order transaction on ETH wallet

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1181]
Need to validate when ETH transactions to any given OB wallet needs to be appropriately associated with the right Order. Since all ETH txs are to the same Address, there needs to be another mechanism for identifying the intended Order to pay for.

Discussed putting this information as metadata for the transaction. 
Note: Need to understand what this UX flow looks like for external wallets destined for OB order payment.

Tasks:

- [ ] ChainCode deserialization example (@cpacia)
- [ ] PR supporting transaction callback change (@amangale)

**Comment by placer14** [comment]
Discussed deserializing the ChainCode out from ExtendedKey response. And adding the orderId to transaction callback.

**Comment by cpacia** [comment]
We've created a path forward with this
