### ISSUE TITLE
404 error on dispute resolution guidelines link

### ISSUE THREAD

**Issue by allen-munsch** [OpenBazaar/openbazaar-go#1182]
Is anyone else receiving a 404 on the following link that is part of the Desktop Client?

https://openbazaar.org/openbazaar-dispute-resolution-guidelines/

Image of UI area "Settings > Moderation":
- https://imgur.com/LBEkJvH

OpenBazaar2 Desktop Client
Version 2.2.5 (2.2.5)

**Comment by jjeffryes** [comment]
Thank you for letting us know about this. The page was left out when moving our site recently. It's fixed now.
