### ISSUE TITLE
Track API endpoint for each coin in CoinConfig

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1183]
Each coin should have a list of insight-compatible endpoints it should communicate with.

Requirements:
- The list will later be used for roundrobin failure so order should be significant.
- The endpoints should be captured as well-formed strings which are validated on startup by `url.Parse`
- The endpoint should be persisted in the current flatfile config for user editing purposes

To-Do:
- [x] Convert default config to produce a list of API endpoints for both mainnet and testnet for each coin (BTC, BCH, LTC, ZEC, and ETH)
- [x] Migrate existing configurations to use the provided lists of endpoints for each coin

API endpoint lists:

*BTC*
https://btc.api.openbazaar.org/api
*BCH*
https://bch.api.openbazaar.org/api
*LTC*
https://ltc.api.openbazaar.org/api
*ZEC*
https://zec.api.openbazaar.org/api
*ETH*
https://rinkeby.infura.io

*TBTC*
https://tbtc.api.openbazaar.org/api
*TBCH*
https://tbch.api.openbazaar.org/api
*TLTC*
https://tltc.api.openbazaar.org/api
*TZEC*
https://tzec.api.openbazaar.org/api
*TETH*
https://rinkeby.infura.io

**Comment by placer14** [comment]
Blockbook endpoints to date:
https://btc.blockbook.api.openbazaar.org/
https://ltc.blockbook.api.openbazaar.org/
https://zec.blockbook.api.openbazaar.org/
https://bch.blockbook.api.openbazaar.org/

Insight endpoints to date:
https://btc.insight.api.openbazaar.org/
https://ltc.insight.api.openbazaar.org/
https://zec.insight.api.openbazaar.org/
https://bch.insight.api.openbazaar.org/

Can you confirm that these are the tentative endpoints for each type, @tyler-smith ?

**Comment by cpacia** [comment]
I believe this is done.
