### ISSUE TITLE
Additional fields in the notification response for orders

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1188]
A typical order related notification looks like this:

```JSON
{
  "notifications": [
    {
      "notification": {
        "buyerHandle": "das_test",
        "buyerId": "QmVLRA8hzADMwYDxXXFgHf2i9bbmbcm9WQHVojeAensNcR",
        "notificationId": "QmUh2aupaEoudW5feEFeyGmturjSDWxpfdDnzKeuZhx4rR",
        "orderId": "QmZwQbg4XPCRqFqWhDw4Z1694jpD7GjdxuxCebkXpwP2t7",
        "slug": "vintage-dress-physical-w-options2",
        "thumbnail": {
          "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
          "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz"
        },
        "title": "Vintage dress (physical; w/ options)",
        "type": "order"
      },
      "read": false,
      "timestamp": "2018-06-08T00:36:16Z",
      "type": "order"
    }
  ],
  "total": 123,
  "unread": 122
}
```

There are two issues:

1. Currently, we have to make a separate API call (`GET /ob/order/{orderId}`) to fetch the *price* of the item from the order notification. This is a problem for mobile as we have this design for displaying order-related notifications:

![image](https://user-images.githubusercontent.com/3887694/45936390-1ed77a00-bff9-11e8-91c2-02d2d40f7d98.png)

Having to make an GET /ob/order API call just to fetch the price is wasteful and adds unnecessary overhead.

2. It is impossible to tell from this notification alone whether or not the node is the buyer or seller. We have to add additional logic in a client to check against the node's own peerId against the `buyerId` to determine whether or not they are the seller.

---

I propose that we:

- [x] Add a `price` object, with the `value` and `currencyCode` to the order notification
- [ ] Add a field called `vendor`, which is a boolean to denote whether the node is the seller or not. (We are breaking this out into another issue since the scope is not clear yet. See #1230)

**Comment by placer14** [comment]
@drwasho Can you show an example of what these fields would look like when implemented? Curious about the diff between value and price. Additionally, how about putting the vendorID into the payload and the user can compare their own VendorID to either the Vendor or the Buyer ID to see which party they are to this transaction?

**Comment by drwasho** [comment]
> Can you show an example of what these fields would look like when implemented?

Sure thing, the only thing I changed was to use `buyer` instead or `vendor` for the boolean value.

```
{
  "notifications": [
    {
      "notification": {
        "buyerHandle": "das_test",
        "buyerId": "QmVLRA8hzADMwYDxXXFgHf2i9bbmbcm9WQHVojeAensNcR",
        "notificationId": "QmUh2aupaEoudW5feEFeyGmturjSDWxpfdDnzKeuZhx4rR",
        "orderId": "QmZwQbg4XPCRqFqWhDw4Z1694jpD7GjdxuxCebkXpwP2t7",
        "price": {
          "amount": 10,
          "currencyCode": "USD",
          "modifier": 0
        },
        "slug": "vintage-dress-physical-w-options2",
        "thumbnail": {
          "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
          "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz"
        },
        "title": "Vintage dress (physical; w/ options)",
        "type": "order",
        "buyer": true
      },
      "read": false,
      "timestamp": "2018-06-08T00:36:16Z",
      "type": "order"
    }
  ],
  "total": 123,
  "unread": 122
}
```

>  Additionally, how about putting the vendorID into the payload and the user can compare their own VendorID to either the Vendor or the Buyer ID to see which party they are to this transaction?

The goal here is to prevent the client from needing to check against the value of their own `peerID`, which they have to do now. They should just be able to tell from the notification whether or not they're the buyer => which will determine whether or not we fetch the buyer's profile to display in the notifications view.

**Comment by placer14** [comment]
Agreed with @drwasho that the price item would be represented as
```
"price": {
          "amount": 1000,
          "currencyCode": "eth",
          "priceModifier": 0.0,
          "coinDivisibility": 100000000
        },
```
where `amount` represents the quantity of the smallest divisible unit of the currency represented in `currencyCode`. `priceModifier` represents the same value present on the listing metadata when the listing type is `CRYPTOCURRENCY`, it represents the markup of the listing's sale price over market value, and defaults to `null`. `coinDivisibility` is the same value present on the listing metadata and indicates the smallest amount of the currency that can be represented.

The role of the node will be represented by the `role` field so the client is informed which party this user represents on the transaction.

Example:
```
{
  "notifications": [
    {
      "notification": {
        "buyerHandle": "das_test",
        "buyerId": "QmVLRA8hzADMwYDxXXFgHf2i9bbmbcm9WQHVojeAensNcR",
        "notificationId": "QmUh2aupaEoudW5feEFeyGmturjSDWxpfdDnzKeuZhx4rR",
        "orderId": "QmZwQbg4XPCRqFqWhDw4Z1694jpD7GjdxuxCebkXpwP2t7",
        "price": {
          "amount": 1000,
          "currencyCode": "eth",
          "priceModifier": 0.0,
          "coinDivisibility": 100000000
        },
        "slug": "vintage-dress-physical-w-options2",
        "thumbnail": {
          "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
          "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz"
        },
        "title": "Vintage dress (physical; w/ options)",
        "type": "order",
        "role": "buyer"
      },
      "read": false,
      "timestamp": "2018-06-08T00:36:16Z",
      "type": "order"
    }
  ],
  "total": 123,
  "unread": 122
}
```

**Comment by placer14** [comment]
Looking further, it appears that the `order` websocket notification is only ever received by the vendor. Can you confirm @drwasho that it is still required? The desktop team has also requested the listing type to be included. You can expect `listingType: "SERVICE"` or similar in the response.

**Comment by placer14** [comment]
Final example of schema:
```
{
  "notifications": [
    {
      "notification": {
        "buyerHandle": "das_test",
        "listingType": "SERVICE",
        "buyerId": "QmVLRA8hzADMwYDxXXFgHf2i9bbmbcm9WQHVojeAensNcR",
        "notificationId": "QmUh2aupaEoudW5feEFeyGmturjSDWxpfdDnzKeuZhx4rR",
        "orderId": "QmZwQbg4XPCRqFqWhDw4Z1694jpD7GjdxuxCebkXpwP2t7",
        "price": {
          "amount": 1000,
          "currencyCode": "eth",
          "priceModifier": 0.0,
          "coinDivisibility": 100000000
        },
        "slug": "vintage-dress-physical-w-options2",
        "thumbnail": {
          "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
          "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz"
        },
        "title": "Vintage dress (physical; w/ options)",
        "type": "order"
      },
      "read": false,
      "timestamp": "2018-06-08T00:36:16Z",
      "type": "order"
    }
  ],
  "total": 123,
  "unread": 122
}
```

**Comment by drwasho** [comment]
Sorry @placer14 I missed your earlier comment. 

- Listing type is awesome, thanks to the desktop team.

> Looking further, it appears that the order websocket notification is only ever received by the vendor.

Is this also true for the REST response, I assume it is? There are other order-related notifications such as disputes (and I think a notification requiring the buyer to release funds and leave a review) where I really need to know the role of node for that order, so if it's not too much trouble could we please include `role`?

**Comment by placer14** [comment]
No problem, @drwasho. The scope of this issue was only for the `order` websocket notification. I don't know about the REST response or the other notifications and prefer not to inflate the scope here (let's discuss that separately from this). Can we agree that the `order` websocket does not require `role` and that 1188 is complete?

**Comment by placer14** [comment]
Resolved with @drwasho with additional discussion moved to #1230
