### ISSUE TITLE
Adjust network timeout for mobile to shorter period

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1191]
To reduce lag in waiting for slow nodes to respond, we will reduce the network timeout for a direct message to be delivered. This network timeout should only affect the mobile server configuration.

TBD: what the new timeout should be? 10 seconds? @cpacia ?

**Comment by rmisio** [comment]
> 10 seconds?

Is there a risk then that 95% of messages will fail?

If they fail, is there a retry process?

**Comment by placer14** [comment]
There's always a risk of failure for every timeout value because this value optimizes between the two extremes of highly-available nodes responding quickly and a responsive UI when the node is not available. We can make a more robust retry method but it would need to be something which retries after the offline message is sent and also doesn't block the UI. Certainly something to discuss, but as a short term solution which would only affect the mobile server this seems like a simple test we can try.

**Comment by drwasho** [comment]
10 seconds is still pretty long for mobile... is there a way we might make this configurable in the mobile package so I can drop down the timeout to 5 seconds?

**Comment by rmisio** [comment]
So does this work where it tries to send an online message for this amount of time and if that fails, it gets delivered as an offline message?

**Comment by drwasho** [comment]
@rmisio speaking for mobile, the node will try and send an online message to the peer (and in most cases fail), before trying to send an offline message; that process takes 30 seconds... and if I understood @cpacia correctly, that 30 seconds is the timeout (as sending the offline message is done in a separate goroutine in the background).

For mobile, reducing it to 5 seconds is probably ok... but ideally this is something we can configure specifically for mobile, as other clients won't have this problem.

**Comment by placer14** [comment]
Merged.
