### ISSUE TITLE
Discrepancy in order.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#120]
order.go has the following [line of code](https://github.com/OpenBazaar/openbazaar-go/blob/a4cccb1cf10d24e3976d48c067607c219d2b2cce/core/order.go#L57):

> AlternateContact string `json:"alternateContactInfo"`

Why is there a naming discrepancy between `AlternateContact` and `alternateContactInfo`?

**Comment by cpacia** [comment]
The name on the left is used internally. It just left it like that because it's shorter.
