### ISSUE TITLE
Previous CountryCode protobuf change breaks backward compatibility

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1207]
Existing listings which ship to all regions will have `SWAZILAND` enumerated in the listing itself. It will probably exist in prior orders and should remain compatible. (Bug created in https://github.com/OpenBazaar/openbazaar-go/pull/1175).

Resolution requires:
- [ ] Enable `allow_alias = true` feature of Protobuffers can Unmarshal `212` to `ESWATINI` while still accepting `SWAZILAND` as a value being Marshaled. This should be proven in a unit test. (https://developers.google.com/protocol-buffers/docs/proto#enum)

 - or -

- [ ] Bumping the listing version number so all future generated/updated listings have the new value.
- [ ] Creating migration to transform existing listings which include `SWAZILAND` in the CountryCodes portion and replace it with `ESWATINI` and increase the version number to match the recently bumped value. Migration should be unit tested as well.

In addition...

- [ ] the commit which causes this bug was reverted in `master` until we get this resolved. We need to reapply https://github.com/OpenBazaar/openbazaar-go/commit/d24c39044df4ab48e8b9e03c6ac38290dd744c09 as part of this fix as well.

Calling `POST /ob/estimatetotal` against [this listing](https://gateway.ob1.io/ipfs/zb2rhXdiuRc5GhfmnvP35DTQNur3cGRUBfL3WNNSF3ZKHEkJd) should produce the error as shown in the screengrab.
![image 2](https://user-images.githubusercontent.com/305332/46451565-e5bfa800-c764-11e8-966f-483fe566dc82.png)

Note: A development environment is provided via Docker and Docker Compose to allow easy compilation of protobufs. After docker is installed, you can run `docker-compose run --entrypoint "make protos" dev` and it will build the dev environment and compile the protobufs in place. `docker-compose down --rmi all -v` will remove all of the built up docker infrastructure on your computer if you want to get rid of it.

**Comment by placer14** [comment]
We would prefer to use the `allow_alias` feature to permit ingesting a CountryCode of `SWAZILAND` if it encodes to 212 and then back to `ESWATINI` when unmarshalled again. I am concerned that unmarshalling from 212 back to the new string cannot be performed deterministically. If it's randomly changing between values it would not allow us to deprecate the old representation. At that point I would recommend pursuing the migration. Please prove in a test (on play.golang.org even) that this unmarshalling is deterministic over many attempts before delivering a PR with the `allow_alias` feature enabled.

**Comment by placer14** [comment]
Note that https://github.com/OpenBazaar/openbazaar-go/commit/d24c39044df4ab48e8b9e03c6ac38290dd744c09 was reverted in master and must be reapplied as part of this fix.

**Comment by allen-munsch** [comment]
@placer14 

I was actually just looking into this.

Couple things on `allow_alias` changes:

```
pb.CountryCode_name
212: "SWAZILAND",
// Duplicate value: 212: "ESWATINI",

pb.CountryCode_value

"SWAZILAND":                   212,
"ESWATINI":                    212,

pb.CountryCodes

CountryCode_SWAZILAND                      CountryCode = 212
CountryCode_ESWATINI                       CountryCode = 212
```

- `pb.CountryCode_name` comments out the 2nd alias.
- `pb.CountryCode_value` keeps both values
- `pb.CountryCodes` also has both values

I've been trying to figure out how best to run the tests on the changed pb files.

I have been trying something like this (note i was getting a 404 on  the wget for bitcoin-0.16.x):

```
docker-compose run --entrypoint "bash -cv 'cd qa && bash runtests.sh /go/src/github.com/OpenBazaar/openbazaar-go/openbazaar-go /opt/bitcoin-0.17.0/bin/bitcoind'" dev
```

I've also tried runnning the changes locally with, but have't been able to find the location of `.cookie`:

```
go run openbazaard.go setapicreds
go run openbazaard.go start
```

And I might be able to `cherry-pick` #1187 based on the revert.

**Comment by placer14** [comment]
@allen-munsch I'm rebuilding the image to check on that 404. 

The QA tests are not an unreasonable way to verify, but they give false negatives that often disappear when the single test is run in isolation. I would be satisfied with passing unit tests via `./test_compile.sh`.

By default, ob without specifying the data path of the config will in the path as described in [this article](https://openbazaar.zendesk.com/hc/en-us/articles/115002761312-How-do-I-backup-my-store-). You'll find `.cookie` in there. Alternatively, the `setapicreds` command will allow you use the provided user/pass with Basic HTTP Auth via curl or provided via the desktop UI's server config screen.

I think a good unit test would be two independent examples showing a `pb.Listing_ShippingOption` which contains a CountryCode of either `SWAZILAND` or `ESWATINI` and proving both examples marshal and unmarshal to `ESWATINI`.

**Comment by allen-munsch** [comment]
@placer14 cool, i'll go the unit test route. but also thank you i was able to test the API from the linked reading. I'll see if I can get the tests done asap ( hopefully by tomorrow sometime )

```
go run openbazaard.go start -v -d ~/Desktop/dev/ob_data

curl -vi --cookie "`cat ~/Desktop/dev/ob_data/.cookie`" http://localhost:4002/ob/listings
```

**Comment by placer14** [comment]
@allen-munsch BTW, the 404 is due to the 0.16.0 release being upgraded to 0.16.3. You can manually change the version in your `Dockerfile.dev`. I'll see that it gets [updated in the repo](https://github.com/OpenBazaar/openbazaar-go/commit/3e1d3209444e68985657327f64c7153108d08cf6). Thanks for the tip. 🍻
