### ISSUE TITLE
Missing checks in order.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#121]
See the shipping checks done [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/order.go#L896). Emptiness checks for `postalCode` and `country` are missing.

**Comment by cpacia** [comment]
The countrycode needs a nil check. @drwasho didn't you say you wanted them to have the option to not enter a postal code in shipping?

**Comment by jjeffryes** [comment]
Only name and country should be required, as I recall.

**Comment by drwasho** [comment]
Yeah some locations don't have a postcode.

**Comment by cpacia** [comment]
The nil check is actual there when shipsTo is checked.
