### ISSUE TITLE
Fix our vendored ipfs-go package

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1215]
The repo is currently vendoring all of it's dependencies. One of the deps is `github.com/ipfs/ipfs-go`. We have modified this package to enable some work arounds required for ob-go. These changes are captured in `github.com/OpenBazaar/ipfs-go`. @cpacia previously attempted to reference our forked package in `OpenBazaar/ipfs-go` inside our import statements without success indicating there were many compilation conflicts between each version of the ipfs-go package and their dependencies. We would like to get this cleared up so we can rebase our changes onto upstream `ipfs/ipfs-go` more easily, isolate (and eventually minimize) our delta with the upstream repo, and correctly reference the actually used package throughout our project.

Due to the wide-reaching impact of this change, it must be carefully coordinated to ensure changes required from this issue do not impede the work in other issues. While this technical debt is painful, it is lower priority than current objectives. Any work/exploration must be applied quickly or risk being ditched. That said, any thoughts on approaching would be welcome.

My personal preference would be to abstract our IPFS package usage with a thin abstraction in `github.com/OpenBazaar/openbazaar-go/ipfs` such that there are no dependencies exposed outside of this abstraction. This would probably make fixing references to our fork much much easier.

*NOTE: This issue requires high coordination with the OB1 development team. Please do not start work on this without being in touch with the team first (on https://openbazaar.org/slack/ or within this issue). Thank you.

**Comment by cpacia** [comment]
We are 90% of the way to getting off of using a fork of go-ipfs. After the next release we should be 100% there.
