### ISSUE TITLE
Calling POST /ob/estimatetotal with garbage causes app panic

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1218]
Found in #1206.

The API does not protect against bad data sent to `/ob/estimatetotal`. An example of this can be achieved with `curl username:password@<HOST:PORT>/ob/estimatetotal -d '{"items":[{"listingHash":"zb2rhaJGKkQkQdPXL84teyCwKG5Mk8ukWRhgfM95fZbwUHRWd","quantity":1,"options":[]}],"moderator":"","paymentCoin":"BCH"}'`

This endpoint should be hardened to reject invalid or missing params. The following body represents the params expected by this endpoint, and an example of what this request was trying to process:
```
github.com/OpenBazaar/openbazaar-go/core.PurchaseData {
	ShipTo: "",
	Address: "",
	City: "",
	State: "",
	PostalCode: "",
	CountryCode: "",
	AddressNotes: "",
	Moderator: "",
	Items: []github.com/OpenBazaar/openbazaar-go/core.item len: 1, cap: 4, [
		(*github.com/OpenBazaar/openbazaar-go/core.item)(0xc42012b440),
	],
	AlternateContactInfo: "",
	RefundAddress: *string nil,
	PaymentCoin: "BCH",
}
```

**Comment by cpacia** [comment]
Which field called the panic?

**Comment by placer14** [comment]
`contract, err := n.createContractWithOrder(data)` returns an invalid contract based on that input which has an nil `contract.BuyerOrder.Payment`. It panics when it accesses `contract.BuyerOrder.Payment.Coin` on `./core/order.go:770`

**Comment by placer14** [comment]
Fix to prevent panic in https://github.com/OpenBazaar/openbazaar-go/commit/eecc98e93fefb82a1bcb32ceb28a18d19e6887c6
