### ISSUE TITLE
What is the commenting style?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#122]
Comments are a bit messy. Sometimes they start with a capital, sometimes not. Sometimes they end with a dot, sometimes not. What is the commenting style to be followed in `openbazaar-go`?

**Comment by cpacia** [comment]
What do you want it to be?

**Comment by JustinDrake** [comment]
My personal preference is for comment fragments to start with a capital and end with no dot. If the comment is one or more full sentences (a sentence has at least a subject and a verb) then the sentences should end with a dot. Sounds good?

**Comment by cpacia** [comment]
That works

**Comment by morebrownies** [comment]
Keep in mind we have many languages to consider

**Comment by JustinDrake** [comment]
@morebrownies What do you mean? Are you referring to some error messages that may need translating, or inline code comments?

**Comment by morebrownies** [comment]
Nevermind, I thought you were referring to user reviews. I misread.
