### ISSUE TITLE
Duplicate currencies when saving via /ob/profile

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1220]
When saving the profile, additional currencies are appended to the profile. The action should not duplicate the items and should instead be idempotent.

Example request:
`curl 'http://0.0.0.0:4002/ob/profile/QmVVdnd8vyUfrmWwFqytr9PYQyxasRQAoG9Azp1B728ug5' -X PUT -H 'Content-Type: application/json' --data-binary '{"about":"","handle":"","location":"","moderator":false,"name":"A change #2","nsfw":false,"shortDescription":"","vendor":true,"colors":{"primary":"#FFFFFF","secondary":"#ECEEF2","text":"#252525","highlight":"#2BAD23","highlightText":"#252525"},"contactInfo":{"website":"","email":"","phoneNumber":"","social":[]},"peerID":"QmVVdnd8vyUfrmWwFqytr9PYQyxasRQAoG9Azp1B728ug5","bitcoinPubkey":"0239e7c045191195324c4c96909c3c15aac92571c6110cc9a1546a9ff017414bd2","currencies":["BTC","BCH","ZEC","LTC"]}' --compressed`

Example response:
```
{
    "peerID": "QmVVdnd8vyUfrmWwFqytr9PYQyxasRQAoG9Azp1B728ug5",
    "handle": "",
    "name": "A change #2",
    "location": "",
    "about": "",
    "shortDescription": "",
    "nsfw": false,
    "vendor": true,
    "moderator": false,
    "contactInfo": {
        "website": "",
        "email": "",
        "phoneNumber": "",
        "social": [
        ]
    },
    "colors": {
        "primary": "#FFFFFF",
        "secondary": "#ECEEF2",
        "text": "#252525",
        "highlight": "#2BAD23",
        "highlightText": "#252525"
    },
    "bitcoinPubkey": "0239e7c045191195324c4c96909c3c15aac92571c6110cc9a1546a9ff017414bd2",
    "lastModified": "2018-10-10T13:26:38.536429800Z",
    "currencies": [
        "BTC",
        "BCH",
        "ZEC",
        "LTC",
        "ZEC",
        "LTC",
        "BTC",
        "BCH"
    ]
}
```

**Comment by jjeffryes** [comment]
The currency codes are also duplicated in profile.moderatorInfo. For example, my test node returns this in it's profile when it's a moderator:

```
"moderatorInfo": {
                "acceptedCurrencies": [
                    "BTC",
                    "BCH",
                    "ZEC",
                    "LTC",
                    "BCH",
                    "ZEC",
                    "LTC",
                    "BTC",
                    "ZEC",
                    "LTC",
                    "BTC",
                    "BCH"
                ],
```

**Comment by drwasho** [comment]
Can confirm.

**Comment by rmisio** [comment]
I can also confirm it seems to be adding to the list rather than replacing it. For example, `PATCH /ob/profile/<guid>` with `{"vendor":true,"currencies":["TZEC","TBCH"]}` results in a subsequent `GETProfile` with the following result:

```
    "currencies": [
        "TZEC",
        "TBCH",
        "TBTC",
        "TBCH",
        "TZEC",
        "TLTC"
    ]
```

The expected result would be:

```
    "currencies": [
        "TZEC",
        "TBCH",
    ]
```

**Comment by rmisio** [comment]
@placer14 @cpacia Was this one fixed? I'm still experiencing it on the latest `mutliwallet` branch. After a few Profile saves, I end up with this hideous thing:

```
        "acceptedCurrencies": [
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC",
            "BTC",
            "BCH",
            "ZEC",
            "LTC"
        ],
```

**Comment by placer14** [comment]
Yeah, [this PR](https://github.com/OpenBazaar/openbazaar-go/pull/1259) was submitted but has been reviewed/merged. Let me get it unblocked.

**Comment by rmisio** [comment]
@placer14 does it also handle the currency list in the `moderatorInfo` object?

**Comment by placer14** [comment]
@rmisio This was two weeks ago, but I seem to recall confirming it did.
