### ISSUE TITLE
API calls where messages are sent to offline stores exceeding intended timeouts 

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1224]
@placer14 [recently committed some code](https://github.com/OpenBazaar/openbazaar-go/commit/37a31e2e1b8654f55f087bfe7ca217bd3cfec026) to reduce the timeout period, for mobile servers, where the node will attempt to send an online message to a peer to 5 seconds. If the timeout is hit, an offline message will be sent via a background goroutine, and any API should return an immediate `200` response while the message is sent in the background.

I was testing this out by trying to send a `POST /ob/follow` API call to `QmTmCkNLUcPGvf3mSYDme4UQudgn9oCVqE13GHnrF6sjLj` (who I confirmed was offline). The call took `64833 ms` to return a response. This seems to indicate that the timeout isn't working as intended in mobile and perhaps desktop (where the timeout should be 30 seconds).

**Comment by placer14** [comment]
Planning to instrument the network connectivity in the IPFS packages. Need to discuss with @cpacia where would be most ideal to instrument for this.

**Comment by placer14** [comment]
Found some opportunities to improve the timeout handling. Going to try these fixes and see if it improves...

**Comment by drwasho** [comment]
What's the latest here @placer14 ?

**Comment by placer14** [comment]
@drwasho I didn't get to finish cleaning it up, but maybe you can try the branch `WIP_1224_timeout_messaging` I just uploaded and see if this isn't improved for you? It builds and should timeout properly now.

**Comment by placer14** [comment]
Update: @drwasho has reported improvement but there are still cases where following causes approx 65 seconds before timeout. Investigation continues into root-causing the source of this intermittent problem. Local reproduction of the event only occurs maybe 5-10% of the time so testing solutions are not quick to confirm.

**Comment by placer14** [comment]
![image 5](https://user-images.githubusercontent.com/305332/52227497-b1c4d280-287d-11e9-9c45-549a1a2e11a0.png)
Another instance as reported by @drwasho

**Comment by drwasho** [comment]
Sorry to report another one @placer14:

![image](https://user-images.githubusercontent.com/3887694/52617499-cc372580-2ee7-11e9-8bb4-6ecdc11eb21c.png)

This one was a bit extreme, being 115 seconds, but the fastest I've seen an offline chat message sent is ~60-65 seconds.

**Comment by cpacia** [comment]
This should be fixed
