### ISSUE TITLE
Insight server bugs

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1232]
NOTE: This was turned into an EPIC. The contents needs to changed into separate issues and used to track individual, external issues. If you find a new insight bug, please open a new issue and reference this issue. Thanks!

---
TO BE MOVED:

I thought I might create a catch-all issue to report problems we come across testing the Insight server:

- [ ] 1. BCH Insight server doesn't appear to detect any UTXOs.. I have funds at a certain address, but the balance returns `0`
- [ ] 2. Sending Zcash returns the following error:

![image](https://user-images.githubusercontent.com/3887694/47052884-c78a8b00-d1ed-11e8-8649-d21372c3a118.png)

Despite receiving a 404 error on the transaction from the server, the wallet history records that it is an unconfirmed transaction:

```JSON
{
    "count": 3,
    "transactions": [
        {
            "address": "",
            "canBumpFee": true,
            "confirmations": 0,
            "errorMessage": "",
            "height": 0,
            "memo": "",
            "orderId": "",
            "status": "UNCONFIRMED",
            "thumbnail": "",
            "timestamp": "2018-10-17T09:17:11.647166844+10:00",
            "txid": "9bc4ed677d08947827fc4b3160b02a1a5a21ca4699af8af4535d4835c9d494b1",
            "value": -1771787
        }
  ]
}
```

If you look at a third party explorer, this transaction doesn't exist... and indeed after some time, the wallet history drops this record.

**Comment by drwasho** [comment]
For the Bitcoin Cash Insight server, we're currently using https://bitcoincash.bitcoin.com, which frequently displays this error:

![image](https://user-images.githubusercontent.com/3887694/47053228-59df5e80-d1ef-11e8-8762-e956d0d8dbd1.png)

So we need to switch to something more reliable asap.

**Comment by cpacia** [comment]
We're using blockbook now :p
