### ISSUE TITLE
<bits/stdc++.h> what is it used for?

### ISSUE THREAD

**Issue by gubatron** [OpenBazaar/openbazaar-go#1236]
anyway to get rid of this dependency or use something similar that works out of the box in non-Linux compilers?

[Fun time on macOS](https://discuss.codechef.com/questions/81564/bitsstdch-does-not-work-in-mac-os)

**Comment by cpacia** [comment]
where is this dependency used?

**Comment by tyler-smith** [comment]
It's probably used in a library that is used by sqlcipher. I never had an issue like this on OSX so it's probably a different lib version than I had; perhaps a newer one.

**Comment by gubatron** [comment]
oh shoot, my bad guys, wrong repo!

**Comment by tyler-smith** [comment]
Well, if it's affecting our users because of our dependence on sqlcipher I think we should still treat it as our issue.
