### ISSUE TITLE
"Posts" Requirements Epic

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1248]
- User can publish new content in a Post.
    - ~User can include images and formatting in content.~
        - ~Q: OBIP indicates images are linked suggesting they are not included in the body. Are we not putting images inline? No.~
        - ~Q: Are formatting/images allowed in the status? No rich formatting expected.~
    - User can post only title for short content.
    - User can post title with long-form body for large content.
- Posts can attached Tags with a folksonomy.
- Posts can be included in "channels" (which are different from tags but ALSO an folksonomy).
    - Q: How is this different from Tags?
- Posts are timestamped at the time they are published/edited.
- Posts are editable and deletable.
- ~Post history is traversable.~ (This is more about traversing a series of posts, not traversing a single post's changelog.)
- User can view Posts from others (or their own).
    - Collection of Posts and Reposts can be viewed by PeerID in a list (without associated comments.)
        - All content for collection included.
    - Single Posts and Reposts can be viewed by slug including associated comments and reposts.
        - Q: Do we need to show who reposted the content or posted the comment?
    - Content from others can be hidden.
        - Q: What is the effect of hiding for the local user. Is this the same as blocking a peerID but only for one post? Local blacklist that hides the content in local view?
- Interactions with the content are tracked with the content.
	- Comments are counted.
		- Q: Can reposts have comments or are comments appended to the original content? (Commands are applied to the content which received the action (and not the original).)
	- Reactions (Likes) are counted. (Concern?: Reactions/Like actions are not data on the network and are communicated to a specific endpoint.)
	- Reposts are counted. (Concern: Repost counts are going to be lost just like Reaction counts (which are solved by posting a Like to a specific endpoint available from the crawler.)
- Interactions produce notifications. (Note: these interactions are displayed alongside the Follow/Unfollow notifications.)
	- Repost notification indicates who, when, and the title of the original content.
	- Comment notification indicates who, when, and the content of the comment.
	- Reaction notification indicates who, when, and the title of the original content.
- Posts can be indexed by search providers.
    - Q: What is indexed?
    - Q: Are we mirroring content that falls off the network? (High content loss could create bad UX.)

**Comment by drwasho** [comment]
Many of these questions are answered in the issue I created for the PR: https://github.com/OpenBazaar/openbazaar-go/issues/1235

**Comment by placer14** [comment]
I think the "channels" concept is an overloaded version of "tags" and is still not clear to me what use case requires them to be separate. Your example from the PR:

> For example, one could imagine a channel called `sneakers`. [...] I am selling Yeezy Boost 700 "Wave Runner" sneakers. To promote my content, I'd publish posts with channel addresses like `sneakers`, `sneakerheads` etc, and tag my post with `700 "Wave Runners"` or `Australia` (to try and get the attention of Australian buyers).

My counter example would be to put all of those strings into tags. My example gives the same benefits and no drawbacks that I see. I can construct a view which only shows content with tags `sneakers` AND `australia` for consumption purposes. Or just one or the other. And promotion using tags vs channels is unclear why I'd choose one or the other. Seems I could promote a "tag" just as easily as I could a "channel address".

**Comment by drwasho** [comment]
Not sure what you looked at in Weibo, but here's how they do it:

In this feed, the 'category' is set to `Movie`. Weibo crawls all the posts made on their network and creates predefined categories.

Individual posts can be tagged with a `topic` that doesn't influence whether or not they end up in a specific category.

<img src="https://user-images.githubusercontent.com/3887694/47402319-5700e280-d788-11e8-9e3a-5a841f682a67.png" width="300" />

The difference between what Weibo is doing and what I'm proposing is that the content found in `categories` (`channels` in our case) is user-defined in that a user can select where their post can be addressed to. Adding `tags` to the post allows for more granular filtering of posts by a `tag` within a channel.

This is an example of how a user picks a category in Weibo:

<img src="" width="https://user-images.githubusercontent.com/3887694/47402460-05a52300-d789-11e8-93b4-e14cecb23beb.png" />

**Comment by drwasho** [comment]
I think we can probably close this @placer14
