### ISSUE TITLE
Use camelcase for JSON

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#125]
The file params.go has the following [line of code](https://github.com/OpenBazaar/openbazaar-go/blob/master/api/params.go#L48)

> ShortDescription string `json:"short_description"`

The JSON convention is to use camelcase, so `shortDescription`.

**Comment by cpacia** [comment]
@hoffmabc created this file. Are we doing anything with this brian or should we get rid of it?

**Comment by hoffmabc** [comment]
I guess we can just dump it if we are not using the commenting system.
