### ISSUE TITLE
Add Field to Skip Online Send for Relayed Messages

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1253]
When a message is sent from a source using a relay node, currently the receiving node attempts to send response messages to the original sender. If the sender can only receive messages through the relay node, this results in a delay while the server tries to send an online message that can't ever be received.

It would be ideal to allow the sender to set a flag to let the recipient node know that it should not send an online message back when communicating with that node. This is most important in chat.

The receiving server would remember the flag, and skip sending online messages to that node until it received the same flag from that node with the opposite value.

**Comment by cpacia** [comment]
We're taking the pure IPFS route not and not the relay server.
