### ISSUE TITLE
1 Satoshi missing from LTC order payment

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1274]
I have an order for a listing requiring `987980` in order to fund:

```
            "payment": {
                "method": "ADDRESS_REQUEST",
                "moderator": "",
                "amount": 987980,
                "chaincode": "",
                "address": "",
                "redeemScript": "",
                "coin": "LTC"
            },
```

I call `/wallet/spend/` with that amount:

```
{"feeLevel":"NORMAL","memo":"","address":"LUTbVq25FTtNmJuZCnLG89SugjZNmmf2TC","amount":987980,"wallet":"LTC"}
```

But, the payment that ends up bing applied to the order ends up a Satoshi short:

```
    "paymentAddressTransactions": [
        {
            "txid": "3fd0cd350f87fccef29306959c9e84792d91eaa70d51fccce1aa7577bd27c360",
            "value": 987979,
            "confirmations": 0,
            "height": 0,
            "timestamp": "2018-11-01T22:43:15.834950Z"
        }
    ]
```

resulting in minuscule underpayment:

![image](https://user-images.githubusercontent.com/794517/47928001-84d1df80-de8a-11e8-8a82-387e6d4b2919.png)

**Comment by rmisio** [comment]
Also, 1 sat is below the dust amount, so essentially an order in that state becomes unfundable.

**Comment by rmisio** [comment]
This just happened again after not happening for 20+ orders. Not sure what the trigger is because I'm pretty much doing the same thing for all orders, including buying the same product. Maybe something is happening on the insight end?

**Comment by cpacia** [comment]
The amount that was paid in the transaction was correct. The amount that was shown as paid to the UI was off by one. Either the insight server returned the wrong value or there was some kind of rounding error converting it.

**Comment by rmisio** [comment]
> The amount that was shown as paid to the UI was off by one. Either the insight server returned the wrong value or there was some kind of rounding error converting it.

Ok, but in either case it's something we need to rectify because the UX is horrible in this case. The order becomes unfundable and the buyer needs to ask the vendor to refund or mod to rule in their favor and then make another order hoping it doesn't happen again.

**Comment by hoffmabc** [comment]
If it’s a bug with insight we need to know. Keep us posted.

**Comment by hoffmabc** [comment]
Did you post a bug fix for this @cpacia?

**Comment by cpacia** [comment]
fixed
