### ISSUE TITLE
Order appears to have swept wallet

### ISSUE THREAD

**Issue by tyler-smith** [OpenBazaar/openbazaar-go#1279]
From @rmisio 

> wow, this is quite alarming. As part of my testing, I’ve just been buying the same $12 product over and over. For some reason, my last purchase of the $12 product last night just drained my wallet  of it’s remaining $461 worth of TBTC.

[Screenshot](https://i.imgur.com/cN6dfL1.png)

> Also, even though the order is returned via `http://localhost:4002/ob/purchases`, when I try and get it’s details via `http://localhost:4002/ob/order/Qmf5LY83FQzHaVzvjcTQDPx4MduaXvsMY8si8JWskDgiWS`, it returns `Not found`.
Th only thing I did different with this order is that a dispute was opened, the escrow expired and I attempted to have the vendor claim funds a few times, which keeps failing with some type of broadcast error.

[Transaction on blockexplorer](https://www.blocktrail.com/tBTC/tx/35fb823354eeed6ea2d4ca0cba00efa0d7d81293b8f39c4a8c3e90c6dd56b7fe)

**Comment by rmisio** [comment]
Here's some more details. On the `GETOrder` payload, the payment does appear to be for the correct amount. Not sure what the second, negative, payment is for. This was a direct order.

```
    "paymentAddressTransactions": [
        {
            "txid": "ea7639deed10afc86b4c2f2a65cc9a2bae170f1dc672be2655901080eb62d0a3",
            "value": 938040,
            "confirmations": 380,
            "height": 1521864,
            "timestamp": "2018-11-05T22:29:18.857295Z"
        },
        {
            "txid": "d9519116a632a40718461adfc1d621e9fce78216d1c24580870dde1df474852e",
            "value": -1876080,
            "confirmations": 2,
            "height": 1522242,
            "timestamp": "2018-11-06T14:22:45.067268Z"
        }
    ]
```

In the wallet transactions, however, the amount is not correct for the same `txid`.

```
        {
            "address": "LbEYvSKw9ykFoc4ESd8ssa6Ucifd71TgSD",
            "canBumpFee": false,
            "confirmations": 378,
            "errorMessage": "",
            "height": 1521864,
            "memo": "big pickle time",
            "orderId": "QmdzEP1JDZ7GJjpGiSgatPi2RrfTceaf26BLung3o1yXWE",
            "status": "CONFIRMED",
            "thumbnail": "zb2rhYN33LsirsxFq7QhpQMmN4ftwske95tjSRuDuvbxZSrLf",
            "timestamp": "2018-11-05T16:31:00-06:00",
            "txid": "ea7639deed10afc86b4c2f2a65cc9a2bae170f1dc672be2655901080eb62d0a3",
            "value": -7125859
        },
```

**Comment by rmisio** [comment]
FWIW, if I add up the transactions in my wallet to determine what the balance should be, it did take out the $3.87 (wrong inflated amount) from my wallet.

**Comment by rmisio** [comment]
Happened again to me. Happening pretty regularly now.

**Comment by jjeffryes** [comment]
Since we haven't seen this happen for 3 months now, I think it's safe to close it.

**Comment by placer14** [comment]
Decided to remove insight support until some later date. Closing issue.
