### ISSUE TITLE
Incomplete refund data for the buyer

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1280]
After issuing a refund, the vendor has the complete `refundAddressTransaction` data returned via GETOrder:

```
    "refundAddressTransaction": {
        "txid": "b78b4d9f861f72b73884495de6a78ad842883b2e82631e44797e5a1c070b5fd0",
        "value": 937806,
        "confirmations": 2,
        "height": 1521846,
        "timestamp": "2018-11-05T21:53:50.410037Z"
    }
```

whereas the buyer does not:

```
    "refundAddressTransaction": {
        "txid": "",
        "value": 0,
        "confirmations": 0,
        "height": 0
    }
```

(this was observed on an order made on LTC mn - haven't tested it with the other coins yet)

**Comment by cpacia** [comment]
Looks like the other side never received the socket notification on the order.

**Comment by rmisio** [comment]
No it did, because thats what the client uses to know to re-fetch the order data. So, the buyer gets the socket , refreshes and a refund of $0 ends up appearing. Prior to the refund the `refundAddressTransaction` isn't even in the order. Afterwards, it shows up with incomplete data.

**Comment by cpacia** [comment]
By socket I mean socket from the insight server.

**Comment by placer14** [comment]
Leaving this open to make sure this isn't an issue with blockbook (or simply a bug in ob-go).

**Comment by cpacia** [comment]
Pretty sure this was just a missed socket from the wallet server. I just tested and both sides got the correct information.
