### ISSUE TITLE
Funds show up in the wallet balance without a corresponding transaction

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1283]
`/wallet/balance`:

```
   "BTC": {
        "confirmed": 155826,
        "height": 549031,
        "unconfirmed": 0
    },
```

`/wallet/transactions/BTC?limit=25`:

```
{
    "count": 0
}
```

**Comment by placer14** [comment]
Today, (using 99e559ba5aacebc2117c3a4e9728af3beb2fa664) I have been able to import a mnemonic with 46 transactions in the history and it appears to accurately show the transactions and balance in LTC.

**Comment by placer14** [comment]
Let's reopen this if we can confirm a new case now that we're using blockbook.

**Comment by rmisio** [comment]
> Today, (using 99e559b) I have been able to import a mnemonic with 46 transactions in the history and it appears to accurately show the transactions and balance in LTC.

Well, to be clear, I never took that approach to reproduce the bug. I believe the way I was doing it was that I would send funds into a node and the balance would be updated, yet the transaction wouldn't be in the list.

It may well have been a race condition where the API was giving notice of a new balance before sending over it's corresponding transaction. FWIW, if the time between the two was seconds, I probably wouldn't have logged the bug. It was likely minutes and/or the transaction never showed.

**Comment by rmisio** [comment]
> Let's reopen this if we can confirm a new case now that we're using blockbook.

that's fine.
