### ISSUE TITLE
The latest Docker image for `openbazaar/server:latest` is v0.11.0-rc5 not v0.12.4

### ISSUE THREAD

**Issue by dmoonfire** [OpenBazaar/openbazaar-go#1285]
I noticed that when using `openbazaar/server:latest` it was pulling an old version of the server down. The front end complained about it not being 0.12.x. I think it would make sense to have these relatively in sync instead of needing someone to specifically enter the version number when installing fresh.

Thank you.

**Comment by tyler-smith** [comment]
Yeah we need to get the automated builds working. I've pushed v0.12.4.

I've created #1286 to track adding Docker builds to Travis.
