### ISSUE TITLE
Blockbook Websocket Provides Change Instead of Spends

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1304]
When I sent $1 in LTC out of a total of $3.62 directly from the wallet, when the transaction arrived over the socket it showed the change transaction of +$2.62 instead of the outgoing transaction of -$1.

The timestamp was also "49 years ago."

After a few minutes the change transaction disappeared, and was replaced by the correct outgoing transaction with the correct timestamp.

This is using the TS_blockbook branch.

**Comment by jjeffryes** [comment]
A little more data: resyncing seems to show the correct spends, but calling wallet/transactions/[coin] still shows the change transactions instead of the spends.

**Comment by cpacia** [comment]
Fix the timestamp bug

**Comment by cpacia** [comment]
Looks like the other bug has been fixed as well.
