### ISSUE TITLE
A transaction should not be created until it successfully broadcasts

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1305]
Steps:
- spend some LTC

Observed:
While the Spend call is pending, a wallet socket comes with a new transaction and GET transactions returns it as well. Then if the spend fails to broadcast, you're left with this ghost transaction.

It's also really weird that you see an alert for a new transaction while you're still looking at a spinner on the spend call. So essentially the UI is displaying a new transaction while the spend is still pending.

It also gives a lot of confusion to the user since they don't know it's a "ghost" transaction. For all they know, it will succeed at one point since it's in the list. So... I was asking myself should I or should I not try the spend again. Of course, if I try it again and it fails again, I get another ghost in the list.

Expected:
The new transaction is not created unless the spend successfully completes.

**Comment by tyler-smith** [comment]
We should still track the tx in the db so we'll need to just mask those out of the GET transactions call or maybe put them behind a flag.

**Comment by rmisio** [comment]
Actually according to CP, the transaction will be retried. But then this is an incredibly confusing UX and we need to discuss how to communicate this state to the user.

Some suggestions:
- The spend should return a special error code so the UI doesn't treat this as a standard error.
- The transaction in the transaction list maybe gets a unique state so the user could tell it is a ghost transaction that will probably be retried at some point
- Maybe a manual retry button in case the user doesn't want to wait on the server

It's also incredibly weird that the transaction comes while the Spend process is still happening. So, user click `Send`, 2 seconds later they get a pop-in `1 new transaction` and the transaction then appears in the list, all while the `Send` button still has a spinner and 30 seconds later the user gets a "failed to broadcast" error message. We should probably delay that new transaction until after the Spend call completes and will probably have to give some custom messaging after it "fails".

**Comment by rmisio** [comment]
It's even more confusing if you Pay for and order and that transaction fails to broadcast, since other than an error message everything looks like that payment work to you:

![image](https://user-images.githubusercontent.com/794517/48870860-0345e100-eda8-11e8-98a0-6573266cfee0.png)

This UX would lead to a lot of scenarios where the buyer is claiming they paid and the vendor sees nothing, because in fact, there's no blockchain transaction. It's just the node is masquerading as if there is one.

**Comment by placer14** [comment]
As decided in our meeting, the transaction record can be persisted after being broadcast and accepted into the mempool. This change was completed as part of https://github.com/OpenBazaar/multiwallet/issues/36 and updated in ob-go in 
https://github.com/OpenBazaar/openbazaar-go/pull/1338. Hopefully this satisfies the UX concerns in this issue. Please reopen if something has been overlooked.
