### ISSUE TITLE
How does a buyer node request a status update about an order?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#131]
What happens if a buyer node makes a request but, for some reason, never gets a `ORDER_ACCEPTANCE` or `ORDER_CONFIRMATION`? Is there a message the buyer can send to the seller asking for the state of his order?

**Comment by cpacia** [comment]
A chat message. Get's routed into the order.

**Comment by JustinDrake** [comment]
I'm worried about those missed messages scenarios that arise because of bugs. We've seen these happen for moderation in OB1.0 where manual intervention was required to the database of the buyer or seller.

**Comment by tyler-smith** [comment]
It would be nice for UX if they could request the current status so the client can issue the request when loading an order it hasn't seen an update for in a while if it's expecting one. This seems like a good addition to the protocol imo.
