### ISSUE TITLE
BTC wallet cannot syncUtxos

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1340]
The output from https://btc.blockbook.api.openbazaar.org/api/utxo/1Hdp6CapjAH9cD3etjVQLGqx2Xm35nfPLb is failing with `[multiwallet/syncUtxos] Error downloading utxos for Bitcoin: json: cannot unmarshal object into Go value of type []model.Utxo` when Washington starts his OB server.

Payload appears to be missing `Address` and `PubKeyScript`. Unsure of the impact that has on `util.CalcBalance` but it's probably a bug that needs looking at.

**Comment by cpacia** [comment]
This should be completely fixed now. I believe the blockbook server has been updated and I'm not seeing this error on mainnet using master.
