### ISSUE TITLE
go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:149:28: undefined: math.Round

### ISSUE THREAD

**Issue by agd-media** [OpenBazaar/openbazaar-go#1348]
This is new: When I download with 
 go get github.com/OpenBazaar/openbazaar-go
 following error (3 instances)  shows up:
go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go:149:28: undefined: math.Round

Same happens when I start the server deamon.

**Comment by placer14** [comment]
`openbazaar-go` recently updated its required go version to be 1.10.1 or greater. If you update to at least that version and use that for your build, this problem should go away.
