### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by agilob** [OpenBazaar/openbazaar-go#1374]
Could you please add documentation how to use docker server? https://hub.docker.com/r/openbazaar/server 

Which port do I need to expose, do I need any volumes added?

**Comment by placer14** [comment]
Sorry about that. I'll see that some docs get added. To answer your questions:
Exposing ports `4001, 4002, and 9005` should be enough.
Vollumes are not required, but `/var/lib/openbazaar` is used for storing your configuration and state. You can mount an external config to that path if you wish to keep that outside of the running container.

**Comment by raisty** [comment]
Documentation will be very helpful. Please.
I try to connect to DigitalOcean, but what is default username and password?
Where I can find/define/change it?

**Comment by bill-mcgonigle** [comment]
I'm getting this straightened out in my Puppet class for ob too.  Is this right?

4002 - OB client RPC
4001 - OB IPFS data/swarm
9005 - OB IPFS control/websockets

**Comment by tyler-smith** [comment]
@bill-mcgonigle The 4002 is HTTP RPC (just to be explicit). 4001 and 9005 are essentially the same protocol but over different transports. Raw TCP (4001) and websockets (9005).

**Comment by tyler-smith** [comment]
@raisty There is no default username/password. You have to [set it in your config file](https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/security.md#api-authentication).
