### ISSUE TITLE
GETOrder for contract with missing payment.coin causes failure

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1395]
When processing a contract whose `buyerOrder.payment.coin` is missing or empty (`""`) does not allow the correct wallet to be loaded. The origination of the missing value is unknown, but the GETOrder could be changed to use the `paymentCoin` field from the Purchase/Sale datastore row. 

Example payment occurring in both the buyer and the seller's nodes:
```
"payment": {
            "method": "DIRECT",
            "moderator": "",
            "amount": 1644,
            "chaincode": "a4a85e6514cf98cb97335d06f6d01608eec0bdf23d69dad184bcf55e9a36a2ae",
            "address": "bc1qd2gjygmrsl7muwvx427hg7xqwakrl6m7xty0vzv75q80ekqcs4wsdrzr4d",
            "redeemScript": "5121022a47723cf373681b2749c0f79b7249adb42da60a556b1613e89b0812a6f82a8421021b6760ee997bdfe453e77b92f32f67c9fc6d06570946de39db53f0531bd444bd52ae",
            "coin": ""
        },
```

**Comment by placer14** [comment]
Looking at a 2.2.3 dataset, the contract does not appear to be touched at all. Though the contract is missing the value here, the problem is only exposed in this case due to GETOrder not getting the Purchase/Sales `paymentCoin` value set in the table.

The backtrace looks like this:
```
0  0x0000000000da3578 in github.com/OpenBazaar/openbazaar-go/vendor/github.com/OpenBazaar/multiwallet.(*MultiWallet).WalletForCurrencyCode
   at ./vendor/github.com/OpenBazaar/multiwallet/multiwallet.go:115
1  0x0000000000e7b5a1 in github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).BuildTransactionRecords
   at ./core/utils.go:74
2  0x0000000000f61f9a in github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).GETOrder
   at ./api/jsonapi.go:1653
3  0x0000000000f50f98 in github.com/OpenBazaar/openbazaar-go/api.get
   at ./api/endpoints.go:155
4  0x0000000000f53300 in github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP
   at ./api/jsonapi.go:169
```

We can begin passing this value separately into `BuildTransactionRecords` but it seems more concerning that the contract is not in the correct state for this method to work.

**Comment by placer14** [comment]
Updating issue to indicate failure as a result of malformed or incomplete contract. There are no migrations which touch those fields. There is likely some other root cause and will track that separately.

**Comment by cpacia** [comment]
fixed
