### ISSUE TITLE
Feature request: Build source with go get

### ISSUE THREAD

**Issue by mtlynch** [OpenBazaar/openbazaar-go#14]
It is currently not possible to build openbazaar-go with `go get`. This hampers development because it makes it difficult to set up CI tools like Travis, Coveralls, and godocs. It also creates a barrier to entry to new developers who would like to contribute

It would be great if a contributor could download and build just by running:
```bash
go get -u github.com/OpenBazaar/openbazaar-go/...
```

**Comment by cpacia** [comment]
Once the zmq dependency is removed it should be able to be installed that way.

**Comment by JustinDrake** [comment]
What are the steps to installing zmq?

**Comment by cpacia** [comment]
http://zeromq.org/intro:get-the-software

**Comment by cpacia** [comment]
Closing this issue. It can mostly be installed with go get, but it does require you have openssl installed as well. There's no getting around that one.
