### ISSUE TITLE
Add path hint detection for Migration014

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1403]
Add path hinting when setting the `migrations.WalletCoinType` (https://github.com/OpenBazaar/openbazaar-go/blob/master/cmd/start.go#L212) in case the user did not run the migrations in version 2.2.5 (server v0.12.4) and went straight to version 2.3 (server v0.13.0).

It should detect if the config path used the pre-2.3 defaults for --bitcoincash and --zcash directories and use that to infer the original currency of the node. If the config path doesn't match either directory, then allow the existing as default behavior.

**Comment by cpacia** [comment]
closed by #1404
