### ISSUE TITLE
ob/order returns contract.buyerOrder.payment.amount as a string in some ETH orders

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1417]
For ETH orders over a certain amount, the value of contract.buyerOrder.payment.amount is returned as a string instead of a number, which throws an unhandled error in the client. I was able to narrow it down to a value higher than 8978034788986922 ETH, and at least 9062733230392460 ETH.

Returns as a number: 8978034788986922
Returns as a string: 9062733230392460

**Comment by amangale** [comment]
@jjeffryes - This seems to be the default behavior of grpc.
Refer: https://github.com/grpc-ecosystem/grpc-gateway/issues/438#issuecomment-330741034

TL;DR: Above a certain value, proto3 will marshal the number as a string.

**Comment by jjeffryes** [comment]
If the issue is 53 bit integers, we should be safe up to 9062733230392460, 9007199254740991 is smaller than that? 

I guess it's a problem regardless, because we'll hit the 53 bit limit with ETH due to it having a much smaller smallest unit vs. BTC and BTC-like currencies.

@rmisio if we're stuck with string numbers for ETH values above $1.00 (roughly), what do you think the best way to handle that is?

**Comment by rmisio** [comment]
> I'm not sure what confluence of variables would need to come into play for the granularity of `microether` to not be sufficient.

Just thinking out loud to try and make peace with this.

At `microether`, it means the largest JS number works out to 9007 ETH, which at current prices is over a million dollars. So we'd need a product priced more than that for `microether` to not be sufficient. Of course if ETH plummets, then so does the price threshold. At a price of 1 ETH being a penny (extreme case), then the max USD priced product could be 10k.

I get it, future proofing is safest, but just understand there is non-trivial scope to account for it and the circumstances under which it helps us are arguably remote.

**Comment by rmisio** [comment]
Another thing to keep in mind is we probably shouldn't offer the user 'WEI' as a display price, like we do with Satoshi. Not only will it introduce issue of not enough screen real estate, but I doubt the localization libs (mostly native) we are using support numbers represented as strings.

**Comment by placer14** [comment]
@amangale When we originally talked about how to represent the value of ETH outside of the wallet, I think we agreed to use the implied default (of `1e-8`) until we can better represent the divisibility of each different currency. In other words, the wallet should not express values in wei externally and needs to find some way to protect against transactions which cannot be expressed within the network's current range.

Before we can accept any divisibility different from Bitcoin's satoshi we would need to ensure every data representation where we show some currency value being used also considers that currency's coinDivisibility without it being implicitly defined by the server or client.

**Comment by drwasho** [comment]
> When we originally talked about how to represent the value of ETH outside of the wallet, I think we agreed to use the implied default (of 1e-8) until we can better represent the divisibility of each different currency. In other words, the wallet should not express values in wei externally and needs to find some way to protect against transactions which cannot be expressed within the network's current range.

Regrettably, I wasn't present during that discussion, and when Ashwin and I had a chat about it the following day, I concluded that this wasn't a viable solution. It introduces so many problems when it comes to calculating gas fees (which are priced in `wei`) and conversion issues when pricing listings, let alone the issues it might cause with our smart contracts. It is a **hard no** as far as we're concerned.

Furthermore, as a crypto-project it's a little ridiculous that we're not handling large numbers, and it would frankly be embarrassing that we're the one Dapp out there that doesn't treat `wei` correctly. If we're going to integrate Ethereum then we need to integrate it properly on the server and client level, and no resort to ugly hacks to avoid the hard refactoring work that is necessary.

**Comment by cpacia** [comment]
Closing because we have a larger planned solution for the broader issue
