### ISSUE TITLE
releasefunds and orderconfirmation have insufficient gas for ETH orders

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1418]
Attempting to accept an offline order with `orderconfirmation` or accept a dispute resolution with `releasefunds` returns an error of `insufficient funds for gas * price + value` when using ETH.

This appears to be true for orders between $0.01 and $1.00 of ETH. Larger amounts couldn't be tested due to the number as string bug (#1417).

**Comment by cpacia** [comment]
Yeah people will need to have a positive eth balance to accept eth orders due to how eth works.

**Comment by cpacia** [comment]
Maybe we need a custom error code for insuffient gas
