### ISSUE TITLE
wallet/spend returns nothing when using ETH

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1419]
When calling wallet/spend, it returns a status of 200, and seems to work, but returns no data. 

It should behave normally, and return data similar to other coins, like:

```
{
  "amount": 27106,
  "confirmedBalance": 145637,
  "memo": "test new listing",
  "timestamp": "2018-04-19T15:16:18-04:00",
  "txid": "ee4f0bb4b405f17eeeb3e84aaf6bb02a13763cf87a71375f7d59ca5fe916a47d",
  "unconfirmedBalance": 0
}
```

**Comment by amangale** [comment]
@jjeffryes - I have pushed a fix for this in the commit https://github.com/amangale/openbazaar-go/commit/2871f4fef02c91b16ae018e87fd499aaf7810324.
