### ISSUE TITLE
Socket notifications for ETH transactions don't appear to be working

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1420]
I didn't see any notifications arrive over the socket for ETH transactions in the wallet. The only way to see new transactions in the desktop client was to reload the client so the transactions would be obtained from a GET call.

**Comment by drwasho** [comment]
Presently there isn't a websocket to alert the client that any Ethereum or ERC-20 transfer to the user's account has occurred (whether it's related to an order or not). 

Any order-related transactions has it's own socket message, but for non-order transactions it can be worked-around by polling the transaction history for ETH/ERC-20 token.

We'll have to implement a better solution by opening a websocket to Infura or Etherscan, to listen for events occurring at the user's account, after the ETH integration is released.

**Comment by drwasho** [comment]
Closing as it's being tracked in #1701 and #1783

**Comment by drwasho** [comment]
Fixed in PR 1951
