### ISSUE TITLE
We'll need to provide moderators a scripthash for ETH disputes

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1421]
Normally, a moderator is able to look at the address of the escrow used in a dispute to see the transactions that funded it.

For ETH disputes, we can give the moderator a link to the contract (https://etherscan.io/address/0xb221aC6622AE5348375d0048Dcff0049Ebb97d89#readContract), but they will need to have the scripthash from the dispute returned in the ob/case api to see the transactions related to it.

**Comment by amangale** [comment]
@jjeffryes - Alternatively, the ID of the transaction which put the buyer funds into escrow can be shared. Scripthash is a key used by escrow contract to lookup the order details. Other than verifying the parties involved, the scripthash is not of much use. 
In case of the ethereum wallet, there are no partial escrow payments. One transaction ID is sufficient for the moderator to ascertain the transfer of funds.
Let me know your thoughts on this.

**Comment by drwasho** [comment]
This is an example of a funding transaction made to the escrow smart contract that triggered the event `addTransaction`:

![image](https://user-images.githubusercontent.com/3887694/65854699-9eccb880-e3a0-11e9-91ab-f5e98f28cc9d.png)

If you click on the [link](https://rinkeby.etherscan.io/tx/0x7af8fbd462a4e11f074f2f359e6f0262e8ed43d22d04feacf5fd664e7b334b2a) to that transaction, you'll see:

![image](https://user-images.githubusercontent.com/3887694/65854790-d2a7de00-e3a0-11e9-8eb2-1a84c1fb7ae3.png)
(need to click 'See more' to see the `Input data` section at the bottom)

Then you need to click on 'Decode Input Data':

![image](https://user-images.githubusercontent.com/3887694/65854831-f66b2400-e3a0-11e9-9888-29a999732dee.png)

This will reveal the `scriptHash`.
