### ISSUE TITLE
Email Notifikation only works with Gmail

### ISSUE THREAD

**Issue by 6543** [OpenBazaar/openbazaar-go#1430]
I like to use my own email provider (smtp.strato.de:465).
Same settings work with thunderbird but on bazaar i get an timeout.
an test google account works fine.

sidenote: eaven the openbazaar deamon is in tor mode, it cant use hidden smtp servers (name resolv issue)

**Comment by cpacia** [comment]
Thanks for reporting. Wasn't aware of the tor issue. Afaik it does work with other email providers. Could it be a wrong port or some other setting?

**Comment by 6543** [comment]
At the moment i can just guess

**Comment by 6543** [comment]
- close it becaues time passed and i dont had time to test it at the moment -
