### ISSUE TITLE
Unable to manually sweep ETH wallet all funds

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1431]
Exploring the wallet's limits and I can't seem to drain the remaining 0.000032 ETH (32e12 wei) from the wallet. A call to `/ob/spend` trying to send 1 wei is being blocked with responses of `"insufficient funds for gas * price + value"`.

Reproducing steps:
I filled my wallet with arbitrary amount... then attempted to manually sweep the wallet via the Spend call:

- I started with the full amount of wei in my wallet,
- then estimated the fees
- subtracted that estimated fee amount from the full amount
- added a little more than available and then walked back downward until the actual spend completed.

I know this approach is imperfect, but I would've expected a LOT fewer wei to be left over.

**Comment by drwasho** [comment]
Couple of questions:

1. Is it always 0.000032 ETH?
2. What was the gas price (in Gwei) and total gas that you estimated for the fee?

**Comment by placer14** [comment]
1. In 3 trials, it was always 0.000032 remaining when the spend finally succeeds.
2. I used Normal Priority (not sure what the gas setting is there). The fee was consistently estimated as `53000000000000 wei` regardless of the amount sent. Could this be another bug? Intended behavior?

**Comment by drwasho** [comment]
It sounds like a gas calculation bug, @amangale can take a look.

**Comment by drwasho** [comment]
At the time this issue was created, we didn't have the `spendAll` flag for `POST /wallet/spend`.

- [ ] As as result, calling this API with `spendAll: true` needs to be tested by @amangale
