### ISSUE TITLE
Add resolver redundancy

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#144]
The OneName resolver for handles is a central point of failure in the current OB1.0 design. Starting from [version 0.14.0 of Blockstack Core](https://blog.blockstack.org/blockstack-core-v0-14-0-release-aad748f46d#.1y6x082le), Duo Search will be running its own resolver.

Does it make sense to add Duo Search's handle resolver into the reference client? 3-way redundant Blockstack nodes via OneName, OB1 and Duo Search would mitigate the central point of failure.

**Comment by cpacia** [comment]
We'd need to figure out how we'd want to do that. Query all resolves in the list? That would be slow. Rotate through the list on failure?

**Comment by JustinDrake** [comment]
IMO a neat solution is to first randomize the list of resolvers and then rotate through the list on failure. The initial randomization makes sure that a single resolver doesn't have an opportunity to spy (IP harvesting, query harvesting) on the whole network.
