### ISSUE TITLE
ACKs for Some or All Direct Messages

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1459]
We should consider whether there are some messages that need an ACK even when they are sent directly to another online node.

If there are, they need to be carefully examined for how this affects the user experience and state management, so user's don't end up in unexpected states if messages are resent.

Related to #1442

**Comment by placer14** [comment]
@amangale is exploring a simple approach to this problem as first-step. Deliverables at this point are just discussion and recommendations forward.
