### ISSUE TITLE
Rating timestamp

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#146]
In OB1.0 the ratings object doesn't have a timestamp which makes it hard for services such as Duo Search to display a timestamp. (I'm assuming that it is possible to extract a timestamp from `proof_of_tx`, is that correct? Nonetheless, the Bitcoin transaction confirmation block is a poor proxy for when the rating happened.)

In the OB2.0 protobuf, I would suggest adding a timestamp for when the rating occurred.

**Comment by cpacia** [comment]
+1
