### ISSUE TITLE
Broken setapicreds command

### ISSUE THREAD

**Issue by raisty** [OpenBazaar/openbazaar-go#1480]
The command `setapicreds` is broken on Linux.

JSON-API in config file have duplicate after ran with: `go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go setapicreds`

Tested on:
Digital Ocean
Ubuntu 18.04.2 LTS / bionic

This block config to be parsed and you cannot start the server. Possible security issue as well.
Most probably related to another bug #738 🐐

**Comment by cpacia** [comment]
Thanks @raisty. Going to close this issue because it has been fixed in master and will be released into production shortly.
