### ISSUE TITLE
Rating max length

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#149]
I have noticed in OB1.0 that 100% (0 exceptions) of the 779 ratings we have scrapped are less than 100 characters. I'm assuming OB1 has some sort of max length for ratings to explain that behaviour.

Looking at other e-commerce platforms, ratings can be *very* long. I suggest making the rating max length much larger 100 characters.

**Comment by cpacia** [comment]
There is no limit in v1. We will probably put one in for v2.

**Comment by JustinDrake** [comment]
In v1 there is a limit of 80 characters on the frontend.
