### ISSUE TITLE
Invalid IPFS path ref

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1491]
We are seeing occurrences of the following error: `invalid 'ipfs ref' path`

```
parse cid to path (/ipfs/): path must contain at least one component
parse path (): parts fewer than 3: invalid 'ipfs ref' path
```

Could be related to not finding certain content on the network.

**Comment by placer14** [comment]
Created a branch `ipfs-path-debug` which additional logging output to test this case.

**Comment by jjeffryes** [comment]
I haven't seen this occur, @placer14 I think it's safe to close this one.
