### ISSUE TITLE
ZeroMQ dependency

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#15]
The ReadMe states

> You will need ZeroMQ version 4.0.1 or above installed with libsodium enabled.

I understood from the OpenBazaar 2.0 global hangout that the ZeroMQ dependency was dropped. Is that correct?

If it's not, would it be possible to expand upon the ZeroMQ installation steps?

**Comment by hoffmabc** [comment]
This was due to libbitcoin which is being removed and in progress.

**Comment by cpacia** [comment]
zmq is gone
