### ISSUE TITLE
0.13.1 Dual-stack Tor: transports already registered

### ISSUE THREAD

**Issue by gavriilos** [OpenBazaar/openbazaar-go#1507]
I have just updated my node from `0.13.0` to `0.13.1`. Now it fails on start with following error message:
> transports already registered for protocol(s): tcp

My node is running in dual-stack mode, with Tor and clearnet. Here's the relevant part of the config file:
```json
   "Addresses": {
      "Swarm": [
         "/ip4/0.0.0.0/tcp/4001",
         "/ip6/::/tcp/4001",
         "/ip4/0.0.0.0/tcp/9005/ws",
         "/ip6/::/tcp/9005/ws",
         "/onion/mybeautyonionadd:4003"
      ]
```

The node starts successfully with no errors if I delete the line with the onion address.

**Comment by placer14** [comment]
Thank you for the report @gavriilos. @cpacia would you please investigate this? Perhaps the rewritten onion transport has a mislabeled protocol?

**Comment by pinheadmz** [comment]
Same issue here.

**Comment by placer14** [comment]
@gavriilos @pinheadmz Can you validate that https://github.com/OpenBazaar/openbazaar-go/releases/tag/v0.13.2-rc1 solves this problem for you?

**Comment by placer14** [comment]
We have internal reports that the issue has been resolved with v0.13.2 release. Please reopen as necessary.

**Comment by pinheadmz** [comment]
Can confirm dual-stack config is working. Clearnet is accessible and I can ping onion-only peers as well:
```
{
    "Addrs": [
        "/onion/mde5pgdvolq5m34p:4003"
    ],
    "ID": "QmZtDNYXSJzKMNCEjiRxBcC2eZ19u4fuYJRsA9MuGBggcz"
}
{
    "status": "online"
}
``

**Comment by gavriilos** [comment]
Working here too. Thanks for the quick action!
