### ISSUE TITLE
Listings not resolving properly on mainnet

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1557]
As a result of recent router changes, we are finding a large set of listings which are not resolving properly. 
(Note: This bug appears to only affect 0.13.3-rc1.)

**Comment by drwasho** [comment]
I've noticed in 0.13.3 I cannot resolve by IPFS listings with older format hashes... e.g. `zb2rheTAmRB27kY5BfT396nYXh8ktZ5K1PYT9aKb4YT8qDQCk`
