### ISSUE TITLE
IPNS name publish failed

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1564]
Regular startup of the daemon will produce the following log output after the OpenBazaar service starts:
```
13:08:05.066 [ERROR] [core/publish] name publish failed
```

**Comment by placer14** [comment]
This appears only on certain nodes, but it is unclear what the conditions for which nodes are affected. It's very likely a side-effect of some data mismatch in changing from IPFS 0.4.18 to 0.4.19 and will likely be highly correlated with nodes that have started with version 0.13.2 (last release version) or earlier.

**Comment by SamPatt** [comment]
Report on Reddit with log:

https://www.reddit.com/r/OpenBazaar/comments/ahcgsx/openbazaar_megathread_post_bugs_troubleshooting/eo1i6p8/

Another from support ticket:

```
"Publishing failed. Retry." -- I get that error all the time when I'm publishing something.

System: Ubuntu 18.04.2 (Cinnamon DE)

What I've done:

* Deleted cached files -- not helped.
```
