### ISSUE TITLE
Mobile: Fails to resolve old-style IPFS hashes

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1570]
Using the `master` branch of version `13.3`, I was able to resolve by IPFS content with old-style hashes (e.g. `zb2rhj2TpNPsjPsPNFXoaiaeBtKny1KxcFgFWFiEkeKkRJqJ8`, `zb2rhiG4zJJaASeuxfdtxJhbQY1MpwvW2H1VqDA9FALBw3Kcq`). However, when I switched run the mobile version (`go run mobile/cmd/main.go -d mobileTest`), these hashes failed to resolve.

**Comment by placer14** [comment]
@drwasho Do you happen to know how that listing hash was created?
