### ISSUE TITLE
BlockBook 400 response: -26: 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1579]
We are finding instances of transactions which are attempting to make transactions against Blockbook and getting a 400 response with this in the body:
```
{"error":"-26: 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)"}
```

We are tracking the following information for these failures for the time being. If you have hit this error, open a support ticket at (link) and include: 
- your OpenBazaar version (either daemon or bundle release version)
- a copy of the output in your `logs/ob.log` file (which can be found via https://openbazaar.zendesk.com/hc/en-us/articles/360022335771) around the same error you see there. Be aware that the error output contains identifying transaction data which you may which to keep private...submitting your logs through the support link is the recommend way to share private data with the OB1 team.)

Once you have created the support ticket, please leave a comment here indicating your support number so we can further research the issue.

**Comment by placer14** [comment]
This appears to have occurred due to the consensus rules changing on BCH during the May15 network upgrade. Transactions were attempting to be broadcast however the blockbook node was not able to accept blocks past the network upgrade height of 582680. As a result, the node had an incomplete state of the ledger and could not validate the newly produced signatures. We have upgraded the BCH node to include the May15 consensus changes (as part of ABC v0.19.4) and have found some cases are now succeeding. Following up on other reported cases before confirming as resolved.

**Comment by placer14** [comment]
Given that this is infrastructure related, we're going to close this as a solution is being tracked elsewhere.

**Comment by placer14** [comment]
Seems we are experiencing this issue again. Reopening...

**Comment by cpacia** [comment]
Superseded by issue https://github.com/OpenBazaar/openbazaar-go/issues/1673
