### ISSUE TITLE
Correct the math for header images.

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#158]
The formula for header images can produce incorrect sizes.

For example, if the uploaded image is 4000 x 1000, the large image will be 2450 x 175, instead of 2800 x 700. 

The right formula to fit the image into the desired size would be something like this:

```
targetWidth := uint(2450)
targetHeight := uint(700)
w := uint(imgCfg.Width)
h := uint(imgCfg.Height)
targetRatio = targetWidth / targetHeight
imgRatio = w / h

if imgRatio > targetRatio {
  newHeight = targetHeight
  newWidth = targetHeight * imgRatio
} else {
  newWidth = targetWidth
  newHeight = targetWidth * h / w
}
```

This could be used for the listing images as well. The avatar images appear to be working correctly.

**Comment by cpacia** [comment]
@jjeffryes I noticed the header has a different ratio for tiny and small then it does for medium and large. Is that on purpose? Am I supposed to crop it?

**Comment by jjeffryes** [comment]
No, that was just a mistake. I've updated the doc.

The correct sizes for the header are:
2450 x 700
1225 x 350
608 x 174
304 x 87
