### ISSUE TITLE
Do not force a coinDiv of 100000000 on crypto currency purchases

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1580]
When creating / updating a Cryptocurrency listing, the server currently rejects any `metadata.coinDivisibility` other than 100000000.

Can this restriction please be removed now that we support deeper precision so that clients can send in a coinDiv appropriate for the coin being traded (e.g. 18 for ETH)?

Note also that the server should support the new format instead of the old one (e.g. 8 instead of 100000000).

**Comment by rmisio** [comment]
@placer14 I don't think I have permission to tag this as eth-precision, but this bug is for that branch.

**Comment by drwasho** [comment]
Fixed in `ethereum-master`.
