### ISSUE TITLE
Expose known CurrencyDefinitions via the JSON API

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1586]
In order for clients to understand the supported currencies of the daemon, the daemon will expose a JSON API endpoint which includes all of the known `repo.CurrencyDefinitions` defined for that daemon's release. 

Guarantees and Expectations
- The data returned by the API is intended to define local support but does not represent the supported currencies of the network. (A listing may contain a currency not represented by a local node.)
- The dictionary guarantees to never have more than one definition with the same Currency Code.
- The dictionary guarantees to remain static for any given build. (This may change in the future.)
- The divisibility of the definitions represent an upper bound.
- The divisibility may change for a Currency. If the divisibility changes, it will never decrease.

Requirements
- Proposed index endpoint of `GET /wallet/currencies/`
- Proposed lookup endpoint of `GET /wallet/currencies/:currencyCode`
- All endpoints should provide a browser-cacheable response which appropriately breaks cache when the dictionary index is updated with different content. 
- The index should return mainnet Currency Definitions when the daemon is on mainnet. And testnet Currency Definitions when the daemon is on testnet.
- The endpoint will accept an optional argument which represents a specific currency definition to return. The argument is the currency code. If the code isn't found (undefined), a `404` response would be returned. If no code is provided, the index is returned with a `200`.
- When looking up a specific CurrencyDefinition, the endpoint supports testnet lookups as well regardless of the mode of the daemon. (Testnet Currency Definitions are equivalent to their mainnet definitions and _currently_ only differ by their Code and human-readable Name.) (Testnet Currency Definitions do not exist without the mainnet Currency Definition.)
- CurrencyDefinitions must reconcile `https://ticker.openbazaar.org/whitelist` against CoinMarketCap's API to disambiguate coins with conflicting symbols

**Comment by jjeffryes** [comment]
@placer14  can you provide example outputs for what the JSON should look like?

**Comment by rmisio** [comment]
> The Currency Codes represented in the definition require 3 letters with the exception of testnet Currency which has 4 and always starts with "T". (Currency Codes which are passed into other API endpoints need not be capitalized, but will be persisted/processed as capitalized...noteworthy in cases which deal with cryptographic calculations.)

Don't think 3 will work. CMC has dozens (maybe hundreds) of coins where the code is not 3. A quick scripts to get codes that are not 3 characters shows me they have codes with anywhere from 1 - 9 (and who knows what the future holds).

0xBTC
1337
2GIVE
42
A
ABBC
ABDT
ABYSS
ACAT
ACDC
ACED
ACES
ACOIN
ACRE
AE
AEON
AERGO
AGLT
AGRS
AGVC
AIDOC
AION
ALIS
ALLN
ALTX
AMLT
AMMO
ANKR
ANON
APIS
APOT
APPC
ARAW
ARCO
ARCT
ARDR
AREPA
ARGUS
ARION
ASAFE
AT
ATCC
ATLS
ATMI
ATOM
AU
AUNIT
AUTO
AV
AVINOC
AXIOM
AXPR
AZART
B@
BAAS
BANCA
BBGC
BC
BCAC
BCARD
BCDN
BCDT
BCEO
BCPT
BCZERO
BEAM
BEAT
BECN
BEET
BELA
BENJI
BENZ
BERN
BERRY
BETHER
BETR
BHIG
BIFI
BIGUP
BIRDS
BITB
BITBTC
BITCNY
BITEUR
BITG
BITGOLD
BITS
BITSILVER
BITUSD
BITX
BKBT
BLACK
BLAST
BLAZR
BLCR
BLOC
BLOCK
BLTG
BLUE
BNANA
BNTY
BOAT
BOLI
BOLT
BOLTT
BORA
BOST
BOTX
BOUTS
BOXX
BQ
BQTX
BRAT
BRDG
BRIA
BRIT
BRZC
BSTN
BSTY
BTAD
BTCL
BTCM
BTCN
BTCONE
BTCP
BTCRED
BTCS
BTCZ
BTDX
BTMX
BTNT
BTPL
BTRN
BTXC
BU
BUBO
BUMBA
BUNNY
BURST
BUZZ
BZ
BZKY
BZNT
C2
C8
CANDY
CANN
CAPP
CARAT
CARBON
CARD
CARE
CASH
CATO
CC
CCCX
CCRB
CEDEX
CEEK
CELR
CENNZ
CENT
CF
CFUN
CGEN
CHAT
CHEESE
CHESS
CHEX
CHSB
CJ
CKUSD
CL
CLAM
CLOAK
CLUB
CMCT
CMIT
CNET
CNNC
CNNS
CNUS
COAL
COBRA
COFI
COIN
COLX
COMP
CONI
CONST
CONX
COSM
COSS
COTN
COVA
COVAL
CPAY
CRAVE
CRED
CREDO
CREVA
CROAT
CROP
CRPT
CRYP
CS
CSNO
CSPN
CSTL
CTIC3
CTRT
CTXC
CURE
CV
CVNT
CYFM
CYMT
D
DACC
DACHX
DACS
DADI
DAGT
DALC
DAPS
DART
DASC
DASH
DASHG
DATA
DATP
DATX
DAXT
DBET
DBIX
DCTO
DEAL
DEEX
DELIZ
DELTA
DENT
DERO
DGTX
DICE
DIME
DIVI
DKPC
DOCK
DOGE
DOGEC
DOGET
DOOH
DOPE
DP
DREP
DRGN
DROP
DRPU
DT
DTEM
DTRC
DUTCH
DX
EARTH
EBST
EBTC
ECASH
ECHT
ECOB
ECOM
ECOREAL
ECTE
EDRC
EFYT
EGCC
EGEM
EL
ELAC
ELEC
ELET
ELITE
ELIX
ELLA
ELLI
ELTCOIN
EMC2
EMPR
ENGT
ENRG
ENTRC
ENTS
EOSDAC
EQUAD
ERC20
ESBC
ESCE
ESCO
ETBS
ETGP
ETHM
ETHO
ETHOS
EUNO
EURS
EVIL
EVOS
EXCL
EXMR
EXRN
FACE
FAIR
FIII
FLASH
FLDC
FLIK
FLIXX
FLOT
FLUZ
FNKOS
FNTB
FOAM
FOIN
FOTA
FOXT
FREC
FREE
FRGC
FRST
FSBT
FT
FTXT
FUEL
FUNDZ
FUZZ
FX
GALI
GAME
GARD
GB
GBYTE
GENE
GETX
GFUN
GMBC
GMCN
GO
GOLF
GOLOS
GOOD
GOSS
GPKR
GRFT
GRID
GRIM
GRIN
GRLC
GRMD
GRPH
GUESS
GUSD
GZRO
HALLO
HALO
HAND
HAVY
HB
HC
HDAC
HEAT
HEDG
HELP
HERB
HERC
HN
HNDC
HODL
HOLD
HONEY
HORSE
HORUS
HT
HTML
HUSH
HUZU
HVCO
HXRO
HYDRO
HYPX
IBANK
IBTC
IC
ICHX
ICNQ
ICOB
ICON
ICOO
IDEX
IDXM
IETH
IFLT
IFOOD
IG
IGNIS
IMPL
INCNT
INCO
INCX
INNBCL
INSN
INSTAR
INSUR
INVE
INXT
IONC
IOST
IOTX
IPSX
IQ
IRIS
J
JC
JIYO
JOINT
JS
KARMA
KCASH
KICK
KIND
KLKS
KNDC
KNOW
KOBO
KORE
KT
KUBO
KURT
KWATT
LA
LABH
LABX
LALA
LAMB
LANA
LATX
LBTC
LDOGE
LEDU
LEMO
LEND
LEVO
LIFE
LIGHT
LIKE
LINA
LINDA
LINK
LINX
LION
LOBS
LOCI
LOKI
LOOM
LTCR
LTCU
LTHN
LUNA
LUNES
MAID
MANA
MANNA
MASH
MATIC
MEDIBIT
MEDIC
MEDX
MEET
MEETONE
MEME
MERI
MERO
MESG
MESSE
META
METM
MFIT
MFTU
MICRO
MILO
MINEX
MINT
MIOTA
MITH
MITX
MNTP
MOAC
MOBI
MODX
MOIN
MOJO
MOLK
MONA
MONK
MOON
MORE
MOTO
MRPH
MSCN
MT
MTRC
MUSIC
MWAT
MYST
NANJ
NANO
NANOX
NASH
NAVI
NAVY
NBAI
NCASH
NEBL
NEOS
NEOX
NETKO
NEVA
NEWOS
NEXO
NEXT
NLC2
NOAH
NOBS
NOKU
NOTE
NPER
NPLC
NPXS
NPXSXEM
NRVE
NTRN
NUKO
NULS
NYAN
NYEX
OBITS
OBSR
OBTC
OC
OCEAN
OF
OK
OLMP
OLXA
OMEN
OMNI
ONION
ONOT
OPAL
OPCX
OPEN
OPTI
ORBS
ORME
OROX
P2PX
PARETO
PART
PASC
PASS
PAWS
PAXEX
PAYX
PC
PEDI
PENG
PEOS
PEPECASH
PGTS
PHON
PI
PING
PINK
PIPL
PIRL
PIVX
PLACO
PLAT
PLAY
PLBT
PLNC
PLTC
PLURA
PLUS1
PMNT
PNDM
POLIS
POLL
POLY
PONZI
POSS
POST
POSW
POWR
PRIV
PRIX
PROC
PROUD
PRTX
PTON
PTOY
PURA
PUREX
PYLNT
QASH
QBIC
QBIT
QNTU
QTUM
QUAN
QUBE
QUIN
QURO
QUSD
QWARK
R
RADS
RAGNA
RAIN
RATING
RBBT
RBIES
RBLX
RBTC
RC20
READ
REAL
REBL
REPO
RHOC
RISE
RIYA
RMESH
RNTB
ROBET
ROCK
ROCK2
ROCO
RSTR
RUFF
RUNNERS
RUPX
S
SAFE
SAKE
SALT
SANDG
SBTC
SC
SCRIV
SCRL
SCRT
SDUSD
SEAL
SEELE
SEER
SENC
SEND
SENSE
SENT
SERV
SETH
SEXC
SFCP
SHADE
SHARD
SHDW
SHIFT
SHIP
SHMN
SHND
SHOW
SHPING
SHVR
SICA
SIGMA
SIGT
SINS
SJCX
SKCH
SKIN
SLRM
SMART
SMLY
SNET
SNGLS
SNIP
SNOV
SNPC
SNRG
SNTR
SNTVT
SOAR
SOCC
SOLVE
SONG
SONIQ
SONO
SOUL
SPANK
SPDR
SPEC
SPHR
SPHTX
SPND
SPRKL
SPRTS
SRCOIN
SS
STAC
STACS
STAK
STAR
START
STASH
STEEM
STEEP
STORJ
STORM
STRAT
SUMO
SUPER
SUQA
SUSD
SWFTC
SWIFT
SWING
SWTC
SWTH
SXDT
SXUT
SYNX
TAAS
TALK
TCAT
TEAM
TELL
TELOS
TEMCO
TENA
TERN
TFUEL
TGAME
THETA
THRT
TIME
TIOX
TIPS
TMTG
TOKC
TOMO
TOPC
TOSC
TOTO
TPAY
TRAC
TRAID
TRAK
TRAT
TRCT
TRDT
TRIO
TROLL
TRST
TRTL
TRTT
TRUE
TRUMP
TRXC
TT
TUBE
TUSD
TV
TVNT
TWINS
TX
TYPE
UBEX
UBTC
UC
UCASH
UDOO
UGAS
UNIFY
UNIT
UP
URALS
USDC
USDS
USDT
USNBT
UT
UTNP
V
VALOR
VEC2
VEIL
VERI
VEST
VIBE
VIDT
VIDZ
VIEW
VIKKY
VIPS
VITAE
VITE
VITES
VIVID
VIVO
VOCO
VOISE
VOLLAR
VOLT
VSYS
VTHO
VULC
WABI
WAGE
WAND
WAVES
WBTC
WC
WEBD
WEBN
WELL
WETH
WHEN
WICC
WIKI
WINGS
WINK
WIRE
WISH
WOMEN
WT
XAUR
XBASE
XBTC21
XCASH
XCLR
XCON
XCXT
XDCE
XDNA
XG
XGOX
XIND
XLMG
XMCC
XMCT
XP
XPAT
XPTX
XSPEC
XSTC
XTRD
XUEZ
YEED
YOYOW
YUKI
ZB
ZEIT
ZENI
ZEON
ZEUS
ZINC
ZIPT
ZP
ZT

**Comment by rmisio** [comment]
> Proposed endpoint GET /wallet/currencies/:currencyCode

Please also ensure there is an endpoint that returns the full dictionary.

**Comment by rmisio** [comment]
> The index should return mainnet Currency Definitions when the daemon is on mainnet. And testnet Currency Definitions when the daemon is on testnet.

@placer14 One issue with this for the desktop client is that the coin's readable name is in our translation files, keyed by mainnet code... so if the coin data doesn't provide both mn and tn code's, then we would need an way to convert from testnet to mainnet.

If we're on testnet, would the mainnet code be the testnet code minus the first character? I'm 99% sure that's the case, but just want to make sure there are no exceptions you are aware of.

**Comment by placer14** [comment]
Notes from discussion regarding coin disambiguation problems we've already "solved":

> https://ticker.openbazaar.org/whitelist
> 
> CMC has a bunch of coins that share the same code (but have different IDs). When multiple coins share a symbol, OB chooses the one with the highest volume and clearly indicates the selection via the API above indicating which CMC ID is intended for each symbol. This is important for clients so they don’t show the wrong icon for a particular currency or use the exchange rate of one when the other was intended.

**Comment by placer14** [comment]
Dropped this expectation:
> The Currency Codes represented in the definition require 3 letters with the exception of testnet Currency which has 4 and always starts with "T". (Currency Codes which are passed into other API endpoints need not be capitalized, but will be persisted/processed as capitalized...noteworthy in cases which deal with cryptographic calculations.)

**Comment by placer14** [comment]
> One issue with this for the desktop client is that the coin's readable name is in our translation files, keyed by mainnet code...

@rmisio I will attempt to find an elegant way of referring to the coin's testnet and mainnet symbols within the same definition instead of referring to them as separate definitions. Meaning both versions of the symbols will be available during runtime. Would that work for you?
