### ISSUE TITLE
Add shipping info to the listing index

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#159]
Please add the following fields to the listing index for each listing in order to allow the client to implement the Shipping filter on the Store page:

![image](https://cloud.githubusercontent.com/assets/794517/19495526/8e0420c4-9538-11e6-9a73-f85e0a905d27.png)

* *shippableCountries* - a list of countries the listing will ship to.
* *freeShipping* - Whether the listing has a free shipping option.

The idea is that the server would compute these fields based on the data from the shippingOptions section of each listing. This would avoid having to add the full shippingOptions to the index, which could make the unpaginated index quite bulky.

**Comment by rmisio** [comment]
Our discussion on #161 brings up a good point. The listing may have a Free Shipping option, but it's likely limited to a specific country or set of countries, so as @jjeffryes mentioned, I think we'd need some data structure provided here that indicates what countries the listing ships for free to.

Then for the purposes of this filter, if the Free Shipping checkbox is checked, the store would show listings that ship for free to the country of the user who is viewing the store.

**Comment by morebrownies** [comment]
That sounds right to me.

One edge case to consider... The user may not have an address on file. If so, is there an alternative way we could determine their country and display the "Free shipping" badge? Or, would we need to hide the functionality?

**Comment by rmisio** [comment]
I would think in that case we should just hide the whole Shipping filter since we can't determine the Ships To part either.

I think there is Geo location data we could use to get a users coordinates, but I think you need some API to convert that to a country and if I recall correctly @jjeffryes mentioned there was some hang-up in going that route. Perhaps there's no free APIs or they would require the user to register to get an API key.

**Comment by morebrownies** [comment]
We could potentially make country a required field in on-boarding too.

**Comment by cpacia** [comment]
This is going to get to be a ton of data. I'd need to include a list of countries for each shipping option including free. We we're trying to keep the data in the index to a minimum. I worry this will blow it out.

**Comment by rmisio** [comment]
well, i think it would require two lists of countries added to each listing. These lists could be computed off of the shipping options.

```
{
  shipsTo: ['UNITED_STATES', 'SPAIN', 'PORTUGAL'],
  freeShipping: ['UNITED_STATES'],
}
```

So... it might not be too bad, but if someone is selecting dozens of countries a listing could ship to - which is possible, then yeah, it could definitely add some bloat.
