### ISSUE TITLE
starting OB2 with --tor, get errors: transport conductor failed, connect: connection refused

### ISSUE THREAD

**Issue by blouseequipment** [OpenBazaar/openbazaar-go#1605]
## The Issue:
I've set up and run OB2 stores on a VPS before, but this time I wanted to do it through tor first. And I'm getting stuck in the same place every time.  

Installed TOR and Openbazaar-go on an Ubuntu server, but when I start tor (connects successfully) then

     go run openbazaard.go start --tor

I get the following startup and fail error messages:

> ________                      __________
> \_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
>  /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
> /    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
> \_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
>         \/|__|        \/     \/       \/      \/      \/     \/     \/
> 
> OpenBazaar Server v0.13.3
> 2019/05/26 20:25:22 
> OpenBazaar Server v0.13.3
> [Press Ctrl+C to exit]
> transport constructor github.com/OpenBazaar/openbazaar-go/vendor/gx/ipfs/QmYv2MbwHn7qcvAPFisZ94w85crQVpwUuv8G7TuUeBnfPb/go-onion-transport.NewOnionTransportC.func1 failed: dial tcp4 127.0.0.1:9051: connect: connection refused
> exit status 1

## Steps to replicate the problem (and corrective measures I've taken):

Start a brand new instance of my VPS (Ubuntu 19.04 x64 with 4096 MB RAM )

Startup stuff:

    sudo apt-get update && sudo apt-get upgrade -y 

Installed and configured openbazaar-go according to the github instructions [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/install-linux.md). 

```
sudo apt-get install build-essential git -y
wget https://storage.googleapis.com/golang/go1.11.5.linux-amd64.tar.gz
sudo tar -zxvf  go1.11.5.linux-amd64.tar.gz -C /usr/local/
mkdir $HOME/go
echo "export GOPATH=$HOME/go" >> .profile
echo "export PATH=$PATH:/usr/local/go/bin" >> .profile
source ~/.profile
go get github.com/OpenBazaar/openbazaar-go

```
Opened up port 4002 as suggested in [this tutorial](https://steemit.com/openbazaar/@atmandigital/openbazaar-2-0-guide-installation) and saw that an Openbazaar developer commented that you should open 4001, too. Opening both allows me to connect my desktop client later.

    sudo ufw allow 4001/tcp
    sudo ufw allow 4002/tcp

Initialize OB2 
```
cd $GOPATH/src/github.com/OpenBazaar/openbazaar-go
go run openbazaard.go init
go run openbazaard.go setapicreds
```
Gave the program a username & password that I later will use in the desktop client. Now to further configure the `config` file:
 
```
cd $HOME/.openbazaar
cp config config_OLD //backup just in case, 'cause I'm gonna be mucking about!

```
I find I won't be able to connect to the server from my desktop client unless I change the Gateway IPaddress in the `config` file from 127.0.0.1 to my server's IP address:

    sed -i -E "s|(\"Gateway\": \"/ip4/)127.0.0.1|\1$(dig +short myip.opendns.com @resolver1.opendns.com)|" config

Generate SSL keys:

```
ExternalIPAddress=$(curl ipinfo.io/ip) && openssl genrsa -out rootCA.key 4096
openssl req -x509 -new -nodes -key rootCA.key -days 1024 -out OpenBazaar.crt -subj "/C=DE/ST=Germany/L=Walldorf/O=SAP SE/OU=Tools/CN=OpenBazaar.crt"
openssl genrsa -out server.key 4096
openssl req -new -key server.key -out server.csr -subj "/C=DE/ST=Germany/L=Walldorf/O=SAP SE/OU=Tools/CN=$ExternalIPAddress" && openssl x509 -req -in server.csr -CA OpenBazaar.crt -CAkey rootCA.key -CAcreateserial -out server.crt -days 1024
```

Update the `config` file so it knows to use SSL and where the keys are:

```
sed -i -E "s/(\"SSL\": )false/\1true/" config
sed -i -E "s|(\"SSLCert\": \")|\1$HOME/.openbazaar/server.crt|" config
sed -i -E "s|(\"SSLKey\": \")|\1$HOME/.openbazaar/server.key|" config
```
Open up a new terminal window, and scp the `OpenBazaar.crt` file to my local machine:

    scp root@<server's ip address>:/root/.openbazaar/OpenBazaar.crt ~/Dropbox/sshtuff

*safety note: in case you noticed, I'm installing & running everything as root until I figure out how to get this working. Once I know how to start a server and get ob2 working over tor consistently, I'd take steps to create a new user, give sudo access, disable root login, all that good server stuff. I'm just on my 7th iteration of nuking the server and starting from scratch because I keep changing so many config files that I forget what's changed and decide to start over*

I install that .crt on my local machine. 

Moment of truth check:

    go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go start &

That starts up OB2. I fire up my desktop client, enter server IP, user/password, have it use SSL... and success! Ok, I've got a working OB server install and the desktop client can connect.

### Now to add tor to the mix:

Installed tor, following [torproject's instructions](https://2019.www.torproject.org/docs/debian.html.en) 

get my password: 

        tor --hash-password "makeupyourownpassword_IEUHE34"

which gave output:

>16:E57D72B6998427816043C9BE9A1B732851F7D6A9F167BCDC9E0C948EE9

_(I was initially confused that this command gave me a different hash every time, thought that might be the issue. but turns out tor hashes the password with a salt, so that is why)_ Taking that output, I modified the `/etc/tor/torrc` file to uncomment out the Control Port and give it my hashed password:

```
## The port on which Tor will listen for local connections from Tor
## controller applications, as documented in control-spec.txt.
ControlPort 9051
## If you enable the controlport, be sure to enable one of these
## authentication methods, to prevent attackers from accessing it.
HashedControlPassword 16:E57D72B6998427816043C9BE9A1B732851F7D6A9F167BCDC9E0C948EE9
#CookieAuthentication 1
```
Then modified the `~/.openbazaar/config` file to pass it the Tor password I created above and use the same control port.
```
    "Tor-config": {
        "Password": "makeupyourownpassword_IEUHE34", // see update below
        "TorControl": "127.0.0.1:9051"
    },
```
_**Edit: as @placer14 pointed out in the comments, THIS is why I had my error. So instead of putting in your password, put in the HASH of the password as he suggests**_

    reboot

rebooted the server just so I can be sure everything starts cleanly. Made sure tor was running and checked to make sure it was connecting properly with

    curl --socks5 localhost:9050 --socks5-hostname localhost:9050 -s https://check.torproject.org/ | cat | grep -m 1 Congratulations | xargs

and got 

>Congratulations. This browser is configured to use Tor.

...But now when I try to run the OB2 server:

    go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go start --tor &

...I get the error message stated at the top of this post. 

------------------------------
Any help is **greatly** appreciated. Turns out that there are [several](https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/install-linux.md) different [tutorials](https://steemit.com/openbazaar/@atmandigital/openbazaar-2-0-guide-installation) on [setting up](https://zokos.com/blog/site/public/2019/04/24/Self-Host%20your%20Own%20OpenBazaar%20Store/) OB2 on a linux server,  but only bits and pieces of info on how to properly configure it for tor first. When I crack this nut I'll make a detailed tutorial and post it, probably including setting up ssh keys, ssl certs, hardening the server afterwards, all that good stuff so even less technical people can get a store set up properly and start playing with their own stores. 

THANKS!

**Comment by placer14** [comment]
Try changing `"Password": "makeupyourownpassword_IEUHE34",` to `"Password": "16:E57D72B6998427816043C9BE9A1B732851F7D6A9F167BCDC9E0C948EE9",

**Comment by placer14** [comment]
BTW, greatly appreciate all the detailed input. This documentation is going to help many. ❤️

**Comment by blouseequipment** [comment]
> Try changing `"Password": "makeupyourownpassword_IEUHE34",` to `"Password": "16:E57D72B6998427816043C9BE9A1B732851F7D6A9F167BCDC9E0C948EE9",`

Thanks! I made that change... and now no more error message! Gave the command:

    go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go start --tor &

and saw:

>  ________                      __________
> \_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
>  /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
> /    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
> \_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
>         \/|__|        \/     \/       \/      \/      \/     \/     \/
> 
> OpenBazaar Server v0.13.3
> 2019/05/30 13:16:39 
> OpenBazaar Server v0.13.3
> [Press Ctrl+C to exit]

(although I think it's funny that the password I chose was hashed - and that hash was placed into two different files. The actual password I made wasn't used anywhere... so I guess the 'password' in both cases just needs to be a random sha256 hash.)

## Trying to connect desktop client... 

In desktop client Made a New Server:
Name: AWESOMESERVERNAME
Server IP: <My server's IP>
Username: <same username set up when I ran `go run openbazaard.go setapicreds`>
Password: <same password set up when I ran `go run openbazaard.go setapicreds`>
SSL: On 
Port: 4002
Use Tor: CHECK

OB2 server seems to be running fine on tor with `go run $GOPATH/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go start --tor &`

But now the issue is **I'm not able to connect with my desktop client.** (sigh). Desktop client just times out when trying to connect.

### Things I've tried:

# 1 Turning off TOR connection on my desktop client. Just to see if it's with my local tor configuration. Left TOR off for the rest of these tests. Once I can connect without tor I'll try checking this again.

# 2 Turning SSL off (maybe I didn't install the SSL cert correctly on my machine?)

Nope. That makes the server spit out this error over and over:

> 2019/05/30 13:06:51 http: TLS handshake error from 45.56.152.109:53428: tls: first record does not look like a TLS handshake

So I changed SSL back to 'On'

# 3 Earlier in my setup I changed the `config` file Gateway to:
```
   "Addresses": {
        "Gateway": "/ip4/<MY.SERVER'S.IP.ADDRESS>/tcp/4002",
```
I needed to do that earlier to connect with my desktop client (without using tor). So I changed it back to the default 127.0.0.1 to see if that mattered.

Not sure where to go next. Server seems to be running fine, but desktop client tries to connect and... just doesn't. Are there any logs I can check to narrow down the problem?

**Comment by placer14** [comment]
The issue seems to be mostly with poor setup documentation. Closing this specific issue as resolved with a new issue to track the need to update our docs (issue 1772, linked above).
