### ISSUE TITLE
Research messaging designs

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1616]
This research will include making messaging more durable for both the offline and online cases as well as researching potential new designs for the offline messaging to make it more durable, decentralized, and secure. 

Supporting of #1442

**Comment by cpacia** [comment]
Here's a first pass thoughts after researching the possibility of bolting store and forward functionality onto the circuit relay:

```
On another topic:

I'm not sure the circuit relay is really the best place to bolt in store and forward functionality.

For one, the circuit relay could easily be made pluggable as it's just a single function used by libp2p, but we would need to get a PR to libp2p to do that at minimum.

But maybe more importantly it just doesn't feel like the correct place for it.

The relay nodes actual performs handshakes with both nodes in the circuit before starting the relay. For store and forward purposes we'd either need to make the sending node _think_ it established a circuit while actually just storing relayed packets or going further and modifying the relay protocol. Which doesn't sound like a great option. This also has implications where we keep the circuit open for the purpose of storing OB messages, but it makes the sender think that the stream is open to also send DHT messages or Bitswap message... which would obviously just end up timing out and causing the connection to close and degrade performance.

Further, the actual relaying is just done with `io.CopyBuffer` so we'd need to some how inspect the byte stream (which has a number of different protocols multiplexed together) and then extract the streams that are just related to OB, read the stream into messages, and store. Doing that is possible but very complex.

Ultimately this seems like a hacky approach. (edited) 
```

**Comment by placer14** [comment]
When we talked about this before, we discussed the possibility of creating a new protocol. The protocol would accept messages on behalf of another node ("XYZ") who has "registered" their ID/key there. Then XYZ could announce a mutiaddr (say, in their profile) which indicates opting-into using this other node as an offline custodian for their encrypted messages for later retrieval.

Does an IPFS custom protocol do anything for us that an OB protocol message couldn't do also? Maybe this is just a new protocol message on OB?

**Comment by cpacia** [comment]
> Does an IPFS custom protocol do anything for us that an OB protocol message couldn't do also? Maybe this is just a new protocol message on OB?

No it doesn't. Just would be nice if it was native libp2p. It would be useful to others and we wouldn't need to maintain it.

**Comment by cpacia** [comment]
Going to close this issue. Imo the designs we talked about at the retreat are still likely the best way to go. 

A prototype of a reliable messaging design can be found here: https://github.com/cpacia/openbazaar3.0/blob/master/net/messenger.go

I also had a prototype of the store and forward layer for libp2p but unfortunately I lost it in an OS reinstall where I didn't have it committed to github.

This was really only a single file though so not much effort to recreate.
