### ISSUE TITLE
Multisig autoupdates

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#164]
(This was briefly discussed during the partners call.) As I understand, the current plan for autoupdates is:

- New releases are signed by a single party and submitted to online nodes
- Online nodes will receive a notification, and if they so wish, can do a 1-click install

From a security perspective the worry is that the signing key gets compromised. An attacker could then push malevolent releases to the network. A solution to this problem is to have multisig, e.g. 2-of-3 multisig. Here is a possible 2-of-3 setup with Duo Search involved:

* Signing key number 1, held by OB1
* Signing key number 2, held by Duo Search
* Deep cold storage signing key number 3 for backup, held by OB1

In the above setup, an attacker would have to compromise both signing keys 1 and 2 from two different parties.

**Comment by cpacia** [comment]
This issue might be better posted in the installer repo (I think that's where the code is, not sure). But I don't think there's anything in this repo that would handle that code.
