### ISSUE TITLE
fully automated downloads?

### ISSUE THREAD

**Issue by vsatmydynipnet** [OpenBazaar/openbazaar-go#1644]
i am just curious asking if openbazaar supports fully automated downloads?

**Comment by placer14** [comment]
We've talked about it and like the concept and have ideas for it, but the platform currently does not support automated downloads.

**Comment by vsatmydynipnet** [comment]
I just want to ask again because I found digital downloads on an IB roadmap. Furthermore will there be a way that people buy through web without installing software? Thank you.
