### ISSUE TITLE
[bug]mac compile error, when can it is fixed about sqlite error?

### ISSUE THREAD

**Issue by DuckulaGL** [OpenBazaar/openbazaar-go#1648]
➜  ~ go get -u github.com/OpenBazaar/openbazaar-go
# github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher
sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by placer14** [comment]
Hi @DuckulaGL. Thanks for the report. This is an upstream dependency warning which is due to our use of sqlite in the daemon. This warning is benign and can be safely ignored for the time being. We'll be sure to resolve this in an upcoming version.

**Comment by DuckulaGL** [comment]
OK, thank you.
