### ISSUE TITLE
Create an enum for currency codes

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#165]
`contracts.proto` is lax regarding currency codes:

```
    string acceptedCurrency          = 5;
    string pricingCurrency           = 6;
```

Instead of a plain `string`, I think it would make sense to `enum` the possible values, similar to `countrycodes.proto`.

Duo Search has recently seen a vendor use currency code `US` instead of `USD`, and this broke our client-side JavaScript.

**Comment by cpacia** [comment]
I suppose we could do that. The issue is if people end up creating an altcoin fork in the future, then the contract wont be able to parse enums for altcoins it doesn't know if. It would probably cause the contract to display.
