### ISSUE TITLE
Force multiwallet to cycle past non-segwit LTC addrs which downcase to having the `ltc1` prefix

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1662]
We've found that non-segwit addrs which begin with the case-insensitive prefix of `ltc1` (to include `LtC1`, `lTC1`, `LTc1`, etc) are breaking when being looked up by BB since that is assumed to be the segwit prefix. We need to ensure that we never offer this addr from our multiwallet LTC impl.

This issue is to track this gets resolved in multiwallet and pulled into ob-go.

**Comment by cpacia** [comment]
Done
