### ISSUE TITLE
Change Fee Calculation for BCH, LTC, ZEC

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1664]
We should change the current fee calculation for non-BTC coins. Currently fees for BCH are higher than they need to be, while LTC and ZEC are low enough they may cause transactions to fail. It's possible this is related to #1659.

A single algorithm should be used for all three. The exact level of fee to aim for needs to be determined. It should be high enough to ensure even economic level fees still go through, but lower than the current level of BCH fees.

**Comment by cpacia** [comment]
Based on discussion we are going to replicate the bch fee handling process in ZEC and LTC. This makes the most sense as it maximizes the likelihood the fee will always be above the network relay minimum. 

We are also going to lower the default (normal) fee for BCH to me more inline with user expectations.
