### ISSUE TITLE
Is there a profile validator?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#167]
In [`profile.go`](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/profile.go) I cannot find an equivalent of `validateListing` for profiles. I'm assuming this is planed but not yet written.

**Comment by cpacia** [comment]
Unlike listings, the only opportunity to validate a profile would be when the user saves it. I suppose we could do that. We would need to come up with some sizes for the fields.

**Comment by JustinDrake** [comment]
What happens when the frontend requests a random profile? Shouldn't it be validated by the server  before it is manipulated by frontend JavaScript?

A key reason I'm reviewing the server validators is because at Duo Search we need the scrapers to filter out nefarious stuff.

**Comment by JustinDrake** [comment]
> What happens when the frontend requests a random profile? Shouldn't it be validated by the server before it is manipulated by frontend JavaScript?

I believe that @cpacia is working on a refactoring of the API to address that. See for example [here](https://github.com/OpenBazaar/openbazaar-desktop/issues/260).
