### ISSUE TITLE
Investigate LTC payment address not being accepted by Exodus wallet

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1670]
Unknown what type of order produced this address, but when entered into Exodus, the following error occurred:

![u5IlE0lx jpg_large](https://user-images.githubusercontent.com/305332/62493959-58901a00-b7a0-11e9-986b-5190d2c1500c.jpeg)

**Comment by drwasho** [comment]
Possibly related:

![image](https://user-images.githubusercontent.com/3887694/62778214-26115480-baf3-11e9-89dd-62059084efaf.png)

**Comment by placer14** [comment]
Good catch. This might be related to https://github.com/OpenBazaar/openbazaar-go/issues/1662

**Comment by placer14** [comment]
Presumably resolved as part of 1662. Closing.
