### ISSUE TITLE
Order in FULFILLED state with no funds pending cannot completed by vendor

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1681]
In the scenario that a vendor has an order that is in a FULFILLED state but the inputs to the payment address have already been spent (unsure of how this state was achieved), the vendor gets a 400 Bad Request from the wallet API due to have no inputs for sweeping.

We want to bypass the Sweep attempt if all inputs are spent to allow the order to progress to PROCESSING_ERROR with text associated indicating that there are no inputs to process to FINALIZE_PAYMENT.

**Comment by hoffmabc** [comment]
This scenario is reproduced by at least the following:

- Buyer cancels order
- Buyer sweeps funds to himself when the `cancel` message fails or is not received by the vendor in time

**Comment by hoffmabc** [comment]
@placer14 I'm not sure how this scenario could possibly occur. Funds for a direct offline order are swept when the orders is accepted not when it is fulfilled. So there would definitely be no inputs to sweep at the ORDER_FULFILLED stage.

**Comment by hoffmabc** [comment]
#1940 is not going to allow the order to proceed because we don't know if the order still has inputs that are not synced up from the blockchain yet and if we proceed then we may cause the order to have issues. For now we'll just error earlier with a message about missing inputs.
