### ISSUE TITLE
Currencies added to a profile are mainnet even when creating the profile on testnet

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1694]
When you POST (create) a profile, the server appends a currency list based on the currently supported wallet currencies.

Previously, ob-go had correctly been putting testnet codes into the list when the app is run on testnet and mainnet otherwise.

The current `ethereum-master` branch is putting in mn codes regardless if we're running the app on mn or tn.

(I think the normalizeCurrency function and subsequent lookup just aren't `testnet/mainnet` aware)

**Comment by placer14** [comment]
Confirmed. Thanks for the report.

**Comment by drwasho** [comment]
Fixed.
