### ISSUE TITLE
Problem to Track Inventory

### ISSUE THREAD

**Issue by Majsin** [OpenBazaar/openbazaar-go#1697]
Using the example from the API I am trying to add inventory tracking to listing (physical, no options), however the listing still has "do not track inventory". What am I doing wrong? How to set inventory tracking? Does this function work?

            $json = json_encode(array(array(
                "slug" => $id,
                "quantity" => $qty
            )));
            $curl = curl_init();
            curl_setopt_array($curl, array(
                CURLOPT_URL => "http://localhost:4002/ob/inventory",
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_ENCODING => "",
                CURLOPT_MAXREDIRS => 10,
                CURLOPT_TIMEOUT => 10,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                CURLOPT_CUSTOMREQUEST => "POST",
                CURLOPT_POSTFIELDS => $json,
                CURLOPT_HTTPHEADER => array(
                    "Content-Type: application/json",
                    "Authorization: Basic ".$hash
                ),
            ));
            $response = curl_exec($curl);
            $err = curl_error($curl);
            curl_close($curl);
            if ($err) {
                echo "cURL Error #:" . $err;
            } else {
                echo $response;
            }

**Comment by jjeffryes** [comment]
You'll need to update the listing with an item.skus object of {quantity: 1}.

The inventory is tracked using the skus array, even if no options exist. If you have options, the skus are set by the options, if you don't a single sku is created.

**Comment by Majsin** [comment]
Using sku also didn't help:

```
$json = json_encode(array(array(
                "slug" => $sku,
                "quantity" => $qty
            )));
            $curl = curl_init();
            curl_setopt_array($curl, array(
                CURLOPT_URL => "http://localhost:4002/ob/inventory",
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_ENCODING => "",
                CURLOPT_MAXREDIRS => 10,
                CURLOPT_TIMEOUT => 100,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                CURLOPT_CUSTOMREQUEST => "POST",
                CURLOPT_POSTFIELDS => $json,
                CURLOPT_HTTPHEADER => array(
                    "Content-Type: application/json",
                    "Authorization: Basic ".$hash
                ),
            ));
            $response = curl_exec($curl);
            $err = curl_error($curl);
            curl_close($curl);
            if ($err) {
                echo "cURL Error #:" . $err;
            } else {
                echo $response;
            }
```

**Comment by Majsin** [comment]
How do you update the quantity? The following code not work. Do I have to complete all the fields again?

            $data = array(
                "currentSlug" => $id,
                "slug" => $id,
                "item" => array(
                    "skus" => array(
                        array(
                            "productID" => $id,
                            "surcharge" => 0,
                            "quantity" => $qty
                        )
                    )
                )
            );
            $json = json_encode($data);
            $curl = curl_init();
            curl_setopt_array($curl, array(
                CURLOPT_URL => "http://localhost:4002/ob/listing",
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_ENCODING => "",
                CURLOPT_MAXREDIRS => 10,
                CURLOPT_TIMEOUT => 0,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                CURLOPT_CUSTOMREQUEST => "PUT",
                CURLOPT_POSTFIELDS => $json,
                CURLOPT_HTTPHEADER => array(
                    "Content-Type: application/json",
                    "Authorization: Basic ".$hash
                ),
            ));
            $response = curl_exec($curl);
            $err = curl_error($curl);
            curl_close($curl);
            if ($err) {
                echo "cURL Error #:" . $err;
            } else {
                echo $response;
            }

**Comment by Majsin** [comment]
SKU assignment when creating a listing has fixed the problem, thank you.
