### ISSUE TITLE
ETH - wallet message is missing

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1701]
The client listens for a socket message with a .wallet object containing a tx and coin type to show new transactions.

As of 4ba53f7d in the ethereum-master branch, that message is no longer being sent when new outgoing or incoming transactions happen.

This was working previously, so a recent change might be responsible.

**Comment by rmisio** [comment]
@placer14 Just to clarify, this is a `wallet` socket which is distinct from the `walletUpdate` socket. I'm fairly sure it was in a few days ago and wondering if somehow it got borked when you updated the `walletUpdate` socket?

**Comment by rmisio** [comment]
Just to be clear, the `wallet` socket comes when a transaction is first seen and when it initially confirms (goes from 0 to 1 confirmations).

**Comment by rmisio** [comment]
Just tried this on `ethereum-master` and it's still an issue - no `wallet` socket comes.

**Comment by drwasho** [comment]
Updated this in https://github.com/OpenBazaar/openbazaar-go/issues/1420 but we don't have a websocket to report new ETH/ERC-20 transactions. The only socket message we'll get is the `orderspend` network message for now.

**Comment by rmisio** [comment]
> Updated this in #1420 but we don't have a websocket to report new ETH/ERC-20 transactions. The only socket message we'll get is the orderspend network message for now.

@drwasho Just to be clear, this issue is reported that the `wallet` socket is missing for every coin, not just ETH.

I was in up to a few weeks ago and somehow along the way got lost.
