### ISSUE TITLE
Never used calculateNewTotal arg for core.NewOrderConfirmation

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1723]
Seems a logic oversight or incomplete, but `core.NewOrderConfirmation` does not ever get called with `calculateNewTotal` ever being true. Is this intentional or oversight?

**Comment by drwasho** [comment]
In other words: where `NewOrderConfirmation` is invoked (`net/service/handlers.go:356`, `net/service/handlers.go:421`), there is never an instance where we pass `true` as an argument for `calculateNewTotal`... so either one of those places needs to be passing `true`, or it's not necessary at all.

Ashwin recalled that the purpose of `calculateNewTotal` was to handle rapidly changing listing prices or something. Is this code still relevant? Are we handling the problem elsewhere in a different way?
