### ISSUE TITLE
Wallet spend (Bug): API returns a 400 error for spending ETH/TETH but still sends funds 

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1730]
- Same issue as (2) from https://github.com/OpenBazaar/openbazaar-go/issues/1704
- I'm on the `update-listing` branch, based off of the latest `ethereum-master`

The payload sent to the API:

![image](https://user-images.githubusercontent.com/3887694/65850106-c3209900-e390-11e9-9e82-fe7637671adc.png)

Even though the server is returning a 400 error, the spend attempts are succeeding:

![image](https://user-images.githubusercontent.com/3887694/65850196-3c1ff080-e391-11e9-9938-103207472085.png)

**Comment by amangale** [comment]
This issue has been fixed in PR 1763.
