### ISSUE TITLE
Additional abstractions needed

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1738]
In addition to pb.Listing fields have also changed in:

- [x] `BuyerOrder`
- [x] `OrderFulfillment`
- [x] `OrderConfirmation`
- [x] `Dispute`
- [x] `DisputeResolution`
- [x] `Refund`

Currently anywhere these objects are referenced they are referenced in their protobuf form in the most recent version. However, if a previous version is unmarshalled then we will be referencing the wrong fields. What is needed is to abstract out the fields that changed similar to how it was done in repo.Listing.

Ideally we would have a function to do that across the whole contract as many parts of the code interact with the full contract.

**Comment by placer14** [comment]
This work completed is related to https://github.com/OpenBazaar/openbazaar-go/issues/1610 and only converts the current version into the v5-compatible schema but we would eventually use this within the abstractions indicated in 1610.
