### ISSUE TITLE
When there are no ETH transactions, the `/wallet/transactions/` response does not match the response of other coins

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1756]
for example:

`http://localhost:4002/wallet/transactions/TBTC?limit=25`

returns:

```
{
    "count": 0
}
```

whereas `http://localhost:4002/wallet/transactions/TETH?limit=25` returns:

```
{
    "success": false,
    "reason": "etherscan server: No transactions found"
}
```

Can the ETH response be consistent with the other coins and return `{ "count": 0 }`

**Comment by drwasho** [comment]
Duplicate of #1754
