### ISSUE TITLE
Update Listing.Item.Sku.Quantity to string to support big.Int

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1757]
Sku.Quantity is used to track the amount of coins available for sale in a cryptocurrency listing. This needs to be updated to string to support big.Ints for ETH-related sales.

May be related to #1746

**Comment by rmisio** [comment]
> Sku.Quantity is used to track the amount of coins available for sale in a cryptocurrency listing.

If I'm not mistaken it's also used to track inventory for non-crypto listings whether the listing has variants or not.

Is it correct that now `bigQuantity` should be used for all inventory, crypto currency or otherwise?

**Comment by placer14** [comment]
@rmisio Yes, that's right. If you see cases with the listing shows values in the legacy keys, please let me know.
