### ISSUE TITLE
32-bit software versions do not store chat message timestamps correctly

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#1759]
Due to precision issues messages will be stored in the database incorrectly and have wildly inaccurate timestamps making communication confusing. We need to either deprecate 32-bit support or fix this timestamps issue for 32-bit servers.

**Comment by placer14** [comment]
Based on our internal discussions, I believe we have decided to remove 32-bit builds from future releases for the time being as it appears our download count for these are few. We can reassess how to support 32-bit builds if there proves to be a need for it.
