### ISSUE TITLE
Issue converting buyer order for compatibility in sales DB

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1765]
Here's what I see, I think the only place were we might need to do a conversion is in `GetUnfunded` But here's the issue. The conversion function is converting from a string coin to a `CurrencyDefinition` and as such it needs access to the node's currency lookup function to get the divisibility.

But the db package doesn't have access to the lookup function. What do you think is the best way to handle that. 

I could make it so that if the nil is passed into the conversion function for the lookup function that it just doesn't set the divisibility.

**Comment by placer14** [comment]
As discussed on the phone call, we can use `repo.AllCurrencies` as long as there are no collisions on the currency code between testnet and mainnet.
