### ISSUE TITLE
Moderator unable to resolve dispute

### ISSUE THREAD

**Issue by jenncloud** [OpenBazaar/openbazaar-go#1767]
https://openbazaar.zendesk.com/agent/tickets/11555

Message:

IMPORTANT: As a moderator I'm currently disputing an order. After collecting the information and evidence I would like to resolve the dispute but that's the problem: I can't.

After clicking on "resolve dispute" I can't award the funds to the seller because of the error message 
"The vendor's contract has not yet arrived. It will be sent over the next time they come online."
What does this mean and how I can resolve it? The error message is bullshit, because the buyer and vendor both were online multiple times for 2 weeks now and the message still not disappears. Any help would be really appreciated, I already tried to reach out to the team on Reddit but seems no on cares which is very frustrating. OpenBazaar is full of bugs and at the current state not usable.

**Comment by drwasho** [comment]
Chat with MG and I: Improve the log for 'error decrypting offline message' to display the orderId so we can determine if we're having issues decrypting order messages meant for the user.

**Comment by hoffmabc** [comment]
@placer14 @cpacia I'd like to close this as the associated Zendesk ticket is closed and extremely old with limited information. I've added an issue and PR addressing the logging for decrypting offline messages in lieu of this.
