### ISSUE TITLE
Have coinType be used consistently across the listing and listing index apis

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1768]
For crypto currency listings, the listing API refers to the coin being traded as `coinType`, but in the listing index, it comes back as `cryptoCurrencyCode`.

Can the listing index use `coinType` to be consistent with the Listing api?

**Comment by placer14** [comment]
Absolutely. I'll get this fixed in the next merge.

**Comment by placer14** [comment]
Dupe of #1727.
