### ISSUE TITLE
Modularise refund address

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#179]
The `Purchase` function in `order.go` refers to the SPV wallet for the refund address, e.g. line 66:

> order.RefundAddress = n.Wallet.CurrentAddress(spvwallet.EXTERNAL).EncodeAddress()

At Duo Search we want to allow users to enter a custom refund address. I would assume that the reference client would also want that.

To decouple the SVP wallet, modularising the refund address seems like the way forward.

**Comment by cpacia** [comment]
I can make it so if a refund address is included in the api call then it will use that one.

**Comment by JustinDrake** [comment]
That works. As a side note, the refund address code is duplicated (line 66, and line 117):

    order.RefundAddress = n.Wallet.CurrentAddress(spvwallet.EXTERNAL).EncodeAddress()

and 

	refundAddr := n.Wallet.CurrentAddress(spvwallet.EXTERNAL)
	order.RefundAddress = refundAddr.EncodeAddress()
