### ISSUE TITLE
Refund address transaction value error

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1803]
![image](https://user-images.githubusercontent.com/3887694/67063104-d1e8b780-f1a8-11e9-96fa-a4a0a1e6bc64.png)

**Comment by rmisio** [comment]
@placer14 Your initial instinct on #1812 was correct. Not only is the refund value prefaced with a double hyphen, that actual number part is double what it should be.

For example, for my order, here's my payment:

```
        {
            "txid": "56ea55a1228d549a1c3cd9ca4cc8712aa0ebc0d18207652ca005cadd4f886b21",
            "value": 0,
            "confirmations": 590,
            "height": 1723653,
            "timestamp": "2019-10-22T15:28:58.358225Z",
            "currency": {
                "code": "LTC",
                "divisibility": 8
            },
            "bigValue": "165731"
        },
```

and here's the refund. Notice the value is double what was paid.

```
    "refundAddressTransaction": {
        "txid": "56d8ffcbcbccd428c5248062d3b595724a44e32722650dc6645702fbed869cb7",
        "value": 0,
        "confirmations": 589,
        "height": 1723654,
        "timestamp": "2019-10-22T15:29:15.683059Z",
        "currency": {
            "code": "LTC",
            "divisibility": 8
        },
        "bigValue": "--331462"
    }
```

If I go to a blockexplorer, the actual amount refunded is correct (matches the payment), so it's just ob-go giving the wrong figure in `bigValue` for the refund.

https://blockchair.com/litecoin/transaction/56d8ffcbcbccd428c5248062d3b595724a44e32722650dc6645702fbed869cb7

**Comment by drwasho** [comment]
@hoffmabc @cpacia @placer14 yes this is 100% still a problem:

If you want to replicate the bug:

1. Both buyer and seller can be online
2. Make a listing (listing hash: `QmZVLSXATnTzoV2bAWGv5FcPKLjcbbU5qy2Bwy6bQY8w3T`) with a moderator also running `ethereum-master`
3. Make a purchase with the buyer using testnet Litecoin
4. Refund the order from the seller
5. Fetch the order details from the buyer and you'll see something like this at the end of the JSON object:

```JSON
    "refundAddressTransaction": {
        "txid": "8d372db2aab41a27bc0f8bc066aaae1093c082af857785105740d69b8c818abf",
        "value": 0,
        "confirmations": 0,
        "height": 0,
        "timestamp": "2019-12-20T06:25:15.444763Z",
        "currency": {
            "code": "TLTC",
            "divisibility": 8
        },
        "bigValue": "--5024218"
    }
```

**Comment by drwasho** [comment]
Fixed in PR 1970
