### ISSUE TITLE
Listing hash in `GET /ob/order` is in the wrong format

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1804]
For both the buyer and seller, the listing hash in the response from `GET /ob/order/:orderId` is formatted as:

![image](https://user-images.githubusercontent.com/3887694/67064313-6ce39080-f1ad-11e9-989f-57b5d15ccaae.png)

However, we know listing hashes were updated to the new format, which is correctly returned by the sever in APIs like `GET /ob/listing/:slug`:

![image](https://user-images.githubusercontent.com/3887694/67064421-d82d6280-f1ad-11e9-9d6f-7549faeff459.png)

**Comment by cpacia** [comment]
I think we're probably going to have to leave this as it is. 

- This hash is not used to look up the listing on IPFS. Only to "validate" that the listing goes with the order. 
- Unfortunately the validation code also uses the same hashing and serializing algorithm so if we change it then it breaks backwards compatibility. 
- It may be possible to do a long rolling transition to change it in the future, but probably not needed for this release.
