### ISSUE TITLE
PUTListing does not update PriceCurrency (and possibly other items)

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1819]
The failure case looks like this:

1. `POST /ob/listing` within the `item.priceCurrency` populated.
2. `PUT /ob/listing/:slug` with the `item.priceCurrency`
3. `GET /ob/listing/:slug` and observe the value is not updated

Would like to understand the scope of the missing fields and if others are missing.

**Comment by rmisio** [comment]
@drwasho FWIW, this does work for me. Maybe there's something unique about your data that's tripping it up?

Anyhow, I just changed `item.priceCurrency.code` from `USD` to `LTC`, send it over in a `PUT` and then re-fetched the listing and it was updated.

Let me know if you want to provide specific data.

**Comment by placer14** [comment]
I've updated the scenario in which it occurred for me originally.

**Comment by rmisio** [comment]
> I've updated the scenario in which it occurred for me originally.

@placer14 Thanks for posting, but that scenario works for me.

**Comment by jjeffryes** [comment]
I can replicate this.

I created a listing with USD, and tried changing it to AED. It saved normally, but when I refreshed the listing and edited it, it was USD again. The GET call had `lisitng.item.priceCurrency` of USD.

I tried changing it to ZWL, and the same thing happened, it changed back to USD.

**Comment by jjeffryes** [comment]
Further details: changing the currency to a crypto currency works correctly, it appears to only have problems when changing to a fiat currency.

Weirdly, if you change it to a crypto currency, for example, BTC, *then* change it to a fiat currency, such as AED, it works correctly.

**Comment by jjeffryes** [comment]
Deleted those comments. I thought I had reproduced it, but instead I was fooling myself by being lazy with creating similar listings, and it was working fine.

**Comment by placer14** [comment]
Okay, thanks for investigating. I'll adjust the labels appropriately.

**Comment by drwasho** [comment]
@placer14 I'm on the lastest commit of `ethereum-master` and I can't reproduce this issue; if you can't, let's close this.
