### ISSUE TITLE
Decouple Wallet from Purchase

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#182]
At Duo Search we want buyers to make payments from their personal wallet (not the OpenBazaar wallet). I would assume the reference client also wants to provide that option.

Right now, the `Purchase` function in `order.go` is deeply coupled with `Wallet` (used 16 times in the code). The [refund address](https://github.com/OpenBazaar/openbazaar-go/issues/179) is just one instance of a larger opportunity to decouple `Wallet` from `Purchase`.

**Comment by cpacia** [comment]
It's mostly using the wallet to get keys and to listen for transactions. That's core functionality. I don't see anyway to get rid of it.

**Comment by JustinDrake** [comment]
Ok, it looks like I was being stupid. I'm a bit confused by this line of code. What is the `RefundFee`? 

    contract.BuyerOrder.RefundFee = n.Wallet.GetFeePerByte(spvwallet.NORMAL)

**Comment by cpacia** [comment]
Buyer specifies what bitcoin fee he wants the vendor to use if he has to refund it.
