### ISSUE TITLE
Refund after fulfillment 

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#184]
`POSTRefund` has the following piece of code:

```
if state != pb.OrderState_FUNDED {
    ErrorResponse(w, http.StatusBadRequest, "order must be funded before refunding")
    return
}
```

What if the vendor has fulfilled the order (e.g. sent the goods) but the goods were damaged or the buyer was not satisfied, and the vendor wants to make a refund?

Should the vendor be able to make a refund if the order state is `FULFILLED`?

**Comment by cpacia** [comment]
The code snippet above only checks that it was funded. Should still work if it's fulfilled.

**Comment by JustinDrake** [comment]
As I understand, if the state is `FULFILLED` then `if state != pb.OrderState_FUNDED` fails, so the function `return`s, and `i.node.RefundOrder` doesn't get called.

	if state != pb.OrderState_FUNDED {
		ErrorResponse(w, http.StatusBadRequest, "order must be funded before refunding")
		return
	}
	err = i.node.RefundOrder(contract, records)

**Comment by cpacia** [comment]
Looks like you're right.
