### ISSUE TITLE
Dead code in moderation.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#185]
In `moderation.go`, the `init` function uses `log.Fatal` but `log` is not imported. This should be a compile error but it seems that the whole file is dead code.

**Comment by hoffmabc** [comment]
Is this not an issue anymore?

**Comment by JustinDrake** [comment]
I must be missing something as `SetSelfAsModerator` is used `jsonapi.go`.

**Comment by cpacia** [comment]
log is defined in core.go.

This isn't dead code it's used in jsonapi as you mentioned.
