### ISSUE TITLE
Multi-identity node

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#186]
At Duo Search we want multi-identity nodes to power our in-browser chat and purchases. A multi-identity node acts just like the current single-identity node, but has multiple identity keys and multiple corresponding GUIDs and IPFS identities. (Note that Duo Search is mainly interested in buyer-only nodes.)

Every time a user starts engaging with a vendor (e.g. via chat), we want to give that user a fresh identity. This keeps every Duo Search user independent (in the case of chat, independent chat threads) and it's great for privacy.

Is OB1 interested in integrating multi-identity nodes in the reference server (this repo)? I'm opening this issue as preparation for the partners call.

I see the refactor as relatively straightforward:

1. In `openbazaard.go`:
 - Change `core.Node.IpfsNode` to `core.Node.IpfsNodes`
 - Extend the IPFS node setup to multiple nodes in the `Start` function
 - Extend `core.Node.IpfsNode.Close()` to all nodes
2. In `db.go`, rewrite `GetIdentityKey` to `GetIdentityKeys`
3. In `networkservice.go`, extend the `NetworkService` interface methods to take two `peer.ID`s (source and destination) e.g. `srcPeerId` and `dstPeerId`.
4. In `service.go`, extend `SendRequest` and `SendMessage` to take a source PeerId
5. In `handlers.go`, extend the handlers to take a source PeerdId (the buyer-centric message handlers to extend for purchases are `PING`, `ORDER_CONFIRMATION`, `ORDER_REJECT` and `ORDER_FULFILLMENT`).
6. In `net.go`, extend the message senders to take a source PeerId (the buyer-centric message senders to extend for purchases are `SendOrder`, `SendCancel` and  `SendOrderCompletion`.)
6. Extend the signing functions in the `core` folder for the business logic. The buyer-centric signing functions are:
 - In `order.go`, extend `SignOrder` to take a specific `IpfsNode` as argument
 - In `completion.go`, extend `SignOrderCompletion` to take a specific `IpfsNode` as argument
7. Extend the chat handler to take a `srcPeerId` when the chat code has been written

**Comment by cpacia** [comment]
I'm not too convinced the benefit here would be worth the cost. Almost the entire app would need to be refactored (more than what you have up there). And at the end of the day, IPFS is a fairly heavyweight application. Running multiple nodes on a single computer is possibly, but it's not really designed for that and people on slower machines would likely see a performance hit.

**Comment by tyler-smith** [comment]
This is something I've been very interested in myself. I attempted to make 1.0 multi-tenant but it ended up being not worth the effort. Unfortunately I was preoccupied when 2.0 was brewing otherwise I would have tried making it a design decision that we kept in mind.

At the end of the day I see multi-tenancy as feature for commercial use far more than for general users. I don't think it makes sense for OpenBazaar as a team to expend the effort to retrofit the 2.x codebase. If a company wants/needs it they'll need to build it themselves; either refactoring the reference code or building their own.

If/when there's a rewrite in the far distant future working toward a multi-tenancy would be nice.

**Comment by cpacia** [comment]
I would also point out that just spinning up a separate OpenBazaar node on the same machine isn't *that* much more heavyweight than spinning up a separate IPFS node inside an OB node.

**Comment by JustinDrake** [comment]
> spinning up a separate OpenBazaar node on the same machine isn't that much more heavyweight than spinning up a separate IPFS node inside an OB node

I believe that is incorrect, at least if the IPFS nodes are spun up in a smart way. Have a look at [IPTB](https://github.com/whyrusleeping/iptb) where 1000s of IPFS nodes can be spun up on the same machine.

**Comment by JustinDrake** [comment]
@tyler-smith: Duo Search will be putting the effort for multi-tenancy (at least for buyer-centric code). The question is would OB1 be interested in having our efforts integrated in the reference server?

**Comment by tyler-smith** [comment]
@JustinDrake As an OB member I certainly would like that 👍. I can't speak for what OB1 as a company would want. I don't think we have much of a use for multi-tenancy, but think that OB as a product does.

**Comment by JustinDrake** [comment]
To put a bit of flesh on the bones, the main [bottleneck seems to be RAM](https://github.com/whyrusleeping/iptb/issues/26).

@Kubuxu writes:

> It is about 100MiB per node right now, but we are working on reducing it further

**Comment by whyrusleeping** [comment]
We can do a lot of work to reduce the overhead of running many ipfs nodes in a single process. we're doing a good amount of work this quarter to reduce the resource consumption (ram, bandwidth, cpu). Let us know if you guys have any issues or need something prioritized :)

**Comment by JustinDrake** [comment]
Thanks @whyrusleeping. I'd be interested in how low you think the RAM consumption for IPFS nodes in a single process could be taken down to. For example, could it ever be 1MB per node?

OpenBazaar 2.0 should ship towards the end of Q1 2017, or Q2 2017. From a business perspective, it would be great if we could smoothly run 100 IPFS nodes in a single $5 DigitalOcean droplet. Is that an achievable goal for end of Q1 2017?

**Comment by Kubuxu** [comment]
Do you need to run multiple separate nodes, or do you multiple IPNS keys?

**Comment by JustinDrake** [comment]
The nodes can share resources but need different identity. I'm not familiar with the internals of IPFS, but I imagine they can share a single process, share a single repo (cached data), as well as share network connections (e.g. to the DHT).

**Comment by cpacia** [comment]
I don't think ipfs does any of that at the moment. I'm pretty sure it can't share network connections as they are encrypted using the identity key.

**Comment by JustinDrake** [comment]
Duo Search is taking a completely different approach, so multi-identity nodes is no longer something we are looking to have.
