### ISSUE TITLE
ob/purchase call hangs when offline order send times out

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1861]
1.) Attempt to make an offline purchase
2.) Simulate a slow connection or otherwise cause the order request to time out:
`12:50:28.029 [ERROR] [core/SendOrder] failed to send order request: timed out writing message`

The `ob/purchase` API call never comes back with an error. It just hangs until you force kill the server.

**Comment by hoffmabc** [comment]
@rmisio I have gone through and hard-coded timed out orders and timed out ticker endpoints to replicate this issue and even on a 0.1mbps bad connection it was still going through eventually.

I'm not sure how else to replicate this. Perhaps there is something else causing the hang here.

**Comment by hoffmabc** [comment]
If currency is not tracked, that just means it falls back to the default fee value.

**Comment by rmisio** [comment]
ok, then I don't know why this is happening for me and fairly regularly. Is it possible it would still go through after more than 10 minutes (I'm pretty sure I've waited at least that long)?

It looks at least one other person is seeing this:

https://github.com/OpenBazaar/openbazaar-desktop/issues/1779

**Comment by rmisio** [comment]
@hoffmabc Yeah, I don't know if this is a node having the "currency not tracked" issue. I do know the logs clearly show this:

`12:50:28.029 [ERROR] [core/SendOrder] failed to send order request: timed out writing message`

Which looks like a failure that prevents the purchase. But... this failure is never bubbled back to the UI via a 500 error on the API. Instead, the call just hangs.

Can you find in the code where that log message would happen, simulate an error and if you're able to replicate the order hanging, fix it so the call comes back with an error? Otherwise, it's a horrible UX where the user has a ghost never-ending HTTP call clogging up their request queue, until they restart.

**Comment by hoffmabc** [comment]
All that error means is that an online purchase did not work.

**Comment by rmisio** [comment]
@hoffmabc You may be conflating this bug with another bug. This bug is specifically about an offline order failing.

> All that error means is that an online purchase did not work and yes this is what I did. I forced it to error on that.

Ok, and did the purchase API call return an error to the client... or does it just remain in pending state?
