### ISSUE TITLE
Dispute payout bigAmounts do include a currency definition

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1877]
Currently a dispute payout amount is just a string based number, for example:

```
                "buyerOutput": {
                    "address": "LfmkwWVgjV6ncAKhakvQF8MqD2AzB9Kjfw",
                    "amount": 0,
                    "bigAmount": "502381"
                },
```

That leaves ambiguity as to what the divisibility is.

- Should the divisibility of the embedded payment be used? (Keep in mind that the user may have provided a custom divisibility when they funded the order)

```
            "payment": {
                "bigAmount": "542200",
                "amountCurrency": {
                    "code": "LTC",
                    "divisibility": 8
                }
            },
```

- Should the divisibility from the currency definition api be used (`/wallet/currencies`)?

It's maybe clearest if a currency definition was embedded with the actual dispute payout (it could probably be one for all three parties).

Alternatively, if we go the implicit approach can the ambiguity please be clarified (and if it's not done so already, update the api docs so it's clear)?

**Comment by rmisio** [comment]
@cpacia @placer14 Until this issue is fixed and the ambiguity remains, what divisibility should clients be using for the dispute payout amounts? Should it come from the wallet currencies api or from the currency definition that's embedded with the order payment?

**Comment by hoffmabc** [comment]
@rmisio it looks like the Dispute Resolution payout struct provides for a universal payout current definition per your last suggestion.

Is it just not being populated? 

```
type DisputeResolution_Payout struct {
	Sigs                 []*BitcoinSignature              `protobuf:"bytes,1,rep,name=sigs,proto3" json:"sigs,omitempty"`
	Inputs               []*Outpoint                      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	BuyerOutput          *DisputeResolution_Payout_Output `protobuf:"bytes,3,opt,name=buyerOutput,proto3" json:"buyerOutput,omitempty"`
	VendorOutput         *DisputeResolution_Payout_Output `protobuf:"bytes,4,opt,name=vendorOutput,proto3" json:"vendorOutput,omitempty"`
	ModeratorOutput      *DisputeResolution_Payout_Output `protobuf:"bytes,5,opt,name=moderatorOutput,proto3" json:"moderatorOutput,omitempty"`
	PayoutCurrency       *CurrencyDefinition              `protobuf:"bytes,6,opt,name=payoutCurrency,proto3" json:"payoutCurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}
```

**Comment by hoffmabc** [comment]
Ok looks like it's not included so I submitted a PR to add this.

**Comment by rmisio** [comment]
@hoffmabc I think you need to collaborate with @placer14  because he has other ideas. He mentioned something about using the divisibility from `item.pricingCurrency` in the listing, but that doesn't work because the item is often priced in a different currency than the dispute payout.

I think maybe what he wants if he doesn't want to duplicate the divisibility everywhere is to use the divisibility of the payment.

**Comment by hoffmabc** [comment]
Well the fix I submitted just populates field already present but not being used. If @placer14 wants to do something different then that’s fine as well.
