### ISSUE TITLE
The vendorOrderConfirmation bigRequestAmount does not include a divisibility

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1878]
This issue is similar to:
https://github.com/OpenBazaar/openbazaar-go/issues/1877

Since the `bigRequestAmount` does not include a currency definition with a divisibility, there's some ambiguity as to which divisibility to use. Should it come from the wallet currencies API or from the currency definition in the embedded order payment?

**Comment by drwasho** [comment]
I don't believe we need to specify divisibility any more; closing for now, but please reopen if I'm mistaken.
