### ISSUE TITLE
ETH-Precision PATCH profile returns nothing

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1879]
When doing a PATCH on profile to save moderator info, nothing is returned. 

The data below was sent, and the status of the call was 200, but nothing was returned which causes an error in the client. We expect at least {} to be returned on calls.

This is happening on ethereum-master 257a3e84 

```
{
  "moderator": false,
  "moderatorInfo": {
    "fee": {
      "feeType": "PERCENTAGE",
      "percentage": 5
    },
    "description": "test",
    "termsAndConditions": "test",
    "languages": [
      "en-US"
    ]
  }
}
```

**Comment by hoffmabc** [comment]
@jjeffryes I think this is out of date since the call has changed. 

{ 
   "moderator": false,
   "moderatorInfo":{ 
      "fee":{ 
         "feeType":"PERCENTAGE",
         "fixedFee":{ 
            "bigAmount": "0",
            "amountCurrency": { 
               "code":"USD",
               "divisibility": 2
            }
         },
         "percentage": 5
      },
      "description": "test",
      "termsAndConditions":"asdf",
      "languages":[ 
         "en-US"
      ]
   }
}

**Comment by jjeffryes** [comment]
@hoffmabc I'm not sure what you mean, I have the latest code for the desktop and server, it is not sending a fixed fee object, and is getting nothing as a response.

**Comment by jjeffryes** [comment]
This is fixed on ethereum master
