### ISSUE TITLE
Remove profile validation that disallows mod info if moderation is turned off

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1880]
Please remove this validation, which was added recently:

`invalid profile: moderator information is provided but moderator is not enabled`

Moderators turn moderation off temporarily all the time, from anecdotal evidence.

The desktop client UX was designed to support providing and changing moderation info independent of whether moderation is off or on:

![image](https://user-images.githubusercontent.com/794517/69762991-6f80c080-1131-11ea-9437-eb685e57e056.png)

If the server wants to put in validation preventing that, I think we need to have a larger meeting where Wolf could revisit the designs and in general we could discuss whether the proposed benefits of this change justify the added scope.

**Comment by drwasho** [comment]
Agree @rmisio 

We shouldn't be introducing any new validation that breaks patterns we've introduced in the client for years... I saw this not to assign blame or anything, we have a big app and sometimes it's hard to know when a seemingly logical validation will cause problems for one of the client implementations.

I think the most prudent thing to do now is remove that validation until we have the time to discuss this further post-ETH lauch.

**Comment by hoffmabc** [comment]
What branch is this on @rmisio I can't find it in the `eth-master` branch of go.
