### ISSUE TITLE
ETH Precision- ETH to LTC conversion is incorrect on purchase

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1889]
This is happening on Dispute payout precision OpenBazaar/openbazaar-desktop#1838 and ethereum-master latest as of 11-27-19.

I made a purchase of an item at a price of 0.0000002 ETH in LTC (the item price is 0.0000000001, the quantity was 2000).

The receipt on the purchase page showed a total of 0.00000064 LTC, which seems right.

But the purchase call had an amount of 314000, or 0.00314 LTC when it was submitted to the server.

This is the listing `ob://QmVF14jczeRFii8ptcvXScFVkHWCg9WnThU2dPoqqDjLep/store/test-eth-precision`

This is the data sent:

```
{
  "address": "",
  "addressNotes": "",
  "alternateContactInfo": "",
  "city": "",
  "countryCode": "",
  "items": [
    {
      "listingHash": "QmVC7NMWYQ9NwQgS9ZKmns99xhqsQH4z9kF6HM1ARoKZ1G",
      "options": [],
      "shipping": {
        "name": ""
      },
      "memo": "",
      "coupons": [],
      "bigQuantity": "2000"
    }
  ],
  "moderator": "",
  "paymentCoin": "LTC",
  "postalCode": "",
  "shipTo": "",
  "state": ""
}
```

This is the response:
```
{
    "amount": {
        "amount": "314000",
        "currency": {
            "code": "LTC",
            "currencyType": "crypto",
            "divisibility": 8,
            "name": "Litecoin"
        }
    },
    "orderId": "QmWT4gdyQSvEH4aDaodtBgkNbUUafpT8g5v1d9iLYPVgXP",
    "paymentAddress": "ltc1q7frr4ywwc8a4alntwqlznrug57httajf63mwxqxv8h3mu8rw799s4kcghe",
    "vendorOnline": false
}
```

**Comment by jjeffryes** [comment]
This problem is still reproducible. 

As of today, the client is calculating an estimated total of 0.00000065 LTC, but purchase is returning 0.00356 LTC.

**Comment by rmisio** [comment]
I'm also experiencing this issue.

**Comment by rmisio** [comment]
It was hypothesized that this bug only affects purchases that are priced below `0.00000001`. I found this was not the case:

I had a purchase price of `0.00002999 ETH` and the resulting LTC funding total the server calculated was `0.0018 LTC`, which if my math is right is not correct.

`1 ETH` is currently `$127`. `1 LTC` is currently `$40`. So `0.00002999 / 3.175 = 0.00000944`, which a good ways off from `0.0018`.

**Comment by rmisio** [comment]
Well, the conversion was right on a purchase of 1.00000001 ETH, so it looks like this issue probably is limited to low priced purchases, we just don’t know how low other than no lower than 0.00002999 ETH.

**Comment by hoffmabc** [comment]
![image](https://user-images.githubusercontent.com/45482/71201741-aa75a000-2268-11ea-9afd-50f1bd3ff204.png)

**Comment by drwasho** [comment]
I need to write a test for this in Postman to see if it's still a problem after the recent currency conversion code was added.
