### ISSUE TITLE
Error handling in Purchase()

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#189]
The `Purchase` function in `order.go` has instances of silently ignored errors. For example,

    n.Wallet.AddWatchedScript(script)

and 

    n.Datastore.Purchases().Put(orderId, *contract, pb.OrderState_CONFIRMED, true)

and

    refundAddr := n.Wallet.CurrentAddress(spvwallet.EXTERNAL)

In the last example, the function `CurrentAddress` intentionally discards the error, which seems strange given the important of the refund address:

     addr, _ := w.rpcClient.GetAccountAddress(account)

For the line `n.SendOrder(contract.VendorListings[0].VendorID.Guid, contract)`, the only error check is `err != nill` to determine "Vendor offline". This is a bit blunt.

**Comment by cpacia** [comment]
I'll look into them

**Comment by jjeffryes** [comment]
@cpacia is this issue still open?

**Comment by JustinDrake** [comment]
It turns out openbazaar-go has many errors that are ignored throughout the repository. There are various tools to help you find such instances, e.g. https://github.com/kisielk/errcheck. Actually, I would run the whole repo under https://github.com/alecthomas/gometalinter to find low-hanging bugs.

**Comment by tyler-smith** [comment]
Have you done that?

**Comment by tyler-smith** [comment]
All errors should always be handled. If you find some that are not please feel free to patch it or start a discussion on how to best handle the failure if it's not straightforward.
