### ISSUE TITLE
Custom HTTP Transport Potentially Causing Timeouts

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#1899]
In order to support the TOR transport within OpenBazaar we have created custom HTTP clients throughout the codebase. When we implemented this we not only created a custom transport dialer for TOR but we also made a small tweak to the default transport configured and set it to be a net.Dial. 

```
dial := net.Dial
	if dialer != nil {
		dial = dialer.Dial
	}
	tbTransport := &http.Transport{Dial: dial}
	client := &http.Client{Transport: tbTransport, Timeout: time.Minute}
```

For some reason net.Dial does not act similar to if we just use the default transport afforded us by the http.Client object. The result though is that when making large amounts of calls to a common remote HTTP address we can see recurring timeouts like below:

```
12:58:05.276 [ERROR] [client/doRequest] timed out executing: Get https://ltc.api.openbazaar.org/api/utxo/LKT4RHgAboxb1LGxa5wpfWNMYLm4igLTcQ: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
12:58:05.276 [ERROR] [client/doRequest] timed out executing: Get https://ltc.api.openbazaar.org/api/utxo/LX44xwZWiSBqEANJzk6mdRPaqGcrngS6xP: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
12:58:05.276 [ERROR] [client/doRequest] timed out executing: Get https://ltc.api.openbazaar.org/api/utxo/LNPPRUkYxK69EQwT7EnBdnPZRfMJU8vZpE: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Fixed in https://github.com/OpenBazaar/openbazaar-go/pull/1898

The PR above aims to revert back to using default transports and restore that execution to alleviate the issue.

**Comment by hoffmabc** [comment]
https://github.com/OpenBazaar/openbazaar-go/pull/1898#issuecomment-565293843

**Comment by placer14** [comment]
Resolved with https://github.com/OpenBazaar/openbazaar-go/pull/1925
