### ISSUE TITLE
On GET /ob/listing/<slug> convert v4 listings to v5

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1903]

**Comment by hoffmabc** [comment]
This is a dupe for #1846.

**Comment by rmisio** [comment]
@hoffmabc Is it a dupe? #1846 talks about the server panicing on `GET /ob/order/:orderID`. This one is about `GET /ob/listing/<slug>` (and there's no server panic - the client does throw exceptions though on unrecognized data).

Or are you say that the underlying cause of #1846 is an unnormalized listing fetch and fixing that cause would take care of both #1846 and this bug?

**Comment by hoffmabc** [comment]
The latter. I was trying to consolidate these issues.
