### ISSUE TITLE
On GET /ob/profile/<peer-id> convert profile to the latest schema

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1904]
I'm not sure if this is the only thing requiring conversion, but mod fees need to be updated (e.g. an integer fixed fee `amount` of 1 should be a `bigAmount` of `"1"`. Also, `currencyCode` should now be a full currency definition in `amountCurrency`).

**Comment by hoffmabc** [comment]
Profile needs to be normalized for the new version (i.e. moderation info).

**Comment by hoffmabc** [comment]
- Profile schema still includes old attributes so we can just include them for v4 nodes so that they don't bomb against reading v5 profiles
- This fix requires a migration of v5 users profiles to v5 format AND normalization for reading profiles.

**Comment by placer14** [comment]
FYI, https://github.com/OpenBazaar/openbazaar-go/pull/1882 contains the normalization behavior for reading profiles.
