### ISSUE TITLE
Consider Adding Additional Tests

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1908]
Below is a non-exhaustive list of tests to consider adding to the server. Each one could be covered by unit tests, QA tests, or some other kind of tests, based on what would be most efficient and effective.

## Try to figure out a way to efficiently test multiple order types.
One recurring gap is current tests tend to cover only one kind of order (direct/moderated, online/offline) and one type of listing (physical, digital, service, crypto) each.

Rather that write more individual tests, it seems like it would be ideal to create a method of creating tests that can be set to use each of the 16 different combinations of orders so each test can be run against all 16 combinations.

## If it doesn't exist, also automate testing all the currencies, including ETH.
Any test involving detecting or creating a crypto transaction should test all of our supported currencies. If we don't already have something in place, we should create a system to automate this so we can be confident all currencies work for all tests.

## Modified Existing Tests to Consider
- [x] **Complete Order:** add tests for direct offline and moderated offline.
- [x] **Complete Disputed Order:** It looks like we currently only test this for online orders. We should also test it for offline moderated orders.
- [ ] **Complete Moderated Order with Timeout:** how is this different from the CompleteModeratedOnlineTest? It looks like it tests the same things.
- [ ] **Disputed Escrow Timeout Release:** it would be good to test whether vendors can finalize payments after an order has timed out.
- [x] **Fulfill Order:** it would be good to test direct offline, and moderated online/offline too.
- [x] **Purchase:** it would be good to have tests for Physical and Service listings.
- [x] **Extend Purchase Tests:** there are purchase only tests for Moderated Online/Offline purchases, we could extend those to cover some of the missing scenarios above.

## New Tests to Consider
- [x] **Shipping Charge on Purchase:** we should test if shipping on 1 or more items is added to the total correctly (I'm not sure if we need separate test for 1 vs multiple items).
- [x] **Additional Shipping Charge on Purchase:** we should test if shipping charges are added to the total correctly when there is a different charge for the 2nd and later items.
- [x] **Purchase Error Tests:** there are many scenarios when purchase attempts should return errors that we don't test, it would be good to cover as many of those as we can.
    - ex: missing or invalid data for all the listing types.
    - ex: sending a moderator the store doesn't allow.
    - ex: ordering a quantity of zero.
- [x] **Purchasing Variants:** we should test if a purchase with variants of various prices and quantities returns the expected total price and the order works correctly.
- [x] **Currency Conversions:** we've caught bugs with purchase calls returning incorrect amounts when the listing is priced in one currency and purchased in another. We should have tests that cover a variety of different purchasing vs. listing currencies, both fiat and crypto.
- [x] **Purchases with Coupons:** we should have some tests to make sure if coupons are applied, both fixed price and percentage, the total returned from the purchase is correct.
- [ ] **Notifications:** also checking to see if the expected notifications were fired on each step of the order process would be good, maybe as part of the other tests?
- [ ] **Illegal Disputes:** we could add tests to make sure disputes can't be triggered when they should be disallowed, such as a buyer when the order isn't paid for, or a seller when the order isn't fulfilled, or both after the order is completed, etc.
- [ ] **Illegal Order Flows:** in general, tests to make sure orders can't be moved to disallowed order states (fulfilled to pending, complete to fulfilled, etc.) would be good.

## v4 to v5 Tests
I'm not sure what the best approach here is, but it'd be really nice if we could automate testing whether a node with existing v4 orders that is migrated to v5 still passes all of the tests that apply to in-flight orders.

**Comment by hoffmabc** [comment]
I thought that there was no ability to cancel a moderated offline order. What's the intended use case here @jjeffryes @cpacia ?

**Comment by hoffmabc** [comment]
We also have tests for:
* direct offline
* moderated offline

Is there something special you were intending @jjeffryes ?

**Comment by jjeffryes** [comment]
Mistake on my side, I forgot some order operations can't be done on moderated orders because they're 2 of 3 signatures. I'll update.

**Comment by drwasho** [comment]
@jjeffryes @hoffmabc I created a list of compatibillity tests we should consider: https://github.com/OpenBazaar/openbazaar-go/issues/1785

**Comment by drwasho** [comment]
After reviewing the QA tests, I have the following recommendation:

- [ ] 1. These tests need to be batched together so that they run within a single environment. This will significantly speed-up how quickly these tests can be run and minimize the resources required to run them.

Presently, each scripted testing scenario creates a fresh testing environment. This involves installing BCHD and instatiating 3 nodes (buyer, seller, and moderator where applicable):

![image](https://user-images.githubusercontent.com/3887694/74209789-fe36bf80-4cd4-11ea-8803-789efabeba6c.png)

Creating a fresh testing environment takes a non-trivial amount of time, with apparently very little gain. 

It makes more sense to create a single instance of BCHD and the obgo nodes (buyer, seller, moderator), create the listings you need once, and cycle through all of the testing scenarios between these nodes. 

At the very least we'll eliminate a significant amount of time the tests take for installation.

### OR

- [ ] 2. If there is a compelling reason to justify creating a unique environment for each test, then we should consider parallelising these tests so a well-resourced VPS can run these tests in a fraction of the total time it that it takes presently.

---

I acknowledge this requires some investment of time up front, but ultimately I believe it may be worth it given the amount of testing we will be doing for implementing ETH.

**Comment by drwasho** [comment]
These are the order-specific QA tests that we have coverage for in the `ethereum-master` branch:

**UTXOs**
The coin used for purchasing is Bitcoin.

![image](https://user-images.githubusercontent.com/3887694/74210921-612a5580-4cd9-11ea-9e1d-482483e52a86.png)

**Ethereum**
The coin used for purchasing is ETH.

![image](https://user-images.githubusercontent.com/3887694/74210936-743d2580-4cd9-11ea-8233-6657ee4a8906.png)

- As @jjeffryes highlighted above, our tests predominantly examine orders between online nodes buying/selling phsyical listings
  - We only have 1 test for digital listings, and no tests for services.
  - The Ethereum QA tests are a replica of the UTXO tests in terms of scenario coverage.
- Fortunately we have tests in place to cover all the major order states for [direct](https://i.imgur.com/SNWxKbX.jpg) and [moderated](https://i.imgur.com/wE6xk4W.jpg) orders, both online and offline, we just don't test them consistently between the listing types.

---

We also have some unnecessary tests whose steps are included in other tests. For example:

![image](https://user-images.githubusercontent.com/3887694/74211323-1e697d00-4cdb-11ea-9c98-872e30584261.png)

If `CompleteModeratedOnlineTest` passes, it stands to reason that what we're testing for in `PurchaseModeratedOnlineTest` has passed too given that they share the same steps. These are the tests that can be removed (and their ETH equivalents):

1. Purchase direct online
2. Purchase moderated online
3. Purchase direct offline*
4. Purchase moderated offline*

*can be removed in 'Complete direct/moderated offline' tests are written to replace them

We may also want to consider eliminating 'dispute close buyer' and '
dispute close split
dispute close vendor

**Comment by drwasho** [comment]
Reclosing this issue since the missing tests have been added to Postman
