### ISSUE TITLE
ZCash sighash upgrade

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1928]
The ZCash blossom hardfork changes the sighash algorithm for replay protection. Unfortunately, unlike BCH which accomplishes this by changing the algorithm for the old version and by keeping the algorithm the same post-fork, ZCash requires all wallets to upgrade to the new algorithm. 

For us this means we need to make a small one-line change to the sighash algorithm so transactions can be made. Prior to this change blockbook will reject transactions signed with the old algorithm. 

This does potentially create a more serious surface area for bugs if funds are in a 2 of 3 escrow address and one party signed to release the funds pre-fork and the other party post-fork as the transaction will be invalid. 

We are considering a change to the protocol to request a party to resign the transaction, though this does not guarantee that party will come back online to do so.

**Comment by jjeffryes** [comment]
For acceptance criteria, we should run through all order scenarios with ZEC to make sure they all continue to function as expected. 

We'll need to step through the purchase and order tests in https://github.com/OpenBazaar/openbazaar-desktop/issues/1766 for ZEC, and at minimum a subset of the same tests for other coins to make sure they're not affected.

**Comment by placer14** [comment]
Resolved with #1926
