### ISSUE TITLE
Improve Error Logging for `unable to decrypt offline message` Message

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#1938]
Related to https://github.com/OpenBazaar/openbazaar-go/issues/1767

**Comment by drwasho** [comment]
@placer14 and I discussed this some time back; we really need logging to determine whether the message we're trying to decrypt was meant for the node (and if so, the type and orderId if applicable) or whether it was meant for another node with a similar peerId prefix.
