### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#194]
OB 1.0 did not support IPv6. This prevented Duo Search from making use of the 16 IPv6 addresses every DigitalOcean droplet is allocated. Does OB 2.0 support IPv6? Looking at the code I see IPv4-centric snippets of code:

    addr, err := gatewayMaddr.ValueForProtocol(ma.P_IP4)

and

    if addr != "127.0.0.1"

and

    `short:"s" long:"stun" description:"use stun on µTP IPv4"`

and

    if x.STUN && p[0].Name == "ip4"

and

    cfg.Addresses.Swarm = append(cfg.Addresses.Swarm, "/ip4/0.0.0.0/udp/"

**Comment by cpacia** [comment]
Yes IPv6 is supported and used.

**Comment by JustinDrake** [comment]
Ok, great!
