### ISSUE TITLE
Don't output ETH fetching tx rcpt not found as an error.

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1942]
When you spend ETH, your terminal gets filled with `[ERROR] [ethwallet/Spend] error fetching txn rcpt: not found` messages.

It would be nice to not display that as an error, since as I understand it that's actually things working as intended.

**Comment by amangale** [comment]
Fixed it in PR #1915 (https://github.com/OpenBazaar/openbazaar-go/pull/1915/commits/bc0091b25aed82e2712d09d0df07f9ee25ef3e8e)
