### ISSUE TITLE
Why only validate the first listing?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#195]
In `order.go` it seems only the first listing is being validated. Is that correct?

    validateListing(rc.VendorListings[0])

Actually, for some strange reason, `contract.VendorListings[0]` is singled out 19 times in `order.go`. This seems like a bug.

**Comment by cpacia** [comment]
The listing list is only used when building an order with multiple items. There should never be a listing published on the network that contains more than one in that field.

**Comment by tyler-smith** [comment]
If that's the case, it seems like we should either make it not a slice or at least validate that there's only 1. I don't think we should assume everything on the network will be published by the reference client.

**Comment by hoffmabc** [comment]
Is this a won't fix or will we be updating this one?

**Comment by cpacia** [comment]
I'm going to refactor it at some point
