### ISSUE TITLE
New install error.

### ISSUE THREAD

**Issue by ultra-pool** [OpenBazaar/openbazaar-go#1953]
`go get github.com/OpenBazaar/openbazaar-go
# runtime
/usr/local/go/src/runtime/map.go:64:2: bucketCntBits redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:65:2: bucketCnt redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:76:2: maxKeySize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:77:2: maxValueSize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:75:17
/usr/local/go/src/runtime/map.go:82:2: dataOffset redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:91:2: empty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:89:19
/usr/local/go/src/runtime/map.go:92:2: evacuatedEmpty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19
/usr/local/go/src/runtime/map.go:93:2: evacuatedX redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:94:2: evacuatedY redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:95:2: minTopHash redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:95:2: too many errors`
Any ideas how to fix this.
Ubuntu 16 Server

**Comment by placer14** [comment]
@ultra-pool What does `go version` return for you?

**Comment by ultra-pool** [comment]
1.11

**Comment by placer14** [comment]
I wasn't able to reproduce this error locally with 1.11. A quick search around the internet suggests that your go installation might be installed on top of a prior installation and may require some cleaning. (https://discourse.gohugo.io/t/hugo-0-48-will-be-go-1-11-only/13826/22)

If it's easy for you to do, you might consider that. Further, ob-go is currently using 1.12 and IIRC 1.11 has some deficiencies which may prevent you from running the software. If you take the above task on, consider a go upgrade as well.

I don't believe this is related to ob-go specifically so I'm going to close this. If you're still having challenges, you're welcome to post an update here and we'll do our best to help.
