### ISSUE TITLE
Abstract away the 5 verifySignaturesOn* functions

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#196]
(Feel free to tag as TODO, and assign me.) The following 5 functions do a lot of the same stuff and there's a significant opportunity to DRY up the code. It took me quite a long time to parse and precisely understand what was going on in those functions, as the code in uncommented and a bit messy. It's important that these crypto functions be crystal clear for review.

- `verifySignaturesOnOrderCompletion`
- `verifySignaturesOnOrderConfirmation`
- `verifySignaturesOnOrderFulfilment`
- `verifySignaturesOnListing`
- `verifySignaturesOnOrder`

**Comment by JustinDrake** [comment]
This refactor is being postponed for #199.

**Comment by yurizhykin** [comment]
I experimented a bit with abstracting those into `verifySignature()` function, that accepts pubkey, message  and function to call from inside to obtain signatures (which is exactly in what they differ). Will submit a PR for review, if that's ok.

**Comment by cpacia** [comment]
@yurizhykin that would be great. Just keep in mind I just merged a change to that code today so make sure you're working with the latest.

**Comment by yurizhykin** [comment]
@cpacia , yep, I specifically waited until that PR was merged:)
