### ISSUE TITLE
Interoperability and code gen

### ISSUE THREAD

**Issue by gedw99** [OpenBazaar/openbazaar-go#1969]
Is jsonapi.go derived from an IDL of spurts.
It's huge.

I am looking to gen the API client in dart.
But can see ant proto's etc. Just the giant hand coded jsonapi go.

**Comment by placer14** [comment]
I'm afriad the jsonapi.go file is completely manual and not generated.

**Comment by gedw99** [comment]
thanks @placer14 !!
