### ISSUE TITLE
Bug: POST /ob/purchase failing inconsistently

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1986]
When it fails, it returns with this error:

![image](https://user-images.githubusercontent.com/3887694/74630931-60953180-51a7-11ea-8cc5-ce56e97d5d67.png)

**Comment by drwasho** [comment]
Same payload tried again just a few moments later successfully went through.

**Comment by hoffmabc** [comment]
Where were the amounts of the purchases? Different or same?

**Comment by drwasho** [comment]
@hoffmabc this API call doesn't involve the user inputting any amounts, and since the API error'd, the amounts for the purchase didn't return.

**Comment by hoffmabc** [comment]
Well I’m wondering if it’s precision related when calculating payment amounts.

**Comment by drwasho** [comment]
I've run several tests without running into this problem, so closing for now.
