### ISSUE TITLE
Change bitcoin signature handling

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#199]
Currently the Ricardian Contract structure calls for all objects to be signed with both the identity key and bitcoin key. 

The reason for the bitcoin signature is that there is a possible attack that goes like:
```
1. Vendor receives a moderated order.
2. Vendor generates a new OpenBazaar identity key.
3. Vendor creates a new Ricardian Contract identical to the order he just receives but swaps out the buyer's identity for the new fake identity and proceeds to sign the contract with the fake identity key and his own identity key.
4. The vendor files a dispute with the moderator saying he sent the goods and the buyer went AWOL before releasing the funds. The malicious Ricardian Contract is sent along to the moderator.
5. The moderator checks the signatures on the contract and notes everything validates. He attemps to contact the buyer to see what's up, but the message is sent to the fake identity and not to the buyer's real identity, so the moderator either never gets a response or the vendor responds on the fake identity and says FU!
6. Moderator releases the funds to the vendor.
```

A similar attack can be crafted by the buyer as well.

By signing the listing and order with the key each party uses as part of the multisig, this attack is thwarted.

The funds were sent to an address which uses `buyerKey`, `vendorKey`, `moderatorKey`. If the vendor were to try the above attack, he would need the `buyerKey` in order to create a fake Ricardian Contract. 

If he tries to fake it by changing the buyer's public key in the `Order` and signing with this new key, then the moderator will calculate that `buyerKey` + `vendorKey` + `moderatorKey` != the p2sh escrow address the vendor wants the funds released from.

What we need to consider is if we can simplify the contract signing. Right now the signature fields looks like:

```
message Signatures {
    Section section = 1;
    bytes guid      = 2;
    bytes bitcoin   = 3;
```

But as far as I know only the listing and order needs the bitcoin signature. Can anyone think of an attack where the other contract sections would also need a bitcoin signature?

If it's only those two sections that need the bitcoin signature.... and obviously only moderated orders need it, can we refactor the contract to put the bitcoin signature elsewhere so that we don't bloat the contract with unnecessary signatures? What's the cleanest way to do that?

This would obviously supersede #198 

@JustinDrake

**Comment by cpacia** [comment]
Could we maybe change ID to 
```
message ID {
    string guid         = 1;
    string blockchainID = 2;
    Pubkeys pubkeys     = 3;
    bytes bitcoinSignature = 4; // covers guid

    message Pubkeys {
        bytes guid    = 1;
        bytes bitcoin = 2;
    }
}
```

There is one of these objects for both the buyer and vendor in the contract. This could then make the signature object just consist of:
```
message Signature {
    Section section = 1;
    bytes signature = 2;
}
```

**Comment by JustinDrake** [comment]
I'll have a look at this. cc @Austin-Williams

**Comment by JustinDrake** [comment]
The goal is to cryptographically link the Bitcoin escrow contract to the GUIDs. The Bitcoin address is linked to the Bitcoin public keys via the P2SH script. Now it suffices for the Bitcoin public keys to be linked to the corresponding GUIDs. As you mention, one way to do this is to sign the GUIDs with the Bitcoin private keys.

But there's another way, which is to derive the GUID from the Bitcoin public key. For example, using [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) terminology, each party simply shares their public parent key, and the GUID can simply be a hash of that.

That way we get linking of GUID and Bitcoin public key for free, there's only a single signature, and we have a much cleaner `ID`:

```
message ID {
    string guid         = 1; // Hash of parentPubKey
    string blockchainID = 2;
    bytes parentPubKey  = 3;
}
```

**Comment by cpacia** [comment]
The problem is the guid needs to be a hash of an RSA key because that's how IPFS works. And bitcoin uses ECDSA.

**Comment by JustinDrake** [comment]
That sucks. Putting a signature there seems like a fine solution then. I would just clean things up a little and add comments:

```
message ID {
    string guid            = 1; // SHA256 of guidPublicKey
    string blockchainID    = 2; // Handle
    bytes guidPublicKey    = 3; // IPFS public key (RSA)
    bytes bitcoinPublicKey = 4; // Bitcoin parent public key (ECDSA)
    bytes guidSigned       = 5; // GUID signed by the Bitcoin parent private key
}
```
