### ISSUE TITLE
Retrieving an ETH-based Sale But No Confirmations Server Crashes

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#1991]
When you receive a sale using ETH and try to view the order before the tx shows up in Etherscan then the server crashes. Essentially the OB-GO server sees the tx and thinks it's been paid but when querying for confirmations on Etherscan (which hasn't seen this yet) the server crashes.

**Comment by cpacia** [comment]
Believe this has been fixed.
