### ISSUE TITLE
ETH wallet does not show ETH transactions.

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1992]
This is on commit 5375eef3

After making a direct purchase in ETH, paying for it and completing the order neither the buyer nor the seller shows any ETH transactions in their wallet.

I tried resyncing both nodes.

`http://localhost:4102/wallet/transactions/ETH?limit=25` returns
`count: 0`

**Comment by hoffmabc** [comment]
This fix has been merged please test.

**Comment by jjeffryes** [comment]
So far purchases are showing up correctly, but at least one direct transfer, maybe 2 have not.
