### ISSUE TITLE
Incorrect ETH transaction height coming from the socket

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1996]
When an ETH transaction is created, a `wallet` socket message is received with the transaction data. The message has `height: 1` which is incorrect.

We determine the confirmations of a transaction by subtracting the confirmations from the block height in the `walletUpdate` socket message. This is causing the confirmations to show as 1 less than the current block height.

I've seen transactions suddenly change to the correct number of confirmations, so some process must be correcting the height eventually.

**Comment by cpacia** [comment]
fixed.
