### ISSUE TITLE
Is this project testable already?

### ISSUE THREAD

**Issue by stevenroose** [OpenBazaar/openbazaar-go#2]

**Comment by cpacia** [comment]
It runs and there is some limited functionality ― setting the profile, avatar, header, fetching them from other nodes, posting a contract, follow, unfollow.

**Comment by stevenroose** [comment]
But it's not functional enough yet to point a client to it?

**Comment by cpacia** [comment]
yes but not the current client. that needs to be modified to use it.

**Comment by stevenroose** [comment]
The two server implementations don't provide the same API?

**Comment by cpacia** [comment]
No IPFS introduces new functionality that requires changes to the API. And while were changing things might as well improve on it.
