### ISSUE TITLE
Listings Mysteriously Change to Track Inventory with 0 Inventory

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#2000]
Two of my listings on eth-master changed from do not track inventory to track inventory with zero inventory without me editing them.

So far I haven't been able to find a sequence of events that reproduces this.

This is on testnet, on fresh nodes. One listing was purchased twice, one purchased only once offline, and that purchase resulted in an error state with `invalid payment address`. Both had several attempts at online moderated purchases that failed with the `invalid payment address` bug.

A third listing created today hasn't had this happen. The only difference I can see is I'm not getting the invalid payment error today on purchases.

**Comment by jjeffryes** [comment]
I can confirm getting the invalid payment bug doesn't cause this. New listings that were returned invalid payment on purchase did not change their inventory.

**Comment by cpacia** [comment]
Unable to replicate
