### ISSUE TITLE
ETH discountCode is not returned by ob/listing when editing a listing

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#2003]
When a listing with a coupon is edited, the `discountCode` is not returned by ob/listing.

The coupon data returned is
```
"coupons": [
            {
                "title": "test",
                "hash": "QmZ5NmGeStdit7tV6gdak1F8FyZhPsfA843YS9f2ywKH6w",
                "percentDiscount": 10,
                "priceDiscount": 0,
                "bigPriceDiscount": ""
            }
        ],
```

The expected data would include `discountCode`.

The hash is also not expected when editing a listing. It looks like this might be the data intended for a buyer viewing the listing, not a seller editing their own listing.

**Comment by cpacia** [comment]
done
