### ISSUE TITLE
ETH Response from estimate fee is inconsistent

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#2004]
Sometimes when I do this call
`http://localhost:4302/wallet/estimatefee/TETH?feeLevel=ECONOMIC&amount=130570359439592`

The server responds with:
```
{
    "success": false,
    "reason": "ERROR_INSUFFICIENT_FUNDS"
}
```

And other times, with no other changes, I get

```
{
    "amount": "53000000000000",
    "currency": {
        "code": "TETH",
        "currencyType": "crypto",
        "divisibility": 18,
        "name": "Testnet Ethereum"
    }
}
```

The wallet had $0.27 worth of TETH in it at the time, the payment was $0.03.

**Comment by jjeffryes** [comment]
This seems to happen roughly 50% of the time, but I can confirm it does not happen consistently every other time. The pattern I saw was status 400, 200, 400, 200, 400, 200, 400, 400, 200.

**Comment by jjeffryes** [comment]
Later with $0.18 in the wallet, a purchase of $0.03 consistently returned the insufficient funds error.

**Comment by drwasho** [comment]
The core issue here is that the price for the listing is far too low and we need to plan for a way to handle this better as far as communicating to the client is concerned.

**Comment by cpacia** [comment]
closing too low price
