### ISSUE TITLE
Include hash in return of listing fetch.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#201]
Since we need to provide the hash of a listing when attempting to buy a listing, please include the hash in the returned content of the various APIs that return a listing.

- `/ipns/<guid>/listings/<slug>` - Sometimes we need to fetch a listing via IPNS (e.g. user enters `<guid|handle>/store/<slug>` directly in the address bar). In this case, we don't have the hash that corresponds to that listing and would need it should the user press the 'Buy Now' button.

- `/ob/listing/<slug>` - Not sure if we will allow a user to complete a purchase of their own listing, but in v1, I believe, we at least allowed them to go through the flow, so they could see what the experience is when a user attempts to buy their listing. Even if we don't allow this, for data consistency purposes, it would be nice to have the hash provided.

Additionally, can we please return the hash on a successful POST of a listing (in addition to the slug that is currently being returned)?

**Comment by cpacia** [comment]
This sucks to have to do this. 

I suppose it will have to wait until I can refactor the endpoints to bring them under /ob/. The problem right now is that I can't modify the data coming back from ipfs. And even if I put a hash in there it would change the hash of file... which would mean it wouldn't work.

Additionally, when I do this refactor I'm probably going to change the format from:
```
{
       vendorListings: [  ],
       signaturres: [   ]
}
```
to 
```
{
     listing: { },
     signature: { },
     hash: "",
}
```

**Comment by rmisio** [comment]
> This sucks to have to do this.

Story of my life with some of the unique architecture constrains we have due to being P2P.

np on the structure change.

**Comment by hoffmabc** [comment]
It's a brave new world out there with p2p.

**Comment by rmisio** [comment]
Updated the description to also request that the hash be returned on a successful POST of a listing. If the user views the listing after it's been created, we'd need the hash on the off chance they want to go through the buy flow.

**Comment by jjeffryes** [comment]
@rmisio is this still open?

**Comment by rmisio** [comment]
Yes, the hash is currently not being provided with a listing. It's my understanding that when buying a listing, we need to provide the hash. If that's true, then we need the API to give it to us.
