### ISSUE TITLE
Web payments cb.outputs

### ISSUE THREAD

**Issue by 9z25** [OpenBazaar/openbazaar-go#2037]
tagging @cpacia and @hoffmabc 

I am going full stride with architecture and coding of this web payments implementation myself but am seeing that I will need to make some changes into OpenBazaar-go.

One thing I'm having trouble with is sending a call out to my middleware on transactions received with cb.Outputs data.

I'm only assuming I need a block of code that acts like SantizedResponse (I see SanitizeProtobuf, maybe I can stuff that in an http call out to my middleware) to unmarshal the data into a go struct.

This is the code I have under OnTransactionReceived.
```
var s = fmt.Sprintf("%+v", cb.Outputs)

url := "http://localhost:8000/api/transactionreceived/"
req, _ := http.NewRequest("POST", url, bytes.NewBuffer([]byte(s)))
...
```

I'm thinking I need something like 

```
var s = SanitizeProtobuf(cb.Outputs)

url := "http://localhost:8000/api/transactionreceived/"
req, _ := http.NewRequest("POST", url, s)
...
```

Before I deep dive into this problem, would this be proper use of the function?

**Comment by hoffmabc** [comment]
@9z25 SanitizeProtobuf takes two parameters, the JSON string and basically the protobuf type so you'd at least need to fix that. I don't know if there is a protobuf type for sending output messages. @cpacia do you know what this would be? I don't even know if it's necessary here.

**Comment by 9z25** [comment]
When I try marshalling the cb.Outputs into json, the addresses are omitted. I found the struct  []wallet.TransactionOutput{} and you're right, there is no protobuf type for it.
