### ISSUE TITLE
What is dropbox?

### ISSUE THREAD

**Issue by duosearch** [OpenBazaar/openbazaar-go#21]
There's a folder called `dropbox` (see [here](https://github.com/OpenBazaar/openbazaar-go/tree/master/storage/dropbox)).

Is that dropbox.com? Is it for testing?

**Comment by cpacia** [comment]
The messaging system requires outgoing messages to be stored somewhere. The default is to seed them over ipfs (which assumes you remain online), but anyone is free to make a plugin to store them somewhere else. Dropbox is one example.

**Comment by duosearch** [comment]
Ok, that's interesting. But then both the sending and receiving peers need the plugin, right?
