### ISSUE TITLE
Strange construction of GetListingFromHash

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#213]
I was surprised to see that `GetListingFromHash` lookups the slug of a listing matching a hash, and then uses `GetListingFromSlug`. Shouldn't it be the other way round? The hash is a clean cryptographic fingerprint; the perfect identifier. Whereas the slug is a user-set string. Isn't it more natural for slug to resolve to hashes?

**Comment by cpacia** [comment]
I don't think it makes any different for security. For this purpose the files on disk are only known by their slugs. If we want to fetch a file via hash, it must be done via an IPFS query, which will attempt to pull it from the IPFS cache. But that assumes the routine that puts it into the cache has finished (and had no errors).
