### ISSUE TITLE
DRY up net.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#214]
In `core/net.go`, it's almost the same code written over and over ahead. Maybe @yurizhykin would be interested in cleaning that up?

The nine functions starting from `Follow` and ending with `SendOrderCompletion` can easily be DRYed up.

**Comment by yurizhykin** [comment]
@JustinDrake sure, I will take a look at it after I'm done with #196

**Comment by yurizhykin** [comment]
Submitted a PR for this, but please see note there in #221
