### ISSUE TITLE
DRY up images.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#215]
Most of `images.go` is the same thing repeated 5 times for the 5 image sizes. Low-hanging DRY stuff.

**Comment by cpacia** [comment]
looks like the only part where you maybe save a few lines of code is os.create. Most of the other stuff creating a loop would probably be the same amount of code or more.

**Comment by JustinDrake** [comment]
Ok, I'll do this myself. Please assign to me.

While DRYing up code isn't about saving lines of code (it's about maintainability, readability, testability, etc.) I reckon I can shrink the file from 317 lines to 200 or less. Challenge accepted :)

**Comment by JustinDrake** [comment]
This has been done by @yurizhykin; thanks!
