### ISSUE TITLE
Simplify IPFS interface

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#217]
As I understand from talking to @cpacia, the IPFS interface code in the `ipfs` folder was written "in the dark" (no documentation) from the IPFS command line tool and ended up being a dirty hack. For example, inside `add.go` the function `AddFile` calls the functions `PreRun`, `Run` and `PostRun` which are not relevant to adding files. As explained in [this issue](https://github.com/ipfs/go-ipfs/issues/3060), there is a much neater way of doing things (see whyrusleeping's answer):

```
func AddFile(ipfs *core.IpfsNode, file string) (string, error) {
    fi, err := os.Open(file)
    if err != nil {
        return "", err
    }

    return coreunix.Add(ipfs, fi)
}
```

instead of

```
func AddFile(ctx commands.Context, fpath string) (string, error) {
	args := []string{"add", fpath}
	req, cmd, err := NewRequest(ctx, args)
	if err != nil {
		return "", err
	}
	res := commands.NewResponse(req)
	cmd.PreRun(req)
	cmd.Run(req, res)
	var fileHash string
	for r := range res.Output().(<-chan interface{}) {
		fileHash = r.(*coreunix.AddedObject).Hash
	}
	cmd.PostRun(req, res)
	if res.Error() != nil {
		return "", res.Error()
	}
	if fileHash == "" {
		return "", addErr
	}
	return fileHash, nil
}
```

**Comment by cpacia** [comment]
If someone wants to do that it's fine, but I think this is the only command that could be simplified that way. And doing so would make this function inconsistent with the rest of the IPFS package.

**Comment by JustinDrake** [comment]
Why is `Add` is the only command that could be simplified? It seems to me that `PreRun`, `Run` and `PostRun` are just helper functions for the IPFS command line, which we are not using. Looking into coreunix, I see [`add.go`](https://github.com/ipfs/go-ipfs/blob/master/core/coreunix/add.go).

**Comment by cpacia** [comment]
Because as far as I know add is the only one where you have a function like coreunix.add. If you can find others in the IPFS code to do the same thing for the other functions then that works.

**Comment by JustinDrake** [comment]
Well for one I think there's cat.go

https://github.com/ipfs/go-ipfs/blob/master/core/coreunix/cat.go
