### ISSUE TITLE
Update go-ipfs dependency

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#219]
I've tried to update the go-ipfs dependency using Godep. I've never used the tool before, maybe I'm doing something wrong. Is this documented somewhere?

```
Justins-MacBook-Air:openbazaar-go justin$ go get -u github.com/ipfs/go-ipfs
Justins-MacBook-Air:openbazaar-go justin$ godep update github.com/ipfs/go-ipfs
godep: not in manifest: github.com/ipfs/go-ipfs
godep: error loading dependencies
```

I've also tried doing something similar with the `OpenBazaar/go-ipfs` fork:

```
Justins-MacBook-Air:openbazaar-go justin$ godep update github.com/OpenBazaar/go-ipfs
godep: not in manifest: github.com/OpenBazaar/go-ipfs
godep: error loading dependencies
```

**Comment by cpacia** [comment]
I don't know what the error is but I would recommend against arbitrarily updating IPFS. Any rebase to a new version of IPFS will likely cause merge conflicts or cause things to break in OpenBazaar/go-ipfs.

Rebases need to be don't very carefully. Also, a rebase will almost certainly cause every gx import statement in openbazaar-go to break which will require manually updating every one.

**Comment by JustinDrake** [comment]
I'm doing preparation work for an IPFS crawler, and the IPFS DHT code in `openbazaar-go` is outdated. It's been refactored in `go-ipfs` and I wanted to play with the latest version.

**Comment by JustinDrake** [comment]
@cpacia mentioned that go-ipfs will be rebased for stable releases of go-ipfs.
