### ISSUE TITLE
Unit tests for core folder

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#222]
The `core` folder holds a significant portion of the OpenBazaar business logic but I cannot see any unit tests for it. Maybe adding tests for core should be added to #220 (alpha milestone).

**Comment by cpacia** [comment]
I don't think it's completely necessary for alpha. Maybe for beta and hopefully for the fully release. If someone wants to work on it in the mean time that would be helpful. Most of that code is close to the point where it wont be changing that much.

**Comment by cpacia** [comment]
Superseded by other unit test issues
