### ISSUE TITLE
Public test nodes

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#223]
At these early stages, I think it makes sense to have a few public test nodes continuously running that anyone can send requests to. Maybe OB1 already have such test nodes already running? In any case, Duo Search is happy to participate in this effort by maintaining OB 2.0 public test nodes.

**Comment by cpacia** [comment]
What requests do you want to send to it? 
There's gateway.ob.io but that's just a gateway.

**Comment by JustinDrake** [comment]
Right now for example I am writing a DHT crawler. For this job I'd like to see the nodes in the DHT, as well as ping the online nodes.
