### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#224]
When running `go get` I get a compilation warning as detailed below.

```
Justins-MacBook-Pro:repos justin$ go get -u github.com/OpenBazaar/openbazaar-go
# github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher
../../go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher/sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
```

**Comment by cpacia** [comment]
You might want to push this issue upstream. Looks like the sqlite c binding might need to be rebased.

**Comment by cpacia** [comment]
You can read about it here. Looks like a wont fix as apple isn't expected to remove that code any time soon. https://github.com/mattn/go-sqlite3/issues/332

**Comment by hoffmabc** [comment]
looks like we already went over this @JustinDrake lol

**Comment by hoffmabc** [comment]
I think this only an issue with OS X 10.12 and above. My Sierra machines bombs but before that version seem fine.

**Comment by cpacia** [comment]
^ fixed
