### ISSUE TITLE
libp2p protocols

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#227]
libp2p implements [three protocols](https://github.com/libp2p/go-libp2p/tree/master/p2p/protocol) called `identify`, `ping` and `relay`. Is the intent to keep those protocols as-is in the `go-ipfs` fork for OB 2.0? (I ask because I'm interested in using those protocols.)

**Comment by cpacia** [comment]
I don't have any plans to change any of that code.
