### ISSUE TITLE
Coveralls.io coverage stats are wrong

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#229]
The coveralls page reports 60% coverage, with 2623 relevant lines and 1585 covered lines. The number of relevant lines is wrong. The `openbazaar-go` coverage is much closer to 0% than it is to 60%.

<img width="283" alt="screen shot 2016-11-17 at 16 07 44" src="https://cloud.githubusercontent.com/assets/731743/20397006/04f8d012-ace0-11e6-8eec-db4efe51e022.png">

**Comment by cpacia** [comment]
It only reports packages that have tests in it. It will be more accurate as more packages get tests.

**Comment by JustinDrake** [comment]
So this is not an issue?

**Comment by hoffmabc** [comment]
As far as I have been able to tell there's no way to make it sniff packages not covered and include it. In fact the go devs say that would be bad practice. The only way to improve this would be to put empty test files for those uncovered packages as stubs so there counted. 

I had this same frustration but I think it's just the way this works.

**Comment by JustinDrake** [comment]
What's wrong with stub test files? The code needs testing and we need to get started somewhere. We also need meaningful coverage stats.

**Comment by hoffmabc** [comment]
I don't see anything wrong with it.

**Comment by JustinDrake** [comment]
So should this issue be reopened?
