### ISSUE TITLE
Does libp2p not include stun?

### ISSUE THREAD

**Issue by duosearch** [OpenBazaar/openbazaar-go#23]
I can see code for stunning [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/net/stun.go). My understanding was that the p2p networking was handled by IPFS's libp2p. Is that correct? Does libp2p not handle stun natively?

**Comment by cpacia** [comment]
I don't think it does. It's also broken atm. The utp lib they use has bugs in it and they are trying to find a replacement.
