### ISSUE TITLE
Specify test and quality targets

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#230]
I think it would be good to explicitly define test and quality targets. These will allow to plan for appropriate QA infrastructure that will help us achieve those targets. Below are example QA questions I think should be answered in writing for each release milestone:

* Nodes should be able to stay responsive for **X** days without reboot.
* The network should scale to **X** nodes.
* We aim to reach **X**% test coverage for the overall codebase, and **Y**% test coverage for these critical packages
* Nodes should be able to run on machines with the hardware specs S1, S2, S3, etc.
* Nodes should be able to run on OSes O1, O2, O3 with versions V1, V2, V3, etc.
* Nodes should be able to serve **X** orders without noticeable CPU hogging or memory leaks

**Comment by JustinDrake** [comment]
Closing without a single comment? Cc @hoffmabc — quality still a major pain point with openbazaar-go IMO

**Comment by hoffmabc** [comment]
I'm not sure why we closed this @cpacia yet. If you could share your reasoning would appreciate.

**Comment by JustinDrake** [comment]
I now see that there are test coverage issues (e.g. #450), but this is only a part of what this issue what trying to bring home.

**Comment by cpacia** [comment]
Yeah I opened two issues related to test coverage for other milestones making this mostly redundant. I assumed those would be plenty visible. 

I'm not sure what about the rest of the issues as it seems obvious that:
- Nodes should never need to restart due to memory or CPU issues.
- The network should scale infinitely. It probably can do that now, but this is more related to IPFS than the OB protocol on top of it.
- OS and hardware specs arent changing.

**Comment by JustinDrake** [comment]
> Nodes should never need to restart due to memory or CPU issues.

Nice. It would be great to have the testing infrastructure to support that. Specifically, I am thinking of a long-running (e.g. 2 weeks long) stress test that runs in a VM and tracks resource usage and crashes. The current CI testbench runs short-lived tests, mostly integration and unit tests.

> OS and hardware specs arent changing

Would be great to document the current hardware specs somewhere. At the OpenBazaar helpdesk we've seen people use Raspberry Pi 1's. Does OpenBazaar 2.0 target such low-grade hardware?

**Comment by cpacia** [comment]
Fwiw, the OpenBazaar code that runs on top of IPFS is very light. There's only several processes that run and if there is a problem with them, it should be easy to debug/fix.

Any other issues with performance would likely be IPFS related.
