### ISSUE TITLE
Setup pre-commit hook for go_vet, gofmt, golint, etc.

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#231]
In order to avoid commits that fail linting (see the [go report](https://goreportcard.com/report/github.com/OpenBazaar/openbazaar-go), which for example shows 4 files that haven't been `gofmt`ed), it may make sense to add a pre-commit to warn developers they have code that fails lint.

Since Git 2.9 those hooks can be specified [in the repository itself](http://stackoverflow.com/a/37861972/707381).

**Comment by cpacia** [comment]
The repo just needed to be refreshed. There are no gofmt issues. Travis would return a fail if it did. 

I don't know what you mean by in the repository. Are you saying we can put code in the repo that causes other people's machines to run gofmt?

**Comment by JustinDrake** [comment]
I believe so, see http://stackoverflow.com/a/37861972/707381
