### ISSUE TITLE
Periodic integration test failures

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#234]
The integration tests fail randomly with "Alice failed to detect payment". When the bitcoin logs are dumped it shows the spvwallet received a block that it failed to connect to any other known blocks. 

This needs to be investigated to figure out what the problem is. Is bitcoind in regtest mode generating blocks that don't connect to each other? Seems unlikely. Alternatively we have a bug which is sometimes saving headers incorrectly.

**Comment by cpacia** [comment]
As an update. I'm seeing some transactions fail for a "premature spend of a coinbase". Which makes no sense to me because the order of events I'm working with is:

1. Generate the genesis block
2. Generate to a bitcoind internal address
3. Generate > 100 blocks (cool down period)
4. Send coins from bitcoind to an openbazaar wallet
5. Attempt to spend the coins from the openbazaar wallet

I don't see how step 4 could be a valid spend but not step 5. Also we've clearly generated > 100 blocks as the logs show, so why would this be a premature spend? 

Very annoying.

**Comment by cpacia** [comment]
Still can't figure it out. It looks like bitcoind isn't relaying some transactions. I've also checked the filter and the time it was created so I'm pretty sure the data we need is in the filter. I'm not sure what's going on. 

I notice more failures of this sort when my machine is busy running lots of applications so I'm working if it's just some problem with how regtest mode is running.

**Comment by yurizhykin** [comment]
There may be some problems with timing, for example `sleep()` for 4 seconds is not enough for the payment to end up in block because of the high load average of the machine (`bitcoind` induces pretty high load average) or something like that. There was similar problem in integration test suite in Bitcoin core some time ago.

**Comment by cpacia** [comment]
Yeah that could be it, it's just weird behavior. I've played around with the timeouts and I've seen it happen even when the timeout is like 12 seconds.

**Comment by Riiume** [comment]
(Posted [$15 bounty](https://www.bountysource.com/orders/65670))

**Comment by cpacia** [comment]
There's still periodic failures but seems unrelated to this issue.
