### ISSUE TITLE
When the currency unit of a listing is BTC, the GET listings API is returning the price as a string.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#235]
![image](https://cloud.githubusercontent.com/assets/794517/20545615/f3d89324-b0c4-11e6-97e2-55dbaff7a7fd.png)

The expectation is that the price is returned as a number, which is what happens if the currency unit is a fiat option.

**Comment by JustinDrake** [comment]
@cpacia Does this go through all the checks in `validateListing`?

**Comment by cpacia** [comment]
The problem there is javascript can't handle that number you have in quotes as it's greater than 2<sup>32</sup>

**Comment by rmisio** [comment]
That doesn't sound right. According to [this](http://stackoverflow.com/a/307200/632806), the biggest number JS could handle is +/- 9007199254740991, which is quite a bit larger than the price in my example.

**Comment by cpacia** [comment]
Oh that's right it's 2<sup>53</sup>.

**Comment by rmisio** [comment]
yeah, even with us representing Bitcoins in Satoshi, someone would have to list something at a price greater than 90,071,992.55 bitcoins (about 67,553,994,410$) in order for us to run into the number limit. So, unless Richard Branson is listing something for Warren Buffet, I think we're good!

**Comment by cpacia** [comment]
Yeah bitcoin doesn't have more than 21m bitcoins total
