### ISSUE TITLE
Will supernode routing be supported?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#236]
The [`go-ipfs`](https://github.com/OpenBazaar/go-ipfs) fork changed the protocol string for supernode routing to `/openbazaar/supernoderouting/`. Is the intent to support and/or encourage supernode routing on the OpenBazaar network as an alternative to DHT routing?

**Comment by cpacia** [comment]
I don't have any intention of using it, but I think it can be activated by putting a server in the config file.

**Comment by JustinDrake** [comment]
Thanks
