### ISSUE TITLE
When are golang/protobuf and OpenBazaar/jsonpb used?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#238]
This repo uses two versions of protobufs, [`golang/protobuf`](https://github.com/golang/protobuf) and the OpenBazaar-maintained fork [`OpenBazaar/jsonpb`](https://github.com/OpenBazaar/jsonpb). When is which library used? Is there a plan to fully migrate to `OpenBazaar/jsonpb`?

**Comment by cpacia** [comment]
jsonpb is only used for marshalling and unmarshalling to JSON. It's forked because the default marshalling behavior isn't quite what we want.... like dropping enums with a zero value and making uint64s into strings no matter how small the number.

**Comment by JustinDrake** [comment]
Oh ok

- `protobuf` for unmarshalling/marshalling to byte arrays
- `jsonpb` for unmarshalling/marshalling to JSON
