### ISSUE TITLE
Remove gogo-protobuf

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#239]
In a private conversation @cpacia states:

> gogo-protobuf shouldn't been in any OpenBazaar files. It's an ipfs dependency that isn't really compatible.

There are three files that are affected: `openbazaard.go`, `net/service/service.go` and `ipfs/pointers.go`

**Comment by cpacia** [comment]
Turns out all these areas use that package because the are interacting with ipfs.
