### ISSUE TITLE
Error are silently ignored in repointer.go

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#241]
The function [`republish()`](https://github.com/OpenBazaar/openbazaar-go/blob/master/net/repointer/repointer.go#L32) will silently ignore errors when getting pointers, deleting pointers or republishing pointers. Dealing with the DHT is probably going to be the flakiest part of the application. Errors need to be dealt with carefully.

**Comment by cpacia** [comment]
What would you do if it caught an error? I suppose we could at a log statement, but I don't know what else. 

In the case of this repointer it will eventually try again.

**Comment by JustinDrake** [comment]
Errors should at minimum be log. If the repointer fails repeatedly, maybe the user should be informed through the UI.
