### ISSUE TITLE
Unused argument in Purchase

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#242]
The [`purchase`](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/order.go#L62) function in `order.go` takes as argument `vendorOnline`, which seems to be a superfluous argument.

**Comment by cpacia** [comment]
That boolean is part of the return not the function arguments.

**Comment by JustinDrake** [comment]
Duh. Sorry about that.
