### ISSUE TITLE
When are offline messages retrieved using HTTPS?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#244]
The [`retriever`](https://github.com/OpenBazaar/openbazaar-go/blob/master/net/retriever/retriever.go#L74) has code to download offline messages from some HTTPS resource. When looking at [`SendOfflineMessage`](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/net.go#L15) in `net.go` I don't see any mention of HTTPS (such as HTTPS URLs).

When are offline messages retrieved using HTTPS?

**Comment by cpacia** [comment]
It's not used at present. It's just an option if someone wants to use it. The dropbox example uses https.
