### ISSUE TITLE
Create server init command to determine the state of the database encryption pw.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#245]
Ideally, the init command is a light-weight alternative to having to start the full server and it responds with one of three exit codes:

a.) Uninitialized - The server has never been started before and the client needs to show an interface asking the user whether they would like to create a db encryption PW.
b.) No password needed - The database is not encrypted and the server can be started without credentials.
c.) Password needed - The database is encrypted and the server needs to be started with credentials passed in.

![image](https://cloud.githubusercontent.com/assets/794517/20680844/aebd7530-b555-11e6-9a74-a205140c2600.png)

**Comment by cpacia** [comment]
Probably there will also need to be a flag for each of these responses for "Tor available" where the client will ask the user if they want to use Tor.... if so, the server should be started with the --tor option and the client should enable the socks5 proxy.

**Comment by rmisio** [comment]
Hmmm... ok, as long as we could bake that into the `init` sequence. I wouldn't want to have to start the server a second time just to determine TOR availability.

Maybe something like this? (the specific error codes are just examples)

100: Uninitialized - TOR not available
101: Uninitialized - TOR available
200: No password needed - TOR not available
201: No password needed - TOR available
300: Password needed - TOR not available
301: Password needed - TOR available

FWIW, IMHO, this is a quite crude and limiting way of the client / server communicating. If we find we need any additional flags, I really think we should consider exposing a HTTP API that would allow for richer and easier to manage communication.

**Comment by cpacia** [comment]
That's how I've done it. 

It would be dramatically slower to spin up a server, wait for initialization, query it, then shut it down. 

Using the status code only takes 50 milliseconds, I've timed it.

**Comment by rmisio** [comment]
Will this all be baked into one `init` command or are you suggesting starting the server multiple times to determine different server states?

**Comment by cpacia** [comment]
There's one command to get the status then you start the server.
