### ISSUE TITLE
Allow direct payments to offline vendors 

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#247]
Currently direct payments to offline vendors don't really exist. Instead there is a [1-of-2 intermediary transaction](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/order.go#L457) for buyer clawback. (The idea is that offline vendors are more likely than online vendors to never come back online.) Unfortunately clawback is only possible if the buyer uses the built-in Bitcoin wallet in OpenBazaar to make the 1-of-2 signature. (Standard Bitcoin wallets—Breadwallet, Coinbase, Circle, etc.—do not have this functionality.)

My suggestion is to allow the user to make a direct payment to offline vendors without the OpenBazaar wallet. Certainly some people using the OpenBazaar client will want to use their personal wallet. Third-parties such as Duo Search many not want to implement a custom Bitcoin wallet. Such third-party services may also known the uptime pattern of stores. This information can be communicated to buyers who can then make an informed decision on the risk of making a payment to an offline store.

cc @jjeffryes, @morebrownies

**Comment by JustinDrake** [comment]
Interestingly, the fact that the seller would have to swallow a Bitcoin transaction fee is an incentive for him/her to keep the store online :)

**Comment by drwasho** [comment]
Buyer clawback is a critical security dependency for offline purchases. I'd rather support direct offline purchases without clawback in response to an overwhelming request from the community.

**Comment by JustinDrake** [comment]
I was confused about how direct payments work. (The vendor ack contains the payment address.)
