### ISSUE TITLE
Allow vendor to specify number of confirmations before considering an order funded

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#248]
Some vendors may be happy with a 0-conf (e.g. selling a cheap digital good). Some vendors may require 1-confirmation (e.g. selling a not-too-expensive digital good). Some vendors may require 2+ confirmations (e.g. selling an expensive digital good).

I think the number of confirmations required should be part of the [`Listing` protobuf](https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/contracts.proto#L18), and enforced accordingly by `openbazaar-go`.

**Comment by drwasho** [comment]
I'm favor of this change, but this has a lot of design and front-end implications that (given our workload) I'd prefer to circle-back to in a follow-on release. We can add it to the list.

**Comment by cpacia** [comment]
With the exception of digital goods which aren't coded yet. The number of confirmations before the state is flipped to funded doesn't matter. The vendor should only ship when it has his required number of confirmations.
