### ISSUE TITLE
Embrace IPFS's "PeerID" instead of "GUID"?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#249]
From a user's perspective it's "OpenBazaar ID". From a technical perspective, since we are building on IPFS, I think it makes sense for OB 2.0 to use "PeerID" in the code instead of "GUID".

**Comment by drwasho** [comment]
I think PeerID is more descriptive, but technical audiences will.know what GUIDs mean. So there should be more compelling reasons to make the switch.
