### ISSUE TITLE
Settings data is not being validated

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#252]
In order to prevent invalid data being saved to Settings, which is difficult for the client to manage, can the Settings API please get the same validation type treatment of other APIs (like Listing)?

For example, the following SMPTSettings successfully save:

```
    "smtpSettings": {
        "notifications": true,
        "serverAddress": "",
        "username": "",
        "password": "",
        "senderEmail": "",
        "recipientEmail": ""
    }
```

If notifications is set to true, then the subsequent fields are required and shouldn't be blank.

Also, if you attempt to save Settings with data that's not part of settings (for example: `pear: prickly`), it just ignores that key instead of kicking back an error of an unrecognized key. Ideally, it would behave like the Listings api where it kicks back an error about an unrecognized key.

**Comment by yurizhykin** [comment]
I'll take a look at this, but in general, maybe protobuffers should be used? As I undestand, we get automatic validation for listings API from using pbs.
