### ISSUE TITLE
Break down openbazaard.go into smaller files

### ISSUE THREAD

**Issue by duosearch** [OpenBazaar/openbazaar-go#26]
In the OB1.0 `OpenBazaar-Server` repo, the file `openbazaard.py` was very difficult to work with because it was long and linear (lots of "spaghetti"). `openbazaard.go` seems to be headed in a similar direction, with close to 500 lines of code.

Does it make sense to break down `openbazaard.go` into smaller files?

**Comment by cpacia** [comment]
@tyler-smith you can give your opinion here. I'm not sure I see any logical place to break up the code as it's just initializing everything.

**Comment by tyler-smith** [comment]
Yeah almost the bulk of the code is in the server initialization. You could break out logging and command handlers to their own files but I don't think that'd be things much better. You'd still have a giant Start.Execute() that's pretty unavoidable. I don't care too much one way or another if somebody submits a PR with a good refactoring.

**Comment by cpacia** [comment]
Closing because I mostly agree with Tyler. If someone wants to submit a PR that puts some parts into a separate file I'd be open to it.
