### ISSUE TITLE
Messaging always does a IPFS lookup for the peer's public key, even when you already have it

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#272]
In order-related messaging, the sender already has the public key of the recipient, as it is stored in the listing, but instead of using this information an IPFS lookup is performed (in core.EncryptMessage()). This forces all nodes to publish their public keys to IPFS, which is not useful for Duo or other buyer-only portals.

I propose a second function, core.EncryptMessageWithKey, which allows you to directly specify a public key instead of the peerID, and core.SendOfflineMessageWithKey which uses this. We could then adapt all contract-related functions in net to pull out the public key (of either buyer or seller) and use these new functions. 

This is more efficient, and also opens the door for buyers that are not nodes, and given the new offline message relay functionality, that have no interaction with IPFS at all.

**Comment by cpacia** [comment]
That's probably fine to do. I would maybe just make the net functions take in an optional key and use it if it's passed in and if not, just look it up.

**Comment by jjeffryes** [comment]
Does #274 close this issue?

**Comment by jackkleeman** [comment]
Yup!
