### ISSUE TITLE
A profile fetched via IPNS has a ridiculously high cache setting.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#273]
Fetching a profile via IPNS returns a response with a cache header instructing the browser to cache the resource for 336 days:

![image](https://cloud.githubusercontent.com/assets/794517/21233032/972564fa-c2a2-11e6-9e3d-69b713142390.png)

This is IMHO way too high. If I make a change to my profile, other users would need to wait up until 336 days to see the change.

Since we are very heavily fetching profiles in the app, I do agree some caching is appropriate, but I would think somewhere between 10 minutes and a few hours would be the right setting.

FWIW - to be clear. This only applies to fetching other peoples' profiles. Fetching your own profile will be via the local `ob/profile` which AFIK will not be cached. So, viewing your own profile will always return the current data.

**Comment by cpacia** [comment]
I think is only happening if you fetch your own profile via ipns and not ob/profile. The rest are set to cache 600
