### ISSUE TITLE
Package the OpenBazaar server for the Sandstorm app store

### ISSUE THREAD

**Issue by john-light** [OpenBazaar/openbazaar-go#277]
I recently started using [Sandstorm](https://github.com/sandstorm-io/sandstorm) to self-host open-source server applications. Self-hosting usually has a relatively high barrier to entry, so relatively few people do it. The result is massive centralization and insecurity of data on the web. Sandstorm is one part of the solution to this problem by making it easy and secure to self-host open-source server applications.  

I would like to see the OpenBazaar server packaged for the Sandstorm app store so that Sandstorm users like myself can easily install and run our own OpenBazaar node. You can find instructions for packaging your app for Sandstorm here:  

https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

**Comment by hoffmabc** [comment]
@john-light I looked into this, but I have a few questions.

1) Do you have any references on how to set this up for a Golang application as ours?
2) I'm wondering if this is really valuable since you can just run the installable app and the server is run locally anyways?

**Comment by john-light** [comment]
@hoffmabc 

> Do you have any references on how to set this up for a Golang application as ours?  

I do not, you might be able to poke them on [IRC](https://kiwiirc.com/client/irc.freenode.net/?channel=#sandstorm) and ask.  

> I'm wondering if this is really valuable since you can just run the installable app and the server is run locally anyways?  

I think this would be useful for users that want to run their own node and have 100% uptime for their store. Running it locally requires the local machine to be on 24/7 for 100% uptime. Sandstorm makes it easy to set up a self-hosted node that can stay online 24/7 with little manual intervention. My 2 bits.
