### ISSUE TITLE
On purchase, order.RefundAddress is set twice

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#280]
[Line 65](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/order.go#L65) and [line 124](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/order.go#L124) of core/order.go both set order.RefundAddress to the same thing.

**Comment by tyler-smith** [comment]
Closed with Jack's PR #281
