### ISSUE TITLE
Remove misleading documentation about an `-a, --allowip=` command line option

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#287]
There is documentation accessible via the command line (-h) and in the README.md of this repo that indicates an `allowip` command line option is available to configure which addresses a server will allow API connections from.

Apparently, this is not a valid option (perhaps the documentation is a hold-over from v1) and the correct way to do this is to set the Addresses.Gateway setting in the config file.

Expected results:
- mentions of the `allowip` flag are removed from the documentation
- it would be nice if there was some documentation that the `Addresses.Gateway` setting should be used to accomplish this (perhaps in general some documentation is needed on how to configure a node to work with a remote client)

**Comment by hoffmabc** [comment]
Are we going to actually enable this feature @cpacia or no?

**Comment by cpacia** [comment]
Maybe eventually. It can be removed from the help menu for now.

**Comment by jjeffryes** [comment]
@cpacia what's the status of this issue?
