### ISSUE TITLE
Use ephemeral ids for addressing offline messages

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#288]
Currently every offline message is addressed to the peer id of its recipient. This would allow a network spy to view the exact quantity of messages any peer is receiving, which is useful information (eg it is likely proportional to trade volume). It would also allow a relay like Duo to know who its users is talking to, and how often.

I suggest that the following protocol is used:

1. First message (online or offline) to peer - use peer id (`A`)
2. Peer response (offline or online) includes a randomly generated id (`B`) (which it stores in its db). This id is of a different format to normal peer ids.
3. User stores new id (`B`) in its db, associated with the peer id (`A`)
4. Upon any following offline messages from user to peer, this new id (`B`) is used for addressing. New online messages to the peer include the id (`B`) within the body for acknowledgement.
5. If the user recieves a new message (online or offline, including acks) from the peer, the ephemeral id is updated (`C`)
6. Upon any following offline messages from user to peer, this new id (`C`) is used for addressing. New online messages to the peer include the id (`C`) within the body for acknowledgement.
7. When the peer receives online (with acknowledgement of `C`) or offline (addressed to `C`) messages from the user, they stop looking for the old id (`B`) in DHT

Peers would search DHT for a list of ephemeral ids as well as their peer id, 1-2 (1 if the last communication was from user to them, 2 in the opposite case) for every user they have previously communicated with. To prevent growing network load due to this, ids can have a timeout, less than the offline message timeout, after which point offline messages from the user to the peer will revert to the peer id, and the peer will stop searching for the ephemeral address.

A snooper can now only tell when a peer receives a message from someone they haven't communicated from before (though it's occasionally someone they have, due to the timeout). A relay can only acertain the set of peers that a user has ever talked to, but not whether it occured multiple times (and thus, it could be a follow or something similarly harmless).

I also suggest that pings return an ephemeral id, so that users can obtain an id when the vendor is online, for use later when they are offline.

This solves a lot of the aims of #275.

**Comment by cpacia** [comment]
DHT keys use prefix filtering so it isn't possible to determine who a message is intended for with any accuracy.

**Comment by jackkleeman** [comment]
I appreciate that this means that a key is not reversable into the peer id (without essentially brute forcing it with every peer id on the network), but surely even with prefix filtering multiple messages to the same peer are addressed to the same key. This would allow you to work out which keys are most active, and then brute forcing it to obtain a peer id is not particularly difficult (if you want to acertain who might be behind a very active key, there are probably currently only a handful of vendors it could be)

**Comment by cpacia** [comment]
It's not just the hash of the key. If the peerId is 818b5cc5f21d3e6e4e6071c06294528d44595022218446d8b79304d2b766327a

Only 81 might go into the DHT. There's no brute forcing you can do to tell you what the rest of the key is. It could be one of any number of people.

**Comment by jackkleeman** [comment]
I see, that makes more sense, thanks
