### ISSUE TITLE
Migrate from CIDv0 to CIDv1?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#290]
So it turns out that IPFS's Base58 scheme (aka CIDv0, `/ipfs/<mhash>`) is being superseded by a new scheme called CIDv1 (`/ipfs/<mbase><version><mcodec><mhash>`). Further information can be found [here](https://github.com/ipld/cid). IPFS v0.4.5 will add support for CIDv1, and IPFS v0.5 will make CIDv1 the default.

Given that OpenBazaar 2.0 hasn't launched yet, we are not beholden to using CIDv0. And given IPFS v0.4.5 (the next release; to come very soon) provides support CIDv1, it may be a wise choice to prefer CIDv1 for OpenBazaar, i.e. to use it as a default.

Thoughts?

**Comment by cpacia** [comment]
@JustinDrake or @jackkleeman do you know how to activate this application wide?

**Comment by JustinDrake** [comment]
It's scheduled for the 0.4.9 release https://github.com/ipfs/go-ipfs/issues/3699

**Comment by JustinDrake** [comment]
The go-ipfs PR has now been merged.
