### ISSUE TITLE
Indicator for store seeding across network

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-go#293]
I expect many stores which are focused on privacy will choose not to continually operate their stores but instead go offline once their store is seeded and return online only to complete orders or make changes.

In order to do that a user will need to know how widely their store has been seeded before they go offline. How can this be done?

**Comment by cpacia** [comment]
I don't know if there is any good way of doing this. 

For one, each piece of data might have a different number of seeders. Also, the number of providers found in the DHT isn't necessarily the number of providers who are online. You'd have to basically request the file from each one to see if they are really seeding it.

**Comment by JustinDrake** [comment]
> You'd have to basically request the file from each one to see if they are really seeding it.

It's probably sufficient to request a single random block, instead of the whole file.
