### ISSUE TITLE
Why do dispute fund releases have 0 transaction fee?

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#296]

**Comment by cpacia** [comment]
What line of code are you referring to specifically?

**Comment by jackkleeman** [comment]
Apologies: [Both MultiSign and CreateMultisigSignature](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/disputes.go#L988) in disputes.go have a '0' as their feeperbyte argument

**Comment by cpacia** [comment]
Oh. I've calculated the fee prior to passing into that function and don't need it to take an additional fee off of it.

**Comment by jackkleeman** [comment]
Thanks, I should have noticed that!
