### ISSUE TITLE
More lenient order logic (moving away from online/offline orders)

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#297]
(This was discussed during the technical hangout on December 22. @cpacia, @jackkleeman and @justindrake agreed this was probably a good idea. No one voiced an opinion against it.)

At the moment there are online orders and offline orders. I suggest moving instead to automatically confirmed orders and manually confirmed orders. Whether or not the buyer and vendor can establish a secio connection, the same order message is sent from the buyer to the vendor. When the vendor is made aware of the order, two cases arise:

1. If the order is denominated in a currency other than BTC and the exchange rate leads to a price outside of the (optional) mispayment buffer, then the order needs to be manually confirmed (or rejected) by the vendor.
2. Otherwise the order is automatically confirmed.

This is more lenient for several reasons:

- Listings denominated in BTC should be automatically confirmed, regardless of whether or not the buyer and seller could establish a secio connection.
- Listings not denominated in BTC could still have an exchange rate within the mispayment buffer, even if the buyer and seller could not establish a secio connection.
- It is better UX for the buyer to receive a confirmation as soon as possible, and for the vendor to avoid manually confirming orders if not necessary. The above scheme maximises automatically confirmed orders.
- This decouples the type of payment (direct payments vs 1-of-2 clawbackable payments) from the type of order (automatically confirmed vs manually confirmed). For example, the protocol would allow for 1-of-2 clawbackable payments even for moderated payments, and would allow for direct payments even when the vendor is offline. The reference client may choose to be opinionated on the type of payment, but other implementations may give the buyer more choice.
- Services (such as Duo Search) send orders using `OFFLINE_RELAY` messages even when the vendor is online. This scheme allows for such orders to be automatically confirmed orders.

This also simplifies the code:

- There is no need to make an exception for `SendOrder` in `net.go` as described [here](https://github.com/OpenBazaar/openbazaar-go/pull/221#issuecomment-269648301).
- There is no need to have an `options interface{}` for the handlers, and no need to [hardcode `options`](https://github.com/OpenBazaar/openbazaar-go/blob/82a1f51f3658a39ae8c6e8802945ba89f4af776b/net/service/handlers.go#L147) in `OFFLINE_RELAY`.
- The logic in `handleOrder` can be significantly simplified.
- The type of payment and type of order are decoupled (see above). This should result in more modular code.

**Comment by cpacia** [comment]
I'm not following this:

> This decouples the type of payment (direct payments vs 1-of-2 clawbackable payments) from the type of order (automatically confirmed vs manually confirmed). For example, the protocol would allow for 1-of-2 clawbackable payments even for moderated payments, and would allow for direct payments even when the vendor is offline. The reference client may choose to be opinionated on the type of payment, but other implementations may give the buyer more choice.

Seems like it would be very inefficient to send the payment into a 1 of 2 during a moderated order, only to move it into a 2 of 3 afterwards. 

Also, keep in mind direct payments where the vendor is online work differently because it provides the vendor with a chance to provide an addresses. 

```
order ----> ack (with payment address) -----> payment
```

When the vendor is offline we don't know the payment address.

**Comment by JustinDrake** [comment]
> Seems like it would be very inefficient to send the payment into a 1 of 2 during a moderated order, only to move it into a 2 of 3 afterwards.

To me it seems it is the opposite. Doing a clawback through a moderator (as opposed to directly with a 1-of-2) is very inefficient, if not completely broken. The moderator has to check that the clawback request from the buyer is legit (i.e. that the buyer is not trying to defraud the vendor). So the moderator has to contact the vendor before doing the clawback... but the vendor is offline! So the moderator has to wait the inactivity period as agreed in his moderation policy (say, 1 week). The buyer also has to cover the moderator fee (say, 2%), and it takes time and effort to liaise with the vendor. Notice also that if the moderator is also offline, it is impossible for the buyer to singlehandedly change moderator, and the funds would be lost forever. In summary, clawbacks using a moderator does not work, so buyer will want to send funds to a 1-of-2 first.

> When the vendor is offline we don't know the payment address.

I wasn't aware of this. Why does the vendor need to provide a payment address? Can't the buyer derive a payment address from the vendor public key and a random chaincode, similar to [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/order.go#L429)?
