### ISSUE TITLE
GetMessages seems to return all messages, not just those of the right peerId and subject

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#299]
As far as I can tell, GetMessages queries the ChatDB for all messages, then parses all of them setting peer ids and subjects to those in the signature. This means that messages of the wrong peerId and subject are incorrectly returned, but with modified peerid and subject so that they seem correctly returned.

The test is set up to check if 3 messages are returned, but only 2 exist of the correct peerId and subject; thus the test passes even though I think the function is incorrect.

**Comment by cpacia** [comment]
Yeah it looks like peerId needs to be added to the query

**Comment by jackkleeman** [comment]
And subject as well. Or is getMessages meant to return everything for a peer? I feel like this would be preferable, or otherwise the UI will have to know subjects to call, and subjects are not returned by getConversations

**Comment by cpacia** [comment]
The subject is intended to be "" for chat messages and set to an order ID if the message is about an order.

**Comment by jackkleeman** [comment]
As far as I can tell, your fix means only messages of the right peer id are returned, but of any subject. The subject is then modified to be the same as the one requested. I think both subject and peerId need to be in the query, or otherwise use logic to filter out incorrect subjects.
