### ISSUE TITLE
Will openbazaar-go also work with libbitcoin?

### ISSUE THREAD

**Issue by stevenroose** [OpenBazaar/openbazaar-go#3]
As an alternative, the Go implementation btcd could be considered.

**Comment by cpacia** [comment]
I believe Poon and Dryja are building an spv wallet based on btcd. I think that would be ideal. Maybe optionally turn on the full node.

**Comment by cpacia** [comment]
Re libbitcoin, it will probably need to be that for now. The zmq client portion needs to be ported to go, however.

**Comment by cpacia** [comment]
Libbitcoin has been ported. It's likely the wallet implementation will be the libbitcoin for now. Even if we switch that code can probably stay in case people want to use it.
