### ISSUE TITLE
Can we agree on sane versioning?

### ISSUE THREAD

**Issue by duosearch** [OpenBazaar/openbazaar-go#30]
Versioning is important communication for collaborative dev work. Part of what made `OpenBazaar-Server` hard for others to work on was the versioning was inconsistent and poorly updated.

Ideally, the various version numbers appears in a single place and there are clear guidelines for updating them, e.g. http://semver.org

For example at the moment we have 

> fmt.Println("OpenBazaar Server v2.0 starting...")

from [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/openbazaard.go#L472) and

> "version": "0.2.0"

from [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/package.json#L13) and

> var ProtocolOpenBazaar protocol.ID = "/openbazaar/app/1.0.0"

from [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/net/service/service.go#L22).

Can we agree on a clear versioning process?

**Comment by cpacia** [comment]
The wire protocol version is different from the app version

**Comment by hoffmabc** [comment]
Ok so maybe we just need somewhere in the README that explains the versioning and what they mean @cpacia ?

**Comment by duosearch** [comment]
@cpacia One confusing thing is that the wire protocol is already at 1.0.0 but seems to be changing during the development process. Are we really already at 1.0.0? How will version numbers change during the development process?

**Comment by cpacia** [comment]
When we get docs.openbazaar.org built out the versioning explanation will be in there.
