### ISSUE TITLE
Testing out openbazaar-go

### ISSUE THREAD

**Issue by duosearch** [OpenBazaar/openbazaar-go#31]
Ok, I've got `openbazaar-go` running

```
Justins-MacBook-Air:openbazaar-go justin$ go run openbazaard.go start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v2.0 starting...
generating 4096-bit RSA keypair...done
15:56:02.029 [DoInit] [INFO] initializing openbazaar node at /Users/justin/OpenBazaar2.0
15:56:04.087 [Execute] [INFO] Peer ID:  QmcQSSjQZi2bHGbR3e7xU9UYEjKwAiWoGbzVdbXftnTjsy
15:56:04.087 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/4001
15:56:04.088 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/udp/4001/utp
15:56:04.088 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.0.16/tcp/4001
15:56:04.088 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.0.16/udp/4001/utp
15:56:04.088 [printSwarmAddrs] [INFO] Swarm listening on /ip4/78.221.67.24/tcp/4001
15:56:04.088 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/4001
15:56:04.088 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/udp/4001/utp
15:56:04.101 [Execute] [INFO] Starting bitcoin wallet...
15:56:04.101 [serveHTTPGateway] [INFO] Gateway/API server listening on /ip4/127.0.0.1/tcp/8080
15:56:04.131 [SetupOpenBazaarService] [INFO] OpenBazaar service running at /openbazaar/app/1.0.0
```

The `README.md` file doesn't have further steps after `go run openbazaard.go start`, so now what? How can I play around with the server? What can I do?

I notice there's an API server listing on 127.0.0.1:8080 but a naive GET request responds with `404 page not found` without further information or documentation.

**Comment by cpacia** [comment]
https://github.com/OpenBazaar/openbazaar-go/blob/master/api/endpoints.go

**Comment by hoffmabc** [comment]
This is not really an issue but support request. We can deal with this in Slack please.

**Comment by duosearch** [comment]
@hoffmabc: This is a documentation issue, no?

**Comment by hoffmabc** [comment]
1) First of all the issue is not descriptive at all.
2) How can I play with the server is not a great issue description. If you want us to have a request around improving documentation it probably needs to be formatted quite a bit better.

Is that a better understanding of the problem with this issue? If we don't have clear and actionable issues we won't be able to keep track of all of these and help you get what you need.

**Comment by duosearch** [comment]
@hoffmabc Fair enough. Should I create a new issue titled "Add usage instructions in README.md"?

**Comment by hoffmabc** [comment]
Yes that would be more helpful. Thank you.
