### ISSUE TITLE
Add memo to OrderFulfillment and ETA to PhysicalDelivery

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#313]
The [`OrderFulFillment` protobuf](https://github.com/duomoney/openbazaar-go-encrypter/blob/master/pb/protos/contracts.proto#L230) should probably have a `memo` for any notes related to the fulfillment.

The [`PhysicalDelivery` message](https://github.com/duomoney/openbazaar-go-encrypter/blob/master/pb/protos/contracts.proto#L230) should probably have an `ETA` field to indicate the shipping ETA.

**Comment by JustinDrake** [comment]
cc @morebrownies and @jjeffryes 

The reason for adding a `memo` is for the vendor to add a note attached to the fulfilment, e.g. "Sorry for the late dispatch, we had issues with our provider. We've upgraded shipping to Express."

The reason for adding an `ETA` for physical deliveries is pretty self-explanatory, e.g. "Estimated delivery between Jan 26 and Jan 28".

**Comment by hoffmabc** [comment]
Since the ETA would be free text I think they can put this in the memo field anyways.

**Comment by placer14** [comment]
`OrderFulfillment` has a `note` field already.
