### ISSUE TITLE
list dependencies somewhere off of README

### ISSUE THREAD

**Issue by themusicgod1** [OpenBazaar/openbazaar-go#316]
Getting this into Debian is going to take a list of all dependencies somewhere, even if they are managed by this go platform thing.  Where can this be located?

**Comment by themusicgod1** [comment]
found the deps list https://github.com/OpenBazaar/openbazaar-go/blob/master/Godeps/Godeps.json :  
this is a rather large list: 
github.com/OpenBazaar/go-blockstackclient
github.com/OpenBazaar/jsonpb
github.com/OpenBazaar/spvwallet
github.com/boltdb/bolt
github.com/btcsuite/btcd/addrmgr
github.com/btcsuite/btcd/blockchain
github.com/btcsuite/btcd/btcec
github.com/btcsuite/btcd/btcjson
github.com/btcsuite/btcd/chaincfg
github.com/btcsuite/btcd/chaincfg/chainhash
github.com/btcsuite/btcd/connmgr
github.com/btcsuite/btcd/database
github.com/btcsuite/btcd/peer
github.com/btcsuite/btcd/txscript
github.com/btcsuite/btcd/wire
github.com/btcsuite/btclog
github.com/btcsuite/btcrpcclient
github.com/btcsuite/btcutil
github.com/btcsuite/btcutil/base58
github.com/btcsuite/btcutil/bloom
github.com/btcsuite/btcutil/coinset
github.com/btcsuite/btcutil/hdkeychain
github.com/btcsuite/btcutil/txsort
github.com/btcsuite/btcwallet/internal/helpers
github.com/btcsuite/btcwallet/wallet/internal/txsizes
github.com/btcsuite/btcwallet/wallet/txauthor
github.com/btcsuite/btcwallet/wallet/txrules
github.com/btcsuite/fastsha256
github.com/btcsuite/go-socks/socks
github.com/btcsuite/golangcrypto/ripemd160
github.com/btcsuite/seelog
github.com/btcsuite/websocket
github.com/ccding/go-stun/stun
github.com/davecgh/go-spew/spew
github.com/dropbox/dropbox-sdk-go-unofficial
github.com/dropbox/dropbox-sdk-go-unofficial/apierror
github.com/dropbox/dropbox-sdk-go-unofficial/async
github.com/dropbox/dropbox-sdk-go-unofficial/files
github.com/dropbox/dropbox-sdk-go-unofficial/sharing
github.com/dropbox/dropbox-sdk-go-unofficial/team
github.com/dropbox/dropbox-sdk-go-unofficial/users
github.com/fatih/color
github.com/golang/protobuf/proto
github.com/golang/protobuf/ptypes
github.com/golang/protobuf/ptypes/any
github.com/golang/protobuf/ptypes/duration
github.com/golang/protobuf/ptypes/timestamp
github.com/gorilla/websocket
github.com/ipfs/go-ipfs/Godeps/_workspace/src/bazil.org/fuse
github.com/ipfs/go-ipfs/Godeps/_workspace/src/bazil.org/fuse/fs
github.com/ipfs/go-ipfs/Godeps/_workspace/src/bazil.org/fuse/fuseutil
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-is-domain
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/mitchellh/go-homedir
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/mtchavez/jenkins
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/texttheater/golang-levenshtein/levenshtein
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/chunker
github.com/ipfs/go-ipfs/assets
github.com/ipfs/go-ipfs/blocks
github.com/ipfs/go-ipfs/blocks/blockstore
github.com/ipfs/go-ipfs/blocks/bloom
github.com/ipfs/go-ipfs/blocks/key
github.com/ipfs/go-ipfs/blocks/set
github.com/ipfs/go-ipfs/blockservice
github.com/ipfs/go-ipfs/commands
github.com/ipfs/go-ipfs/commands/cli
github.com/ipfs/go-ipfs/commands/files
github.com/ipfs/go-ipfs/commands/http
github.com/ipfs/go-ipfs/core
github.com/ipfs/go-ipfs/core/commands
github.com/ipfs/go-ipfs/core/commands/files
github.com/ipfs/go-ipfs/core/commands/object
github.com/ipfs/go-ipfs/core/commands/unixfs
github.com/ipfs/go-ipfs/core/corehttp
github.com/ipfs/go-ipfs/core/corerepo
github.com/ipfs/go-ipfs/core/coreunix
github.com/ipfs/go-ipfs/diagnostics
github.com/ipfs/go-ipfs/diagnostics/pb
github.com/ipfs/go-ipfs/exchange
github.com/ipfs/go-ipfs/exchange/bitswap
github.com/ipfs/go-ipfs/exchange/bitswap/decision
github.com/ipfs/go-ipfs/exchange/bitswap/message
github.com/ipfs/go-ipfs/exchange/bitswap/message/pb
github.com/ipfs/go-ipfs/exchange/bitswap/network
github.com/ipfs/go-ipfs/exchange/bitswap/notifications
github.com/ipfs/go-ipfs/exchange/bitswap/testnet
github.com/ipfs/go-ipfs/exchange/bitswap/wantlist
github.com/ipfs/go-ipfs/exchange/offline
github.com/ipfs/go-ipfs/exchange/reprovide
github.com/ipfs/go-ipfs/flags
github.com/ipfs/go-ipfs/fuse/ipns
github.com/ipfs/go-ipfs/fuse/mount
github.com/ipfs/go-ipfs/fuse/node
github.com/ipfs/go-ipfs/fuse/readonly
github.com/ipfs/go-ipfs/importer
github.com/ipfs/go-ipfs/importer/balanced
github.com/ipfs/go-ipfs/importer/chunk
github.com/ipfs/go-ipfs/importer/helpers
github.com/ipfs/go-ipfs/importer/trickle
github.com/ipfs/go-ipfs/merkledag
github.com/ipfs/go-ipfs/merkledag/pb
github.com/ipfs/go-ipfs/merkledag/test
github.com/ipfs/go-ipfs/merkledag/utils
github.com/ipfs/go-ipfs/mfs
github.com/ipfs/go-ipfs/namesys
github.com/ipfs/go-ipfs/namesys/pb
github.com/ipfs/go-ipfs/namesys/republisher
github.com/ipfs/go-ipfs/notifications
github.com/ipfs/go-ipfs/path
github.com/ipfs/go-ipfs/pin
github.com/ipfs/go-ipfs/pin/gc
github.com/ipfs/go-ipfs/pin/internal/pb
github.com/ipfs/go-ipfs/repo
github.com/ipfs/go-ipfs/repo/common
github.com/ipfs/go-ipfs/repo/config
github.com/ipfs/go-ipfs/repo/fsrepo
github.com/ipfs/go-ipfs/repo/fsrepo/lock
github.com/ipfs/go-ipfs/repo/fsrepo/migrations
github.com/ipfs/go-ipfs/repo/fsrepo/serialize
github.com/ipfs/go-ipfs/routing
github.com/ipfs/go-ipfs/routing/dht
github.com/ipfs/go-ipfs/routing/dht/pb
github.com/ipfs/go-ipfs/routing/dht/providers
github.com/ipfs/go-ipfs/routing/kbucket
github.com/ipfs/go-ipfs/routing/keyspace
github.com/ipfs/go-ipfs/routing/mock
github.com/ipfs/go-ipfs/routing/none
github.com/ipfs/go-ipfs/routing/offline
github.com/ipfs/go-ipfs/routing/record
github.com/ipfs/go-ipfs/tar
github.com/ipfs/go-ipfs/thirdparty/datastore2
github.com/ipfs/go-ipfs/thirdparty/delay
github.com/ipfs/go-ipfs/thirdparty/dir
github.com/ipfs/go-ipfs/thirdparty/ipfsaddr
github.com/ipfs/go-ipfs/thirdparty/loggables
github.com/ipfs/go-ipfs/thirdparty/math2
github.com/ipfs/go-ipfs/thirdparty/peerset
github.com/ipfs/go-ipfs/thirdparty/pq
github.com/ipfs/go-ipfs/thirdparty/tar
github.com/ipfs/go-ipfs/thirdparty/testutil
github.com/ipfs/go-ipfs/thirdparty/todocounter
github.com/ipfs/go-ipfs/tour
github.com/ipfs/go-ipfs/unixfs
github.com/ipfs/go-ipfs/unixfs/archive
github.com/ipfs/go-ipfs/unixfs/archive/tar
github.com/ipfs/go-ipfs/unixfs/io
github.com/ipfs/go-ipfs/unixfs/mod
github.com/ipfs/go-ipfs/unixfs/pb
github.com/jbenet/go-base58
github.com/jbenet/go-context/io
github.com/jbenet/go-multiaddr
github.com/jbenet/go-multihash
github.com/jessevdk/go-flags
github.com/kennygrant/sanitize
github.com/mattn/go-colorable
github.com/mattn/go-isatty
github.com/mitchellh/go-homedir
github.com/mutecomm/go-sqlcipher
github.com/natefinch/lumberjack
github.com/nfnt/resize
github.com/op/go-logging
github.com/tyler-smith/go-bip39
github.com/yawning/bulb
github.com/yawning/bulb/utils/pkcs1
golang.org/x/crypto/hkdf
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/scrypt
golang.org/x/crypto/sha3
golang.org/x/crypto/ssh/terminal
golang.org/x/net/context
golang.org/x/net/html
golang.org/x/net/html/atom
golang.org/x/net/proxy
golang.org/x/oauth2
golang.org/x/oauth2/internal
golang.org/x/sys/unix
gx/ipfs/QmNLvkCDV6ZjUJsEwGNporYBuZdhWT6q7TBVYQwwRv12HT/go-nat
gx/ipfs/QmNQynaz7qfriSUJkiEZUrm2Wen1u3Kj9goZzWtrPyu7XR/go-log
gx/ipfs/QmNaS34WZRjs4U1kDfRR2aooYSsBSusFPMEg3dAKk7VZid/go-libp2p-loggables
gx/ipfs/QmNtxDQBrVzy88FEjVikyM5tAbyfnHm5jJbJZcUhVykusq/snappy
gx/ipfs/QmPJUtEJsm5YLUWhF6imvyCH8KZXRJa9Wup7FDMwTy5Ufz/backoff
gx/ipfs/QmPSBJL4momYnE7DcUyk2DVhD6rH488ZmHBGLbxNdhU44K/go-humanize
gx/ipfs/QmPSR1zYgWRmTSt6nTGXdeeUhWkq9AdvK4sva4Y2H5daPi/utp
gx/ipfs/QmPpRcbNUXauP3zWZ1NJMLWpe4QnmEHrd2ba2D3yqWznw7/go-multiaddr-net
gx/ipfs/QmQdnfvZQuhdT93LNc5bos52wAmdr3G2p6G8teLJMEN32P/go-libp2p-peerstore
gx/ipfs/QmQdnfvZQuhdT93LNc5bos52wAmdr3G2p6G8teLJMEN32P/go-libp2p-peerstore/addr
gx/ipfs/QmQdnfvZQuhdT93LNc5bos52wAmdr3G2p6G8teLJMEN32P/go-libp2p-peerstore/queue
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/context
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/periodic
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/ratelimit
gx/ipfs/QmQvJiADDe7JR4m968MwXobTCCzUqQkP87aRHe29MEBGHV/go-logging
gx/ipfs/QmQzTLDsi3a37CJyMDBXnjiHKQpth3AGS1yqwU57FfLwfG/cors
gx/ipfs/QmRBqJF7hb8ZSpRcMwUt8hNhydWcxGEhtk81HKq6oUwKvs/go-libp2p-peer
gx/ipfs/QmRBqJF7hb8ZSpRcMwUt8hNhydWcxGEhtk81HKq6oUwKvs/go-libp2p-peer/addr
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp/dcps/internetgateway1
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp/dcps/internetgateway2
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp/httpu
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp/scpd
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp/soap
gx/ipfs/QmRLjY36txVm2b44k1PameqWbAX6aGZepfRMeLbbKSZHnt/goupnp/ssdp
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/mpool
gx/ipfs/QmSHTSkxXGQgaHWz91oZV3CDy3hmKmDgpjbYRT6niACG4E/go-smux-yamux
gx/ipfs/QmSMZwvs3n4GBikZ7hKzT17c3bk65FmyZo2JqtJ16swqCv/multiaddr-filter
gx/ipfs/QmSscYPCcE1H3UQr2tnsJ2a9dK9LsHTBGgP71VW6fz67e5/mdns
gx/ipfs/QmT6n4mspWYEya864BhCUJEgyxiRfmiSY9ruQwTUNpRKaM/protobuf/proto
gx/ipfs/QmT8rehPR3F6bmwL6zjUN8XpiDBFFpMP2myPdC6ApsWfJf/go-base58
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/flatfs
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/keytransform
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/leveldb
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/measure
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/namespace
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/query
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/sync
gx/ipfs/QmTxLSvdhwg68WJimdS6icLPhZi28aTp6b7uihC2Yb47Xk/go-datastore/syncmount
gx/ipfs/QmURG1yr3RXYD2YKYaA5JMzMnThiKuKtqbgrP3nQX5ZVAz/go-nat-pmp
gx/ipfs/QmUWER4r4qMvaCnX5zREcfyiWN7cXN9g3a7fkRqNz8qWPP/go-libp2p-crypto
gx/ipfs/QmUWER4r4qMvaCnX5zREcfyiWN7cXN9g3a7fkRqNz8qWPP/go-libp2p-crypto/pb
gx/ipfs/QmUsh7scAkKe2erRhfGJpvxokArYL46ye2EJvFEp6XSbLr/golang_protobuf_extensions/pbutil
gx/ipfs/QmUusaX99BZoELh7dmPgirqRQ1FAmMnmnBn3oiqDFGBUSc/go-keyspace
gx/ipfs/QmV3NSS3A1kX5s28r7yLczhDsXzkgo65cqRgKFXYunWZmD/metrics
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/discovery
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/host
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/host/basic
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/host/routed
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/metrics
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/metrics/conn
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/metrics/stream
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/nat
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/conn
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/filter
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/mock
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/swarm
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/net/swarm/addr
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/protocol
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/protocol/identify
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/protocol/identify/pb
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/protocol/ping
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/protocol/relay
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/p2p/test/util
gx/ipfs/QmVCe3SNMjkcPgnpFhZs719dheq6xE7gJwjzV7aWcUM4Ms/go-libp2p/testutil
gx/ipfs/QmVYxfoJQiZijTgPNHCHgHELvQpbsJNTg6Crmc3dQkj3yy/golang-lru
gx/ipfs/QmVYxfoJQiZijTgPNHCHgHELvQpbsJNTg6Crmc3dQkj3yy/golang-lru/simplelru
gx/ipfs/QmVcmcQE9eX4HQ8QwhVXpoHt3ennG7d299NDYFq9D1Uqa1/go-smux-multistream
gx/ipfs/QmVdtNvi3madh1HtiX4HByrpjQqkkHUYh6DARq2QC6NxXt/spdystream
gx/ipfs/QmVdtNvi3madh1HtiX4HByrpjQqkkHUYh6DARq2QC6NxXt/spdystream/spdy
gx/ipfs/QmVjz1uf6U3sVQ5DbWWj7ktTtDd4GgsptYc7FBp33nWE53/go-libp2p-secio
gx/ipfs/QmVjz1uf6U3sVQ5DbWWj7ktTtDd4GgsptYc7FBp33nWE53/go-libp2p-secio/pb
gx/ipfs/QmVvJ27GcLaLSXvcB4auk3Gn3xuWK5ti5ENkZ2pCoJEYW4/autobatch
gx/ipfs/QmWHgLqrghM9zw77nF6gdvT9ExQ2RB9pLxkd8sDHZf1rWb/go-temp-err-catcher
gx/ipfs/QmWQ2SJisXwcCLsUXLwYCKSfyExXjFRW2WbBH5sqCUnwX5/bbloom
gx/ipfs/QmWchsfMt9Re1CQaiHqPQC1DrZ9bkpa6n229dRYkGyLXNh/dns
gx/ipfs/QmWi28zbQG6B1xfaaWx5cYoLn3kBFU6pQ6GWQNRV5P6dNe/lock
gx/ipfs/QmWzfrG1PUeF8mDpYfNsRL3wh5Rkgnp68LAWUB2bhuDWRL/go-libp2p-transport
gx/ipfs/QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa/go-context/frac
gx/ipfs/QmX6DhWrpBB5NtadXmPSXYNdVvuLfJXoFNMvUMoVvP5UJa/go-context/io
gx/ipfs/QmXPKMT5cT8ajqamSD1YaeEpfeaHvs9AU4MQzte4Bkr6V4/sys/unix
gx/ipfs/QmXwr6sCMxHSgHkYtpg9u8WtLL2qwGabKHBujNQmLwawBs/xhandler
gx/ipfs/QmYPZJkvydXC1MkXaERL5ohNdghqwdQprKgjMTVHuf26vd/hdrhistogram
gx/ipfs/QmYVkdUUNyPfPGYKc49TMd9BV8ByxRgoCauaZghh3bu81d/go-smux-spdystream
gx/ipfs/QmYf7ng2hG5XBtJA3tN34DQ2GUN5HNksEw1rLDkmr6vGku/go-multihash
gx/ipfs/QmYkNhwAviNzN974MB3koxuBRhtbvCotnuQcugrPF96BPp/client_model/go
gx/ipfs/QmYnf27kzqR2cxt6LFZdrAFJuQd6785fTkBvMuEj9EeRxM/proquint
gx/ipfs/QmYzDkkgAEmrcNzFCiYo6L1dTX4EAG1gZkbtdbd9trL4vd/go-multiaddr
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/proto
gx/ipfs/QmZ8MMKFwA95viWULoSYFZpA4kdFa8idmFSrP12YJwjjaL/yamux
gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util
gx/ipfs/QmZRjKbHa6DenStpQJFiaPcEwkZqrx7TH6xTf342LDU3qM/go-sysinfo
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/context
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/html
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/html/atom
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/html/charset
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/internal/iana
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/ipv4
gx/ipfs/QmZy2y8t9zQH2a1b8q2ZSLKp17ATuJoCNxxyMFG5qFExpt/go-net/ipv6
gx/ipfs/Qma5KQppqMBmpdNeVUDuNtEkec1BRNWcS3dodUdiP9267q/gateway
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport
gx/ipfs/QmaaC9QMYTQHCbMq3Ebr3uMaAR2ev4AVqMmsJpgQijAZbJ/go-reuseport/poll
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/charmap
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/internal
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/internal/identifier
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/japanese
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/korean
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/simplifiedchinese
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/traditionalchinese
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/encoding/unicode
gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ/go-text/transform
gx/ipfs/QmaeRR9SpXumU5tYLRkq6x6pfMe8qKzxn4ujBpsTJ2zQG7/go-os-rename
gx/ipfs/Qmb1DA2A9LS2wR4FFweB4uEDomFsdmnw1VLawLE1yQzudj/base32
gx/ipfs/Qmb1US8uyZeEpMyc56wVZy2cDFdQjNFojAUYVCoo9ieTqp/go-stream-muxer
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/cache
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/comparer
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/errors
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/filter
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/iterator
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/journal
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/memdb
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/opt
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/storage
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/table
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/util
gx/ipfs/QmbNinL4ErzM73BxQSNf8q2vPmAM4v3MNQM2DmDqDjt47D/perks/quantile
gx/ipfs/QmbcS9XrwZkF1rZj8bBwwzoYhVuA2PCnPhFUL1pyWGgt2A/go-notifier
gx/ipfs/Qmc2wJGUy2Gr9CyXNkUewoK6LRn9nnbBCrM6f9qap4xTNP/sync
gx/ipfs/Qmc5do1bC3JH73MThEgKgKkgNKLmqrvh2uaE6919yDmUaa/procfs
gx/ipfs/QmcLqWSFsaQ8Ujh8Ys8i9JPHVy1CcdPoqV23M9S3ufdVbn/go-sockaddr/net
gx/ipfs/QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa/go-semver/semver
gx/ipfs/QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV/go.uuid
gx/ipfs/QmdYwCmx8pZRkzdcd8MhmLJqYVoVTC1aGsy5Q4reMGLNLg/atomicfile
gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus
gx/ipfs/QmdjUo6xTRaLxmxYeRioG7uGMcywZzxubsVpnkUKiztmY3/common/expfmt
gx/ipfs/QmdjUo6xTRaLxmxYeRioG7uGMcywZzxubsVpnkUKiztmY3/common/internal/bitbucket.org/ww/goautoneg
gx/ipfs/QmdjUo6xTRaLxmxYeRioG7uGMcywZzxubsVpnkUKiztmY3/common/model
gx/ipfs/QmduCCgTaLnxwwf9RFQy2PMUytrKcEH9msohtVxSBZUdgu/go-peerstream
gx/ipfs/Qme1boxspcQWR8FBzMxeppqug2fYgYc15diNWmqgDVnvn2/go-crypto/blowfish
gx/ipfs/Qme1boxspcQWR8FBzMxeppqug2fYgYc15diNWmqgDVnvn2/go-crypto/sha3
gx/ipfs/QmeLQ13LftT9XhNn22piZc3GP56fGqhijuL5Y8KdUaRn1g/mafmt
gx/ipfs/QmeQKXFrogdhUZ5LJpJFa4jQgwX8edLzKft6GskfJR2yJT/missinggo
gx/ipfs/QmeQKXFrogdhUZ5LJpJFa4jQgwX8edLzKft6GskfJR2yJT/missinggo/inproc
gx/ipfs/QmeQKXFrogdhUZ5LJpJFa4jQgwX8edLzKft6GskfJR2yJT/missinggo/pproffd
gx/ipfs/QmeWQMDa5dSdP4n8WDeoY5z8L2EKVqF4ZvK4VEHsLqXsGu/hamming
gx/ipfs/QmeWjRodbcZFKe5tMN7poEx3izym6osrLSnTLf9UjJZBbs/pb
gx/ipfs/QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB/go-metrics
gx/ipfs/Qmf91yhgRLo2dhhbc5zZ7TxjMaR1oxaWaoc9zRZdi1kU4a/go-multistream

**Comment by cpacia** [comment]
These are all packaged in the vendor package. I wouldn't recommend downloading the dependencies separately as at least some of the ipfs/go-ipfs package has been modified to use the source found in OpenBazaar/go-ipfs.

**Comment by cpacia** [comment]
Also a list can be found in Godeps.json
