### ISSUE TITLE
Questions about moderation

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#318]
I have a couple of questions regarding moderation:

1. When the buyer or seller initiates a moderated dispute, how does chat work with the moderator? Are there only two separate bilateral chats between the moderator and the buyer/seller? Is a 3-way chat with the moderator, buyer and seller also created?
2. What is the process for the buyer to provide OpenBazaar evidence to the moderator? For example, the buyer may want to disclose the OpenBazaar chat that has happened with the seller. Should we aim to have this disclosure tamper proof by having chat messages signed?

**Comment by cpacia** [comment]
1. UI needs to send separate messages to the other two parties. 

2. There isn't a way to do that atm.

**Comment by JustinDrake** [comment]
Closing in favour of #362.
