### ISSUE TITLE
The application was unable to start correctly (0xc000007b).

### ISSUE THREAD

**Issue by misog** [OpenBazaar/openbazaar-go#320]
Hi, when I run v0.4.1 with the libwinpthread-1.dll in the same directory then it will not start:

The application was unable to start correctly (0xc000007b). Click OK to close the application.

Windows 10, 64bit

![obrazok](https://cloud.githubusercontent.com/assets/6667651/21859769/4260c968-d82e-11e6-8d74-b87f2cc01d22.png)

**Comment by cpacia** [comment]
@hoffmabc did you get this working? I can spin up a windows VM if necessary.

**Comment by hoffmabc** [comment]
Let me check it now.

**Comment by hoffmabc** [comment]
Try with this file https://github.com/OpenBazaar/openbazaar-go/releases/download/v0.4.1/libwinpthread-1.dll

**Comment by misog** [comment]
@hoffmabc it works with that dll :)

**Comment by hoffmabc** [comment]
Looks like we'll need a 64-bit one and 32-bit.

**Comment by Skymax7** [comment]
lol, happen to me , I tried with all dlls but nothing
