### ISSUE TITLE
Timelocked release of escrowed funds to vendor

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#325]
(This was discussed during the partners call on January 12, with unanimous support from @hoffmabc, @cpacia, @jjeffryes, @morebrownies, @jackkleeman and myself. Chris indicated this is doable.)

The concept of manually releasing funds is alien to traditional e-commerce. Instead, buyers expect a dispute window during which they can start a moderated dispute and request a refund. To avoid vendors being stuck with unreleased funds (a scenario that happened often in OB 1.0) it is suggested to add a timelock on escrowed funds to release funds to the vendor. Properties of this timelock:

- The timelock is set on a per listing basis
- The timelock is optional, but set by default with a period of 30 days
- The timelock period can be adjusted (e.g. lowered for instantly-delivered digital goods)
- The timelock is to be clearly displayed to buyers on purchase

This feature should significantly improve the purchase UX of OB 2.0 versus OB 1.0. It reduces the burden for buyers to manually release funds. It reduces the burden for vendors to liaise with the moderator if the buyer does not manually release funds.

**Comment by jackkleeman** [comment]
This can be acheived by the buyer signing a transaction with a locktime on
initiating the purchase, and sending this signature to the vendor, who can
then transmit the transaction after the timelock window if needed.

There is a slight attack vector here in that malicious vendors may reject
or refund transactions from users in the hope that the user will not come
online within the timelock window to retrieve the money from the multisig,
in which case the money will default to the vendor. How could this be
resolved? It is likely only an issue for short timelocks, but it may be
difficult to communicate this responsibility to buyers.

**Comment by cpacia** [comment]
The implementation is going to be somewhat difficult. CLTV probably isn't going to work for a variety of reasons so we'd have to use CSV. 

CSV can release funds based on the time or number of blocks. 

Releasing based on time is complicated as:

1. It doesn't use the timestamp from the block containing the transaction as the start time but rather the median time of the past 11 blocks. So you have to account for the start time being the confirmation time minus ~50 minutes. Which is weird. Also, it's huge pain in the ass to try to track median time in the wallet and try to communicate that to the listener. 

Going by number of blocks is easier to code but it doesn't provide an absolute time period. Instead 4,320 is **about** 30 days. Not sure if it's acceptable to tell the user 30 days if that's only an approximation.

**Comment by cpacia** [comment]
CLTV is an absolute time so you run into an issue where, let's say the time is 24 hours in advance, but the transaction doesn't confirm for 25 hours due to network congestion, then essentially there is no escrow. 

Also, it would be a PIA having the buyer and vendor agree on an exact timestamp because the time is going to be different when the buyer creates the script and when the vendor evaluates it.

**Comment by JustinDrake** [comment]
Somewhat unrelated points, but I think it's worth keeping them in mind in this discussion:

- A 24-hour dispute period does not really account for the realities of human-driven moderation. Realistically, a moderator may take a few days to communicate with the relevant parties and gather evidence. I think the minimum recommended dispute period should be 1 week, even for digital goods.
- Listings with vendor timelocks do not provide an incentive for the vendor to ever change moderator (e.g. if the moderator is offline, or if the moderator cannot make a decision). The buyer is only protected if the current moderator sides with him in a timely manner.
- By having a "custom" moderation script we may be introducing a marker to distinguish Bitcoin transactions related to OpenBazaar (i.e. privacy leak).

**Comment by JustinDrake** [comment]
With automatic release of funds, [this issue](https://github.com/OpenBazaar/openbazaar-desktop/issues/282) to decouple the review process from the fund release process becomes especially relevant. Indeed, as discussed during the partners call, we probably want to allow the buyer to make a review even if the funds were automatically released.

**Comment by jackkleeman** [comment]
Could this be accomplished simply with a message from the vendor to the moderator that automatically goes out after x amount of time, and the moderator automatically responds to and releases with no manual input? This seems simpler than using timelocks, and obviously if the moderator has already received a dispute request then it would disregard the autorelease message. The moderator would then also be able to extend the release time if asked to by vendor or buyer.

**Comment by hoffmabc** [comment]
I don't like the idea of including a moderator and then asking them to automatically release these funds. Also wouldn't this require them to be online? It doesn't really solve the abandonment issue.

**Comment by JustinDrake** [comment]
One advantage of having the moderator automatically release the funds is precisely the abandonment issue I highlighted above

> Listings with vendor timelocks do not provide an incentive for the vendor to ever change moderator (e.g. if the moderator is offline, or if the moderator cannot make a decision). The buyer is only protected if the current moderator sides with him in a timely manner.

If the moderator is offline, at least the buyer can negotiate with the vendor for a new moderator. Otherwise moderator abandonment is a de facto win for the vendor, which is unfair for the buyer.

**Comment by JustinDrake** [comment]
Is this going to be part of the initial release? If so, should it be put in one of the [milestones](https://github.com/OpenBazaar/openbazaar-go/milestones)?

**Comment by cpacia** [comment]
I think it's going to be a punt.

**Comment by JustinDrake** [comment]
Would it make sense to put this issue in a "post-release" milestone for better visibility?
