### ISSUE TITLE
Make DHT key prefix length configurable

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#334]
Duo will be heavily relying on offline messages, and the DHT key prefix length plays an important role for offline messages. In the short/medium term, we'd probably want to reduce the prefix length for two reasons:

- increase deniability
- reduce the possible DHT key space, making it easier to find offline messages

Over time we'd increase the prefix length to match network growth. The prefix length could be put in the profile, although there are probably complications that should be taken into account (e.g. if the profile cannot be fetched).

cc @jackkleeman

**Comment by jackkleeman** [comment]
The prefix length could be published in the same way as the public key, which has to be looked up for any initial message anyway. It would also need to be stored in the contract wherever peer IDs are stored.

**Comment by cpacia** [comment]
I don't think it would work to do either of those things. The prefix can change and if you use a hardcoded prefix from the contract then you could end up sending a message using an out of date prefix and the recipient wouldn't receive it. Also publishing in the DHT doesn't work because again there's the issue of getting the most up-to-date prefix.

**Comment by JustinDrake** [comment]
> publishing in the DHT doesn't work because again there's the issue of getting the most up-to-date prefix.

What about a similar scheme to IPNS? IPNS publishes to the DHT and there's the same issue of getting the most up-to-date data.

**Comment by JustinDrake** [comment]
Actually, we could just add a field to the [IPNS protobuf](https://github.com/ipfs/go-ipfs/blob/73cd8b3e98aba252f0eadcc625472103a2dd1d53/namesys/pb/namesys.proto). The `ttl`, `sequence` and `validity` scheme of IPNS ensures peers get the an up-to-date prefix.

**Comment by hoffmabc** [comment]
@cpacia is this still relevant? do we want to close this?
