### ISSUE TITLE
What is ed25519 used for?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#335]
During the technical call @cpacia mentioned that OpenBazaar will be moving away from RSA crypto, and use ed25519 instead. This brings a number of improvements, including safer crypto, faster identity key generation, and the replacement of certain signatures with HMACs for better deniability.

While libp2p-crypto supports ed25519, it looks like [libp2p-secio still doesn't](https://github.com/ipfs/go-ipfs/issues/3625#issuecomment-2746347240. Did I misunderstand that OpenBazaar will use ed25519 for fast identity key generation?

**Comment by cpacia** [comment]
As far as I can tell the secio uses the libp2p-crypto key interface for which there is an implementation of ed25519. @whyrusleeping can maybe confirm.

**Comment by JustinDrake** [comment]
See response [here](https://github.com/ipfs/go-ipfs/issues/3625#issuecomment-274711419).
