### ISSUE TITLE
Notifying counterparty of errors

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#337]
There is an [`ERROR` message](https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/message.proto#L27), but it is only used once, [in `handleOrder`](https://github.com/OpenBazaar/openbazaar-go/blob/0bfcc8138266da81b31bd8e2b1a386400389cac6/net/service/handlers.go#L166).

What is the intent of the `ERROR` message? Since errors can happen in any of the handlers, why is `ERROR` only used in `handleOrder`?

My assumption is that errors need to be communicated to the counterparty but this is not yet hooked up. For example, if the buyer wants to release funds but an error occurs with the vendor's `handleOrderCompletion` then the funds would not get released. Surely the buyer needs to be notified so that further action can be taken.

**Comment by cpacia** [comment]
It's possible to do that. It's only done for contract right now to make it easier to debug.

**Comment by JustinDrake** [comment]
This was discussed today during the technical call. I think @cpacia and I agree it's a good idea to simply start with putting these errors in a log for ease of debugging.

**Comment by cpacia** [comment]
Partially fixed
