### ISSUE TITLE
Allow reviews for confirmed orders

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#338]
Currently a buyer can only review fulfilled orders. Confirmed orders that are not fulfilled cannot receive a review. As I understand it, the social contract behind an confirmed order places a fiduciary duty on the vendor to fulfil the order. There are two ways an order can get confirmed:

- Manually confirmed: the vendor explicitly agrees to fulfil the order.
- Automatically confirmed: the inventory count is positive and the vendor implicitly agrees to fulfil the order.

Should the vendor confirm but not fulfil, the buyer may want to post a review. For example, the buyer may express frustration with his unfulfilled order, which may be helpful to others.

See also https://github.com/OpenBazaar/openbazaar-desktop/issues/282

**Comment by cpacia** [comment]
I don't think the buyer can place a review at that point because he doesn't have a signature from the vendor ... which comes in the fulfillment message. Without that signature the review cannot be authenticated.

**Comment by JustinDrake** [comment]
Can the confirmation message include a signature from the vendor?

**Comment by cpacia** [comment]
It could but then anyone could leave a signed review without actually buying anything.

**Comment by JustinDrake** [comment]
There can be two types of reviews:

- Pre-transaction reviews, for which it is understood the transaction may not have occurred
- Post-transaction review, for which it is understood a transaction has occurred
