### ISSUE TITLE
Instructions to recompile the protobufs

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#344]
What are the instructions for recompiling the protobufs? I am getting errors. The first problem I encountered was that it could not find the timestamp package.

Then I had a problem with the package name:

> net/networkservice.go:8:2: found packages pb (api.pb.go) and contracts (contracts.pb.go) in /Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/pb

I renamed the package to `pb` and now I get more errors

> Justins-MacBook-Pro:openbazaar-go justin$ go run openbazaard.go start
> import cycle not allowed
> package main
> 	imports github.com/OpenBazaar/openbazaar-go/api
> 	imports github.com/OpenBazaar/openbazaar-go/core
> 	imports github.com/OpenBazaar/openbazaar-go/net
> 	imports github.com/OpenBazaar/openbazaar-go/pb
> 	imports .
> 	imports .
> pb/api.pb.go:21:8: cannot find package "_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/proto" in any of:
> 	/usr/local/go/src/_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/proto (from $GOROOT)
> 	/Users/justin/go/src/_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/proto (from $GOPATH)
> pb/message.pb.go:21:8: cannot find package "_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/any" in any of:
> 	/usr/local/go/src/_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/any (from $GOROOT)
> 	/Users/justin/go/src/_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/any (from $GOPATH)
> pb/api.pb.go:24:8: cannot find package "_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/timestamp" in any of:
> 	/usr/local/go/src/_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/timestamp (from $GOROOT)
> 	/Users/justin/go/src/_/Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/vendor/github.com/golang/protobuf/ptypes/timestamp (from $GOPATH)
> /Users/justin/go/src/github.com/OpenBazaar/openbazaar-go/pb/contracts.pb.go:33:8: local import "." in non-local package

Help!

**Comment by jackkleeman** [comment]
See #266. You need to manually change the package names to pb for sure, not sure what else needs to change. Definitely we need instructions on this

**Comment by JustinDrake** [comment]
The IPFS team use makefiles. That or something similar would be great.

**Comment by cpacia** [comment]
- The package needs to be changed to pb.

- Unless you've added a new import, the imports should be the same as the file it's replacing

- When changing the imports, some of the method calls might need to remove the package identifier

- You need to make sure there is no overlap with numbers used for the filedescriptor. It's easiest to just use the same one as the old file.

**Comment by yurizhykin** [comment]
I couldn't find info on protobuf compiler option for a package, but it can be specialized in `.proto` file syntax. I'll submit a PR for adding package declarations into proto-files and a makefile in `pb` directory for compiling them.

**Comment by yurizhykin** [comment]
Please see #387 for a possible solution.

**Comment by JustinDrake** [comment]
Thanks for looking into it @yurizhykin 👍

**Comment by cpacia** [comment]
make protos
