### ISSUE TITLE
Clean up image sizes

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#349]
This issue was discussed during the partner's call on Thursday Jan 26 with @jjeffryes (@morebrownies also present). The current image sizes (see [here](https://github.com/OpenBazaar/openbazaar-go/blob/master/core/images.go)), which have been specifically tailored for `openbazaar-desktop`, are listed below.

**Avatar**
* 50x50
* 100x100
* 140x140
* 280x280

**Header**
* 304x87
* 608x174
* 1225x350
* 2450x700

**Listing**
* 60x60
* 228x228
* 500x500
* 1000x1000

There are several issues with these sizes:
* The aspect ratio is not consistent (e.g. 304/87 is not exactly equal to 2450/700)
* There is a large gap (the jump from 60x60 to 228x228 is a 14.44x increase in the number of pixels) instead of a smooth sampling of the image size space
* Some numbers are highly non-divisible (e.g. 87 has only two prime factors 3 and 29)
* There are several "arbitrary" constants which not agnostic of client (tailored specifically for openbazaar-desktop) and not future proof

My suggestion is to start with a highly divisible base resolution, and then multiply by 2 at each step. The number 90 is one of the numbers under 100 with the most divisors (1, 2, 3, 5, 6, 9, 10, 15, 18, 30, 45, 90), and it is only divisible by 2 once. This makes it a great base for the listing and avatar image sizes:

* 90x90
* 180x180
* 360x360
* 720x720

My suggestion for the header is to preserve the intended 3.5x aspect ratio, with the following sizes:

* 315x90
* 630x180
* 1260x360
* 2520x720

Notice that the height of the headers would match exactly with the width of the other images, which is neat. Notice also that my suggested header sizes are not far off (in absolute terms) from the original sizes. Notice also the appearance of the familiar number 720 (in regards to screen resolutions), which is not a coincidence.

I'd be happy to make a pull request with the updated sizes.

**Comment by JustinDrake** [comment]
Trying to revive this two-month old issue 👍

cc @jjeffryes, @rmisio, @morebrownies

**Comment by cpacia** [comment]
@jjeffryes @morebrownies what are your thoughts on this. I have no idea how this affects the UI to comment on it. 

Yes before release/yes after release/no

**Comment by jjeffryes** [comment]
Making the sizes have smaller gaps and be more evenly divisible would be beneficial. 

However, the avatar and listing sizes shouldn't be the same. The suggested sizes make the avatar bigger than it needs to be, and the listing images too small. 

The suggested header sizes would be fine.

I suggest instead we start with a size of 60, which is also fairly divisible, and stagger the avatar and listing sizes:

Avatar
60x60
120x120
240x240
480x480

Listing
120x120
240x240
480x480
960x960

This would have some effects on the reference client, mostly that we'd need to change which image sizes were used in some places, or slow down the downloads and rendering slightly by using images that are too large and scaled down. But that wouldn't be a major issue, I don't think.

**Comment by jjeffryes** [comment]
To answer the specific question, we could do this before the 2.0 release if we don't do any refactoring in the client, and defer optimization for the new image sizes to later.

**Comment by JustinDrake** [comment]
FWIW, @jjeffryes's suggestion makes sense and works for me 👍

**Comment by cpacia** [comment]
Merged
