### ISSUE TITLE
Cleaner approach to pointers

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#351]
From what I can tell, all three fields of what makes IPFS providers have been abused for OpenBazaar pointers. Specifically,

- The provider target key is replaced by a peer ID prefix key
- The provider peer ID is replaced by a random magic ID
- The provider addrs are replaced by the ciphertext hash

Moreover, it seems the sole purpose of the magic ID is to distinguish pointers from providers so as to give them a longer TTL.

As it stands this is a puzzling and somewhat poorly documented hack. @jackkleeman and I have been banging our heads with OpenBazaar pointers. Since OpenBazaar is forking IPFS, why not create two new DHT messages `ADD_POINTER` and `GET_POINTERS` to handle pointers?

**Comment by cpacia** [comment]
That wouldn't change how the data is stored. It's still going to be key -> peerInfo.

The code pointers.go code handles everything that is needed to set and get pointers. 

The only difference custom methods would make would be it would remove the reliance on the magic number but then that field would just be filled with random bits anyway. 

Creating and maintaining a third data structure in the DHT seems unnecessary and potentially a source of problems.

**Comment by JustinDrake** [comment]
> It's still going to be key -> peerInfo.

Why use `peerInfo`? We control how data is stored on the DHT. A pointer is *not* a peer info.

> that field would just be filled with random bits

Why? The magic number can be removed—completely. No need for random bits. Just map prefix hash -> ciphertext hash. `ADD_POINTER` adds a ciphertext hash. `GET_POINTERS` gets all ciphertext hashes.

> potentially a source of problems

Why?

**Comment by cpacia** [comment]
You have to build out an entirely different storage interface just to basically replicate 90% of the functionality that IPFS already has. 

And you have to build out separate IPFS network messages and handlers and then all that needs to be maintained. It wont be as easy as a simply rebase to the latest IPFS code. You'd have to keep all these changes in line with the changes going on in IPFS.

**Comment by JustinDrake** [comment]
> You have to build out an entirely different storage interface just to basically replicate 90% of the functionality that IPFS already has.

The storage interface is 90% there. It's a small tweak to the existing providers storage interface.

> you have to build out separate IPFS network messages and handlers

The job is 90% done. The messages and handlers are almost identical to existing messages and handlers for providers.

> You'd have to keep all these changes in line with the changes going on in IPFS.

The OpenBazaar-specific changes will be minimal given the storage, messages and handlers for pointers would be almost identical to those for providers. It's almost a copy-paste job; keeping in sync should not be hard. It would be a shame to knowingly introduce technical debt at the protocol level before OB 2 is even launched.
