### ISSUE TITLE
SUGGESTION: setapicreds flag

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#366]
**Part 1**

If the user has a fresh node that they want to make remote API calls to, they have to send the cmd: `go run openbazaard.go start` first, then stop the server, then type in `go run openbazaard.go setapicreds` in order to setup their remote api credentials.

It would save a lot of time if a user could initiate a new node with just one command: `go run openbazaard.go setapicreds`, whereby the credentials would be added to the config file before the node starts up for the first time.

**Part 2**

In the config file:

```
"JSON-API": {
    "Authenticated": false,
```

This should be automatically set to true with `setapicreds`.

**Comment by tyler-smith** [comment]
@drwasho You should be able to use `go run openbazaard.go init` instead of starting and stopping, but I agree that another cmd could be nice.

In my ideal world we would do all configuration with env variables and you wouldn't have to do any extra commands to configure your instance.
