### ISSUE TITLE
Variants Schema Redesign

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#368]
We need to redesign the contract schema to match the design below.
![image](https://cloud.githubusercontent.com/assets/4504708/23044762/9425f04a-f46f-11e6-8344-235fe712db75.png)

Only exception to the design is I think that Wolf is going to add a Sku to the table as well.

So here's my initial proposal for the new schema:

```
repeated Option options    = 12;
repeated Sku skus          = 13;

message Option {
    string name                = 1;
    string description         = 2;
    repeated Variants variants = 3;

    message Variants {
        string name          = 1;
        Image image          = 2;
    }
}

message Sku {
	string combinations = 1;
	uint64 surcharge     = 2;
	string id                   = 3;
}
```

The `options` field is used primarily to enumerate what options are available so the UI can populate the drop down boxes for option selection during checkout. 

We would eliminate the current string `sku` field and replace it with the repeated `Sku` object. This object would contain a string similar to what is used in inventory to identify which combination it represents. For example `/large/blue`. 

The `surcharge` would be added to the base price found earlier in the listing. 

`id` is a sku number. 

### Issues
1. In the above schema the `image` is attached to each variant (ie: large or blue but not /large/blue). Do we want to keep it this way or should the image be per combination?

2. We need better names for `combinations` and `id`. I called it `id` above just because having `sku` inside `Sku` seems weird. So help would be nice naming them. 

3. What happens if they include a list of options but no list of skus?

4. Does this seem to work?

**Comment by cpacia** [comment]
@rmisio @JustinDrake @jackkleeman @jjeffryes @drwasho

**Comment by JustinDrake** [comment]
This is what I proposed during the last technical call. You have options (e.g. size and color). Each option has variants (e.g. small, medium, large). The SKUs enumerate the variant combinations with a well-defined defined ordering.

Each SKU has a price, quantity, image. This is maximally flexible. If the frontend wants to reuse images across SKUs, it can! If the frontend wants absolute prices, percentage surchages, absolute surchages, or something crazy, it can!

In the special case where there are no options, there's a single SKU corresponding to the empty combination. In general, if there are `n` options and `v_i` is the number of variants for option `i`, then there are `v_1 * ... v_n` SKUs.

```
repeated Option options    = 12; // e.g. [sizeOption, colorOption]
repeated Sku skus          = 13; // e.g. [smallBlueSKU, smallGreenSKU, mediumBlueSKU, ...]

message Option {
    string name                = 1; // e.g. "size"
    string description         = 2; // e.g. "Choose your T-shirt size"
    repeated string variants   = 3; // e.g. ["small", "medium", "large"]
}

message Sku {
	repeated string combination; // e.g. ["medium", "blue"]
	string id;
	uint64 price;
	int quantity;
        Image image;
}
```

**Comment by JustinDrake** [comment]
On second though, the `combination` can be a `repeated int` to save space/bandwidth.

For exampe suppose again the size variants are `["small", "medium", "large"]` and the colour variants are `["green", "blue"]`. Then the possible combinations would be `[0, 0], [0, 1], [1, 0], [1, 1], [2, 0], [2, 1]` corresponding to `["small", "green"], ["small", "blue"], ...`.

**Comment by rmisio** [comment]
I don't think it makes sense to use the "sku" terminology for the repeated skus field. Really, it's just data that pertains to a variant combination. This is further enhanced by the fact that the sku is optional. Perhaps 'combinations' (or 'variantCombinations') would be better?

Also, I do think image would have to be at the combination level, although, since @cpacia mentioned it wouldn't be a problem to add a field later on, I think we could omit it for now. Or, it could be optional. The v2 client is not planning on supporting combo images for the initial release.

```
repeated Option options    = 12;
repeated Combination combinations          = 13;

message Option {
    string name                = 1; // size
    string description         = 2; // Choose a size please
    repeated Variants variants = 3; 

    message Variants {
        string name          = 1; // large, medium, small
    }
}

message Combination {
	string variantCombo = 1; // large/red, large/medium, large/small
	uint64 surcharge     = 2; // 100
	string sku                = 3; // abc123
}
```

With name the only field in the Variants object, it could be flattened to a list of strings, but what if in the future we want to associate some data with a variant? Would it be problematic with existing data to go from list of strings to a list of objects? If so, let's leave it as an object (sacrifice some bloat for some future proofing).

FWIW, I don't think I have any large objection to Justin's alternate representations of how the second object (the one he calls Sku) can reference the variant combo (whether it's 'large/red' or [large, red] or [0, 1]).

**Comment by JustinDrake** [comment]
Agreed with @rmisio that the `Sku` is awkward. I've refined my suggestion below.

```
repeated Option options       // e.g. [sizeOption, colorOption]
repeated Combo combos         // e.g. [smallBlue, smallGreen, mediumBlue, ...]

message Option {
    string name               // e.g. "size"
    string description        // e.g. "Choose your T-shirt size"
    repeated string variants  // e.g. ["small", "medium", "large"]
}

message Combo {
    repeated int combination  // e.g. [1, 1]
    string sku
    uint64 price
    int quantity
    Image image
}
```

**Comment by cpacia** [comment]
Those who haven't worked in a retail or ecommerce setting might find the term sku to be awkward, but that that's what products are called in retail. Nobody calls them combos. They say "I've got 10 skus I need to sell through", etc.

**Comment by JustinDrake** [comment]
How do you differentiate between sku the product struct, and sku the string identifier?

**Comment by jjeffryes** [comment]
Using Stock Keeping Unit in typical commerce can refer to both the product and the identification code, which can be confusing. I think SKU would be fine for the key, and we could use Identifier or Code for the identification in the object.

**Comment by cpacia** [comment]
@jjeffryes @rmisio what do you think about using integers in the variant combos rather than the variant names?

It would look like:
```
"skus": [
                    {
                        "variantCombo": [
                            0,
                            0
                        ],
                        "productID": "932-33-2945"
                    },
                    {
                        "variantCombo": [
                            0,
                            1
                        ]
                    },
                    {
                        "variantCombo": [
                            1,
                            0
                        ],
                        "productID": "123-99-1111"
                    },
    ]
```

**Comment by rmisio** [comment]
(thinking this through...)

```
options: [
  {
    name: 'size',
    description: 'choose a size please',
    variants: [
      {
        name: 'L'
      },
      {
        name: 'M'
      },
      {
        name: 'S'
      },
    ]
  },
  {
    name: 'color',
    description: 'choose a color please',
    variants: [
      {
        name: 'red'
      },
      {
        name: 'green'
      },
      {
        name: 'blue'
      },
    ]
  },
  {
    name: 'shape',
    description: 'choose a shape please',
    variants: [
      {
        name: 'circle'
      },
      {
        name: 'triangle'
      },
      {
        name: 'square'
      },
    ]
  }  
]
```
So is you wanted a SKU for a large/red/circle, it would be [0, 0, 0]?

For small/green/square, it would be [2, 1, 3]?

(Sorry, just had to think that through. If my understanding is correct there on how that would work, then it sounds fine to me.)
