### ISSUE TITLE
Chat message ID can be abused

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#371]
There's a new `MessageID` field for chat messages. This field is assumed to be a unique random number. Unfortunately uniqueness cannot be assumed as an attacker can reuse the same `MessageID`. As it stands, an attacker can rewrite the full chat history to his pleasing as `service.datastore.Chat().Put(chat.MessageId` will overwrite the message database. It's very likely there are other issues with reused `MessageID`s.

**Comment by JustinDrake** [comment]
My recommendation is to use the SHA256 of the message payload for the ID (which contains a timestamp), similar to how order IDs are handled.

**Comment by drwasho** [comment]
If size/space is a concern, we can use RIPEMD-160 hash instead.
