### ISSUE TITLE
Order timeline

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#372]
I think currently the timeline of the order state is not recorded. The `GETOrder` api returns the order's current state, but no metadata on intermediary state changes. I think it would be valuable to keep track of the state changes alongside timestamps. This would allow to display a timeline to the user, e.g.:

Order initiated on Feb 1
Order funded on Feb 2
Order fulfilled on Feb 3
Order completed on Feb 4
etc.

This is useful from a purely informational standpoint. It's also information that is worth keeping track of for moderation purposes. cc @morebrownies @jjeffryes

**Comment by jjeffryes** [comment]
That would be an interesting feature. @cpacia what do you think?

**Comment by morebrownies** [comment]
Makes sense to me. We will need this information in order to display the order summary details in the transaction detail screen: 

![screenshot 2017-02-17 10 14 55](https://cloud.githubusercontent.com/assets/13066886/23077569/f66047b2-f4f9-11e6-826c-3d8b4e21165d.png)

**Comment by tyler-smith** [comment]
A pattern I've used in the past is to have an "audit_foo" table. In this case we'd have `audit_orders`. It simply contains the id of the order, a timestamp, previous state, and new state. This abstraction is great for auditing and progression information as mentioned.

I would think moderators would sync from vendors with protections against manipulated data, and buyers would either do the same or sync from moderators. Nodes would show their local state but sync in the background.

Thoughts?

**Comment by JustinDrake** [comment]
It seems there is interest from several people. (Duo is certainly keen.) Do you have any thoughts @cpacia?

**Comment by cpacia** [comment]
Done

**Comment by JustinDrake** [comment]
Sorry I don't see it. Could you provide a link?
