### ISSUE TITLE
Clean up profile protobuf

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#374]
I suggest bundling colors together:

```
"colors": {
    "primary": "#AF854C",
    "secondary": "#E3E3E3",
    "text": "#FFFFFF",
    "highlight": "",
    "highlightText": ""
}
```

I also suggest bundling stats:

```
"stats": {
    "followers": 2,
    "following": 1,
    "listings": 0,
    "ratings": 2,
    "averageRating": 4.5
}
```

**Comment by cpacia** [comment]
@jjeffryes @rmisio what do you think?

**Comment by tyler-smith** [comment]
I'm a pretty big fan of this proposal. I definitely prefer to structure my data as much as possible and treating colors and stats info as separate objects seems to me to be a good implementation. Additionally, it's nice that like-types (specifically hexcodes) are grouped.

**Comment by JustinDrake** [comment]
One advantage of bundling stats together is the implicit semantic understanding that these are **not** authoritative numbers, and can be trivially faked. As I understand, these stats are there just for convenience. For example, if someone wants to get an authoritative listing count, they'd have to look into `listings/index.json`, or count the number of files in `listings/` (minus one for `index.json`).

**Comment by rmisio** [comment]
While I don't have a burning desire to get this one in, because it will require a bit of client re-work... it does make sense.

FWIW, to minimize future refactoring, let's get changes like this brought up sooner rather than later. The longer we wait, the more potential re-work.

**Comment by drwasho** [comment]
Great suggestion @JustinDrake

**Comment by cpacia** [comment]
done
