### ISSUE TITLE
Capitalisation inconsistency

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#377]
See http://gateway.ob1.io/ipns/QmSLTwZQPxX1peJVXxBBKTrVGVMKSSyom5sTDHxtVricvs/listings/ski-set.json

`btc` vs `USD`:

```
                "acceptedCurrency": "btc",
                "pricingCurrency": "USD"
```

**Comment by cpacia** [comment]
pricing currency is set by the UI while accepted currency is set by the server. In all cases I lcase them before working with them.

**Comment by JustinDrake** [comment]
Is it worth, for aesthetical reasons, normalising the frontend and the backend? cc @jjeffryes

**Comment by tyler-smith** [comment]
I really dislike the idea of not sanitizing/normalizing this before persisting it. All of my development experience leads me to feel that the server should sanitize every single bit of data it gets and be strict about what it serves

"Postel's Law" has a lot of haters but personally I'm a subscriber: `Be conservative in what you send; be liberal in what you accept.`

**Comment by JustinDrake** [comment]
Thanks for bringing up Postel's Law (which I just learned from you). To summarise, only half the law is being applied here. @cpacia is liberal about what is accepted, but the code as a whole (openbazaar-go and openbazaar-desktop) is not conservative about its output.

**Comment by jjeffryes** [comment]
Standardizing the capitalization seems like a good idea to me, I'd slightly prefer it be upper case, since that's the iso standard for currency codes (which is where our codes are derived from). 

But it can be lower case if there's a compelling reason to do so.

**Comment by cpacia** [comment]
currency codes are now upper case https://github.com/OpenBazaar/openbazaar-go/commit/a7cdb247d1a004a50385678d4d333c5b8a79fa94
