### ISSUE TITLE
Why is category an array?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#378]
See http://gateway.ob1.io/ipns/QmSLTwZQPxX1peJVXxBBKTrVGVMKSSyom5sTDHxtVricvs/listings/index.json

```
"category": [],
```

Should it be `categories` (plural), or not an array?

**Comment by cpacia** [comment]
@jjeffryes if I change this will it break the client?

**Comment by tyler-smith** [comment]
@cpacia How do you want to change it? Change the name or the type? I would think allowing multiple categories would be good, even if the reference client doesn't make use of that. I think change the name to `categories` is ideal.

**Comment by cpacia** [comment]
Just to `categories`

**Comment by rmisio** [comment]
It will, whether gracefully or not, break the client. It would probably be a quick fix, but let's coordinate this commit so the server change and corresponding client change could go into master around the same time.

**Comment by drwasho** [comment]
FWIW I'm ready to go for this change on my end.

**Comment by JustinDrake** [comment]
@cpacia Could you please include a reason why this is closed? (fixed, won't fix, duplicate, etc.)

cc @hoffmabc
