### ISSUE TITLE
Node is missing profile

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#379]
See http://gateway.ob1.io/ipfs/QmZPkQT2btirSNHgddmWcv8SeT5mVFKJKMS6naPJL7eebX

The profile link is missing.

**Comment by cpacia** [comment]
I don't know who is running that node but there is no way to force someone to seed a profile.

**Comment by JustinDrake** [comment]
This is not a Duo node. Most likely this node runs the reference client, and this is indicative of a bug with it.

**Comment by hoffmabc** [comment]
I think unless this is replicated or proven to be the case there's not much that can be done about this. Do you have any ways we can demonstrate this isn't a one-off issue on another custom node?
