### ISSUE TITLE
Issue with OpenSSL while the process installing go-sqlchiper 

### ISSUE THREAD

**Issue by mrtinkz** [OpenBazaar/openbazaar-go#38]
I have the gcc properly installed. But looks like there seems to be an issue while installing go-sqlchiper. Has anyone tried to install the new release on windows yet. Any help is greatly appreciated. Thanks

 go get github.com/OpenBazaar/openbazaar-go
# github.com/OpenBazaar/openbazaar-go/vendor/github.com/xeodou/go-sqlcipher
..\..\workspace\src\github.com\OpenBazaar\openbazaar-go\vendor\github.com\xeodou\go-sqlcipher\sqlite3-binding.c:16824:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.

**Comment by mrtinkz** [comment]
This seems to be a related issue to go-sqlchiper

https://github.com/xeodou/go-sqlcipher/issues/1

**Comment by hoffmabc** [comment]
This is already discussed here.
https://github.com/OpenBazaar/openbazaar-go/issues/18

Try this:
```
Download https://www.openssl.org/source/openssl-1.0.1t.tar.gz
Decompress this folder into %GOPATH%\src\github.com\OpenBazaar\openbazaar-go\vendor\github.com\xeodou\go-sqlcipher\
go get github.com/OpenBazaar/openbazaar-go
```

**Comment by mrtinkz** [comment]
My i forgot to mention, i am using the windows and not mac.

**Comment by hoffmabc** [comment]
Were you able to get past it with the headers like I suggested?

**Comment by cpacia** [comment]
@drwasho got it running on windows. Doc can you post the install instructions to the docs repo?

**Comment by mrtinkz** [comment]
No i couldn't get past it. It did not work for me. I am using windows 7

**Comment by cpacia** [comment]
fixed
