### ISSUE TITLE
freeShipping field discrepancy

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#380]
There are discrepancies between the listings `index.json` and the listings. See for example

http://gateway.ob1.io/ipfs/QmXVbyrwdJF7xF1nMqEGb22Km8d4LRq5btVDF4HCzYXD6U

and 

http://gateway.ob1.io/ipfs/QmU29VZSpK89TaeDPZNhTbqeoun4G5URSth7kexSxjE9HL

Notice for example the `freeShipping` field, present only in the `index.json`. Why are there discrepancies?

**Comment by cpacia** [comment]
The index does not have or need all the shipping data. It only needs to know if it's free.

The listing doesn't need that because it has the full shipping data.

**Comment by JustinDrake** [comment]
I see. `freeShipping` sounds like it's a boolean. What about `shipsFreeTo`:

```
        "shipsTo": [
            "FRANCE"
            "UNITED_STATES",
        ],
        "shipsFreeTo": [
            "UNITED_STATES"
        ]
```
