### ISSUE TITLE
Image resizing increases image size

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#382]
See for example http://gateway.ob1.io/api/v0/object/get?arg=QmZLGzavQGz9qjnmfYqguiUNzF8XUbDQidd1xfUoJ14n6B

The `original` has size 112853 whereas the `large` version has size 313473. Image resizing should only ever *decrease* the image resolution/size. Otherwise we can just use the original and resize client-side without wasting bandwidth.

**Comment by jjeffryes** [comment]
I thought that was how we were going to do it, but I might not be remembering it right. 

@cpacia do you remember why we decided to do it this way? Or is it just a todo that isn't complete yet?

**Comment by cpacia** [comment]
I've just resized to the sizes you guys gave me. If this was going to be changed it would also require a change on your side.

**Comment by jjeffryes** [comment]
It wouldn't change the sizes, the question is whether to upsize images that are smaller than the target size.

I remember discussing it, but not what that final verdict was. 

Upsizing small images makes things simpler for any client that is built, but increases the amount of bandwidth if we're sending (for example) a 100 x 100 original image that we've increased to 500 x 500.

**Comment by cpacia** [comment]
PR #349 was merged. That's all the image changes for now

**Comment by JustinDrake** [comment]
Is it not worth having a GitHub issue for this open OpenBazaar issue?
