### ISSUE TITLE
Is OB affected by the BIP39 bug?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#384]
OpenBazaar makes use of BIP39. See discussion https://github.com/iancoleman/bip39/issues/58

**Comment by bip32JP** [comment]
BIP32 bug actually

Specifically in hardened key derivation where private keys are not properly padded when the MSB is a 0x00 byte.

This means there is a 1/256 chance that this bug occurs on any BIP32 wallet that contains hardened derivation.

**Comment by hoffmabc** [comment]
From that thread it seems as though wallets built off of bitcore are affected due to the dropping of the byte. We're building off of btcd so I'm not sure of this affecting us. @cpacia ?

**Comment by cpacia** [comment]
https://github.com/btcsuite/btcutil/blob/master/hdkeychain/extendedkey.go#L217

**Comment by hoffmabc** [comment]
So the answer is no problem?

**Comment by cpacia** [comment]
I think that was the wrong line. Whether or not the leading zero would be dropped (based on the code) depends on how the golang big int handles conversion to bytes. @tyler-smith do you know?

**Comment by cpacia** [comment]
Looks like it does drop the leading zero:
```
keyHex := "0013fb3709b05939f04cf2e92f7d0897fc2596f9ad0b8a9ea855c7bfebaae892"
key, _ := hex.DecodeString(keyHex)
keyNum := new(big.Int).SetBytes(key)

fromBig := keyNum.Bytes()

fmt.Println(len(fromBig))
fmt.Println(keyHex)
fmt.Println(hex.EncodeToString(fromBig))
```
```
31
0013fb3709b05939f04cf2e92f7d0897fc2596f9ad0b8a9ea855c7bfebaae892
13fb3709b05939f04cf2e92f7d0897fc2596f9ad0b8a9ea855c7bfebaae892
```
I'll to double check that this is a bug in btcd

**Comment by cpacia** [comment]
I think btcd handles the padding correctly. I get `17rxURoF96VhmkcEGCj5LNQkmN9HVhWb7F` from that test vector which is consistent with the others.
