### ISSUE TITLE
validateProfile is missing

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#389]
Whenever an external profile is retrieved it needs to be validated. This is similar to how listings are validated. This validation is a part of the OB protocol which is both unwritten in code and unformalised in words. Things that need validating may include:

* the length of the `name`, `location`, `about`, `shortDescription`, etc.
* that the handle is valid
* that the image hashes are actual hashes
* that the `guid` is correct
* that `colors` are actual colors
* that `avgRating` is not >5

There's [an issue from Oct 2016](https://github.com/OpenBazaar/openbazaar-go/issues/167) that I've tried to revive but has gone stale. I'm closing that one in favour of this one.

**Comment by JustinDrake** [comment]
More generally, there is no spec clearly defining what a profile actually.

**Comment by cpacia** [comment]
Implemented
