### ISSUE TITLE
Various problems with the message ID

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#395]
As mentioned in #371, message ID handling is important to protect against attacks. The current message ID logic `sha256.Sum256([]byte(chat.Message + chat.Subject + tss))` is still completely broken from a security standpoint. In particular:

1. It allows for an attacker to change the message and subject. Consider a message with `Subject` "AB" and `Message` "CD" , and a message with `Subject` "A" and `Message` "BCD".
2. It allows for an attacker to change the timestamp (by ending `chat.Subject` with numbers).
3. It allows an attacker to override the `outgoing` flag (making messages sent by the node look like they were received from the node!)

On a similar note, an attacker can reset the `unread` flag by sending the same message after it has been read.

**Comment by cpacia** [comment]
I'm not following any of that. The purpose of deriving the message ID via hash was to prevent someone from overriding an existing message

**Comment by cpacia** [comment]
What's the solution to this?

**Comment by JustinDrake** [comment]
There are several things that need fixing here:

1. The chat struct data needs to be unambiguously encoded into a byte array. (Concatenation of field values is not unambiguous.) For example you can use JSON, protobuf or CBOR encoding. My personal recommendation is CBOR which is used by IPFS. (JSON has poor support for binary data and I believe the binary output of protobuf marshalling depends on the version of the marshaller.) This fixes issues 1. and 2. I'm not an expert in binary encoding; maybe @whyrusleeping can chip in.
2. The `outgoing` flag needs to be part of the ID encoding to prevent it being overwritten. This fixes issue 3.
3. When receiving a new message, the `unread` flag shouldn't be overridable. For security in depth, my recommendation would be to reject all database updates for new messages with the ID already in the database. For example, have a `service.datastore.Chat().Create(chat.MessageId` where instead of a `insert or replace into chat` (used for `Chat().Put()`) it is an `insert into chat` (no replace allowed). This fixes the `unread` flag issue.

On a similar note, once we have canonical IDs we can get message signatures for free simply by signing the id and verifying/storing signatures. This would be a neat and easy solution for #362 which I think would be very nice from the get go. cc @tyler-smith @drwasho

**Comment by hoffmabc** [comment]
Why do we modify chat messages in the database anyways? Shouldn't they always be inserts?

**Comment by JustinDrake** [comment]
`Chat().Put` is currently used twice. Modifications are required for the `unread` flag. More metadata may be added in the future, e.g. to cater for reactions or to specify the read time.

**Comment by hoffmabc** [comment]
Ok I assumed that was why although I would think an ID and subject body content shouldn't be changing.

**Comment by cpacia** [comment]
That's a good point. I'll just make it insert only rather than messing with complex serialization.

**Comment by cpacia** [comment]
And in doing so we can probably go back to random IDs for less complexity.

**Comment by JustinDrake** [comment]
cc @tyler-smith, @drwasho: What are your thoughts on random IDs vs canonical IDs? Canonical IDs buy us several things:

1. Signatures that cover only a short id (as opposed to the whole message)
2. One-to-one correspondence between IDs and messages (useful for debugging)
3. Determinism (useful for testing)

**Comment by JustinDrake** [comment]
Canonical IDs also embrace the IPFS mentality that everything can be content addressed.

**Comment by cpacia** [comment]
For 1, the data structure would need to be refactored.

**Comment by hoffmabc** [comment]
How much effort is that and does it impact the front-end developers?

**Comment by cpacia** [comment]
It doesn't affect the front end

**Comment by rmisio** [comment]
> That's a good point. I'll just make it insert only rather than messing with complex serialization.

How would you then update the 'read' flag for an individual message while leaving that message in the right order?

**Comment by cpacia** [comment]
The mark as read command uses the sqlite `update` command.

**Comment by jackkleeman** [comment]
Plus, tss is a string containing the current unix seconds... so the same message in the same second causes a conflict. Why not use a nanos or at least milliseconds?
