### ISSUE TITLE
Clearing .openbazaar2.0 folder while preserving identity

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#396]
We've had to clear the `blocks/` folder on our bootstrap node as it was taking 17G of space. Now openbazaar-go is crashing. Is there an easy way to extract and reimport the identity into a fresh `.openbazaar2.0` folder? Maybe this could be a command line option to pass in a specific identity.

**Comment by cpacia** [comment]
`init -m "your mnemonic"`

**Comment by JustinDrake** [comment]
Oh cool. What's an easy way to get mnemonic (in human readable format) out of a database?

**Comment by cpacia** [comment]
Either the sqlite viewer or the `wallet/mnemonic/` api call
