### ISSUE TITLE
Uploaded Images go into Pending Forever

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#397]
When editing/creating a listing, and uploading a photo, the call to ob/images works normally, and returns a set of hashes.

When the image attempts to load, the call to the image goes into pending an never resolves.

ex: if ob/images returns
```
[
    {
        "filename": "bedroom-interior-furniture-living-room-awesome-interior-decorating-for-a-luxury-living-room-design-ideas-with-charming-chandelier-combined-attractive-celing-decoration-and-retro-fireplace-ma.jpg",
        "hashes": {
            "tiny": "QmYqT7qhtRmEVKoAezCDKjNYaZpsDFiKcusEiCP8wTf1Ln",
            "small": "QmXji6sr6Xc1RJoPmfxnWER4RKh2UZcCYfq245k6nDaxAX",
            "medium": "QmNUwwsQZsuqnFavprWPGAYjpqh63zj4FyNYQLdQTUnG8r",
            "large": "Qme21DfWiZdnddoiRiM6S42wbSzevz98fbugEsBewZBdGK",
            "original": "QmXHEQCy2UMefYwu43zpoLxbtALStPGHsbgWSZDRAA6RNH"
        }
    }
]
```
and then the following call is made 
```
http://localhost:4002/ipfs/QmXji6sr6Xc1RJoPmfxnWER4RKh2UZcCYfq245k6nDaxAX
```

Nothing is returned, and the call remains in a pending state indefinitely. If the same image is loaded later, it works normally.

How can the client tell when an image becomes available?

**Comment by cpacia** [comment]
Should be fixed.

**Comment by jjeffryes** [comment]
Tested. It worked. Thank you.
