### ISSUE TITLE
API to estimate price of a listing

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#399]
Calculating the price of a listing is a complex task, especially if it includes variants + shipping rules + coupons + taxes etc. @cpacia has a couple of hundred lines of code to do this calculation in the server.

For client implementations, they need to show the user the price before they click/touch 'Purchase'. This means that client developers have to do this complex calculation. If they get it wrong, the user can be misinformed when they go to purchase, and end up spending more than anticipated. Overall, this is just a complex task to externalise to client developers.

What a client developer could do is submit a purchase message order to retrieve the actual price of the listing, but this creates lots of unfulfilled purchase orders... and if the Vendor is offline, it will fill up the DHT.

**I suggest we develop an API to estimate the price of a listing**, leveraging the complex calculation of the final price that already exists in the server. What would be even more helpful is if in addition to the final price, a line-item breakdown of the price modifiers (options, shipping, taxes) could be included in the response, as this data can be used to inform the user how the costs breakdown.

**Comment by drwasho** [comment]
Forgot to add this @cpacia but this will be really important, can we also include in this price, in the breakdown, the estimated transaction fee at the different priority settings?

**Comment by hoffmabc** [comment]
Hey I appreciate the flag REQUEST:  in the title @drwasho but if we need that can we use a label instead so we can sort these?
