### ISSUE TITLE
Settings api attributes are capitalized.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#40]
In order to be consistent with our other APIs (and common API design), can we please not capitalize the attributes on the settings API (and any other API that capitalizes them)?

**Comment by cpacia** [comment]
@tyler-smith I could be wrong but don't they have to be capitalized otherwise it wont parse the json to a struct?

**Comment by tyler-smith** [comment]
@cpacia The Go property names do, yes, because they need to be exported. However you can easy change the json property name for both marshaling and unmarshaling:

```go
type Blah struct {
    Foo   int       `json:"foo"`
    Bar   string    `json:"bar"`
    Baz   []string  `json:"not_even_close_to_the_same_name"`
}
```

More info: https://gobyexample.com/json

I can go through the restapi and add the tags.
