### ISSUE TITLE
REQUEST: API to fetch all orders

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#401]
I don't know if this is already on your agenda @cpacia, apologies if it is, but we could surely use an API to retrieve all of the orders a node has received. I suggested GET `/ob/orders`, with `limit` and `offset` accepted as parameters.

As for the response, each order in the array may contain (and this is totally open for discussion):

1. Buyer GUID
2. Order ID
3. State of the order
4. Funded (true/false)

**Comment by cpacia** [comment]
It's a todo, but it will probably be broken up by purchases, sales, and cases.

**Comment by drwasho** [comment]
No problem.
