### ISSUE TITLE
Create security.md doc

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-go#405]
I cannot find this point in the DOC'S.

As newbie its relay difficult to set up this server without good docs.

ty

**Comment by cpacia** [comment]
I'll have to make a separate doc for it. I'm assuming what you want is to authenticate the API for a remote server (you don't really need to do so on local host).

You need to edit the config file to:
```
"JSON-API": {
    "Authenticated": true,
    "Password": "2e844ad651c6b9a69cbe8f887b6a74dd3b9fc489aae777701e6e2d0d523a0cfb",
    "Username": "alice"
}
```
Where the password is the SHA256 has of your password. 

You can have it hash your password for you by running:
`./openbazaar-go setapicreds`

You can also use cookie based authentication by leaving the un and pw fields empty and sending the string found in the `.cookie` file in the openbazaar2.0 repo in the header of the request. 

Unrelated to the API you can also encrypt your db:
`./openbazaar-go encryptdatabase`

**Comment by i5heu** [comment]
ty - now my shop can be a part of the network!

**Comment by i5heu** [comment]
**NODE** 
The config File is in [home]/.openbazaar2.0 
- not in the go folder

**Comment by i5heu** [comment]
okay still cannot connect to my serve.

what for configs i have to do, to connect with the client to the go server and run a shop?

**Comment by tyler-smith** [comment]
@i5heu Please keep in mind this is the 2.0 version which is still in development. For the current stable version check out https://openbazaar.org/download.html

For connecting to the 2.0 server the configs Chris mentioned should be enough. What do you get when you do `curl <yourserver>:4002/ob`? Make sure your server's firewall is allowing TCP ports 4001 and 4002 ingress.
