### ISSUE TITLE
Mobile apps for Android and iOS

### ISSUE THREAD

**Issue by thekyriarchy** [OpenBazaar/openbazaar-go#408]
In this day and age, it seems like shooting yourself in the foot to not have native apps for mobile. There is plenty of reading on [mobile first](https://www.google.com/search?q=mobile+first) design, why it's so important strategically, and how to do it well.

**Comment by cpacia** [comment]
Thanks for the link. It's unlikely this code base would be used for a native mobile app as it's kind of assuming a desktop environment where you can freely keep the app open for long periods of time. 

But looking forward we'd like to build a buyer-only (at least initially) node in pure javascript that could run in a browser and possibly be ported easily to mobile. (though I agree native would be better). 

And Washington is currently making a mobile front end that can talk to this daemon using some kind of json framework. Though that would still require connecting to your own node.

**Comment by jjeffryes** [comment]
I'm going to close this issue, as we're already working on mobile implementations, and are well aware of how many self-administered bullet holes our feet have.
