### ISSUE TITLE
Outgoing messages are not marked as read

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#414]
Below is an example message as returned by `GET /ob/chatmessages`. Notice that the `read` flag is false although the `outgoing` flag is `true`.

```
{ messageId: 'QmPWKBQR8LAxhD2GKvxpwsAABcqfJQQoJ8rthXW1RtgVNk',
    peerId: 'Qmc7M36cnHr7LiqNXdxqgsEdCArhU2dTetYKK64NrNmRfo',
    subject: 'Testing',
    message: 'TEST',
    read: false,
    outgoing: true,
    timestamp: '2017-03-08T11:06:38Z' }
```

**Comment by cpacia** [comment]
Did the other party mark it as read?

**Comment by JustinDrake** [comment]
Surely outgoing messages (those that I write) are automatically read, right?

**Comment by cpacia** [comment]
Only when the other party marks it as read.

**Comment by JustinDrake** [comment]
Aha, I see. Clever.
