### ISSUE TITLE
What is the outgoing flag for GET /ob/chatconversations

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#415]
When doing `GET /ob/chatconversations` I was surprised to see the `outgoing` flag. What does it mean? Aren't conversations both ways (outgoing and ingoing)?

```
GET /ob/chatconversations?
null [ { peerId: 'Qmc7M36cnHr7LiqNXdxqgsEdCArhU2dTetYKK64NrNmRfo',
    unread: 0,
    lastMessage: '',
    timestamp: '1970-01-01T01:00:00+01:00',
    outgoing: false } ]
```

**Comment by cpacia** [comment]
Outgoing is your own messages.

**Comment by JustinDrake** [comment]
Are we talking about messages or conversations? I thought `chatconversations` was about conversations.

**Comment by cpacia** [comment]
That API returns the last message in each conversation. The outgoing flag tells you who sent the message, you or the other guy.

**Comment by JustinDrake** [comment]
Ok, cool. I don't really understand why the outgoing flag is there but not things like the message ID, but I'm probably not really understanding the use case properly.
