### ISSUE TITLE
Why aren't conversations segregated by subject?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#417]
GET /ob/chatconversations do not seem to be segregated by subject. Surely every purchase chat is a separate "conversation", no?

```
GET /ob/chatconversations?
null [ { peerId: 'QmcCoBtYyduyurcLHRF14QhhA88YojJJpGFuMHoMZuU8sc',
    unread: 0,
    lastMessage: '',
    timestamp: '1970-01-01T01:00:00+01:00',
    outgoing: false },
  { peerId: 'QmeRr7eJh3GYioe6mQm3oDb5H46maxkCbink4hygCPFyHR',
    unread: 0,
    lastMessage: '',
    timestamp: '1970-01-01T01:00:00+01:00',
    outgoing: false },
  { peerId: 'QmeXCzUBNGyox8ctiJu4JqwSkqZRGaKgfHLzeuNZ68xfcH',
    unread: 0,
    lastMessage: '',
    timestamp: '1970-01-01T01:00:00+01:00',
    outgoing: false },
  { peerId: 'Qmc7M36cnHr7LiqNXdxqgsEdCArhU2dTetYKK64NrNmRfo',
    unread: 0,
    lastMessage: '',
    timestamp: '1970-01-01T01:00:00+01:00',
    outgoing: false } ]
```

**Comment by cpacia** [comment]
Conversations is a list chats for the main chat view. 

You can get a list of messages for given peer for a single subject by using get chat messages

**Comment by JustinDrake** [comment]
Aha, I see. I misunderstood what `/ob/chatconversations` is. Is it documented somewhere?

**Comment by JustinDrake** [comment]
If I have several conversations (e.g. for two different purchases) with the same peer those don't seem to be displayed as different conversations.

**Comment by cpacia** [comment]
Yeah conversations only returns those with a subject of "". Could probably make the subject configurable, but don't have any real need for that.

**Comment by JustinDrake** [comment]
Duo has a need to get all conversations including those where the subject is not `""`, for example the conversations associated with purchases. (Note, we wouldn't know upfront what the subject is.)

What's the best way to get *all* conversations?

**Comment by tyler-smith** [comment]
I don't follow what's up with this empty subject stuff. @cpacia could you explain?
