### ISSUE TITLE
What does the timestamp mean in conversations?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#418]
Below is an example conversation as given by `GET /ob/chatconversations`. What does the `timestamp` mean? Also, it seems to be hardcoded to `'1970-01-01T01:00:00+01:00'`.

```
{ peerId: 'QmcCoBtYyduyurcLHRF14QhhA88YojJJpGFuMHoMZuU8sc',
    unread: 0,
    lastMessage: '',
    timestamp: '1970-01-01T01:00:00+01:00',
    outgoing: false }
```

**Comment by cpacia** [comment]
This is another thing I've never seen. All timestamps have been accurate (unless it's not accurate because your system clock is off).

**Comment by hoffmabc** [comment]
Do we know how to replicate this?

**Comment by tyler-smith** [comment]
That's the zero value for time so it seems as if the timestamp isn't being set. Again, it's only looking at messages w/o subjects so there is now `MAX(timestamp)`

https://github.com/OpenBazaar/openbazaar-go/blob/master/repo/db/chat.go#L82
