### ISSUE TITLE
What are the possible statuses?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#422]
Is it documented somewhere what the possible statuses are as returned by `/ob/status`? I can personally only think of "online" and "offline", in which case using a boolean flag seems more semantic. So instead of

```
GET /ob/status/Qmc7M36cnHr7LiqNXdxqgsEdCArhU2dTetYKK64NrNmRfo?
null { status: 'online' }
```

I would suggest something like

```
GET /ob/status/Qmc7M36cnHr7LiqNXdxqgsEdCArhU2dTetYKK64NrNmRfo?
null { online: true }
```

**Comment by hoffmabc** [comment]
Looks like online or offline per:

https://github.com/OpenBazaar/openbazaar-go/blob/a35763bfc58cea6874ad4d0c03525b952fa5f707/core/net.go#L96

This should be in the API docs though @drwasho @cpacia

**Comment by JustinDrake** [comment]
Then using a boolean is better design.
