### ISSUE TITLE
GET/POST image/images inconsistency

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#424]
I'm trying to wrap my head around the images API and got confused by the naming. Is it `images` (plural) or `image` (singular) in the two cases below:

```
	case strings.HasPrefix(path, "/ob/images"):
		i.GETImage(w, r)
```

and 

```
	case strings.HasPrefix(path, "/ob/images"):
		i.POSTImage(w, r)
```

**Comment by hoffmabc** [comment]
@JustinDrake this seems more suited for a slack question rather than an issue. If it is an issue then it would be nice for it to be structured as an actionable ask.

**Comment by JustinDrake** [comment]
This is an issue. Notice the inconsistency `"/ob/images"` versus the internal API `GETImage`. The other endpoints don't have this issue.

**Comment by cpacia** [comment]
this was fixed
