### ISSUE TITLE
Case API call low-level error message "sql: no rows in result set"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#425]
GET /ob/case is returning `{ success: false, reason: 'sql: no rows in result set' }`. Is such a low-level error expected?

**Comment by tyler-smith** [comment]
That's clearly how the code is written, yes, but I think what you're getting at is having friendlier user-facing error message which I agree would be good.

This is all part of the larger story of insufficient http i/o.
