### ISSUE TITLE
Rename message text to "text"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#431]
The current naming of the message text is really awkward because both the message and the message text are labelled `message`:

<img width="447" alt="screen shot 2017-03-08 at 14 26 54" src="https://cloud.githubusercontent.com/assets/731743/23707760/6e2984f0-040b-11e7-8014-b7a807cf43d3.png">

Can the message text be called `text`?

**Comment by tyler-smith** [comment]
If renaming these, I would also do `messageId` > `id` and `peerId` > `peerID`.

gorename should be able to do this quickly.

**Comment by tyler-smith** [comment]
Actually, I just noticed this was JSON. I was thinking Go so gorename won't help, however it should just involve change the `json` struct tags on that type.

**Comment by cpacia** [comment]
`peerId` is used allover the place. It would need to be changed everywhere if that's the case.

**Comment by tyler-smith** [comment]
Yes, ideally.

**Comment by JustinDrake** [comment]
That's the Go convension. ID variables end in `ID` not `Id`.

**Comment by JustinDrake** [comment]
I've gone through the source code, and there are a bunch of `Id` changes to do:

- `orderId`
- `peerId`
- `listingId`
- `offsetId`
- `messageId`
- `buyerBlockchainId`
- `vendorId`
- `buyerId`
- `moderatorId`
- `msgId` => this should probably be `messageID`
- `nofitId` => this should probably be `notificationID`

**Comment by cpacia** [comment]
It wouldn't just be a find/replace as the client needs to change all its variables as well.

**Comment by tyler-smith** [comment]
Yes, the `gorename` tool can rename any identifier in your entire GOPATH though.

**Comment by tyler-smith** [comment]
`golint` should check for incorrect names if you use that. I personally use VSCode and Atom with their respective main Go plugins and both will golint in realtime.
