### ISSUE TITLE
Default SKU related validations

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#435]
If someone doesn’t have any variants and wants to set a quantity or productId, the procedure is to create a "default" SKU without a variantCombo field and set the values there.

However, the following validation would prevent that?

```
if len(listing.Item.Skus) > maxCombos {
    return errors.New("More skus than variant combinations")
}
```

Please allow the default SKU. Also, please ensure there are at most one default and if there is a default, it is the only SKU (i.e. no combo of default and non-default SKUs).

**Comment by cpacia** [comment]
Fixed
