### ISSUE TITLE
Clean up mentions of "guid"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#437]
It seems like we're going forward with the IPFS nomenclature of `PeerID` and dropping `guid`. The `guid` is still lurking around in various places. (Example snippets below.) The naming inconsistency is especially problematic in the API and the protobufs.

`fmt.Fprintf(w, `{"guid": "%s", "cryptoCurrency": "%s", "testnet": %t}`, i.node.IpfsNode.Identity.Pretty(), i.node.Wallet.CurrencyCode(), testnet)`

`guidSig, err := n.IpfsNode.PrivateKey.Sign(serializedOrderFulfil)`

`pid, err := peer.IDB58Decode(guid)`

```
message ID {
  string guid         = 1;
```

```
 message Pubkeys {
   bytes guid    = 1; // IPFS public key
```

**Comment by tyler-smith** [comment]
Changing the Go identifiers should be easy (but take a bit of time). Fixing the JSON will be a lot more involved since it'll need to be in tandem with the client. A 2 phase approach here seems like a good idea.

**Comment by JustinDrake** [comment]
When closing issues could you please include a link to the commit or PR that fixes the issue? If it's a dupe, please link to the dupe. Thanks! 👍 

cc @hoffmabc
