### ISSUE TITLE
Shared block list

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-go#440]
I have an idea,

i think we have a problem with OB and TOR.
In Germany - you are responsible for links you put on your homepage.
If the link directs you to eg. a drug site - you are responsible for this link.

I think, sharing the Hash in OB for a store with drugs or worse -  you are responsible

we can maybe handle it like Facebook(with moderators - blocking bad content - and therefor Facebook is not responsible )

But i do not want to block all the bad stuff myself - i need a method for a shared block-list i can expand.

example:

I(a) discover a ChildPorn store (this is the 
death sentence - OB has to face it, if its get better known and TOR) - i can block it 

A second guy(b) is blocking it too.

If a guy(c) is flowing the blocklist of me(a) and (b) = (c) is blocking the store automatically(without marking the store by himself as blocked)
-- so if (d) is following only (a) and (c) = the bad store is not blocked for (d)

with this we prevent blocking good stores who have bad customers and good customers.
-and we have a bad-content management to prevent legal bullshit 

-maby its a good

**Comment by hoffmabc** [comment]
I'm trying to understand what the problem really is here in this scenario. Why would you be sharing direct links to "drug sites" for instance on your OB page? Are you really responsible for using a protocol that has users on it conducting illegal activities? If so, how come web browsers are not illegal in Germany?

Perhaps I'm misunderstanding your problem.

**Comment by cpacia** [comment]
So the way the app is being designed it's a bit like YouTube in that you wont see any content that you don't explicitly subscribe to. Nor would it seed anything that you haven't personally clicked on. 

So I'm not sure we need to go a whole lot further than that. 

The ban/block concept in the code is more for the scenario where someone is hassling you in a DM or something and you just don't want to deal with them. 

It could be useful to have a public list of malicious peers but I'm not sure if it's a necessity.

**Comment by i5heu** [comment]
> I'm trying to understand what the problem really is here in this scenario. 
-I think its a problem that you share the hash of the drugstore - so the hash is working like a link.

So i dont have found a explanation of the search method - but:
the network is p2p what means that i have to share peerlist of other stores.

so at some point my server is serving a hash or content of an "bad store"

- at the last layer you send a link > ob://(hash)  of the badstore if someone calls your follower-list

> So the way the app is being designed it's a bit like YouTube in that you wont see any content that you don't explicitly subscribe to. Nor would it seed anything that you haven't personally clicked on.

If a search - you see products of stores you are not follow .


So as out of my understanding - OB is like a decentralized Bittorent tracker - and ThePirateBay was 
sentenced for acting as tracker.


- im no layer so im not to 100% shure

**Comment by jjeffryes** [comment]
If you find a listing that is innocuous, and load that store, but the store has other listings that are illegal in Germany, then those listings would be stored in your node, which could be an issue for German users. 

It would be good to make sure if you block that node all traces of it are purged from your node. 

Search services could have similar functionality, if you do a search for "shoes" and something illegal or inappropriate comes up, ideally there would be a way to report that to the search service, and block that result and any other results so you never see them again.

**Comment by i5heu** [comment]
If OB uses IPFS - my server will send maby share iligal content - this is realy bad.

my biggest concerns going to child porn - in Germany you can be sued for have this content in your cache, you even don´t have to look at this, only because you have it in the cache is enough.

or if someone sells a human (human trafficking/slave trate) whatever - im pretty sure that i can be sued (if i cannot effectively block this) for "Aid to human trafficking"
