### ISSUE TITLE
Incoming transaction in transaction history don't make much sense

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#445]
## The Problem

1. The data in the response doesn't make much sense for an incoming transaction into the OpenBazaar wallet
2. The response should include the OpenBazaar destination address; currently it has nothing (not sure if this is because the transaction is unconfirmed)
3. Related to 2, it says 1093136 confirmations, when clearly the transaction is unconfirmed.
4. Related to (2 & 3), it is an unconfirmed transaction but it says 'CONFIRMED'
5. The response doesn't say whether funds are incoming or outgoing from the wallet

### Data

This is the response I got from the server from a transaction I made to top-up the OpenBazaar wallet:

```JSON
[
  {
    "Address": "",
    "Confirmations": 1093136,
    "Memo": "",
    "OrderId": "",
    "Status": "CONFIRMED",
    "Thumbnail": "",
    "Timestamp": "2017-03-10T06:19:44Z",
    "Txid": "52b70ab04a5e23d621404ef8e256d4a646a6a9cc34a7aa28df880fa38f4233eb",
    "Value": 631385
  }
]
```

And at the time of posting, this is the testnet transaction according to Blocktrail:

![screen shot 2017-03-10 at 4 25 35 pm](https://cloud.githubusercontent.com/assets/3887694/23784524/43031bfc-05ae-11e7-8f51-ab3053a02906.png)

**Comment by drwasho** [comment]
After a few minutes the response changed:

```JSON
[
  {
    "Address": "",
    "Confirmations": 1,
    "Memo": "",
    "OrderId": "",
    "Status": "PENDING",
    "Thumbnail": "",
    "Timestamp": "2017-03-10T06:19:44Z",
    "Txid": "52b70ab04a5e23d621404ef8e256d4a646a6a9cc34a7aa28df880fa38f4233eb",
    "Value": 631385
  }
]
```

Not sure what's going on.

Also not sure why it says `PENDING' when it appears as 'confirmed' in the `/wallet/balance`

**Comment by cpacia** [comment]
2) The issue with the address is Mike wanted to show the address it was sent from, the information for which simply doesn't exist. I could maybe have it show the address it was received to, but then again, there can be more than one address (unlikely though). But it would also be hard to get that data.

The current wallet designs only show an address when it's an outgoing payment. This api conforms to that. 

5) the value will be negative if it's outgoing.

**Comment by hoffmabc** [comment]
All of this would be great in the API docs :)

**Comment by drwasho** [comment]
No @hoffmabc, I prefer to let developers suffer.

**Comment by drwasho** [comment]
@cpacia one of my outgoing transactions still shows a positive value:

```
[
  {
    "address": "",
    "confirmations": 109,
    "memo": "",
    "orderId": "",
    "status": "CONFIRMED",
    "thumbnail": "",
    "timestamp": "2017-03-10T06:19:44Z",
    "txid": "52b70ab04a5e23d621404ef8e256d4a646a6a9cc34a7aa28df880fa38f4233eb",
    "value": 631385
  },
  {
    "address": "",
    "confirmations": 101,
    "memo": "",
    "orderId": "",
    "status": "CONFIRMED",
    "thumbnail": "",
    "timestamp": "2017-03-10T07:43:31Z",
    "txid": "06f3fa084a1ab573bf9cae438943fd949796c75682fa8c1996d2e2ea3c02a77f",
    "value": 126820
  },
  {
    "address": "mvsbfdCLSpsgaWE61rvpt9i5zv38yu9wDY",
    "confirmations": 0,
    "memo": "",
    "orderId": "",
    "status": "UNCONFIRMED",
    "thumbnail": "",
    "timestamp": "2017-03-11T03:15:45Z",
    "txid": "58d079de37dff09e276c5139685787b4400d0e5cd4b9045183a622be51691405",
    "value": 476905
  }
]
```

https://www.blocktrail.com/tBTC/tx/58d079de37dff09e276c5139685787b4400d0e5cd4b9045183a622be51691405
