### ISSUE TITLE
What's the dependency strategy?

### ISSUE THREAD

**Issue by duosearch** [OpenBazaar/openbazaar-go#45]
There seems to be dependency-related stuff all over the repository:

- The `vendor` folder
- The `Godeps` folder which seems to be related to [this dependency tool](https://github.com/tools/godep)
- The `gx` folder which seems to be related to [this package manager](https://github.com/whyrusleeping/gx)
- The [Makefile](https://github.com/OpenBazaar/openbazaar-go/blob/master/Makefile) has six (!) undocumented dependency-related commands (`godep`, `toolkit_upgrade`, `gx_upgrade`, `gxgo_upgrade`, `deps`, `vendor`)

What's the dependency strategy (i.e. can it be documented)? Can the current dependency structure be simplified?

**Comment by cpacia** [comment]
It uses Godeps. The vendor package is auto-generated by godeps. gx is used by the ipfs dependency. The makefile is out of date. I will delete it.

**Comment by duosearch** [comment]
Would it be possible to add a bit of Godeps documentation in the README?
