### ISSUE TITLE
Add image hashes to variants object in the listing schema

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#454]
The recent refactor resulted in the loss of adding images to variants. This should be added back in and clients can support showing these images when they're ready.

A discussion is required to figure out the best way to add it back:

**Current schema (no image hashes):**

```JSON
"options": [{
        "name": "Color",
        "description": "Color of the dress.",
        "variants": ["Red", "Cream", "Black"]
      }
]
```

**Approach 1: Restore pre-factor variant schema:**

```JSON
"options": [{
    "name": "Color",
    "description": "Color of the dress.",
    "variants": [{
        "name": "Red",
        "image": {
          "filename": "front",
          "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz",
          "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
          "medium": "QmTJfeeapZwFM8EoZAuf16JsSJyxZtKaAR6hmWiMf4CTcF",
          "large": "QmfTKL3Z67mWKTKf9XKSCj1ptmDRaZLr5yjPS4JrVDgo5h",
          "original": "QmNexx7SaJCVCjyGGG3j2k7fenn3iVhtWdm9RvKvT7GTLq"
        }
      },
      {
        "name": "Cream",
        "image": {
          "filename": "cream",
          "tiny": "QmU1cBgjyHpuzDYbEd4iDVuPzxgKM3CqhRhDJqkHWCKBXq",
          "small": "QmP3BVFuga7N4XEX8iU2MFYC7pc6mfTRQRrpZbKiVy2Csr",
          "medium": "QmQaSzaoHzp8raZLtPEFyCjTnwfXvDGKdXFM83STDVWG43",
          "large": "QmNsFdsX2LNALG2WBxw6E6FTPZWgJcRAcLHnKdWczrCNf9",
          "original": "QmTEUnCjuQPj1ggj5UL5vJujkgBiNYY4jkteugnogiCJny"
        }
      },
      {
        "name": "Black",
        "image": {
          "filename": "black",
          "tiny": "QmdA3Nmc8VnwSvt98Deo2RQztEiCsAkNLhron73bnBzARe",
          "small": "QmcADxUo89ZsEAWiYsuUk7hrgjWDMKXL1CtoA9sTNrQFFP",
          "medium": "QmZydpAJoLsJWbP5vmh59W6bW1kuiCV34yD62hq28AtP7b",
          "large": "QmXixGseetihe6vZiWcTw9N1pieok1YtRoxwvyd5d7jz6s",
          "original": "QmZsZ78FJwt281gfeUvGzDnsBW7WNjPWW3aJWDKskhpCRr"
        }
      }
    ]
  }
]
```

**Approach 2: Create a new key for image hashes:**

```JSON
"options": [{
  "name": "Color",
  "description": "Color of the dress.",
  "variants": ["Red", "Cream", "Black"],
  "variants_images": [{
    "filename": "red",
    "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz",
    "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
    "medium": "QmTJfeeapZwFM8EoZAuf16JsSJyxZtKaAR6hmWiMf4CTcF",
    "large": "QmfTKL3Z67mWKTKf9XKSCj1ptmDRaZLr5yjPS4JrVDgo5h",
    "original": "QmNexx7SaJCVCjyGGG3j2k7fenn3iVhtWdm9RvKvT7GTLq"
  }, {
    "filename": "cream",
    "tiny": "QmU1cBgjyHpuzDYbEd4iDVuPzxgKM3CqhRhDJqkHWCKBXq",
    "small": "QmP3BVFuga7N4XEX8iU2MFYC7pc6mfTRQRrpZbKiVy2Csr",
    "medium": "QmQaSzaoHzp8raZLtPEFyCjTnwfXvDGKdXFM83STDVWG43",
    "large": "QmNsFdsX2LNALG2WBxw6E6FTPZWgJcRAcLHnKdWczrCNf9",
    "original": "QmTEUnCjuQPj1ggj5UL5vJujkgBiNYY4jkteugnogiCJny"
  }, {
    "filename": "black",
    "tiny": "QmdA3Nmc8VnwSvt98Deo2RQztEiCsAkNLhron73bnBzARe",
    "small": "QmcADxUo89ZsEAWiYsuUk7hrgjWDMKXL1CtoA9sTNrQFFP",
    "medium": "QmZydpAJoLsJWbP5vmh59W6bW1kuiCV34yD62hq28AtP7b",
    "large": "QmXixGseetihe6vZiWcTw9N1pieok1YtRoxwvyd5d7jz6s",
    "original": "QmZsZ78FJwt281gfeUvGzDnsBW7WNjPWW3aJWDKskhpCRr"
  }]
}]
```

**Comment by drwasho** [comment]
@jjeffryes made a worthwhile comment about this wrt approach 2: "Relying on order is generally more fragile than making it explicit."

This is true, but we are kinda doing this with `skus`. Either way, I'm not fussed.

**Comment by cpacia** [comment]
@JustinDrake @tyler-smith @jackkleeman @gubatron @jjeffryes @rmisio do you guys have any input on the schema for images. It looks like if we use approach 1 it will be a breaking change for what Rob is working on.

**Comment by rmisio** [comment]
> It looks like if we use approach 1 it will be a breaking change for what Rob is working on.

It would be a breaking change, but I think #1 is cleaner. As Josh mentioned, relying on order as a mapping has some fragility to it.

If want to do this, I say go with #1 and the client will need to adjust.

My concern here is more of a process issue. Why do we keep having changes like this come after features have been coded up and therefore require refactors? We had a [good discussion](https://github.com/OpenBazaar/openbazaar-go/issues/368) about the updated variant schema and all seemed to agree on something.

(It may be something that's unavoidable. I understand that sometimes you need to play around with something for all the reqs to really click in.)

**Comment by jjeffryes** [comment]
I think our previous conversation in #368 prematurely dropped the images without really coming to a consensus about it, since we were all focused on the SKUs and how to name everything. So this is just a case of spreading conversations across github and slack not being a great way to keep a large volume of details in sync. 

As I see it, the question was whether images should be on the variants and/or if there should be an image for the combination. 

I think it would make sense to add images to the variants now, and consider images for combinations later.

ie: we would add the ability (in the back end) to have an image for Large and an image for Red, but not an image for Large Red.

**Comment by rmisio** [comment]
> I think it would make sense to add images to the variants now, and consider images for combinations later.

Ok, but maybe we don't change the client UI to display them? Having to adjust to the new schema is one thing. Having to have the designs adjusted and manage the actual image (and image upload) in the UI is a whole other thing.

**Comment by jjeffryes** [comment]
Right. No changes to the reference client for the 2.0 release. 

I'll add appropriate issues to the backlog.

@cpacia please don't work on this until we've done planning on it, worked through a story, and added it to a sprint. I think we need to make sure we're all on the same page and ready for it so we don't get everyone out of sync again.

**Comment by gubatron** [comment]
If you need to keep one, variant 1 FTW for several reasons, the most important the one Dr. Washo mentioned, variant 2 opens itself to data corruption and unnecessary headaches in the future.

### Approach 3
If I had my things my way and I had to satisfy the following needs:
- have the variant names as keys.
- preserve variants order.
- have random access based on variant name.

this is what I would do to:
1. make `variants` a dictionary, not an array.
2. make the keys of the dictionary be the name of the variant.
3. add an `offset` parameter to guarantee order (sorted map)

```
"variants" : {
    "Red" : {
        "offset": 0,
        "image": {
            "filename": "red_dress.jpg",
            "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz",
            "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
            "medium": "QmTJfeeapZwFM8EoZAuf16JsSJyxZtKaAR6hmWiMf4CTcF",
            "large": "QmfTKL3Z67mWKTKf9XKSCj1ptmDRaZLr5yjPS4JrVDgo5h",
            "original": "QmNexx7SaJCVCjyGGG3j2k7fenn3iVhtWdm9RvKvT7GTLq"
        }
    },
    "Yellow" : {
        "offset": 1,
        "image": {
            "filename": "yellow_dress.jpg",
            "tiny": "QmbjyAxYee4y3443kAMLcmRVwggZsRDKiyXnXus1qdJJWz",
            "small": "QmVsoT9iabv6GZhxhvtjSpQMJA6QyMivGTs6MmHJr6TBm9",
            "medium": "QmTJfeeapZwFM8EoZAuf16JsSJyxZtKaAR6hmWiMf4CTcF",
            "large": "QmfTKL3Z67mWKTKf9XKSCj1ptmDRaZLr5yjPS4JrVDgo5h",
            "original": "QmNexx7SaJCVCjyGGG3j2k7fenn3iVhtWdm9RvKvT7GTLq"
        }
    },
}
```

**Comment by drwasho** [comment]
> As I see it, the question was whether images should be on the variants and/or if there should be an image for the combination.
> I think it would make sense to add images to the variants now, and consider images for combinations later.
> ie: we would add the ability (in the back end) to have an image for Large and an image for Red, but not an image for Large Red.

I tend to agree: let's keep it simple. Each variant should have an image as far as the server is concerned, and it is up to the client developer to figure out how they handle combinations.
