### ISSUE TITLE
New API to estimate purchase cost

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#458]
This is something we've discussed on other channels, but it would be great if we could have an API to estimate the total + line-item costs (i.e. shipping, coupon, taxes, Bitcoin tx fee) for purchasing an item. This can be shown to the user and it saves client developers from having to replicate the challenging calculation (and potentially getting it wrong).

**Comment by cpacia** [comment]
I think you've already got an open issue for this.

**Comment by drwasho** [comment]
Quite right, apologies. Duplicated here https://github.com/OpenBazaar/openbazaar-go/issues/399
