### ISSUE TITLE
Paginate the wallet transactions api

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#477]
Add parameters to the wallet transactions api to allow its results to fetched in pages. Ideally, the page parameter would be ID based - perhaps off of the txid.

So, if you wanted to fetch the 25 transactions prior to a transaction with the txid of 123, you would call:
/wallet/transactions?offsetId=123&limit=25

Also, please return the total transaction count in the payload, for example:

```
{
  transactions: [ ... ],
  count: 155,
}
```

**Comment by drwasho** [comment]
Great suggestion @rmisio

**Comment by rmisio** [comment]
Could this also please return the total transaction count? I've update the description to reflect this.

**Comment by cpacia** [comment]
What's the count needed for?

**Comment by rmisio** [comment]
The designs have it in the UI:

![image](https://cloud.githubusercontent.com/assets/794517/24259125/30a1b960-0fad-11e7-8803-3c45bf708941.png)

**Comment by cpacia** [comment]
done
