### ISSUE TITLE
Misc contracts.proto comments

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#48]
1. `double price` -> Prefer using integers for prices, especially given JavaScript and Go handle floats differently.
2. `string slug` -> What is a slug? Maybe add a descriptive comment
3. Why do `Coupon`s have a `hash`?
4. `Tax tax` -> Should this be `repeated Tax tax`?
5. `string moderator` -> Should this be more structured, e.g. `ID moderator`?
6. Why is the `Metadata` separated out from the `Item`? It's confusing for the listing data to be spread out. Can these two be merged?
7. Why does `Image` have a `fileName`? I don't see how this is helpful.
8. I suggest adding a `description` to `Image`. Different images can show different aspects of a listing, and image descriptions can provide context.
9. `string condition` -> Having constraints on the `condition` makes it manageable (e.g. the current the five options `New`, `Good`, `Excellent`, `Poor`, `Refurbished` add consistency throughout)
10. `ID vendorID` -> Can the naming be simplified to `ID vendor`? Same with `ID buyerID`.
11. `Shouldn't be included in the seeded listing.` (referring to `inventoryCount`) -> Why not make this public?
12. `Price pricePerUnit` -> Can the naming be simplified to `Price price`?
13. `string estimatedDelivery` -> Generally freetext strings produce messy listings that are hard for machines to parse/understand. Should this be a timestamp, i.e. `uint64 estimatedDelivery`?
14. `string chaincode` -> What is `chaincode`? Should it be `chainCode`?
15. `Method method` -> This seems redundant given we have `string moderator` right below. (No moderator chosen means direct payment.)
16. Why do we have `bytes listingHash` but `string hash` for `Image` and `Coupon`?
17. It's a bit confusing that `Listing` and `Order` both have `Item`, but those are very different.

**Comment by cpacia** [comment]
1. I don't so much matter to me. Either way there needs to be a conversion. If it's an int then you need to convert to a float to display fiat to the user. If it's float then you need to convert to int get back to satoshi. My opinion is that if it's displayed as a float at least it's clear what the price is when looking at the contract. 1234 could be interpreted as $1234 or $12.34 if the person doesn't know what the rule is. 

2. The identifier for the contract ex) kickass-blue-tshirt

3. It's the hash of the coupon code.

4. Probably

5. It's a string guid. I don't know what turning that into an id would do.

6. metadata has more to do with the type of listing not the actual item. 

7. for ipfs purposes. 

8. That would be a decision for the UX people.

9. Doesn't matter to me. It seems like string would provide more flexibility.

10. When dealing with it in the code "vendor" isn't very descriptive as to what it is. If I see listing.vendor it's not clear what that actually is. vendorID is more clear to me. 

11. Inventory counts are handled locally and the listing does not change when the inventory changes. Doing creates problems with constant republishing and losing caching. 

12. i suppose

13. I don't think we use this field for anything that requires machine parsing. It's just displayed to the user. A timestamp seems to give less flexibility. I can't say something like "4-6 days". 

14. Chaincode is used for bitcoin address creation. 

15.  That's just style preference. I think it's clearer what's going on with the enum.

16. should probably change that. 

17. What is more descriptive for order.item than Item?

**Comment by JustinDrake** [comment]
2. Where is that identifier used? (I guess I can wait for code to be written.)
3. Why is the `hash` useful? (I guess I can wait for code to be written.)
5. The label `moderator` doens't convey that it's a GUID. Maybe create a `GUID` type, or add a descriptive comment.
8. Paging @morebrownies @jjeffryes @hoffmabc
9. Paging @morebrownies @jjeffryes @hoffmabc
13. On Duo Search we'd like to be able to do stuff like Amazon, e.g. "If you order within 1 hour and 12 minutes you'll get your item by tomorrow." which requires machine readability. Maybe OpenBazaar would like to do the same? Paging @morebrownies @jjeffryes @hoffmabc
17. What about `order.orderSub`, which mirrors `categorySub`? Stuff like `quantity` does not describe an item, it's itself an order.
18. Does it make sense to add a version number for the protobuf to the top-level contract, so that future upgrades to the protobufs are properly communicated?

**Comment by jjeffryes** [comment]
8: adding a description to images, we've discussed this in the past, it would be useful, but would also complicate adding images to a listing. We'd probably need to change the design for that. @morebrownies?

9: constraining the condition value to a pre-set list would be useful if we were searching on it, currently we don't have plans to do so. It might be useful for future-proofing.

**Comment by JustinDrake** [comment]
@jjeffryes

9: Duo Search allows for searching on the condition (see sidebar [here](https://duosear.ch/listings)). I understood Duo Search would probably be included in the 2.0 client.

**Comment by jjeffryes** [comment]
@JustinDrake Ok, we'll take that into account.

**Comment by hoffmabc** [comment]
Is there any further action to take on this issue or can we close it? @jjeffryes @cpacia ?

**Comment by JustinDrake** [comment]
Another comment regarding the protos is inline documentation. At Duo Search it took us too much time to reverse engineer what fields represented what. Please have a look at the documentation I have prepared [here](https://blog.duosear.ch/openbazaar-historical-data-for-all-c812f58ac2e6#.wdz61vze7) for example inline documentation of the OB1.0 proto fields.

**Comment by JustinDrake** [comment]
> float weight               = 10; // kilograms

As I understand, the postage industry works in grams as their "working unit", not kilograms.

**Comment by cpacia** [comment]
I think almost all of these have been address in one way or another. We can open another issue if further changes are needed.
