### ISSUE TITLE
ValidateProfile review

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#480]
1. Do we want to allow `profile.Name` to be empty?
2. `AboutMaxCharacteres` => `AboutMaxCharacters` (typo)
3. `ShortDescriptionLength` => `ShortDescriptionMaxCharacters` (consistency)
4. Do we want to allow empty `s.Username`?
5. Do we want to allow nil `profile.AvatarHashes`?
6. Do we want to allow nil `profile.HeaderHashes`?
7. The check `len(profile.BitcoinPubkey) > 66` seems very weak. Why not check it's a valid public key?
8. Is the `peerID` validated?
9. Do we want to allow `moderator == true` and `profile.ModeratorInfo == nil`?
10. Do we really want `Colors` to be arbitrary strings?
11. Listings have a `Version` but not profiles. Is that intended?
12. The constants are gathered [in listings.go](https://github.com/OpenBazaar/openbazaar-go/blob/8a315f9bed73f637b63408543bd7a7571c948e11/core/listings.go#L27) but not solely relevant to listings.

**Comment by cpacia** [comment]
> The check len(profile.BitcoinPubkey) > 66 seems very weak. Why not check it's a valid public key?

The primary purpose of the length checks is to prevent people from downloading a 50 GB profile. I don't think it matters so much if the key is invalid unless you try to use them as a moderator.. then you'll know.

**Comment by JustinDrake** [comment]
> don't think it matters so much if the key is invalid unless you try to use them as a moderator

**Comment by JustinDrake** [comment]
> I don't think it matters so much if the key is invalid unless you try to use them as a moderator

Could there be future use cases (that you haven't necessarily thought of) that require a valid bitcoin public key?
