### ISSUE TITLE
Validating order messages

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#482]
Recently I made an error when sending a fulfilment message from the Vendor to the Buyer, where I didn't include the `slug`. The server accepted the call anyway, sent the fulfilment message to the Buyer, and changed the state of the listing.

The Buyer rejected the order message because it was missing the `slug` and didn't change the state order.

This experience highlights a couple of things:

1. The server shouldn't accept a fulfilment API call, from the Vendor, that omits the `slug`
2. The Vendor should be able to resend a fulfilment message (I understand this may be trickier)

More broadly at some point we'll need to go over how strictly the server is validating these order API calls before accepting them.

**Comment by cpacia** [comment]
I changed it allow there to be no slug when the order only has one item.
