### ISSUE TITLE
Could magic ids be deterministic?

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#484]
Is it necessary for magic ids on outgoing offline messages to have a random component? Could they be deterministic based on the ciphertext hash, for example. This would mean, for example, that trying to post the exact same ciphertext to DHT twice would have the same magicID, which is probably desirable.

If there's support for this I can do a PR

**Comment by cpacia** [comment]
I don't see any reason why they couldn't be.
