### ISSUE TITLE
Data on categories

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#485]
At Duo we'd like to encourage vendors to use the eBay categorisation tree that is [shared publicly](http://pages.ebay.co.uk/categorychanges/). (There's a full CSV [here](http://pics.ebaystatic.com/aw/pics/uk/categorychanges/UK_New_Structure_(Oct2016).csv).)

Unlike OB1.0 which had a single category field, OB2.0 has [a list of categories](https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/contracts.proto#L62). This list can be used for subcategories, up [10-levels deep](https://github.com/duomoney/encrypter-core/blob/master/core/listings.go#L20). For reference, eBay's category tree goes down to the 6 levels deep. The maximum character length category within the eBay catalogue is `Other Warner Bros Collectibles`, which is 30 characters. This falls within the OB2.0 limit of [40 characters](https://github.com/duomoney/encrypter-core/blob/master/core/listings.go#L24). So it looks like OpenBazaar 2.0 is capable of reusing eBay's category tree out of the box!

What do people think of encouraging vendors to reuse the eBay category tree when creating listings? Should we encourage vendors to use the first category and their "top level" one, then walk down into finer and finer subcategories? At the very least, this would help a lot for SEO on Duo. Could we include eBay's category tree as a dropdown suggestion, in addition to the free-text fields?

cc @hoffmabc @tyler-smith @jjeffryes @tiavlovskiegor24 @jackkleeman

**Comment by hoffmabc** [comment]
I think it's actually a rather good idea. I have been tossing the idea around about a tool that would bulk move listings from eBay to OB2.0 and then those categories would make even more sense. 

One clarification though. How are you suggesting we encourage people? Through the UI or some other means?

**Comment by hoffmabc** [comment]
Oops I got excited and jumped past your last sentence on mobile.

**Comment by hoffmabc** [comment]
I think we'd have to talk through the UI on this but certainly seems like a reasonable suggestion for the backlog.

**Comment by JustinDrake** [comment]
I see several ways of encouraging people to use consistent categorisation:

1. Integration with the reference client
2. Informational blog posts from OB, OB1, Duo
3. An information OBIP to define a standard
4. Chatbots that contact vendors with categorisation suggestions (Duo is may pursue this)
5. Categorisation plugins?

As I understood integration with the reference client was no go because:

1. It is not translated (English only)
2. It uses suggestions from an external authority (eBay)
3. OpenBazaar doesn't want to be constrained to a single categorisation tree

In my opinion the costs of not having a categorisation tree outweigh the above downsides.

**Comment by tyler-smith** [comment]
I don't like the idea of requiring users to use any specific categorization but having them as defaults in the reference client sounds reasonable.

I just want to be clear on whether or not the proposal is just for recommendations, or if you're suggesting we require adhering to this taxonomy.

**Comment by jackkleeman** [comment]
I think defaults in the UI is a good middle ground. Something like a drop down to select categories from the eBay tree, but you are able to suggest your own category if you aren't satisfied with that; you could even suggest a category within the eBay tree, so it maintains a lot of structure while still being up to the user.

**Comment by JustinDrake** [comment]
Instead of the eBay taxonomy we can also use the Google taxonomy. This may be more appropriate for OpenBazaar because it's shorter (less overwhelming) and translated in many languages! Below are some example languages. The product codes are consistent across languages.

https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt
https://www.google.com/basepages/producttype/taxonomy-with-ids.fr-FR.txt
https://www.google.com/basepages/producttype/taxonomy-with-ids.de-DE.txt
https://www.google.com/basepages/producttype/taxonomy-with-ids.it-IT.txt

What do you guys think?
