### ISSUE TITLE
Can no longer build on MacOS

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#486]
Master is not compiling anymore :(

```
Justins-MacBook-Pro:openbazaar-go justin$ go run openbazaard.go start
# github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher
vendor/github.com/mutecomm/go-sqlcipher/sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
signal: killed
```

**Comment by hoffmabc** [comment]
I thought this issue has already come up and there was a solution. @cpacia any ideas? I'll test on my own machine.

**Comment by hoffmabc** [comment]
Ok confirmed @cpacia @JustinDrake definitely an issue.

**Comment by hoffmabc** [comment]
This is a dupe of #224 I think.

**Comment by JustinDrake** [comment]
The problem is not the warning, but the `signal: killed` part.

**Comment by hoffmabc** [comment]
Oh it's unrelated to the warning? Gotcha.

**Comment by hoffmabc** [comment]
I went ahead and pushed a PR to remove the warnings. Signal: killed is still a problem @cpacia.

**Comment by hoffmabc** [comment]
I'm not sure if related @JustinDrake but it sure seems to hang on 

github.com/OpenBazaar/openbazaar-go/net/service 

for quite a while. From what I can tell on Google it seems like signal: killed happens frequently when running out of memory, which doesn't seem to be the case on my machine since I have at least 8GB of RAM, but perhaps something is chewing up resources when compiling the web socket stuff in that file?

**Comment by hoffmabc** [comment]
Also for me the build works it's running the binary afterwards when the signal: killed happens.

**Comment by JustinDrake** [comment]
I also have 8GB RAM.

**Comment by hoffmabc** [comment]
It seems to work fine on El Capitan. I'll have to debug this issue on 10.12.

**Comment by hoffmabc** [comment]
What version Go are you on @JustinDrake ?

**Comment by JustinDrake** [comment]
`go version go1.8 darwin/amd64`

**Comment by hoffmabc** [comment]
1.7.5 and 1.8 works on El Capitan. Hmm...

**Comment by JustinDrake** [comment]
I've just tried again with your PR, and I get the same output:

```
Justins-MacBook-Pro:openbazaar-go justin$ go run openbazaard.go start
# github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher
vendor/github.com/mutecomm/go-sqlcipher/sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
signal: killed
```

When you say "it seems to hang on github.com/OpenBazaar/openbazaar-go/net/service", how do you know that? Is there some sort of verbose mode you are using? Maybe I could share verbose logs.

**Comment by hoffmabc** [comment]
Yeah it won't fix the problem it just suppresses that warning message.

go run -v openbazaard.go start -t

**Comment by JustinDrake** [comment]
The warning message is still there for me.

**Comment by JustinDrake** [comment]
I wonder what the '# ' means for `# github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher`.

**Comment by hoffmabc** [comment]
probably just because it's a warning?

**Comment by jackkleeman** [comment]
@hoffmabc yup. @JustinDrake that log makes it look like /net/service builds and then /repo/db? Surely it is the package coming after that which is causing issues.

**Comment by hoffmabc** [comment]
Maybe it's something to do with the db? The sqlite3 vendored library I believe is like from July of last year. Perhaps we should bring the latest stable into our vendor?

**Comment by cpacia** [comment]
Did make just update or something. Why is this happening now?

**Comment by JustinDrake** [comment]
As per @hoffmabc's recommendation, I uninstalled Go, rebooted, installed Go 1.8.1, pulled master, and it worked. No idea what was wrong.

**Comment by jackkleeman** [comment]
Bit late, but did you try clearing your build cache?

**Comment by hoffmabc** [comment]
I don't know about @justindrake but I did.

**Comment by JustinDrake** [comment]
I did, yes
