### ISSUE TITLE
Chat message reactions

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#488]
Now that chat messages have an ID (used by the `READ` flag) it's easy to add Slack-style reactions. So every chat message can receive a reaction such as ❤️ or 👍. This seems like an easy win.

cc @morebrownies

**Comment by hoffmabc** [comment]
This is definitely a nice to have feature, but will probably need to go in the low priority pile for the moment if we want to ever get this app done. 

Unless someone wanted to submit a PR. Might be a good task for a new dev trying to get involved.

**Comment by TimothyShimmin** [comment]
@cpacia Why was this closed? Is it already implemented?
