### ISSUE TITLE
Provide visibility on milestones

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#489]
We have a nice set of [milestones](https://github.com/OpenBazaar/openbazaar-go/milestones?state=open) for the full release:

- Milestone 2 (pre-alpha)
- Milestone 3 (pre-alpha)
- Milestone 4 (alpha)
- Milestone 5 (beta 1)
- Milestone 6 (beta 2)
- Full Release

The problem is that 5 of these 6 milestones have no issues assigned to them. Of the 101 issues currently open, only 9 are assigned to a milestone.

It would be very helpful if the milestones could be made concrete by assigning open issues to them.

**Comment by hoffmabc** [comment]
Yeah we kind of jumbled up our priority issues recently so we will need to go back and clean this up. Thanks.
