### ISSUE TITLE
Include gometalinter as part of the build process

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#499]
I've manually gone through some of the linters of [gometalinter](https://github.com/alecthomas/gometalinter) and filtered out the relevant messages. It's a great tool. I think it caught ~50 bugs with the openbazaar-go codebase. I suggest automating this process to catch bugs earlier, maybe through the CI system. Gometalinter allows for configuration files and below is an example configuration file I use:

```
{
	"DisableAll": false,
 	"Enable": [
		"aligncheck",
		"deadcode",
		"dupl",
		"errcheck",
		"gas",
		"goconst",
		"gocyclo",
		"gofmt",
		"goimports",
		"gosimple",
		"ineffassign",
		"interfacer",
		"lll",
		"misspell",
		"staticcheck",
		"structcheck",
		"test",
		"testify",
		"unconvert",
		"unused",
		"varcheck",
		"vet",
		"vetshadow"
 	],
 	"Deadline": "60s",
 	"LineLength": 120
}
```

**Comment by cpacia** [comment]
I'm going to combine issues #492 #493 #494 #495 #496 #497 and #498 into this one as they are all just linting issues. Feel free to contribute as well.

**Comment by cpacia** [comment]
Superseded by #499

**Comment by placer14** [comment]
Closing. Remaining work captured in #1169.
