### ISSUE TITLE
What is test_compile.sh?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#50]
What is test_compile.sh and how do I run it?

This is the output I'm currently getting

```
Justins-MacBook-Air:openbazaar-go justin$ ./test_compile.sh
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
cat: *.cover.out: No such file or directory
```

**Comment by cpacia** [comment]
@hoffmabc can answer that

**Comment by hoffmabc** [comment]
This is the workaround for generating coveralls reports across multiple packages since the tool can't handle that yet. 

You can read more here: https://mlafeldt.github.io/blog/test-coverage-in-go/

**Comment by JustinDrake** [comment]
I'm lost. Still have no idea what `test_compile.sh` is and how it's meant to be used.

**Comment by hoffmabc** [comment]
It's used by Travis to run the unit tests on all the Go packages we built.

The results of those tests are files which are combined to generate a coveralls report which is reported to Coveralls.
