### ISSUE TITLE
If the productID is a number, the server throws an error

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#504]
If the productID of a sku is set to a number when doing a PUT to ob/listing, the server returns an error.

For example, if this is sent (along with the rest of the necessary data):
```
{productID: 2, quantity: -1, surcharge: 0, variantCombo: [0, 1]}
```

The server returns:
```
{
    "success": false,
    "reason": "json: cannot unmarshal number into Go value of type string"
}
```

**Comment by cpacia** [comment]
In the protobuf schema the productID is a string. It's expected to be a user entered sku number... for example, "932-33-2945".

**Comment by jjeffryes** [comment]
Skus can be any set of numbers and letters, what happens if the sku is 234234?

**Comment by jackkleeman** [comment]
The string "234234" would be fine, the numeric 234234 wouldn't

**Comment by tyler-smith** [comment]
encoding/json has a [type to handle these issues](https://golang.org/pkg/encoding/json/#Number). Maybe at some point we can build an analog for PB.
