### ISSUE TITLE
Add "status" field to the profile

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#509]
I think Slack has done it right with its new status feature. You pick an emoji and a short text. The text only shows when you hover over the emoji.

This will be useful for vendors who go on holiday, or are temporarily unavailable, or have a special promotion, or whatever.

cc @morebrownies

**Comment by JustinDrake** [comment]
<img width="209" alt="screen shot 2017-04-14 at 08 12 10" src="https://cloud.githubusercontent.com/assets/731743/25036168/1d456b70-20ea-11e7-8f0b-c191e8110a48.png">

**Comment by morebrownies** [comment]
Cool feature. We don't have the bandwidth to add additional features until after 2.0 is released. We'll revisit all feature requests after 2.0 and start to prioritize our 2.X releases.
