### ISSUE TITLE
Very slow compilation

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#511]
openbazaar-go used to take a couple seconds on my computer to compile. Now it takes a minute.

**Comment by jackkleeman** [comment]
It takes me a fair while the first time but the cache helps. Could you just be used to compiling with a cache? Try go install which uses cache better

**Comment by hoffmabc** [comment]
It doesn't seem to be out of the ordinary for me...

**Comment by cpacia** [comment]
Large changes effect compilation time but once cached it's fairly fast.

**Comment by JustinDrake** [comment]
I've compiled multiple times on the same codebase, so caching should be factored in. Even with `go install` it takes 40s!

```
Justins-MacBook-Pro:openbazaar-go justin$ time go install
# github.com/OpenBazaar/openbazaar-go/vendor/github.com/mutecomm/go-sqlcipher
vendor/github.com/mutecomm/go-sqlcipher/sqlite3.c:20897:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

real	0m40.751s
user	0m52.326s
sys	0m4.654s
```

**Comment by JustinDrake** [comment]
@hoffmabc Could you time it using `time`?

**Comment by tyler-smith** [comment]
What version of Go are you using? I'm still on 1.7.4 but it's pretty fast for me:

```
~> go version
go version go1.7.4 darwin/amd64

~> time go install github.com/OpenBazaar/openbazaar-go

real	0m0.416s
user	0m0.407s
sys	0m0.156s

~> time go build ./*.go

real	0m3.634s
user	0m3.990s
sys	0m0.748s

```

**Comment by cpacia** [comment]
I don't think there's anything we can do here. Sounds like it's specific to one machine.
