### ISSUE TITLE
OpenBazaar Foundation

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#513]
The OpenBazaar ecosystem (see specifics below) is currently mostly controlled by OB1. (Seemingly for traditional reasons?) The OpenBazaar ecosystem is lacking a not-for-profit OpenBazaar Foundation (OBF) in a similar vein to the [Mozilla Foundation](https://www.mozilla.org/en-US/foundation/) or the [Wikimedia Foundation](https://wikimediafoundation.org).

The OBF's purpose would be to forward the OpenBazaar mission in a neutral, transparent and open context, inviting for broad membership and participation. The OBF's existence would formalise, clarify and put into effect the separation of concerns between itself and other entities such as OB1 and Duo. Below is a list of things currently managed by OB1 which I believe should be handled by the OBF:

1. **Donation address** (see [here](https://blockchain.info/address/3BDbGsH5h5ctDiFtWMmZawcf3E7iWirVms)) This includes ownership and control of the address and setting the policy for spending funds.
2. **Trademark** This includes ownership of the OpenBazaar trademark, the policy for trademark enforcement, and its actual enforcement.
3. **Autoupdate keys** (see [here](https://github.com/OpenBazaar/openbazaar-go/issues/164)) This includes ownership and control of the reference client autoupdate keys.
4. **Commit access** This includes ownership and control of the [OpenBazaar GitHub](https://github.com/OpenBazaar) as well as setting and enforcing the policy for who can have commit access.
5. **openbazaar.org** This includes ownership and control of the domain, as well as setting and enforcing the policy for deciding upon the content of the website.
6. **Protocol specifications** This includes writing and maintaining detailed specifications for the OpenBazaar protocol.
7. **Seed nodes and gateways** This includes ownership and maintenance of seed nodes and gateways.
8. **Social media** This includes ownership and control over [Twitter](https://twitter.com/openbazaar), [Medium](https://medium.com/@therealopenbazaar), etc.
8. **Other assets** This includes ownership and control of miscellaneous assets such as 
 [Blockstack](https://onename.com/openbazaar), [ZenDesk](https://openbazaar.zendesk.com), etc.

Having an effective OBF means OB1 significantly relinquishing power. I believe ultimately this will drive a healthier OpenBazaar ecosystem with increased openness, transparency and neutrality. Duo will happily relinquish control of assets such as the @helpdesk, [Meetup](https://www.meetup.com/openbazaar) and any other asset relevant for the OBF.

cc The OB1 founders (@hoffmabc, @drwasho, Sam Patterson)

**Comment by hoffmabc** [comment]
I will have to put a deeper amount of thought into this, but I don't want to leave it without an initial response. Personally I think it is extremely early to try and enact this kind of structure. It will take a massive amount of effort to coordinate this and there is probably a very small return on that time investment at the moment. One other major note for this request is that I don't ever plan to relinquish overall control of the project for the foreseeable future. This means that even if this foundation type structure would be implemented I would fully expect to structure it so that I run the foundation and have final say over all of those matters described above. I strongly feel that the mess we've seen in the crypto space is a direct result of the failure to have strong leadership. Until a best practice exists around successfully moving communities forward in a more decentralized manner I hope to avoid it.

I'll have more to say on this, but I'm fully expecting this to not meet your hopes or wants @JustinDrake. All of this is also subject to me changing my mind later on, but right now I'm not convinced that this will significantly improve our network or community. If this is in response to needs not being met by any project or company working with OpenBazaar then I am fully willing to work through those needs to make sure they're met as we discussed the other day.

**Comment by michaelfolkson** [comment]
This is a well thought through GitHub issue and I think if OpenBazaar is successful as a protocol in terms of gaining widespread usage, it is inevitable that there will need to be a foundation. I would definitely support delaying discussion of this until after the 2.0 release as I suspect it could be distracting at a critical time for OpenBazaar (and OB1, Duo). At this time there is no obvious candidate to head the foundation other than @hoffmabc and so acting now would just introduce unnecessary bureaucracy with the same end result, namely being @hoffmabc heading up both OpenBazaar development and OB1. However, I do think that there is significant room for improvement post 2.0 in terms of attracting more developers into the ecosystem and more applications being built on top of the protocol. If OpenBazaar is to meet its potential as a protocol, there will need to be a much clearer divide between the discussions/decision making with regards to OpenBazaar development and OB1 development than there currently is (even if @hoffmabc is heading up both).

**Comment by drwasho** [comment]
There is only one candidate to consider for the head of the foundation:

![0](https://upload.wikimedia.org/wikipedia/en/5/53/Jabba_the_Hutt_in_Return_of_the_Jedi_%281983%29.png)

**Comment by michaelfolkson** [comment]
I stand corrected

**Comment by JustinDrake** [comment]
> if OpenBazaar is successful as a protocol in terms of gaining widespread usage, it is inevitable that there will need to be a foundation

Which is the chicken and which is the egg? :)

**Comment by michaelfolkson** [comment]
Hmm I don't think the Bitcoin Foundation can claim responsibility for Bitcoin's success. More of a product of Bitcoin's success than a significant driver of it.

**Comment by JustinDrake** [comment]
My point was not "foundation => success" rather "no foundation => no success".

**Comment by michaelfolkson** [comment]
We all agree the OpenBazaar protocol isn't successful yet. If it is, it will need a foundation. But I don't think a foundation plays a significant role in that early success, it is set up as a product of that success. Only OB1 and Duo are significantly contributing to OpenBazaar development at moment so foundation seats would be filled by OB1 (majority) and Duo (minority) and Duo would still need the agreement of the OB1 representatives to make changes :)

**Comment by michaelfolkson** [comment]
Should definitely be on the roadmap though (especially if 2.0 is a success)

**Comment by AlbinCauderlier** [comment]
Mubiz would like being part of it.

**Comment by mariodian** [comment]
`We all agree the OpenBazaar protocol isn't successful yet. If it is, it will need a foundation.`

I don't agree. Just look at Bitcoin Foundation. Lots of scandals and is basically non-functional now.

**Comment by michaelfolkson** [comment]
True. An example of it not working/adding value. Sample size of 1 though. I don't know if foundations on other coins are adding value.
