### ISSUE TITLE
Token's SOFA protocol

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#520]
See [here](https://www.sofaprotocol.org/). SOFA is "A protocol to quickly develop apps for an open financial system."

Like Coinbase's [Token](https://blog.tokenbrowser.com/introducing-token-2f2ceeab6d4c) I think of OpenBazaar as a _platform_ (specifically, a marketplace platform), not as a standalone (ecommerce) app. Is OpenBazaar the next eBay? Or is it _also_ the next Uber, AirBnb and KickStarter?

I believe we eventually want to give developers the power to write their own "OpenBazaar apps". The SOFA protocol which specifies allowable UI interactions is a possible way forward.

**Comment by drwasho** [comment]
> Like Coinbase's Token I think of OpenBazaar as a platform (specifically, a marketplace platform), not as a standalone (ecommerce) app. Is OpenBazaar the next eBay? Or is it also the next Uber, AirBnb and KickStarter?

Agreed, this was the vision all along. eCommerce is the beachhead.

> I believe we eventually want to give developers the power to write their own "OpenBazaar apps". The SOFA protocol which specifies allowable UI interactions is a possible way forward.

It's a nice and simple model, and doing something similar would be worthwhile pursuing.
