### ISSUE TITLE
Suggestion: refactor structure of the notification response

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#522]
The notification response looks like this (shortened):

```JSON
{
  "notifications": [
    {
      "id": 56,
      "notification": {
        "moderatorAdd": "QmanUuiLTckNXPDCfamKYJeWPjxBoCKrSwzi4XU7j9B3tr"
      },
      "read": false,
      "timestamp": "2017-05-02T19:24:28Z"
    }
  ]
}
```

Under notification, we can also have `moderatorRemove`, `follow`, `unfollow`, and several more keys if it is an order.

Developing this on the client side is perhaps a little more labor intensive than it needs to be, especially in the case of notifications related to moderators, follow/unfollow... where the key to a `peerID` is different in every case.

I suggest that the response is refactored in this way:

```JSON
{
  "notifications": [
    {
      "id": 56,
      "notification": {
        "type": "moderatorAdd",
        "peerID": "QmanUuiLTckNXPDCfamKYJeWPjxBoCKrSwzi4XU7j9B3tr"
      },
      "read": false,
      "timestamp": "2017-05-02T19:24:28Z"
    }
  ]
}
```

So `type` can be: moderatorAdd, moderatorRemove, follow, unfollow, order etc. `peerID` in the context of an order would be the buyerID.

This would make it easier, from a client perspective, not have to check the response for a changing key to determine the type, and also easier to pull out the `peerID` of the node interacting with the user.

**Comment by cpacia** [comment]
So the current notification format is:
```
{
    "notification": {
        "type": "data"
    }
}
```
Where type is obviously the type of data and data varies based on what type it is. For example, in the `moderatorAdd` message above you have a string. For other types like `order` you have an object.

That same structure is reused for all notifications. So if this is to change then all notifications would need to change. 

(also note the `notification` object shown in the list @drwasho posted is identical to what goes over websockets)

**Comment by drwasho** [comment]
> That same structure is reused for all notifications. So if this is to change then all notifications would need to change.

I think it's a worthwhile change, plus it conforms to the idea that a JSON should by-in-large have the same keys... also if it makes it consistent with WS that's a plus too.

Thoughts @jjeffryes @rmisio ?

**Comment by rmisio** [comment]
I think I'm fine with the proposed change. If we make it though, I would also make the change to the web sockets. I also want to point out that different notifications / sockets have different data (or multiple pieces of data), for example:

```
"notification": {
        "type": "moderatorAdd",
        "peerID": "QmanUuiLTckNXPDCfamKYJeWPjxBoCKrSwzi4XU7j9B3tr"
      },
```

```
"notification": {
        "type": "newOrder",
        "vendorId": "QmanUuiLTckNXPDCfamKYJeWPjxBoCKrSwzi4XU7j9B3tr",
        "buyerId": "sdfsdfsd",
        "orderId": "312312312", 
      },
```

That second one is a semi-hypothetical example. My point is that it should be flexible enough for different types to provide different data.

So... @drwasho I don't think you'll be able to completely abstract things. For example, if you get a notification that an order was funded, I think you'd want to link to the order, so you need to use the orderId, not peerId.

**Comment by drwasho** [comment]
> I don't think you'll be able to completely abstract things. For example, if you get a notification that an order was funded, I think you'd want to link to the order, so you need to use the orderId, not peerId.

That's fine.

**Comment by drwasho** [comment]
@cpacia @jjeffryes @rmisio I just recently solved a problem in my work where a dispute notification has no indication of whether this applies to the Buyer or Vendor or Moderator. I essentially have to check to see whether the orderId under the dispute notification returns an error in the `/ob/order` API call, and if so then I know it belongs to the Moderator and I make an `/ob/case` call.

If this refactor is going to go ahead, it should happen sooner rather than later, and perhaps include a `role` key or something so I can know which notifications apply to the user in the appropriate context.

What do you guys think?

**Comment by rmisio** [comment]
> If this refactor is going to go ahead, it should happen sooner rather than later, and perhaps include a role key or something so I can know which notifications apply to the user in the appropriate context.

Yes, I 100% with this. Having to do what you suggested is quite horrible.

I'm quite confident there will be other notifications that aren't providing the necessary data and  it's important we identify those and where it's possible have the server give that data. Having to make an API call just to determine where a notification should link to is really bad.
