### ISSUE TITLE
POSTMarkChatAsRead overwrites read timestamps

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#523]
I believe the `POSTMarkChatAsRead` API call wrongly updates the timestamps of already read messages.

**Comment by cpacia** [comment]
What makes you think this? There's no code to update timestamps after the initial put.

https://github.com/OpenBazaar/openbazaar-go/blob/master/repo/db/chat.go#L178

**Comment by JustinDrake** [comment]
Apologies this is a bug specific to openbazaar.go, not openbazaar-go
