### ISSUE TITLE
how to migrate openbazaar 1.0 server data to openbazaar 2.0 server? 

### ISSUE THREAD

**Issue by vyloy** [OpenBazaar/openbazaar-go#527]
I used 1.0.
but I want to use 2.0 now.
how can I migrate openbazaar 1.0 server data to openbazaar 2.0 server?

**Comment by cpacia** [comment]
@vyloy we still haven't written any migration scripts. It's probably mature enough to do at this point. Help would be valuable.

**Comment by cpacia** [comment]
There is now an `importlistings` api which takes in a CSV. There is also an `exportlistings` api in v1
