### ISSUE TITLE
Please include NSFW status and the first image filename in the listings.index.json array

### ISSUE THREAD

**Issue by Austin-Williams** [OpenBazaar/openbazaar-go#528]
In your API, please include the NSFW status and the first image filename for each listing shown in (for example)
http://gateway.ob1.io/ipns/Qmai9U7856XKgDSvMFExPbQufcsc4ksG779VyG4Md5dn4J/listings/index.json

If you do that, then we can render [this page](https://projects.invisionapp.com/share/7VAVKRDPC#/screens/224085994
) using only a single API call -- instead of N API calls, where N is the number of listings being offered by that vendor.

For example, rather than:

```
{
        "hash": "QmaEejHcEVZKbJ6iHFKd6idWtLKTCK13Lh2YyyL2Q3vQY6",
        "slug": "shoe",
        "title": "Shoe",
        "categories": [],
        "contractType": "PHYSICAL_GOOD",
        "description": "Shoe",
        "thumbnail": {
            "tiny": "QmPuXLACw2uhjLfX8wwy3udxHXsXAHPBDZEKA95ST6Vn7v",
            "small": "QmU6NsKDr34zA7wPiCRhdaWa5QRnouUgSmR27tujLLMeNR",
            "medium": "QmfP7aCXFd9mzjnn3csCmTHxTMPMFMS4fF8hcDc3zxQmvg"
        },
        "price": {
            "currencyCode": "USD",
            "amount": 200
        },
        "shipsTo": [
            "ALL"
        ],
        "freeShipping": [],
        "language": "",
        "averageRating": 0,
        "ratingCount": 0
    }
```

we would instead return: 

```
{
        "hash": "QmaEejHcEVZKbJ6iHFKd6idWtLKTCK13Lh2YyyL2Q3vQY6",
        "slug": "shoe",
        "title": "Shoe",
        "nsfw" : false,
        "categories": [],
        "contractType": "PHYSICAL_GOOD",
        "description": "Shoe",
        "thumbnail": {
            "filename": "171087141",
            "tiny": "QmPuXLACw2uhjLfX8wwy3udxHXsXAHPBDZEKA95ST6Vn7v",
            "small": "QmU6NsKDr34zA7wPiCRhdaWa5QRnouUgSmR27tujLLMeNR",
            "medium": "QmfP7aCXFd9mzjnn3csCmTHxTMPMFMS4fF8hcDc3zxQmvg"
        },
        "price": {
            "currencyCode": "USD",
            "amount": 200
        },
        "shipsTo": [
            "ALL"
        ],
        "freeShipping": [],
        "language": "",
        "averageRating": 0,
        "ratingCount": 0
    }
```

That small change would make my life easier, and also reduce the number of calls by a factor of N (where N is the number of listings a given vendor has).

As it stands now, in order to render that page I need to make an extra call to the API for every vendor listing just to get the filename for the image, and to get the NSFW status of the listing.

**Comment by jjeffryes** [comment]
We will need the NSFW boolean in this call.

Why do you need the file name, Austin? You should be pulling the image form IPFS using the hash, which is provided.

**Comment by cpacia** [comment]
I've added the nsfw bool. The hash should probably be enough to fetch the image.
