### ISSUE TITLE
Profile POST is requiring a PUT even when the fetch 404s

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#53]
When I fetch a Profile and it 404s, this indicates to the client that the Profile was never created. On a subsequent POST, sometimes the we get the following error:

![image](https://cloud.githubusercontent.com/assets/794517/17311288/fe28586a-57fe-11e6-9d80-806da4e9e332.png)

If we refetch the Profile, we still get a 404:

![image](https://cloud.githubusercontent.com/assets/794517/17311369/c50694ba-57ff-11e6-8dd3-5d7f262798aa.png)

But, a subsequent POST responds with an error to use PUT:

![image](https://cloud.githubusercontent.com/assets/794517/17311378/d6bf567e-57ff-11e6-9286-e3bb17f86cd0.png)

With this behavior, it's very hard for the client to determine whether they should POST or PUT. Can the discrepancy be fixed where the fetch is 404ing, but the POST is still demanding a PUT?

Alternatively, if it's just easier to eliminate PUTs on the endpoint, that would probably work.

**Comment by cpacia** [comment]
I am unable to replicate this. 

1) Delete .openbazaar2.0 data folder. 
2) Start the node 
3) Query localhost:8080/ipns/<guid>/profile
4) Get 404 response.
5) POST to profile.
6)Get 200 response.

If you can figure out what you're doing differently that would help debug it.

**Comment by rmisio** [comment]
Yeah... I'm doing the same as you listed. It doesn't happen every time, but if I keep repeating the steps it happens pretty regularly. I just wiped and repeated 4 times and the error happened on 3 of them.

I think the heart of the problem may be if you're starting fresh frequently in a short window of time.

Anyways... if you can't reproduce we could wait and see if others are experiencing it. It might be an OS specific thing or just some weirdness on my set-up.

**Comment by rmisio** [comment]
Ok, after pulling the latest server, the situation changed for the worst. Now, I'm not randomly getting some 'pinned' error, but I'm consistently getting a 404 on the profile, followed by a 'Profile already exists. Use Put' on the subsequent POST.

![image](https://cloud.githubusercontent.com/assets/794517/17499277/34957bda-5d81-11e6-86e1-a36df298bfef.png)

**Comment by cpacia** [comment]
Ok let me take a look. It's possible something broke in the rebase.

**Comment by cpacia** [comment]
@tyler-smith can you test this on your mac when you get a minute?

I'm still getting success 100% of the time. 

![image](https://cloud.githubusercontent.com/assets/4504708/17499570/1e5f3354-5d9c-11e6-8956-6a7c9c50e6e6.png)

**Comment by cpacia** [comment]
@rmisio are you using electron or chrome when you're testing this?

**Comment by rmisio** [comment]
I'm using Electron, which has chromium (and it's dev console) embedded in it.

**Comment by cpacia** [comment]
See if settings CORS:true in the config file (and restarting) helps. I was under the impression electron didn't need cors headers.

**Comment by rmisio** [comment]
You don't.

I don't think this is a cors issue, otherwise the error would be something to the effect of 'cross-domain request not allowed'.

**Comment by rmisio** [comment]
Plus, once I use PUT, it goes through.

**Comment by cpacia** [comment]
@hoffmabc maybe you want to test on mac as well. I can't imagine why it would behave different on mac.

**Comment by hoffmabc** [comment]
Alrighty

**Comment by cpacia** [comment]
@rmisio when you see this happen to you can you go and check the OpenBazaar2.0/root/ folder to see if there is a profile file in there (before you do a subsequent put). 

If so see what data is in the file.

**Comment by hoffmabc** [comment]
This works perfectly fine using the REST extension in Chrome for me.

![image](https://cloud.githubusercontent.com/assets/45482/17517421/60be87ac-5e11-11e6-9b8d-c6608bda300f.png)

**Comment by hoffmabc** [comment]
Nope that went through as well.

![image](https://cloud.githubusercontent.com/assets/45482/17517517/c446486e-5e11-11e6-8580-d9837dc068b9.png)

**Comment by hoffmabc** [comment]
```
iMac:openbazaar-go brianhoffman$ rm -rf ~/Library/Application\ Support/OpenBazaar2.0
iMac:openbazaar-go brianhoffman$ go run openbazaard.go start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v2.0 starting...
generating 4096-bit RSA keypair...done
09:13:59.433 [DoInit] [INFO] initializing openbazaar node at /Users/brianhoffman/Library/Application Support/OpenBazaar2.0
09:14:01.531 [Execute] [INFO] Peer ID:  QmYdx7ScYrerQdtUQkF4bSPZbDXoy1r5vpKqF1HxQndxyg
09:14:01.531 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/4001
09:14:01.531 [printSwarmAddrs] [INFO] Swarm listening on /ip4/173.79.161.229/tcp/1024
09:14:01.531 [printSwarmAddrs] [INFO] Swarm listening on /ip4/192.168.1.15/tcp/4001
09:14:01.531 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/4001
09:14:01.531 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::18c2:c613:8022:de13/tcp/4001
09:14:01.531 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::2091:1441:bff:941b/tcp/4001
09:14:01.532 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::2af0:76ff:fe4a:f144/tcp/4001
09:14:01.532 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::3095:e432:53aa:3eed/tcp/4001
09:14:01.532 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::6ca8:416f:69b3:b432/tcp/4001
09:14:01.532 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::85f8:e2db:c71c:6bc/tcp/4001
09:14:01.532 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::b5c3:ba96:ee07:b0da/tcp/4001
09:14:01.532 [printSwarmAddrs] [INFO] Swarm listening on /ip6/fd00::e1d1:6c5:f125:7153/tcp/4001
09:14:01.536 [Execute] [INFO] Starting bitcoin wallet...
09:14:01.537 [serveHTTPGateway] [INFO] Gateway/API server listening on /ip4/127.0.0.1/tcp/8080
09:14:01.537 [fetchCurrentRates] [INFO] Fetching bitcoin exchange rates
09:14:01.538 [SetupOpenBazaarService] [INFO] OpenBazaar service running at /openbazaar/app/1.0.0
09:14:11.717 [Publish] [INFO] Published Qmf16T6tUcZsogQFq5iKoSyPQ3osVmYgq8sJvxFPtRjVnF to IPNS
09:14:38.521 [ServeHTTP] [DEBUG] POST /ob/profile HTTP/1.1
Host: localhost:8080
Cookie: TWISTED_SESSION=63c41489a9c1482e1bcf0f55bb555ffa

09:14:48.656 [Publish] [INFO] Published QmaazSLkNRerA6jhSb2BtvVMwSdmzXRt7qiA8oh7bxqfD9 to IPNS
```

**Comment by rmisio** [comment]
@cpacia Yes, I do have a Profile file there. So, I'm not sure why it's 404ing.

![image](https://cloud.githubusercontent.com/assets/794517/17524750/aa9589cc-5e14-11e6-94ca-07200ea3144c.png)

**Comment by rmisio** [comment]
Ok, more pieces to the puzzle. I can confirm after wiping my data folder and starting fresh, this works. So, it correctly 404s (no profile file), then we do a POST and it works. But, then on next restart of the client, the profile is 404ing for some reason.

**Comment by cpacia** [comment]
Looks like all resolved.
