### ISSUE TITLE
"language" et "currency" fields compliant with a RFC or ISO

### ISSUE THREAD

**Issue by AlbinCauderlier** [OpenBazaar/openbazaar-go#533]
Should the "language" and "currency" fields be compliant with a RFC or ISO?

( https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/contracts.proto )

I don't know +/- of a "stand-alone" enumeration.

**Comment by cpacia** [comment]
I think we are going to try to do something like that. The issue we didn't up to this point is the intention is to support arbitrary altcoins in that field as well and if we define an enum for all currencies then any we don't like would cause validation to fail. 

I think the compromise is going to be to validate the `pricing currency` field only if it's not also set to the same value in the `accepted currency` field (which would imply that `pricing currency` is fiat). 

Language could probably be an enum as well.

**Comment by cpacia** [comment]
So the issue with enums for the currency fields is we'd like to support arbitrary altcoins and if the field is an enum, and the given altcoin isn't in the field, then it couldn't be used. 

It could be possible for someone building an altcoin implementation to add their coin to the enum list, but that would cause that currency to display in the client as "" for anyone who isn't running code compiled to show that currency. 

We could maybe make the `pricing currency` field an enum of all fiat currencies then have maybe the zero value set to `same as accepted currency` or something like that for listings where the price is quoted in the `accepted currency`. 

That might be acceptable, but it would mean that `accepted currency` would need to remain a string.

**Comment by placer14** [comment]
Agreed the fields should not modified as described. Would entertain adding a separate field if the need justified it, but that's not what this issue was about.
