### ISSUE TITLE
Incorrect output for "estimatedDelivery" in listing info

### ISSUE THREAD

**Issue by Austin-Williams** [OpenBazaar/openbazaar-go#535]
Check out `listing.shippingOptions.services` here:
[https://gateway.ob1.io/ob/listing/QmbcXa9fQyALiq34WkPxqRSTZYg8shWN4ypr5Pj3GPK486/QmckU3dnmTcHsPK3FgkB1cPajaKmhUr1sjPy3Nhn2FvtHQ](https://gateway.ob1.io/ob/listing/QmbcXa9fQyALiq34WkPxqRSTZYg8shWN4ypr5Pj3GPK486/QmckU3dnmTcHsPK3FgkB1cPajaKmhUr1sjPy3Nhn2FvtHQ)

Looks like some logic is leaking: 
```"estimatedDelivery": "{{$get.est_delivery}}"```

I can't tell if this is an issue with the API or whether someone just entered a strange estimated delivery date (perhaps some program auto-generating random listing info for testing purposes).

I figured it was worth pointing out either way. nbd.

**Comment by hoffmabc** [comment]
Looks like @drwasho did this. It's Jasonette leaking out.

**Comment by hoffmabc** [comment]
Bad data and a won't fix unfortunately.

**Comment by Austin-Williams** [comment]
Ah okay. Not an api issue. Closing.
