### ISSUE TITLE
Need to validate user handles to ensure conformance

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#538]
Handles must be in the @userhandle format. Right now users can save their handles as @@userhandle or @@@@userhandle or whatever they choose.

**Comment by rmisio** [comment]
It may just be simpler to not allow the @ at all and the client can add it in wherever the design demands it.

So `@userhandle`, `@@userhandle` and `@@@@@@userhandle` would all cause errors.

Is this what you were thinking too @jjeffryes ?

**Comment by jjeffryes** [comment]
Yes. The actual blockchain id does not include the @, so we should not accept any @ when it is saved.

**Comment by cpacia** [comment]
Fix. You'll need to blow away the data to remove the old @ symbols.
