### ISSUE TITLE
Support deleting a listing by URL path

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#540]
We're doing it for chat conversations and notifications but not listings.

**Comment by cpacia** [comment]
There's a few places where the id didn't yet get moved from the body to the path. This is one of them. Let's see if we can't track the others so that the client can make the changes.

**Comment by drwasho** [comment]
@cpacia as far as `delete` calls are concerned, this was the only one

**Comment by drwasho** [comment]
I think we're good to go here @cpacia 

Missing anything here @jjeffryes @rmisio @tyler-smith @hoffmabc?

**Comment by drwasho** [comment]
https://github.com/OpenBazaar/openbazaar-go/commit/7ed1b618ce17e953aaaa05f2badbbb5387c2e94d
