### ISSUE TITLE
Request: GET API call to return entire rating history of a peer

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#543]
The way the endpoint works now, you either need to know the hash of the specific rating, or the slug + peerID of the specific rating.

In some of the designs for desktop and mobile, we support the idea of a user touching on the aggregate rating score of a node and viewing their entire rating history, which we could paginate/scroll-through piecemeal.

This issue is to track some of the design considerations of that API call, especially regarding scalability.

**Comment by rmisio** [comment]
I think we had been talking about the server keeping track of the aggregate rating and exposing it to the client somehow. Having the client fetch the entire rating history to make the calculation is really inefficient and not scalable. An item might have 10k reviews and having to fetch a payload that large just to calculate an aggregate is far from ideal.

**Comment by drwasho** [comment]
@rmisio Fetching the entire rating history wouldn't be used to make a calculation, but rather a way for a user to browse the rating history of a node or a listing. Rather, the aggregate calculation (done by the server) displayed in the app would trigger a view to browse this history.

**Comment by drwasho** [comment]
Any thoughts @jjeffryes @rmisio @hoffmabc @tyler-smith

**Comment by jjeffryes** [comment]
I can see the utility of being able to look at all the ratings for a person in one place, my main concern would be that it would be very, very slow. It would be best, I think, to fetch them in batches, the way ratings for individual items are, with an async option.

That way 20, for instance, could be loaded, and when the user takes an action (scrolls to the bottom, presses a next button, etc) the next 20 are loaded. Ideally the number to load each time can be specified in the REST call.

**Comment by jjeffryes** [comment]
As Rob reminded me, we do eventually want to add pagination to the per listing ratings fetch, so when one day listings have thousands of ratings we're not sending all of them in a single list. 

If/when we put in an API for fetching a list of all ratings for all listings, it would be ideal if it had pagination, since it will grow faster than the per-listing ratings list. And it would be nice if at the same time we added pagination to the per listing call.

**Comment by drwasho** [comment]
^ 100%
