### ISSUE TITLE
Disallow Zero Price Listings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#546]
Currently it's possible to save a listing with a price of zero, and the purchase API allows a purchase to be made with a price of zero.

Since you can't have a successful transaction with a price of zero, it shouldn't be possible to save a listing with that price.

The same is true for a purchase, that should return an error if somehow a listing has bad data and a purchase is made with a price of zero.

**Comment by michaelfolkson** [comment]
Merchants may want to give a small number of items away for free for promotional purposes? Or give out voucher codes that make a particular purchase free? Maybe disallowing zero price listings makes sense in short term if you're worried about bugs, bad data causing unwanted sales at a price of zero. I don't know how big a problem this is likely to be.

**Comment by jjeffryes** [comment]
If a listing has a price of zero, you can't create a transaction from it, and the transaction flow won't work.

**Comment by michaelfolkson** [comment]
Yeah would need to bypass the transaction just like you wouldn't enter credit card details if you had access to a free download. May be simpler to reject a price of zero for 2.0 but potentially allow for it in later versions. As an aside, you could theoretically create a transaction that sends zero to the multisig address, pays a fee to the miners and returns the rest of the funds to yourself?

**Comment by JustinDrake** [comment]
@jjeffryes: I don't know if you saw https://github.com/OpenBazaar/openbazaar-desktop/issues/76. It expands on why we want free listings, and currently has 6 👍. The fact that you can't create a transaction is irrelevant if we don't require a transaction for free listings. That part of the purchase flow is simply skipped.

**Comment by hoffmabc** [comment]
I believe it's possible to support this, but we will either need some help to flesh this out in the near term or risk pushing this to the backlog for after release.

**Comment by jjeffryes** [comment]
I saw desktop issue 76. 

Currently, listings priced at zero won't work correctly, and are not planned to work correctly at launch, so we shouldn't allow them to be saved the same way we shouldn't save any other invalid data.

In the future, if we support doing something with zero price listing, then we would consider a price of zero to be valid data, and allow listings with a zero price to be saved after that change happens.

**Comment by JustinDrake** [comment]
> In the future, if we support doing something with zero price listing, then we would consider a price of zero to be valid data

Old clients won't be forwards compatible, in the sense that they won't even be able to browse those listings despite being perfectly able to.
