### ISSUE TITLE
Payout amounts are not being set properly in the Order / Case data.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#548]
Observed:

I had an order for 9923 Satoshi and, as the mod, I closed the dispute using the POSTCloseDispute API, sending in the following percentages:

```
buyerPercentage: 60,
vendorPercentage: 40,
```

The API succeeded (200 and no errors) and the order was updated to a DECIDED and a `resolution`/`disputeResolution` data object now returns via the Case/Order API.

The problem is that the payout amounts are not set properly. They come back as strings instead of numbers and they are much larger than they should be.

```
               "buyerOutput": {
                    "script": "76a9148b938d973ec2bba02c074bdcafb6c489debd199b88ac",
                    "amount": "18446744073709497596"
                },
                "vendorOutput": {
                    "script": "76a914e611a87db7b7209c102e8f8b1c4d951cab86a17d88ac",
                    "amount": "18446744073709515603"
                },
                "moderatorOutput": {
                    "script": "76a914d895b38a33170ebab37a79755f263096d97c2ec788ac",
                    "amount": "18446744073709549783"
                }
```

**Comment by cpacia** [comment]
I cannot replicate.

**Comment by rmisio** [comment]
Ok... I just tried it on 3 fresh nodes and it's absolutely happening. Here are the steps I took:

node B:
- set Node C to be your moderator.
- set up a DIGITAL listing for $1.

node A:
- buy the digital listing from node B selecting Node C as the moderator

node A:
- open a dispute (the order was in an AWAITING_FULFILLMENT state when I did this)

node C:
- Specify a payout for the case. I gave 60% to the buyer and 40% to the vendor. Here's the payload that was sent to `ob/closedispute/`:

![image](https://user-images.githubusercontent.com/794517/27553019-4a14ef6a-5a5e-11e7-967d-f9519347545d.png)

on node A or node B:
- load the order and view the response from `ob/order/QmWUnjMbmwm8Y971iiWdGUFK5SdBRHFfdLm84VDsd4uDeG` in the DOM inspector.

A `disputeResolution` key is returned, but the `buyerOutput.amount`, `vendorOutput.amount` & `moderatorOutput.amount` are not correct. First, they are strings, when they should be numbers. Second, they are a ridiculously high amount. They should approximately be the BTC amount of 60% of 1 dollar for the buyer and 40% of 1 dollar to the vendor. The mod amount should be based on the mods fee. (***those figures are approximations because they will each have one-third of the transaction fee subtracted from them).

Here's the ridiculously inflated numbers I'm seeing:

```
               "buyerOutput": {
                    "script": "76a914cca846f52c3303d1a7d5c21d69daf6e09b33a66a88ac",
                    "amount": "18446744073709519383"
                },
                "vendorOutput": {
                    "script": "76a9145565e6bbe50a69bca54592ec4d67bf9ba781532688ac",
                    "amount": "18446744073709530128"
                },
                "moderatorOutput": {
                    "script": "76a91459a61bacc4742e813e1541aa88dbc34a9a07174688ac",
                    "amount": "18446744073709551075"
                }
```

**Comment by rmisio** [comment]
@cpacia I'm regularly seeing this issue. I gave more info above. Can you please try replicating again? Maybe this is another Testnet to BTC conversion issue (although the listing I bough is in USD).

If you can't replicate it (sigh), then I could ask @jjeffryes when he returns to give it a whirl.

You are absolutely welcome to use the client `order-details-dispute` branch if you'd like to replicate it using the client. It seems the server tests are passing scenarios that end up failing when integrated into the app.
