### ISSUE TITLE
Prevent ob/closedispute on a refunded order.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#550]
After an order has been refunded by the vendor, a call to ob/closedispute by the moderator works and changes the order state from REFUNDED to DECIDED.

This may just be a situation where the Case needs to be closed in this scenario.

**Comment by cpacia** [comment]
This is refunded after the dispute is opened?

**Comment by rmisio** [comment]
yes.

**Comment by rmisio** [comment]
Can the moderator get a disputeClosed socket in this case so if they're looking at the case they don't needlessly attempt to send payout?

**Comment by cpacia** [comment]
I have to think about how that will work.
