### ISSUE TITLE
Systemd service issues with paths

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/openbazaar-go#552]
I've created a Systemd service on Linux (Raspbian OS) to run OB server automatically after system restart:

```
[Unit]
Description=OpenBazaar server 2.0
After=network.target auditd.service

[Service]
Type=forking
User=pi
Group=pi
WorkingDirectory=/home/pi
PIDFile=/tmp/openbazaard2.pid
ExecStart=/usr/local/go/bin/go run /home/pi/bin/go/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go start
ExecStop=/usr/local/go/bin/go run /home/pi/bin/go/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go stop
Restart=on-failure
TimeoutSec=60
RestartSec=60

[Install]
WantedBy=multi-user.target
```

but I'm getting the following errors (the list is WAY longer) in `/var/log/syslog` as soon as I `sudo service openbazaar2 start`:

```
Jun 23 18:18:44 decentralberrypi3 go[20396]: bin/go/src/github.com/OpenBazaar/openbazaar-go/openbazaard.go:74:2: cannot find package "gx/ipfs/QmcTnycWsBgvNYFYgWdWi8SRDCeevG8HBUQHkvg4KLXUsW/go-libp2p-record/pb" in any of:
Jun 23 18:18:44 decentralberrypi3 go[20396]: /usr/local/go/src/gx/ipfs/QmcTnycWsBgvNYFYgWdWi8SRDCeevG8HBUQHkvg4KLXUsW/go-libp2p-record/pb (from $GOROOT)
Jun 23 18:18:44 decentralberrypi3 go[20396]: /home/pi/go/src/gx/ipfs/QmcTnycWsBgvNYFYgWdWi8SRDCeevG8HBUQHkvg4KLXUsW/go-libp2p-record/pb (from $GOPATH)
Jun 23 18:18:45 decentralberrypi3 systemd[1]: openbazaar2.service holdoff time over, scheduling restart.
Jun 23 18:18:45 decentralberrypi3 systemd[1]: Stopping OpenBazaar server 2.0...
```

To me, it seems like it's an issue with relative paths within openbazaar. 
When I start the server directly (via go run) it works as intended but I think it's worth making it compatible with Systemd as people will want to run openbazaar as service. 

It's also possible my service script is wrong, but I have no issues with a similar one running openbazaar 1.0.

**Comment by cpacia** [comment]
@mariodian I haven't used it with systemd before. It looks like you're running it on a pi? Have you got it working on a regular computer? 

Also we do have a binary for the pi if you want to give that a try.

**Comment by cpacia** [comment]
Also, I haven't yet hooked up the stop command. Still have to think of the best way to do it so you might want to remove that line for now.

**Comment by mariodian** [comment]
@cpacia I don't have other Linux machine, just pi. Anyway even Ubuntu switched to Systemd from Upstart at least a year ago so I think it's worth making it compatible.

Where can I find the binary? I'll give it a try.

**Comment by cpacia** [comment]
Binaries are here in the releases https://github.com/OpenBazaar/openbazaar-go/releases

**Comment by Canalytic** [comment]
Was this ever fixed?  Is there an up-to-date systemd service file for OB2.0?

**Comment by cpacia** [comment]
I haven't actually run it with systemd. Maybe someone who has can confirm if this is still an issue. Usually just use nohup.

**Comment by placer14** [comment]
Please reopen if further discussion is required.
