### ISSUE TITLE
ENS proposal

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#553]
I'd like to put forward a more concrete proposal for using the ENS for handles in OpenBazaar 2.0. I suggest that we use subdomains of `openbazaar.eth` to register and resolve OB2.0 names. For example,

* `ob://cpacia` would resolve to `cpacia.openbazaar.eth`
* `ob://shoes.cpacia` would resolve to `shoes.cpacia.openbazaar.eth`
* `ob://bnb.cpacia` would resolve to `bnb.cpacia.openbazaar.eth`

Because of the programmability of ENS registrars and resolvers, we can design a contract that registers an OpenBazaar 2.0 handle in a single transaction given the handle and the OpenBazaarID as inputs.

Advantages I can think of versus the current setup for OB1.0:

1. single transaction registration (vs two transactions for OB1.0)
2. low-latency registrations (seconds/minutes for OB2.0 vs hours/day for OB1.0)
3. OpenBazaar subdomains, just like the web (e.g. `ob://bnb.cpacia`)
4. lightclient friendlyness, thanks to Ethereum's Patricia-Merkle trie for state/receipts (Chris [made a lightclient resolver here](https://github.com/cpacia/ens-lite), with an [awesome demo](https://www.youtube.com/watch?v=4VgMYz4OB18))
5. less squatting (there is more incentive to squat a generic naming system like BlockchainIDs instead of an application-specific namespace like `openbazaar.eth`)
6. network effects with other Ethereum applications (as far as I know, the main application that uses BlockchainIDs is OB1.0, yielding no network effect for OpenBazaar)
7. potentially cheaper registrations (assuming $3 per Bitcoin transaction, that's $6 per BlockchainID. It is still unclear how much an OB2.0 registration would cost. My gut feel is that it's <$1.)
8. significantly higher uptake and innovation of the ENS compared to BlockchainID. For example, see [this metric](https://twitter.com/drakefjustin/status/876832576421474305) and integrations with many wallets, explorers, tools (e.g. MEW, ETHTools, Etherscan, Metamask).
9. Looking into the future, I expect ENS will become the primary naming system for an IPFS browser. This means we can finally have native OpenBazaar web links which a user can type in the address bar, and use to point to other stores natively to the web.
10. Generally more awesomeness across the board

Disadvantages I can think of versus the current setup for OB1.0:

1. Unlike with OneName, there is no immediate transaction fee subsidizer for the ENS. My understanding (?) is that Blockstack will stop subsidizing registration fees soon. On that point, handles are really only for vendors, and Duo or OB1 could subsidize the first 10,000 vendor handles. We could have an OB2.0 chat bot automate registration right from the reference client. For example, the bot could check that the vendor has at least one listing, and that the vendor has been online for at least one day.
2. A new currency (Ether) is added in addition Bitcoin. My understanding (?) is that OpenBazaar will eventually achieve currency abstraction anyway, with the possibility to support for example Litecoin, Zcash and Ether. On that point, it is not necessary to have lightclient verification for OpenBazaar handles. An API (similar to OneName) could be good enough to get started. Notice that the API could include Merkle proofs and signatures, providing some level of trustlessness, something the OneName API does not do.
3. The ENS registrar will change. The [current registrar](https://etherscan.io/address/0x6090a6e47849629b7245dfa1ca21d94cd15878ef#code) is temporary, with a plan to move to another registrar in ~2 years. My guess is that the temporary will remain functional for much longer, and be forwards-compatible with the new registrar.
4. There needs to be governance regarding ownership and control of the `openbazaar.eth` handle. This governance can be defined programmatically, e.g. using multisig. With BlockstackIDs there is no such governance issue.

**Comment by hoffmabc** [comment]
You need to explain #4 a little further @JustinDrake. One major concern is that ultimately control of this ENS domain falls outside of current maintainers of OpenBazaar. For instance I maintain control of the DNS records for openbazaar.org and therefore as maintainer am the final stop for governing that. openbazaar.eth on the other hand is likely to be owned/maintained by someone else (I'm assuming you will probably the recipient there). 

Without any kind of organization or group to control this it would likely be risky at this point to move towards that idea. This will have to be an idea in progress and be discussed much further.

**Comment by JustinDrake** [comment]
@hoffmabc Regarding governance, IMO the natural place for ownership and control of these assets would be the [OpenBazaar Foundation](https://github.com/OpenBazaar/openbazaar-go/issues/513). Before such a non-profit organisation is setup, ownership and control of these assets could be distributed across various trusted constituents of the OpenBazaar ecosystem. For illustrative purposes we could have a 2-of-3 multisig where the three signatories are OB1, Duo and Mubiz.

**Comment by hoffmabc** [comment]
So what happens exactly if the $80,000 USD in ETH that you put into that ENS lock starts dropping or you just want it back? I'm very hesitant to rush into this without understanding all the ramifications. I'm very much assuming that you'd like this move to give you more leverage in the direction and control of OpenBazaar and I admire such a huge personal commitment to do so, but this needs some significant thought. This is a fairly considerable architecture shift and the negatives you mention above are not all insignificant regardless of the upsides. Perhaps we should have a discussion next week to talk this through live.

**Comment by JustinDrake** [comment]
@hoffmabc It's too early to tell because the auction process is not completed, but I think it's likely almost all of 250.5 ETH will be immediately refunded to me. I think I explained the rules of the auction to you over Slack. To reiterate, the winning bidder only locks the second-highest bid. (It's a [Vickrey auction](https://en.wikipedia.org/wiki/Vickrey_auction).)

Assuming the second-highest bid is less than 1 ETH, I'd be happy to effectively donate these funds to the OpenBazaar community. The funds would simply stay locked with `openbazaar.eth` for ever.

**Comment by michaelfolkson** [comment]
Ok.... so trying to move this issue towards some 2.0 decisions (I'll leave post 2.0 decisions for later).  I was under the impression that no major changes would be made for 2.0 now we are nearing release. Replacing Blockstack with ENS would be a major change. Even if ENS is superior to Blockstack (which I'm not convinced it is) moving pre 2.0 release would be rash in my opinion. We are already wrestling with the currency/BTC transaction fee issue and this is an added complication. So @JustinDrake are you convinced this transition should be made for 2.0 and what is the rationale for this urgency?

**Comment by michaelfolkson** [comment]
@hoffmabc: Can you update us here when you've spoken to Blockstack and the plans for an identity system are a little clearer? Are you ruling out ENS for handles in OpenBazaar 2.0? (I'm assuming yes but you haven't made that explicit)

**Comment by michaelfolkson** [comment]
Or @JustinDrake has created a separate issue here. https://github.com/OpenBazaar/openbazaar-go/issues/581. Probably don't need both open do we?

**Comment by veox** [comment]
> I'm very hesitant to rush into this without understanding all the ramifications.

IMO rightly so; ENS is still in "evaluation" phase.

I'll drop a few links that seem possibly relevant.

-----

> There needs to be governance regarding ownership and control of the `openbazaar.eth` handle. This governance can be defined programmatically, e.g. using multisig.

There's a [prototype Holder](https://gist.github.com/Arachnid/3acaf6ed437ee79e8e894b2ce5e82441) ([highlighted](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fdavidhq%2FSublimeEthereum%2Fblob%2Fmaster%2FSolidity.YAML-tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.github.com%2FArachnid%2F3acaf6ed437ee79e8e894b2ce5e82441%2Fraw%2Ff32ec0ef9e4f3a0b7a4850346ac1e0da706d761f%2FDeedHolder.sol&code=)) that basically disallows releasing the `Deed` (i.e. it disallows putting the name back up for auction).

> So what happens exactly if the $80,000 USD in ETH that you put into that ENS lock starts dropping or you just want it back?

An [EIP](https://github.com/ethereum/EIPs/issues/705) suggests the deposit is made gradually withdrawable (in the future version of ENS).
