### ISSUE TITLE
The purchase api is returning the wrong amount when buying an item priced in BTC

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#554]
The listing `ob://QmahazHBv98h4Tye4qY7V7fueygpcrYoC3qRyUjGxuhJHU/store/check-it` is priced at 1 BTC (100,000,000 Sat):

```
"item": {
            "title": "check it",
            "description": "",
            "processingTime": "",
            "price": 100000000,
```

When I purchase it via `ob/purchase`, I get the following amount which is many multiples larger than it should be:

```
"amount": 100000000000000,
```

FWIW: this is a digital good with no shipping, no coupons and no variants that would affect the price.

**Comment by cpacia** [comment]
It's probably an issue with the fact that you are setting pricing currency to btc rather than tbtc and it's trying to convert between the two.
