### ISSUE TITLE
Please provide socket to other party when a dispute payout is accepted.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#556]
When one party accepts a dispute payout, please provide a socket to the other so they could update the order state.

Otherwise, if they're looking at the order, there's going to be a CTA that's just going to fail until they refresh:

![image](https://user-images.githubusercontent.com/794517/27557930-4dd309ae-5a70-11e7-8153-eb40945b70d4.png)

It's a much nicer experience if we could update that state in real time and save the user from having to see an untranslated confusing error message.

**Comment by cpacia** [comment]
I really need to get the notifications PR merged first before doing any more notification work because it will just create a mess of merge conflicts.

**Comment by rmisio** [comment]
@jjeffryes what's the status of the client handling the new notifications format?

**Comment by jjeffryes** [comment]
I can work on this next.
