### ISSUE TITLE
Proposal: Health check endpoint

### ISSUE THREAD

**Issue by tyler-smith** [OpenBazaar/openbazaar-go#564]
Example: `GET /health` or `GET /ob/health`

It would:

- Ping sqlite
- Stat the ipfs root
- Check for connected peers

Then we can add the following to our Dockerfile:
`HEALTHCHECK --start-period=1m --retries=10 CMD curl -f http://localhost:4002/health || exit 1`

**Comment by cpacia** [comment]
What do you want the output to look like?

**Comment by tyler-smith** [comment]
Probably 200 with no body or '{}' upon success and 404 with response body indicating why. If sqlite and peers aren't found but the ipfs root is, it'd be something like:

```json
{
  "sqlite": false,
  "ipfs_root": true,
  "peers": false
}
```
