### ISSUE TITLE
No Rows Error On Refund

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#565]
When an order is refunded by a seller, the buyer gets a refund notification and a call is made to ob/order/orderId. When this happens the server responds with a 500 error and "reason": "sql: no rows in result set"

It appears that the call continues to respond with the error any time it is made after that. I thought I saw it start working after a few seconds, but in later tests I haven't been able to reproduce that, and it's always returned an error.

Older orders in a refunded state can be called successfully.

**Comment by cpacia** [comment]
I have seen this once but I can't replicate it. I just refunded a direct and moderated order and they both behaved as expected.
