### ISSUE TITLE
Profile has Out of Date Ratings Data

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#566]
When ob/profile/QmfY12upDQTdi1AUp4EmimpeVhezfq8ZY9MPkhoAcggKRJ is called, the rating data returned is 

```
"stats": {
        "followerCount": 0,
        "followingCount": 1,
        "listingCount": 1,
        "ratingCount": 0,
        "averageRating": 0
    },
```

This is inaccurate. 3 of the listings in the store have a total of 5 ratings.

The store was updated and published, with a change to the profile, before getting the data above. The ratings left on the listings were more than a day old.

**Comment by cpacia** [comment]
Still cannot verify this issue. I've created many review for different types of orders and have tried on both linux and windows. So far I'm unable to reproduce.
