### ISSUE TITLE
Make use of CRDTs for public channels

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#569]
There are some weak spots with the current IPFS solution which I list below. The issues listed may seem unrelated, but I think they all have the same potential solution: CRDTs.

**Problems**

1. The reading and writing of offline messages pointers on the DHT are probabilistic in nature. They can (and will!) fail in practice. Moreover, they expire relatively quickly.
2. The offline message payloads need to be stored somewhere, and currently no one is really incentivised to store and host them. The OB1 gateway may do so, but there are issues there (centralisation, down time, requires hard-coding in the code, ...)
3. Ratings (especially the bad ones) can be censured by vendors. 

The first two issues will lead to communication flakiness between buyers and vendors. The third issue will lead to cheating.

My suggestion is to have a public pub-sub channel for each of these public events ("new pointer added to DHT", "new offline message available", "new rating created by a buyer"). That way, anyone (in particular, centralised service providers) can easily listen to, seed and cache the data, and provide it on a need-to-have basis. For issues 1. and 2., this will significantly mitigate communication flakiness. For issue 3., this will eliminate cheating by vendors. We now need to trust the buyer to publish the rating on the pub-sub channel, as opposed to trusting the vendor to host the rating, which requires significantly less trust.

**Comment by hoffmabc** [comment]
As long as we are talking operation based CRDT and not state based. I think that would scale not nicely.

**Comment by hoffmabc** [comment]
I think this is also nice as we can request missing ratings lazily from many nodes. I like it.

**Comment by cpacia** [comment]
Not a bad idea. How far along is pubsub? The last thing I read about it was they had more they wanted to do.
