### ISSUE TITLE
IPNS entry not republished

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#572]
If a OpenBazaar store stays online for 7+ days, their IPNS entry will not be republished. The `repointer.go` has logic to republish message and moderator pointers every 24 hours, but not the IPNS entry.

**Comment by cpacia** [comment]
IPFS handles republishing of IPNS records.

**Comment by hoffmabc** [comment]
Is this an issue that needs to be pushed up stream?
