### ISSUE TITLE
Specify IPNS sequence number when importing identity to new computer

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#573]
If I import an OpenBazaar identity from computer `A` (with some history) to computer `B` (fresh), IPNS will break. The reason is the IPNS sequence number of `A` will be non-zero (e.g. 1000), whereas a fresh import of the same identity on computer `B` will start with IPNS sequence number 0.

When importing an identity, the IPNS sequence number needs to be specified otherwise changes made on computer `B` will not be registered.

**Comment by cpacia** [comment]
That's a good catch. Without it I suppose the worst case is it takes a week for higher numbered records to drop out of the dht.

Or maybe a worst case is someone hangs on to all records and prevents lower ones from ever being used. 

I'm not too hot on the idea of people needed to remember their record number in addition to their seed. We don't even display the record number anywhere.
