### ISSUE TITLE
Discrepancy between indices

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#575]
As it stands, the app has four indices. The listings and ratings indices are properly marked as `.json` files but the `followers`, `following` indices, despite being JSON files, are not properly marked as `.json` files.

**Comment by JustinDrake** [comment]
There is also a discrepancy between profile and listings. Listings (e.g. `example.json`) has `.json` but profiles are stored in a `profile` file without the `.json` extension.

**Comment by JustinDrake** [comment]
If the followers will be paginated into several files, it may make sense for them to have a separate folder.

**Comment by cpacia** [comment]
done
