### ISSUE TITLE
What is stored in the feeds folder?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#576]
What is the [`feeds` directory](https://github.com/OpenBazaar/openbazaar-go/blob/33c9a76f0d8430310dab6464aef82876d0ca6341/repo/init.go#L104) for OpenBazaar? What is stored there?

**Comment by cpacia** [comment]
Nothing at the moment. It's for a potential future feature.

**Comment by JustinDrake** [comment]
What is that potential future feature? Why is it called "feeds"?
