### ISSUE TITLE
Running two stores on the same computer

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#577]
For testing it's useful to have two OpenBazaar nodes running on the same computer. What is the easiest way to achieve that?

**Comment by jjeffryes** [comment]
When you run the server, add the --datadir= flag to it, and specify a different data directory.

That will run a second (or third, or forth...) instance of the server using that directory.

You will need to init the server in that directory first, and edit the config file that is created. Change the values in the Addresses object to use different ports, so no two nodes use the same ones.

For example, change the values below to 4102, 4101, etc.

```
"Addresses": {
    "API": "",
    "Gateway": "/ip4/127.0.0.1/tcp/4002",
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/tcp/9005/ws",
      "/ip6/::/tcp/9005/ws"
    ]
  },
```

**Comment by cpacia** [comment]
Correct
