### ISSUE TITLE
gateway too many open files

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#588]
<img width="1140" alt="screen shot 2017-07-24 at 17 47 00" src="https://user-images.githubusercontent.com/731743/28531824-3bf10c7a-7098-11e7-8e8d-457077811ab5.png">

This is an example URL https://gateway.ob1.io/api/v0/object/links?arg=QmPJNMNmY5gWBZaChJq5Evyn9da8edTLJASaPy3sX1xKRv

**Comment by cpacia** [comment]
fixed

**Comment by hoffmabc** [comment]
I'm assuming this was fixed by increasing file limit on the gateway @cpacia ? IPFS team has said this is a known issue and won't be fixing it in the near term although they'd like to.

**Comment by JustinDrake** [comment]
@hoffmabc Do you have a link to the IPFS issue?

**Comment by hoffmabc** [comment]
I don't @JustinDrake I believe there are multiple ones that have been reported. What I've stated was from the IRC chat where I brought it up this morning. I can try and link over to it if I can find it.
