### ISSUE TITLE
Use CIDv1 for image hashes

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#589]
The image hashes still use CIDv0 (e.g. see http://gateway.duosear.ch/ipfs/zdj7WYjg5Gek1VmesaAFnT7nzi15xhAYMt1yxBxDyQSNgG1gy/listings/piss.json). They should now use CIDv1.

```
            "images": [
                {
                    "filename": "PISS.jpg",
                    "original": "QmPaFEXWEB3uB5DQNaDAupCUvqYjMc7BPszBDHkPiMbGHn",
                    "large": "QmYzEd1xV7BiWANKqPnDzaMr1W6pNciJEawyh1hKMfQZRR",
                    "medium": "QmT8HWD2mu1ieAhiwyBzWJFfrsvxDmx8ky6Q3pduz47FbR",
                    "small": "QmWassc1riFs9yZWcjoPMNQ8TLD1NXHuxBLQ8jQFxB9zv5",
                    "tiny": "QmWE2wHey4KCsmcQA1rby7wfckP6fZ5Fowek4yF7RDpWqP"
```

**Comment by cpacia** [comment]
That's a cached file

**Comment by JustinDrake** [comment]
Yes, and the IPFS hashes for those cached images are CIDv1 hashes. I suggest we stay consistent.

http://gateway.duosear.ch/api/v0/object/links?arg=zdj7WfcSgpmWxuEuyvUXMWTGMKAd9MF8evF1KiRbLFE8uXuZu
