### ISSUE TITLE
Provide socket when escrow has been released due to timeout

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#597]
Please provide a socket to all 3 parties (vendor, buyer, mod) when an escrow payment has been released due to a timeout.

This way, in case any party happens to have that order open, the UI could update rather than have CTAs that will fail until the page is refreshed.

**Comment by cpacia** [comment]
Like the case of the dispute payout, the moderator doesn't have the information needed to provide the socket. 

I could provide it to the buyer if that's necessary but there isn't any state on the buyer side to change. It would only provide a notification.

**Comment by rmisio** [comment]
How is there not a state to update when after the timeout the order goes into a 'PAYMENT_FINALIZED' state and prior to that it was in something else?

> Like the case of the dispute payout, the moderator doesn't have the information needed to provide the socket.

I don't understand. Isn't it a matter of just sending the 3 parties a socket to let them know that they need to refetch the order since it will now have more data?
- for the buyer and vendor:
1. order state become 'PAYMENT_FINALIZED'.
2. a 'RefundAddressTransaction' transaction object is included with the data so the UI could represent the refund transaction.
- for the mod (if a case was open):
1. I assume the state would become `RESOLVED`.

If the parties don't get the socket and they happen to be looking at the order, there will be CTAs (action buttons) that will fail with weird reasons and it's not until they refresh the page that the order will make sense.

**Comment by cpacia** [comment]
The moderator isn't listening on the blockchain for the funds being released from escrow to send him a socket notification.

As for the payment state I don't think you were on the call where we talked about it. @jjeffryes said it was find if only the vendor state updated since the only thing the buyer has left to do is leave a rating.

**Comment by jjeffryes** [comment]
How does the buyer get to the state where they can leave a review? When we talked about it I thought the buyer would have a way to know the payment went through?

Or are we assuming at that point the buyer is long gone (which is what caused the timeout), so it doesn't matter?

**Comment by cpacia** [comment]
The buyer should be in a state where they can leave a review. Currently it only allows the vendor to release the funds if it's in the FULFILLED state. 

It's an open question if we want to let them release the funds during an active dispute. 

Typically I would say no, but then again they could accidentally open the dispute and the moderator could be go then they're stuck.

**Comment by rmisio** [comment]
So currently the only order state that the timeout release would occur is FULFILLED?

**Comment by cpacia** [comment]
yes

**Comment by cpacia** [comment]
Maybe I should make it so that if a dispute has been open < 14 day then you can't release the funds. If it's been > 14 days since the dispute was opened then you can.

**Comment by rmisio** [comment]
> Maybe I should make it so that if a dispute has been open < 14 day then you can't release the funds. If it's been > 14 days since the dispute was opened then you can.

@jjeffryes I think we would need to have a phone call about this if this is the case. If we're just talking about the timeout release only happens if the order is in the FULFILLED state and would only release the funds to the Vendor, then things are manage-able with just one socket to the vendor.

If we start allowing the timeout release to happen when the order is in different states and the mod potentially being involved, I think more parties would need to be aware of this happening and their respective data would need to be properly updated (e.g. the Case state would need to change to RESOLVED, etc...).

**Comment by rmisio** [comment]
Closing for now, since we are only very minimally handling this in the client for now. At some point we will circle back to this and do a deeper dive into the requirements and desired UX.
