### ISSUE TITLE
Add additional data to various socket types

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#604]
Based on the UX requirements for what the notification text would say, here is additional data various socket types need:

OrderConfirmation:
> %{vendorName} has accepted your order.

- [x]  Need vendor handle and peerId.

declined:
> %{vendorName} has declined your order.

- [x] Need vendor handle and peerId.

cancel:
> %{buyerName} has canceled their order.

- [x] Need buyer handle and peerId.

refund:
> %{vendorName} has refunded your order.

- [x] Need vendor handle and peerId.

fulfillment:
> %{vendorName} has fulfilled your order.

- 

- [x] Need vendor handle and peerId.

orderComplete:
> %{buyerName} left feedback on their order.

- [x] Need buyer handle and peerId.

disputeOpen: (received by mod and other party)
> %{disputerName} opened a dispute with %{otherPartyName} || you. // is it possible to use "you" when the notification goes to the other party? The moderator would always see %{otherPartyName} in the notification.

- [x] Need the handle and peerId of the party that opened the dispute (disputer).

- [x] Need the handle and peerId of the other party (disputee).

disputeUpdate:
> %{otherPartyName} shared their contract for the dispute with %{disputerName}.

- [x] Need the handle and peerId of the party that opened the dispute (disputer).

- [x] Need the handle and peerId of the other party (disputee).

disputeClose:
> The dispute with %{otherPartyName} has been closed. // I should never see my own name in this notification. It should always display the other party.

- [ ] Need the handle and peerId of the party that opened the dispute (disputer).

- [x] Need the handle and peerId of the other party (disputee).

disputeAccepted:
> The dispute with %{otherPartyName} has been finalized.

- [ ] Need the handle and peerId of the party that opened the dispute (disputer).

- [x] Need the handle and peerId of the other party (disputee).

follow:
> %{handle} has followed you.

- [ ] If possible, please provide the handle here, otherwise the client needs to make a profile call.

modAdd:
> %{handle} has added you as a moderator.

- [ ] If possible, please provide the handle here, otherwise the client needs to make a profile call.

modRemove:
> %{handle} has removed you as a moderator.

- [ ] If possible, please provide the handle here, otherwise the client needs to make a profile call.

**Comment by rmisio** [comment]
FWIW, when "name" is used above, the client will show handle (if available) or guid (if not), so `%{vendorName} has accepted your order.` would be `@themes has accepted your order.` or `Qmabc123… has accepted your order.`.

**Comment by cpacia** [comment]
> disputeClose:

> The dispute with %{otherPartyName} has been closed. // I should never see my own name in this notification. It should always display the other party.
> Need the handle and peerId of the party that opened the dispute (disputer).

Why do you need the ID of the peer that opened the dispute here if it's not displayed?

**Comment by cpacia** [comment]
> follow:

> %{handle} has followed you.
 > If possible, please provide the handle here, otherwise the client needs to make a profile call

What are you doing for the avatar... GET avatar? I don't have the handle saved for the node since, like the avatar, the field may change.

**Comment by cpacia** [comment]
> disputeUpdate:

> %{otherPartyName} shared their contract for the dispute with %{disputerName}.
 Need the handle and peerId of the party that opened the dispute (disputer).

 Is it more appropriate here to use the case ID instead of `disputerName`

**Comment by rmisio** [comment]
> Why do you need the ID of the peer that opened the dispute here if it's not displayed?

> Same for dispute accepted

That was a mistake, we just need the peer ID and handle of the other party.

**Comment by rmisio** [comment]
> What are you doing for the avatar... GET avatar? I don't have the handle saved for the node since, like the avatar, the field may change.

I forgot about the avatar. If the handle and avatar are not provided then we'd make a profile call with usecache=true. Seems like a waste to make that call for what could be many notifications. Mike and others have said that stale data is not a problem here. Wouldn't the handle and listing image, etc... be stale for the order notifications too?

Anyways, if it's a big deal to provide that data, then we'll just make the profile calls.

**Comment by rmisio** [comment]
> Is it more appropriate here to use the case ID instead of disputerName?

I'm not following... the UX req is to show the disputer's handle / guid which would link to their user page. How would the case ID help with that?

We do still need the case ID, since the notification should link to the Order Detail overlay for this case.

**Comment by cpacia** [comment]
%{otherPartyName} shared their contract for dispute %{id}. seems to read better to me.

**Comment by rmisio** [comment]
> %{otherPartyName} shared their contract for dispute %{id}. seems to read better to me.

Hmmmm... so you think `@themes shared their contract for dispute QmdvLT6WX18fyhTZ7o7tr8BzNFEduWu53m5QNSG8kqkoQB` is more readable than `@themes shared their contract for the dispute with @skishop`?

@morebrownies thoughts?

@cpacia Is there a technical complication in providing the handle and guid of the disputer, or you just think the first option is better UX?

**Comment by cpacia** [comment]
I don't know. It's possible someone could have multiple disputes with the same store. Not sure if it's likely though.
