### ISSUE TITLE
Allow GET Notifications to be filtered by multiple notification types

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#605]
Based on the following UX requirement:

question:
> @wolf for the notifications Order tab, is your expectation that only the notifications of type ‘order’ would appear there which would be `@pickles placed an order for Pickle Brine Kit.` -or- all order related notification types would appear there ( `@pickles placed an order for Pickle Brine Kit.`, `Your order has been accepted.`, `A refund has been issued for your order.`, etc….)?

response:
> All notifications that relate to orders should display within the Orders tab.

... please allow the GET notification API to accept multiple notification types in the `filter` param.

**Comment by cpacia** [comment]
#607
