### ISSUE TITLE
How should Go Report Card issues be treated?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#62]
The [Go Report Card](https://goreportcard.com/report/github.com/OpenBazaar/openbazaar-go) for this repo flags 44 issues. How should Go Report Card issues be treated? (E.g. which classes of issues are ignored, which should be addressed.)

A piece of documentation in [`docs`](https://github.com/OpenBazaar/openbazaar-go/tree/master/docs) would be great.

**Comment by hoffmabc** [comment]
Will have to look into this one.

**Comment by tyler-smith** [comment]
They should all be taken care of. The only thing we're not scored high on is linting which we know we need to do still. I will start linting this repo after im done with the wallet. Feel free to submit a pr if you'd like.

**Comment by JustinDrake** [comment]
@tyler-smith Have you fixed this?
