### ISSUE TITLE
How are tests run?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#63]
I have tried running `go test` in two different directories, both times unsuccessfully.

- From `$GOPATH/src/github.com/OpenBazaar/openbazaar-go` I get:

```
Justins-MacBook-Air:openbazaar-go justin$ go test
?   	github.com/OpenBazaar/openbazaar-go	[no test files]
```

- From `$GOPATH` I get:

```
Justins-MacBook-Air:ob-go justin$ go test
can't load package: package .: no buildable Go source files in /Users/justin/Desktop/duomoney/ob-go
```

A short testing guide in [`docs`](https://github.com/OpenBazaar/openbazaar-go/tree/master/docs) would be helpful.

**Comment by hoffmabc** [comment]
One of the issues is that this is just standard Golang functionality. I'm not really sure a document that duplicates the Go documentation is really appropriate here. 

What you're seeing is expected output. There are only test cases in some folders not the ones you tried. Files that end in _test.go will trigger test case activity.

**Comment by JustinDrake** [comment]
For posterity, run `go test $(go list ./... | grep -v /vendor/)` from the folder `$GOPATH/src/github.com/OpenBazaar/openbazaar-go`.
