### ISSUE TITLE
Coupon hash commitments

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#635]
The current implement of coupons doesn't work because it's trivial to manually check for coupons in the listings, and simply apply them. I suggest instead using coupon hash commitments. For example, the vendor could say "The coupon code for which the hash is [insert hash] can get a 10% discount." To avoid dictionary attacks, it suffices to salt the hash.

**Comment by cpacia** [comment]
I'm not follow what you mean by commitment. As for the salt.. there needs to be a data source we can use as the salt. What would that be?

**Comment by JustinDrake** [comment]
I'm looking at the code and there seems to already be logic for a hash commitment scheme. I don't understand why the `code` is using a `oneof`:

        oneof code {
            string hash         = 2;
            string discountCode = 3;
        }

Shouldn't it always be a hash? Also, I'm confused as to what the difference between a `discountCode` and a `couponCode` is. The two nomenclatures are used in [this file](https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/contracts.proto#L183).

Regarding the salt, the data source can just be a random number (chosen by the vendor) included in the listing.

**Comment by cpacia** [comment]
hash is published on the network. discount code is used by the client when posting the data. 

As for the salt, this would add more complexity as it would need to be saved by the vendor and then communicated to the moderator.

**Comment by JustinDrake** [comment]
Ok. Would it be possible to clean up the protobuf so that `discountCode` and `couponCodes` are made consistent? (E.g. rename `discountCode` to `couponCode`.)

As for the salt, it would be hardcoded in the listing. So no need for special logic to save and communicate to the moderator.
