### ISSUE TITLE
Add inventory to listings.json

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#637]
The title says it all. Having a listing in `listings.json` (without investory count) means:

> Last time I was online, I had at least one such listing.

Adding inventory count strictly adds information. It means:

> Last time I was online, I had a least [inventory count] such listings.

Like the followers statistics in the profile, it's an approximation, but a useful approximation nonetheless. It would also allow clients to display information to buyers, such as "Only 2 items left! Order quick!"

**Comment by JustinDrake** [comment]
At the moment scrapers (such as Duo) have to make an ad-hoc API call to fetch the inventory counts. IMO it should be under the IPFS root directory.

**Comment by cpacia** [comment]
The server is set up to only do an IPNS republish when the use triggers it. This is because republishing breaks whatever caching has been accumulated. To keep the inventory up to date we would need to automatically republish on each order and deny the user the ability to control his level of caching. 

This is why the inventory is not published on the network.

**Comment by JustinDrake** [comment]
A couple questions:

1. The `following`/`followers` statistic is part of the root folder. If someone follows a store, when is that reflected at the IPNS level?
2. The ratings are also part of the root folder. If someone makes an order and leaves a rating, when is that reflected at the IPNS level?

**Comment by cpacia** [comment]
1 and 2 do not update automatically. Republishing is trigger whenever the user changes any of their data, manually calls the republish api, or restarts.

**Comment by JustinDrake** [comment]
Especially for stores that are online 24/7 on a VPN, the ratings and stats will get very stale.
