### ISSUE TITLE
Unusual OB1 user_agent

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#638]
See for example [this user_agent](http://gateway.duosear.ch/ipfs/zb2rhdjZ4ucygckPVCMmAG53414rn3LSeBepfqeJy1fjEB543), which is `/openbazaar-go:0.7.3/'ob1:v0.7.0d'`. , or [this one](http://gateway.duosear.ch/ipfs/zb2rhYFZCta7ehNRcVQ2PHvPdMReeU1U91rUtyv2qREBiRDfQ) which is `/openbazaar-go:0.7.3/'ob1:v0.7.2-rc3d'`.

Where can I find more information on those ob1 user agents?

**Comment by cpacia** [comment]
The user agent is configurable via a command like option. @tyler-smith might be putting that in there. Note to tyler, the version is redundant there as the command line option keeps the version and appends whatever you enter.
