### ISSUE TITLE
OB1 and Duo gateways behave differently

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#640]
I have configured the Duo gateway as per [the instructions](https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/gateway.md) but they behave differently with regards to 404s. The OB1 gateways returns a 404 immediately (see [here](http://gateway.ob1.io/ipfs/zdj7Wiy5Q5x1d6Ga9Ct3JAbWYDRqS7UPzvoxfmirF2zd2kPsb)) whereas the Duo gateway hangs indefinitely (see [here](http://gateway.duosear.ch/ipfs/zdj7Wiy5Q5x1d6Ga9Ct3JAbWYDRqS7UPzvoxfmirF2zd2kPsb)).

Any idea as to what may be going wrong with the Duo gateway?

**Comment by JustinDrake** [comment]
Hum, actually they do behave the same. I should use the `https://` link for gateway.ob1.io and it hangs:

https://gateway.ob1.io/ipfs/zdj7Wiy5Q5x1d6Ga9Ct3JAbWYDRqS7UPzvoxfmirF2zd2kPsb

**Comment by hoffmabc** [comment]
I see you closed this, but what was the resolution? That they both should hang? Or did you find something else out?
