### ISSUE TITLE
Better ships to logic

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#641]
For many listings most of the bulky data is `shipsTo`. (See example below.) I have a couple suggestions to make it slimmer:

1) Use country codes, not the string label
2) Use "does not ship to" for the (majority of) cases when no countries, or just a handful of countries, are excluded

> [map[thumbnail:map[tiny:zb2rhnJYu7DFbJDPZPEdZzucMFgHzdcSLsRf8trhyir97JAbK small:zb2rhZg3Di8dex85HLSqyjn1k5nhXg4uaj6yzYEi6bF6wqmS5 medium:zb2rhoPcMZ9MjW8WvTiGpdhGhNfNKGKoa2qcxBKJhVizagHrE] shipsTo:[] freeShipping:[] language: ratingCount:0 slug:double-your-money contractType:SERVICE averageRating:0 categories:[] price:map[amount:1e+06 currencyCode:BTC] nsfw:false description:<br><p><p style="text-align: center;"><span style="background-color: initial; color: inherit; font-size: 1.4rem; letter-spacing: 0px;">Send me money, and I'll s hash:zb2rho6JS3rTsuB8PaMU9NBo3fUo3TEF3SFQJNMdC9FhJDCpn title:Double your money!] map[ratingCount:0 description:<div>A car. One previous owner. It had a great mileage! Leaks no oil at all (it doesn't contain any oil, but still). Great ride if you like the feeling of wind  shipsTo:[AFGHANISTAN ALAND_ISLANDS ALBANIA ALGERIA AMERICAN_SAMOA ANDORRA ANGOLA ANGUILLA ANTIGUA ARGENTINA ARMENIA ARUBA AUSTRALIA AUSTRIA AZERBAIJAN BAHAMAS BAHRAIN BANGLADESH BARBADOS BELARUS BELGIUM BELIZE BENIN BERMUDA BHUTAN BOLIVIA BONAIRE_SINT_EUSTATIUS_SABA BOSNIA BOTSWANA BOUVET_ISLAND BRAZIL BRITISH_INDIAN_OCEAN_TERRITORY BRUNEI_DARUSSALAM BULGARIA BURKINA_FASO BURUNDI CABO_VERDE CAMBODIA CAMEROON CANADA CAYMAN_ISLANDS CENTRAL_AFRICAN_REPUBLIC CHAD CHILE CHINA CHRISTMAS_ISLAND COCOS_ISLANDS COLOMBIA COMOROS CONGO_REPUBLIC CONGO COOK_ISLANDS COSTA_RICA COTE_DIVOIRE CROATIA CUBA CURACAO CYPRUS CZECH_REPUBLIC DENMARK DJIBOUTI DOMINICA DOMINICAN_REPUBLIC ECUADOR EGYPT EL_SALVADOR EQUATORIAL_GUINEA ERITREA ESTONIA ETHIOPIA FALKLAND_ISLANDS FAROE_ISLANDS FIJI FINLAND FRANCE FRENCH_GUIANA FRENCH_POLYNESIA FRENCH_SOUTHERN_TERRITORIES GABON GAMBIA GEORGIA GERMANY GHANA GIBRALTAR GREECE GREENLAND GRENADA GUADELOUPE GUAM GUATEMALA GUERNSEY GUINEA GUINEA_BISSAU GUYANA HAITI HEARD_ISLAND HOLY_SEE HONDURAS HONG_KONG HUNGARY ICELAND INDIA INDONESIA IRAN IRAQ IRELAND ISLE_OF_MAN ISRAEL ITALY JAMAICA JAPAN JERSEY JORDAN KAZAKHSTAN KENYA KIRIBATI NORTH_KOREA SOUTH_KOREA KUWAIT KYRGYZSTAN LAO LATVIA LEBANON LESOTHO LIBERIA LIBYA LIECHTENSTEIN LITHUANIA LUXEMBOURG MACAO MACEDONIA MADAGASCAR MALAWI MALAYSIA MALDIVES MALI MALTA MARSHALL_ISLANDS MARTINIQUE MAURITANIA MAURITIUS MAYOTTE MEXICO MICRONESIA MOLDOVA MONACO MONGOLIA MONTENEGRO MONTSERRAT MOROCCO MOZAMBIQUE MYANMAR NAMIBIA NAURU NEPAL NETHERLANDS NEW_CALEDONIA NEW_ZEALAND NICARAGUA NIGER NIGERIA NIUE NORFOLK_ISLAND NORTHERN_MARIANA_ISLANDS NORWAY OMAN PAKISTAN PALAU PANAMA PAPUA_NEW_GUINEA PARAGUAY PERU PHILIPPINES PITCAIRN POLAND PORTUGAL PUERTO_RICO QATAR REUNION ROMANIA RUSSIA RWANDA SAINT_BARTHELEMY SAINT_HELENA SAINT_KITTS SAINT_LUCIA SAINT_MARTIN SAINT_PIERRE SAINT_VINCENT SAMOA SAN_MARINO SAO_TOME SAUDI_ARABIA SENEGAL SERBIA SEYCHELLES SIERRA_LEONE SINGAPORE SINT_MAARTEN SUCRE SLOVAKIA SLOVENIA SOLOMON_ISLANDS SOMALIA SOUTH_AFRICA SOUTH_SUDAN SPAIN SRI_LANKA SUDAN SURINAME SVALBARD SWAZILAND SWEDEN SWITZERLAND SYRIAN_ARAB_REPUBLIC TAIWAN TAJIKISTAN TANZANIA THAILAND TIMOR_LESTE TOGO TOKELAU TONGA TRINIDAD TUNISIA TURKEY TURKMENISTAN TURKS_AND_CAICOS_ISLANDS TUVALU UGANDA UKRAINE UNITED_ARAB_EMIRATES UNITED_KINGDOM UNITED_STATES URUGUAY UZBEKISTAN VANUATU VENEZUELA VIETNAM VIRGIN_ISLANDS_BRITISH VIRGIN_ISLANDS_US WALLIS_AND_FUTUNA WESTERN_SAHARA YEMEN ZAMBIA ZIMBABWE] language: averageRating:0 hash:zb2rhcVuWGx96jTKd9o9UFcYhKNaaGAQnSwkAht7d8RxSZCkL slug:car contractType:PHYSICAL_GOOD nsfw:false thumbnail:map[tiny:zb2rhbP5Uc74krRq2p6gParDFSKu6yJoYGDu9BmHcUNfZVTnK small:zb2rhkDnv3eShKvNoqFpmjAxMmG8qnjAAzpzpypQ5ebcKnPxw medium:zb2rhbAgMLvNQeT1uM2tMeueZ6uNwsLcu86x2dTvCNbzLwNdS] freeShipping:[] title:Car categories:[] price:map[currencyCode:DKK amount:2.5e+07]] map[nsfw:false contractType:PHYSICAL_GOOD thumbnail:map[small:zb2rhfu9ZfB27TBq4gxjqmewGS7wCwZ5jGRnCrt4c2LsMLqfK medium:zb2rhgq1DgbSLyNNCTrCMbgjAd8cLctJtEbE2L1hPbnafa1bX tiny:zb2rhd1ppDWJZgzBXX7tLXVcUPAshUqvJFt7HEYUincLEPkxx] averageRating:5 title:Used record. Good music! categories:[] description:Used record. Almost no scratches! Plays perfectly! In such a good condition, even your CD player will play it!<div></div> ratingCount:4 slug:used-record.-good-music shipsTo:[AFGHANISTAN ALAND_ISLANDS ALBANIA ALGERIA AMERICAN_SAMOA ANDORRA ANGOLA ANGUILLA ANTIGUA ARGENTINA ARMENIA ARUBA AUSTRALIA AUSTRIA AZERBAIJAN BAHAMAS BAHRAIN BANGLADESH BARBADOS BELARUS BELGIUM BELIZE BENIN BERMUDA BHUTAN BOLIVIA BONAIRE_SINT_EUSTATIUS_SABA BOSNIA BOTSWANA BOUVET_ISLAND BRAZIL BRITISH_INDIAN_OCEAN_TERRITORY BRUNEI_DARUSSALAM BULGARIA BURKINA_FASO BURUNDI CABO_VERDE CAMBODIA CAMEROON CANADA CAYMAN_ISLANDS CENTRAL_AFRICAN_REPUBLIC CHAD CHILE CHINA CHRISTMAS_ISLAND COCOS_ISLANDS COLOMBIA COMOROS CONGO_REPUBLIC CONGO COOK_ISLANDS COSTA_RICA COTE_DIVOIRE CROATIA CUBA CURACAO CYPRUS CZECH_REPUBLIC DENMARK DJIBOUTI DOMINICA DOMINICAN_REPUBLIC ECUADOR EGYPT EL_SALVADOR EQUATORIAL_GUINEA ERITREA ESTONIA ETHIOPIA FALKLAND_ISLANDS FAROE_ISLANDS FIJI FINLAND FRANCE FRENCH_GUIANA FRENCH_POLYNESIA FRENCH_SOUTHERN_TERRITORIES GABON GAMBIA GEORGIA GERMANY GHANA GIBRALTAR GREECE GREENLAND GRENADA GUADELOUPE GUAM GUATEMALA GUERNSEY GUINEA GUINEA_BISSAU GUYANA HAITI HEARD_ISLAND HOLY_SEE HONDURAS HONG_KONG HUNGARY ICELAND INDIA INDONESIA IRAN IRAQ IRELAND ISLE_OF_MAN ISRAEL ITALY JAMAICA JAPAN JERSEY JORDAN KAZAKHSTAN KENYA KIRIBATI NORTH_KOREA SOUTH_KOREA KUWAIT KYRGYZSTAN LAO LATVIA LEBANON LESOTHO LIBERIA LIBYA LIECHTENSTEIN LITHUANIA LUXEMBOURG MACAO MACEDONIA MADAGASCAR MALAWI MALAYSIA MALDIVES MALI MALTA MARSHALL_ISLANDS MARTINIQUE MAURITANIA MAURITIUS MAYOTTE MEXICO MICRONESIA MOLDOVA MONACO MONGOLIA MONTENEGRO MONTSERRAT MOROCCO MOZAMBIQUE MYANMAR NAMIBIA NAURU NEPAL NETHERLANDS NEW_CALEDONIA NEW_ZEALAND NICARAGUA NIGER NIGERIA NIUE NORFOLK_ISLAND NORTHERN_MARIANA_ISLANDS NORWAY OMAN PAKISTAN PALAU PANAMA PAPUA_NEW_GUINEA PARAGUAY PERU PHILIPPINES PITCAIRN POLAND PORTUGAL PUERTO_RICO QATAR REUNION ROMANIA RUSSIA RWANDA SAINT_BARTHELEMY SAINT_HELENA SAINT_KITTS SAINT_LUCIA SAINT_MARTIN SAINT_PIERRE SAINT_VINCENT SAMOA SAN_MARINO SAO_TOME SAUDI_ARABIA SENEGAL SERBIA SEYCHELLES SIERRA_LEONE SINGAPORE SINT_MAARTEN SUCRE SLOVAKIA SLOVENIA SOLOMON_ISLANDS SOMALIA SOUTH_AFRICA SOUTH_SUDAN SPAIN SRI_LANKA SUDAN SURINAME SVALBARD SWAZILAND SWEDEN SWITZERLAND SYRIAN_ARAB_REPUBLIC TAIWAN TAJIKISTAN TANZANIA THAILAND TIMOR_LESTE TOGO TOKELAU TONGA TRINIDAD TUNISIA TURKEY TURKMENISTAN TURKS_AND_CAICOS_ISLANDS TUVALU UGANDA UKRAINE UNITED_ARAB_EMIRATES UNITED_KINGDOM UNITED_STATES URUGUAY UZBEKISTAN VANUATU VENEZUELA VIETNAM VIRGIN_ISLANDS_BRITISH VIRGIN_ISLANDS_US WALLIS_AND_FUTUNA WESTERN_SAHARA YEMEN ZAMBIA ZIMBABWE] language: hash:zb2rhhxwyxjeF5vrZfsgUS6nywujwjUakKvEGppmsmhDMLvUf price:map[currencyCode:DKK amount:20000] freeShipping:[]]]

**Comment by cpacia** [comment]
Client switched to ALL
