### ISSUE TITLE
Problems with Tor

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#660]
I'm trying to run OpenBazaaar with Tor for the first time. I have TorBrowser running in the background, and I've edited the config file to add the line `"/onion/erhkddypoy6qml6h:4003"` per the [instructions here](https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/tor.md).

I get the following error:

```
Justins-MacBook-Pro:openbazaar-go justin$ openbazaar-go start --tor
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.9.0 starting...
17:53:39.359 [Execute] [ERROR] Authentication failed: invalid (empty) COOKIEFILE
Authentication failed: invalid (empty) COOKIEFILE
```

What could I be doing wrong?

**Comment by rmisio** [comment]
You need to set-up Tor to use a password and then provide that unhashed password to the OB config.

https://github.com/OpenBazaar/openbazaar-desktop/wiki/Tor-Setup

Tor can only be connected to in an authenticated manner on Mac and Windows. On Linux, you could connect without authentication.

**Comment by JustinDrake** [comment]
I've edited the `torrc` file per the instructions. Now Tor will not launch:

<img width="447" alt="screen shot 2017-09-05 at 18 37 34" src="https://user-images.githubusercontent.com/731743/30074420-63c4341e-9269-11e7-97ce-8810f02063db.png">

**Comment by rmisio** [comment]
Sorry, I've never seen that one. I do notice that in my `torrc`, I don't have an entry for the `ControlPort`. I think for auth purposes, those other two lines are most important. Maybe try that?

**Comment by JustinDrake** [comment]
I managed to launch Tor by removing the `ControlPort` line. How can I tell from the UI that it is using Tor? Is there some sort of visual flag that confirms the setup?

**Comment by rmisio** [comment]
There would be an onion icon in the address bar. It will show up if both the server and client are configured to use tor. To configure the client, check Use Tor in the server configuration:

![image](https://user-images.githubusercontent.com/794517/30075191-f036e536-9228-11e7-9e9f-f96c69a1492a.png)

There's also a Tor password field there. You could put whatever in there if using the stand-alone client. That field is really only needed for the bundled app and it's a bug that it even shows up for the stand-alone app.

**Comment by JustinDrake** [comment]
Hum, I'm not seeing the onion icon in the address bar. Could you show a screenshot of what it's meant to look like? I made sure to tick "Use Tor", and I entered the password I hashed earlier on.

![screen shot 2017-09-05 at 18 58 29](https://user-images.githubusercontent.com/731743/30075272-56609026-926c-11e7-88f6-4226e061132e.png)

**Comment by rmisio** [comment]
![image](https://user-images.githubusercontent.com/794517/30075436-33f0d952-922a-11e7-93c4-b287186b3a56.png)

If you're not seeing it, check the response of the ob/config api call. Tor should be `true`.

![image](https://user-images.githubusercontent.com/794517/30075456-51a11886-922a-11e7-9959-7e66b953ff9f.png)

Other than that, if the server configuration for your client has 'Use Tor' checked, then the indicator should show up.

**Comment by scarar** [comment]
How do you get OpenBazaar 2.0 go-server to run on Tor with CA installed on server and using Mac client to edit the store? Because I'm unable to contact due to websocket error. Has anyone discovered any IP leakages?

**Comment by cpacia** [comment]
> Has anyone discovered any IP leakages?

Yes I fixed one the other day. May be more. Wont know until it has a full audit.

**Comment by cpacia** [comment]
Closing as I don't think there's an issue running it

**Comment by vandelay87** [comment]
I cannot get this working, it always fails to connect:

`Authentication failed: invalid (empty) COOKIEFILE`

**Comment by rmisio** [comment]
@vandelay87 You need to configure your Tor daemon to use a password and then provide that password in the OB client.

This guide should help you:
https://github.com/OpenBazaar/openbazaar-desktop/wiki/Tor-Setup

**Comment by vandelay87** [comment]
I just seen your comment as I was editing mine. Thanks for the info dude, all good now.
