### ISSUE TITLE
Notifications Returns the Wrong Avatar Images

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#661]
When ob/notifications?limit=4 is called, the first notification has the following data:

```
"notification": {
                "buyerHandle": "",
                "buyerId": "QmczPH7Pf7EC67eahRHXLYxTwo3nxYx4W7qEWznsNtCbm4",
                "notificationId": "Qmc5o6MvnNSDkmkLQKWjzFwYQCaTaLvrvThqrL2BmtFisA",
                "orderId": "QmeSycbLuUGfkZs4UcQ4YqzpxSbP9H2EN7KTRkuSB24kdU",
                "slug": "pixel-art-12-x-12",
                "thumbnail": {
                    "small": "zb2rhbJ2J25RgLBoM38fP1GTvhNBtfWr22gLptCJmmaV1wvMY",
                    "tiny": "zb2rhesRsZ1fvcYTqh4bv6ZtRBho3xtPGJAY9FmMZXbaXpRLm"
                },
                "title": "Pixel Art 12 x 12",
                "type": "order"
            },
            "read": true,
            "timestamp": "2017-09-05T16:28:09-04:00"
```

The thumbnail images are for the seller's avatar, not the buyer's.

This happens for every notification of a purchase from that buyer.

![image](https://user-images.githubusercontent.com/1584275/30082453-dd004a9a-9258-11e7-84c0-b607bbb26a7d.png)

**Comment by cpacia** [comment]
Pretty sure this is because the listing uses that image for it's product images. It's not supposed to display an avatar there but rather the product image.

**Comment by cpacia** [comment]
![image](https://user-images.githubusercontent.com/4504708/30086536-84c450d6-9269-11e7-8c81-82c917935448.png)

**Comment by jjeffryes** [comment]
LOL. You're right. That shows me to not use the same image for the listing and avatar.
