### ISSUE TITLE
Server sending wrong timestamp to client

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-go#664]
I'm replicating this issue first opened on client repository (in https://github.com/OpenBazaar/openbazaar-desktop/issues/757):

v.2.0.9

This happens when a sale is done with vendor offline.

When vendor goes online again the following notification appears: 
![notification](https://user-images.githubusercontent.com/10789865/30000679-12dbcd2a-904b-11e7-8c5e-8440ee3b6908.png)

I understand that it means that notification has just arrived a few seconds ago, but when you read the sentence it seems that someone has just bought something. On this case, customer had bought 4 days before.

![pokemon](https://user-images.githubusercontent.com/10789865/30000684-379e9322-904b-11e7-98a3-9dce90e648f5.png)

**Comment by cpacia** [comment]
I guess this is a broader issue of how notifications are supposed to be displayed. Currently the notification list is sorted by timestamp. So I put a different timestamp on the notification it risks going down farther in the list and having the user miss it. @morebrownies
