### ISSUE TITLE
Server Returns Wrong Number of Confirmations

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#666]
When I call /wallet/transactions/?limit=25, one transaction is returned, which is correct, but the confirmations are zero.

When the same transaction is viewed on blockchain.info, the confirmations are 17.

https://blockchain.info/tx/8124ca88a8ce91cbd2d232c1300ef86cb66e6e402ece706573d7ed69e4339b9a

This has been observed on 3 different nodes, on 2 different computers.

**Comment by cpacia** [comment]
Has it been the same transaction and database on three different nodes and computers or is it separate issues?

**Comment by jjeffryes** [comment]
I have seen it on 3 nodes, A, B, and C.

Node A, there is an outgoing transaction for 0.00180035btc. It shows 0 confirmations, but should have 300.
https://blockchain.info/tx/7801397d96682426b61eb763a365bfb2dc4454c8a26c3484bdba5af091a78b82

I see an incoming transaction for the same amount of btc around the same time, with the right number of confirmations.
https://blockchain.info/tx/7bfdfebc32fe9da56379511bb02ae6d23ecfa75614739fda9ee1b6b117815c1e

![image](https://user-images.githubusercontent.com/1584275/30167431-5ccfb33a-93b4-11e7-9484-6fdb20916c2a.png)


Node B, it's an outgoing transaction for 0.00189213btc, with 0 confirmations, it should have 297.
https://blockchain.info/tx/f7c4e4369f8c24104f59ac3290734e6de7fa45156ec9c33b322af62738c4b6d1

I also see an incoming transaction for the same amount with the right number of confirmations.
https://blockchain.info/tx/c67b1e607f98f27b551330f628026bae0ef046dd57635b39f1548e9b27f9ae23

 
Node C looks like it fixed itself overnight after a resync. Resyncing didn't help the two nodes above.

The matching in and out transactions seems significant, what does that indicate?

**Comment by cpacia** [comment]
This would be a bug to file in the spvwallet repo. But in general I'm not sure what would cause this other than a syncing error. Logs would help.

**Comment by jjeffryes** [comment]
I'll send you the logs.

**Comment by cpacia** [comment]
Hopefully fixed now.
