### ISSUE TITLE
Chat Message Delayed if Vendor is Offline

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#669]
If ob/chat is called at the end of a purchase for an offline vendor, the server response to the buyer is correct.

When the same buyer calls ob/chatmessages to retrieve the messages for that order, the previous message they sent is not returned by the server (the response is []).

If ob/chatmessages is called a few minutes later, the buyer can see their own message.

A node should be able to retrieve their own messages sent to an offline other party immediately.

(if both nodes are online, the chat messages can be retrieved as expected)

**Comment by cpacia** [comment]
Fixed with #672
