### ISSUE TITLE
ANY instructions that actually work for rpi?

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/openbazaar-go#674]
Installed [Raspbian Stretch Lite](https://www.raspberrypi.org/downloads/raspbian/), did all the initial config, enabled SSH, got it on my network, logged into SSH, tried  openbazaar-go/docs/install-linux.md instructions. go1.7.1.linux-amd64 threw some couldn't execute error when I did `go get github.com/OpenBazaar/openbazaar-go`, so I switched to https://freedomnode.com/blog/80/how-to-install-and-configure-new-openbazaar-2-0-on-linux-and-mac-os-x after resetting ~/.profile to default with `cp /etc/skel/.profile ~/`
```
pi@pi:~ $ go version
go version go1.8.3 linux/arm
pi@pi:~ $ echo "export GOPATH=$HOME/go" >> .profile
pi@pi:~ $ echo "export PATH=$PATH:/usr/local/go/bin" >> .profile
pi@pi:~ $ source ~/.profile
pi@pi:~ $ go get github.com/OpenBazaar/openbazaar-go
go install runtime/internal/atomic: open /usr/local/go/pkg/linux_arm/runtime/internal/atomic.a: permission denied
pi@pi:~ $ 
```

Wondering if this is an easy fix or how to purge every trace of go from the filesystem to start from scratch, without reinstalling Stretch Lite.

**Comment by hoffmabc** [comment]
Well that above has lead to a permissions error it seems. 

Looks like something up with Debian perhaps?
https://github.com/golang/go/issues/15433

https://groups.google.com/forum/#!msg/golang-dev/BcSBfR2CVo8/ArTy2n7WCAAJ

**Comment by cpacia** [comment]
I ordered a pi zero the other day. My plan is to just use the arm-5 binary rather than trying to build it on there.

**Comment by TheButterZone** [comment]
... so nothing's compatible with the CanaKit Pi 3 I got as a gift? Their discussions looked like they petered out in 2016.

**Comment by TheButterZone** [comment]
https://github.com/OpenBazaar/openbazaar-go/pull/676

**Comment by cpacia** [comment]
Merged. Also note you can just download the arm-5 binary from releases. This is what I did and it ran on a pi zero no problem.

**Comment by IzzySoft** [comment]
@cpacia I just downloaded the arm-5 binary to my BananaPi (running Bananian/Debian Jessie). Trying to start it, all I get to see is an error:

    $ ls -l
    -rwxr--r-- 1 ob ob 59082612 May  2 19:07 openbazaar-go-linux-arm-5
    $ ./openbazaar-go-linux-arm-5 -h
    bash: ./openbazaar-go-linux-arm-5: No such file or directory

Note that the binary is located in the directory I'm in, and even auto-complete worked for the file name (so it obviously **is** there). The file is owned by the "current user" and got a `chmod 0744` (so the user can execute it). What am I missing here? Did I understand you wrong that the binary is the only thing I'd need to download – and simply make it executable and run it?

(side-note: I'm using Gitea (which is also written in Go) on the very same Pi the very same way (i.e. just downloading the binary and running it), though that's an arm-7 binary. But AFAIK ARM is "backward compatible", isn't it?)
