### ISSUE TITLE
Don't use magic number for slug length

### ISSUE THREAD

**Issue by tyler-smith** [OpenBazaar/openbazaar-go#678]
https://github.com/OpenBazaar/openbazaar-go/commit/3a127d38283288904a49d3ac0b063b8bd235598b#diff-594684f11e1137a78e9e52cdecdc7e31

I have no idea why we subtract 5. At worst we need a comment, but we should ideally have a constant for it. I can make the change, but I need the context @cpacia.

**Comment by cpacia** [comment]
done
