### ISSUE TITLE
Stress tests and integration tests

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#68]
[Many people](https://www.reddit.com/r/OpenBazaar/comments/4wm3sq/why_is_it_so_difficult_to_sell_something_on/d683p3p), including myself, felt that OpenBazaar-Server was/is very buggy (the reason I pinpoint OpenBazaar-Server is that the stability bugs would manifest in headless mode also).

I've tried reporting such stability issues (for example [here](https://github.com/OpenBazaar/OpenBazaar-Server/issues/412) on May 22). That particular report (which IMO should have been top-priority) was never replied to, categorised or prioritised. For similar reports from me and others, the responses were along the lines of "can't reproduce", "not enough information", "help wanted".

IMO, the stability issues of OB1.0 are killing OB1.0, and those can be attributed to two things:

1. (technical) Extreme lack of rigorous testing, in particular stress testing (and integration testing). The superficial/easy-to-fix bugs were fixed very quickly, but little effort was done to find and understand the bugs that are subtle, hard-to-reproduce, take time to trigger, affect only some platforms, etc. Those are found with rigorous stress tests and integration tests.

2. (managerial) Releases were rushed. The non-OB1 community had very little time to review the release candidates (usually just a few days), and there's no formal review process (e.g. like Bitcoin's `ACK`, `NACK`, `utACK` and `Concept ACK`). Also, the developers should test their code as they write it. Testing is too important to offload to volunteers after the fact.

I hope my rant can help improve development and release processes for OB2.0. I will personally take on some of the testing debt that `openbazaar-go` has started to accumulate.

**Comment by cpacia** [comment]
> but little effort was done to find and understand the bugs that are subtle, hard-to-reproduce, take time to trigger, affect only some platforms, etc. 

Of course, that isn't true. I spent hours upon ours staring at the code trying to track down memory and cpu issues. You need to consider as well that it was basically just me writing/debugging that code on strict time deadlines, while also working on this code base at the same time. 

Thankfully, I'm not the only person working on it anymore. If you include the ipfs team, we have four or five full time developers working on the codebase. So it should be much improved. 

Please feel free to contribute resources as well if you want to build on top of it.

**Comment by JustinDrake** [comment]
> I spent hours upon hours staring at the code trying to track down memory and cpu issues.

@cpacia Ok, understood. My suggestion for OB2.0 is to invest time in a stress testing framework. It will make it much easier to find bugs than staring at the code. I'm happy to contribute to that. It can be something easy like "instantiate `n` nodes and make them send a random message to `x%` of the nodes every `m` seconds". My guess is that bugs will start manifesting themselves in minutes, bypassing hours of staring.

**Comment by hoffmabc** [comment]
This is something that came up in one of our team meetings the other day. Do you have any scripts already that we can use as a baseline or process recommendations here? I was thinking about a few tools I've used in the past but hadn't started to run with this yet.

**Comment by JustinDrake** [comment]
@hoffmabc Ideally we want to test 100+ nodes communicating with each other at high speed, submitting listings, etc. More likely than not, we're going to need a cluster of machines for that. I believe the most professional way of doing that is with Docker Swarm and Docker Machine (see [here](https://docs.docker.com/swarm/provision-with-machine/). My preference would be to load up DigitalOcean droplets.

Here's a possible roadmap:

1. Figure out how to instantiate a single IPFS node (I'm still at this stage!)
2. Go two IPFS nodes on a single machine to talk to each other. Write a few stress tests between these two.
3. Understand the max number of test IPFS nodes that can fit in a droplet (say `n`) and build a docker container for that.
4. Get two droplets (each with `n` nodes from the container) to talk to each other and write more stress tests
5. Automate the provision of droplets with Docker Machine and Docker Swarm to get to 100+ nodes in 3 different continents
6. Use the above infrastructure as a basis for a public testnet?

**Comment by hoffmabc** [comment]
@cpacia have we gotten #2 to work yet?

**Comment by cpacia** [comment]
Should just be a matter of using two different repo directories.

**Comment by cpacia** [comment]
btw here's for tracking ipfs test coverage https://github.com/ipfs/go-ipfs/issues/3053

**Comment by cpacia** [comment]
I created the qa package to build out integration tests.
