### ISSUE TITLE
Saving Listings Strips Attributes from the Description

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#681]
When the listing description is saved, HTML tags are preserved, but any style attributes are removed.

If we can, we should preserve those, since the rich text editor uses them for formatting. 

If we can't, we'll need to take those options out of the text editor.

See https://github.com/OpenBazaar/openbazaar-desktop/issues/820

**Comment by cpacia** [comment]
What tags are we talking about specifically?

**Comment by cpacia** [comment]
The sanitizer has a comment that says this:
```
// "style" is not permitted as we are not yet sanitising CSS and it is an
// XSS attack vector
```

**Comment by jjeffryes** [comment]
If style is an attack vector, we'll either have to live without it or find some other way to do it.

**Comment by jjeffryes** [comment]
Closing as something we're not going to change for now.
