### ISSUE TITLE
Don't Allow Purchases if Vendor is False

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#683]
If a user has set their vendor flag to false, and the purchase api is called, an error should be returned instead of allowing the purchase.

**Comment by cpacia** [comment]
Done last release

**Comment by jjeffryes** [comment]
This does not appear to be fixed. On the latest master, I can call purchase on a listing for a vendor that is set to false, and the purchase call returns normally, and the transaction appears when the purchases api is called.

This has introduced a new, serious bug, as the seller's sales api does not return the transaction. I was able to make 2 purchases that appear for the buyer, but not the seller.

**Comment by jjeffryes** [comment]
One purchase when the vendor was false was successfully blocked (returned an error), but a second one went through. This resulted in the payment going out, but the transaction doesn't show for either party, which leaves the buyer's funds stuck.

This is the transaction https://blockchain.info/tx/38e3a51676aa15595dadf48af2a81aa33ef284948ff5bdeb00e2fbdaf1565777

**Comment by jjeffryes** [comment]
The issue appears to be that if the buyer node thinks it was an offline transaction (in one case the vendor node was online when the transaction went through, I'm guessing the buying node thought it was offline incorrectly) the transaction is not returned by the purchases API, which mean the buyer cannot cancel the payment.

**Comment by jjeffryes** [comment]
After resyncing a few times, the seller node now shows the second transaction as Awaiting Payment, even though it was paid for, but the buyer node does not.

One additional wrinkle: if I have the orderID of the purchase, I can load it from the order API correctly, it just doesn't get returned by the purchases API.

**Comment by jjeffryes** [comment]
Looks like this was a combination of slow syncing and unexpected (but intended) behavior. 

The transactions got marked as read, but were the only read transactions for that node, which pushed them to the end of the list and off the page, so they weren't visible, and I didn't check there because all the other transactions were ordered by time.

The seller can still see only 1 out of 3 of the transactions. That may be due to the other issues with syncing and offline messages.
