### ISSUE TITLE
Offline chat messages are not received in order

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-go#690]
Win7 64 bits v2.0.11

From client A (online) I've sent 4 chat messages to client B (offline):
"A"
"B"
"C"
"D"

When Client B connected it received the following:
"B"
"A"
"D"
"C"

**Comment by cpacia** [comment]
Not sure how that would happen as it uses the timestamp from when the message was sent when saving offline chat messages.

**Comment by cpacia** [comment]
I looks to me like what's happening is the timestamp rounds to the nearest second. So if you sent all those messages within a one second time frame then they would just appear in random order. 

Can you confirm that's what happened?

Not sure if there's a need for more precision there or not.

**Comment by rhcastilhos** [comment]
![chatorder](https://user-images.githubusercontent.com/10789865/30673892-b5acb9c4-9e4c-11e7-88fb-862cc396613c.png)

If you send messages like 30 seconds apart, they arrive in order. 

If you send like 15 seconds a part, they sometimes arrive in order, sometimes don't.

However, when you close client and open it again, they always start to appear in correct order (see image above, showing chat before and after closing client).
