### ISSUE TITLE
Profile Ratings Change to Zero

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#696]
We've had reports from users that updating their profile data causes their stats.averageRating to change to zero when they have listings with ratings.

This can be seen at ob://QmY8gzdEHTTE1ePcGDEjQuGgZXNz7MeWQWFF8mvy8FKJXj/store

They have one listing with a 5 star rating, This is the only rating they have on a listing. This was being shown in their profile correctly, but after updating the name of their store, the profile API returns stats.averateRating: 0.

**Comment by cpacia** [comment]
Can't replicate

**Comment by jjeffryes** [comment]
You don't see it if you go to that store?

**Comment by morebrownies** [comment]
I have the same issue: ob://QmYTRdwd4nhBRJX5QLNCbKxzPNrNaGCUVnvhFMK1tm3fhz/store

It has been like this for weeks. I've republished many times.

**Comment by cpacia** [comment]
I see it on his store but I can't replicate the failure when leaving a rating.

**Comment by jjeffryes** [comment]
I found the source of this bug, it's on the client due to postCount being sent back in a profile PUT, which apparently resets the stats data returned from the server.

I will put in a client fix, is this the expected behavior if stats is returned as:
```
stats: {
  postCount: 0,
}
```
With no other values?
