### ISSUE TITLE
Error pollutes shell in red

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#70]
See screenshot. I got an error and the my shell went red.

![screen shot 2016-08-08 at 19 03 30](https://cloud.githubusercontent.com/assets/731743/17488696/dc354a0a-5d9a-11e6-9d18-99fece9af8a6.png)

**Comment by cpacia** [comment]
I think that's because it exited the app. Typically the next print statement changes the color so it looks like on this operation there was no next print statement so it stayed in red. Maybe adding a print statement on exit might change it back. Not sure.

**Comment by hoffmabc** [comment]
Can this be closed @cpacia ?

**Comment by JustinDrake** [comment]
Actually, still happening. See screenshot.

![screen shot 2016-11-18 at 13 29 40](https://cloud.githubusercontent.com/assets/731743/20431662/26973e3a-ad93-11e6-868a-1a6c9ba7c194.png)

**Comment by hoffmabc** [comment]
I think this was a no fix close.

**Comment by JustinDrake** [comment]
I originally closed the issue because I thought it was fixed. But actually not, still there. My bad.

**Comment by jjeffryes** [comment]
Is this issue still active?

**Comment by tyler-smith** [comment]
It still happens, yes.

**Comment by tyler-smith** [comment]
To be more explicit, whatever log color was used last persists after shutting down the server. White, blue, red, whatever.

**Comment by hoffmabc** [comment]
@tyler-smith is this easily fixable?
