### ISSUE TITLE
If you spend a portion of unconfirmed funds, the remainder immediately shows up in the confirmed balance

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#700]
When I spend unconfirmed funds, the portion of unconfirmed funds I don’t spend seem to be getting added to the confirmed amount immediately even though the transaction that brought them in remains unconfirmed.

For example, here’s my wallet where I had $7.93 and I sent in $39.64, the latter being unconfirmed. Then, I spend $10, which would be the $7.93 from confirmed and the remainder plus the fee coming out of unconfirmed. As soon as I made this transaction, my confirmed balance jumped up (even though that unconfirmed transaction still had zero confirmations). It looks like it jumped up by the amount that wasn’t spent.

![image](https://user-images.githubusercontent.com/794517/30759819-7f05ed82-9f8c-11e7-8072-7d7087f6e15a.png)

![image](https://user-images.githubusercontent.com/794517/30759826-89b80986-9f8c-11e7-9f9a-9c7a1afc6ee0.png)

**Comment by cpacia** [comment]
Hasn't been an issue since.
