### ISSUE TITLE
can't connect to tor

### ISSUE THREAD

**Issue by Zerophase** [OpenBazaar/openbazaar-go#704]
I tried following the instructions for running with tor, and can't find the server. 

I also get this error message:
> Sep 23 04:18:30 Odin openbazaard-next[6574]: ________                      __________
> Sep 23 04:18:30 Odin openbazaard-next[6574]: \_____  \ ______   ____   ____\______   \_____  _____________
> Sep 23 04:18:30 Odin openbazaard-next[6574]:  /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__
> Sep 23 04:18:30 Odin openbazaard-next[6574]: /    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __
> Sep 23 04:18:30 Odin openbazaard-next[6574]: \_______  /   __/ \___  >___|  /______  /(____  /_____ \(____
> Sep 23 04:18:30 Odin openbazaard-next[6574]:         \/|__|        \/     \/       \/      \/      \/
> Sep 23 04:18:30 Odin openbazaard-next[6574]: OpenBazaar Server v0.9.2 starting...
> Sep 23 04:18:30 Odin openbazaard-next[6574]: 04:18:30.178 [Execute] [ERROR] Tor control unavailable
> Sep 23 04:18:30 Odin openbazaard-next[6574]: Tor control unavailable

I do have tor up and running through systemd, and if I don't edit the openbazaard-next service for launching in tor mode I can connect to my tor server and setup store listings without issues. But, none of the search providers work nor does the onion icon show up near the address bar.

**Comment by cpacia** [comment]
Not sure what OS you're using but on most of them Tor blocks access to the control port without setting up a password. Have you checked out this video? https://www.youtube.com/watch?v=3taNePaXFoE&t=3s

Very similar process for mac.

**Comment by Zerophase** [comment]
I'm running Arch Linux.

**Comment by cpacia** [comment]
You might need to edit your torrc file to open the control port and maybe set up password authentication. 

You can also use this onion endpoint http://my7nrnmkscxr32zo.onion/search/listings I think the url in the current release is broken and will be updated in the next release.

**Comment by tyler-smith** [comment]
Yes, use http://my7nrnmkscxr32zo.onion/search/listings. The vanity URL isn't available right now; I'm having issues getting it to resolve for everybody. The client should be defaulting to the new URL if it isn't already.

**Comment by Zerophase** [comment]
It's no hurries. I'm still waiting on tools for transferring stores to 2.0. Once everything is all up and running I'll be setting my store up in a Whonix vm.

**Comment by Zerophase** [comment]
Do I still need to do this step to get in through tor? https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/tor.md

**Comment by Zerophase** [comment]
Yeah, I just needed to open the control port.

**Comment by pinheadmz** [comment]
Same issue, running server headless on Raspberry Pi. How do I open the Tor control port? And should it be 4003 or 9050?
