### ISSUE TITLE
Ability to "minimize" the server and put it in standby mode

### ISSUE THREAD

**Issue by jenncloud** [OpenBazaar/openbazaar-go#706]
Ability to "minimize" the server and put it in standby mode

**Comment by cpacia** [comment]
are you referring to running only the server from the command line?

**Comment by jenncloud** [comment]
Hm, possibly...this is me translating a Twitter request that Sam thought should be added here. Our impression was the way that you can "minimize" a program and it will take up fewer resources in the background, can that be done with the server?

**Comment by cpacia** [comment]
No. It will always use the same resources if it's running.
