### ISSUE TITLE
ipfs logs getting too large

### ISSUE THREAD

**Issue by botaniver** [OpenBazaar/openbazaar-go#712]
I got 600 MB of logs at ~/.openbazaar2.0/logs in just 24h due to ipfs extensive logging. It creates several timestamped 10 MB files but does not delete the old ones.
There should be ways to:
1. Change ipfs log level.
2. Automatically delete the old logs.

**Comment by cpacia** [comment]
I think this is a permissions issue. I've run into the same thing when running on a VPS. It does have file rotation on those file and doesn't allow more than three.

**Comment by cpacia** [comment]
Definitely would be worth trying to get to the root of the problem though.

**Comment by botaniver** [comment]
This problem appears when the server gets into an erroneous state where it doesn't accept new client connections and keeps outputing `http: Accept error: accept tcp4 0.0.0.0:9005: accept4: too many open files; retrying in [...]`.
After restarting openbazaar-go it deletes all the extra logs, leaving only 3 files on disk.

**Comment by cpacia** [comment]
@botaniver glad you figured that out. I think that's what is happening. 

The `too many open files` is an IPFS issue that they are away of and are trying to optimize. 

You can fix it by increasing the file descriptor limit on your system. I think what was happening to me is I was running under supervisor and didn't realize supervisor has its own file descriptor setting. 

I think changing that would fix the issue. Either way I have a PR in to add a command line option to disable file logging.

**Comment by botaniver** [comment]
> You can fix it by increasing the file descriptor limit on your system.

Indeed.
My soft limit was just 1024 and the hard limit 65536, increasing both to 500000 fixed everything. How-to at: [Increase “Open Files Limit” - EasyEngine](https://easyengine.io/tutorials/linux/increase-open-files-limit/).


You should mention this on your [installation instructions](https://github.com/OpenBazaar/openbazaar-go#install).

**Comment by cpacia** [comment]
Should be fixed with the ulimit code
