### ISSUE TITLE
No notification recevied for new sale

### ISSUE THREAD

**Issue by botaniver** [OpenBazaar/openbazaar-go#719]
A buyer made a purchase on my store and I got no notification about it. Only received a notice when the buyer opened a dispute. Here is a screenshot of my notification bar:

![ob-notifs](https://user-images.githubusercontent.com/32425691/31239771-25b4b690-a9f6-11e7-8d5b-a1c6c4316ed1.png)

This one is severe. Please take a look at it. I'm now handling a dispute when I had no idea there was a pending order.

I tried to search `~/.openbazaar2/logs/ob.log`. Found no reference to words such as "sale", "purchase" or "order".

**Comment by botaniver** [comment]
Sorry, this maybe this is the wrong repo. Should I have opened the issue at [openbazaar-desktop](https://github.com/OpenBazaar/openbazaar-desktop)?

**Comment by cpacia** [comment]
Thanks for the report. I think there has been some flakiness around offline messages due mostly do to the file descriptor issue, which we hopefully will have fixed for the new release. 

Also make sure you're able to accept incoming connections. Visit http://canyouseeme.org/ and enter port 4001. If it doesn't return `success` then you should set up port forwarding in your router.

**Comment by misbach** [comment]
I'm the moderator for this dispute. I think @rmisio has a fix for this bug that will be released in version 2.0.14.

@botaniver Did you get my responses to your messages on this dispute? Another thing you can try is closing and relaunching OB2 desktop, and that can trigger the messages to come in sometimes.

**Comment by rmisio** [comment]
> Also make sure you're able to accept incoming connections. Visit http://canyouseeme.org/ and enter port 4001. If it doesn't return success then you should set up port forwarding in your router.

When you do the test, make sure you have the OB app (at least the server) running.

**Comment by botaniver** [comment]
> do to the file descriptor issue

That may be it. I've increased my file descriptor limits on 04/10, and this order was placed on 02/10, while I was still getting the "too many open files" error.

> make sure you're able to accept incoming connections

I am. Tested just now.

> Did you get my responses to your messages on this dispute?

@misbach Got them, and got the notifications for them too. It seems that this issue really was due to the low file descriptor limits.

**Comment by cpacia** [comment]
Good to hear. I think this issue has been fixed in the new version.
