### ISSUE TITLE
AWS deployment

### ISSUE THREAD

**Issue by 13Flo** [OpenBazaar/openbazaar-go#721]
Hi there,

I'm trying to run Openbazaar-go an an AWS/EC2/Ubuntu instance, but I get the following error:

> 20:09:07.262 [Execute] [INFO] Peer ID:  QmaTVnreRs8rAbdpJXkhSzA4sC2JdaavrfUQPcWVoAzj
> 20:09:07.263 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/4001
> 20:09:07.263 [printSwarmAddrs] [INFO] Swarm listening on /ip4/127.0.0.1/tcp/9005/ws
> 20:09:07.263 [printSwarmAddrs] [INFO] Swarm listening on /ip4/172.31.30.251/tcp/4001
> 20:09:07.263 [printSwarmAddrs] [INFO] Swarm listening on /ip4/172.31.30.251/tcp/9005/ws
> 20:09:07.263 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/4001
> 20:09:07.263 [printSwarmAddrs] [INFO] Swarm listening on /ip6/::1/tcp/9005/ws
> 20:09:07.290 [newHTTPGateway] [INFO] Gateway/API server listening on /ip4/[xx.xxx.xxx.xxx]/tcp/4002
> 20:09:07.290 **[Execute] [ERROR] listen tcp [xx.xxx.xxx.xxx]:4002: bind: cannot assign requested address**

I opened TCP ports 4001, 4002 and 9005 on the AWS console (in Security Groups > Inbounds).
I'm struggling to identify the issue for several days now as I'm not a server expert.

Could anybody help me with that?

**Comment by 13Flo** [comment]
Anybody there?

**Comment by cpacia** [comment]
Are you trying to bind the gateway to 0.0.0.0?

Also make sure you do SSL and possibly restrict API access by IP for security purposes.

**Comment by 13Flo** [comment]
I assigned an Elastic IP to my instance (as far as understand, acting as a static IP) and I followed these steps:
https://freedomnode.com/blog/80/how-to-install-and-configure-new-openbazaar-2-0-on-linux-and-mac-os-x

I did:
sed -i -E "s|(\"Gateway\": \"/ip4/)127.0.0.1|\1$(dig +short myip.opendns.com @resolver1.opendns.com)|" config

And I see the right IP address in the config.

![image](https://user-images.githubusercontent.com/146405/31311317-70b0d8ae-ab5e-11e7-89fc-2fb754d6c39f.png)

Any suggestion I could try?

**Comment by 13Flo** [comment]
Thanks @cpacia

The solution was to use 0.0.0.0 as "Gateway".
SSL is not mandatory (but obviously recommended).
