### ISSUE TITLE
Irregularly, but steadily getting IPNS pinned errors.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#73]
I don't know what the exact steps to reproduce are, because it doesn't always happen. But, it has been happening enough to multiple developers that I think it requires attention. Anyhow, often times, after wiping your data and starting with a fresh server, POSTs on the profile are failing with a 'not pinned' error:

![image](https://cloud.githubusercontent.com/assets/794517/17526879/fb587c1c-5e1d-11e6-996a-58fee60d4a83.png)

Then, a subsequent fetch returns a 404, whereas a subsequent PUT fails with 'Profile already exists. Use PUT':

![image](https://cloud.githubusercontent.com/assets/794517/17526912/1ea85cc8-5e1e-11e6-8f64-1c2b130e5d99.png)

Once again, i think the crux of the problem is that the Profile is erroneously 404ing, when the file does indeed exists. It shouldn't 404 in this case, otherwise the client has no reliable way of knowing whether to onboard or not and whether to save a profile via PUT or POST.

**Comment by cpacia** [comment]
The unpin error was because you were making successive puts before the previous publish completely. I moved the unpin operation to after the publish.
