### ISSUE TITLE
sendEmail authenticates with SenderEmail instead of Username

### ISSUE THREAD

**Issue by rsnel** [OpenBazaar/openbazaar-go#747]
Hi all,

While setting up access to my mailserver (for receiving notifications), I noticed that it did not work. In the logs of the mailserver, I saw authentication attempts using SenderEmail instead of Username. (line 103 of notifier.go)

Please use the Username field for authentication, as my mailserver just expects a UNIX username, without @ in it.

Greetings,

Rik.

**Comment by cpacia** [comment]
I think you're right. I'll fix this shortly.

**Comment by rsnel** [comment]
Thanks!
