### ISSUE TITLE
Ratings API returns duplicate reviews

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#750]
This listing, which is from an app running 2.0.15, is showing duplicate reviews because the ob/ratings call gives the same review twice.

```
{
    "average": 5,
    "count": 2,
    "ratings": [
        "zb2rhjkM5GhwzbBufztNfWJp7FsBvi5JFT9WPKZrCpGXoxh7k",
        "zb2rhjkM5GhwzbBufztNfWJp7FsBvi5JFT9WPKZrCpGXoxh7k"
    ],
    "slug": "kali-bubba-5g"
}
```

**Comment by jjeffryes** [comment]
I don't know if it's related, but the same user has zero returned for their ratingCount and averageRating in their profile call.

**Comment by cpacia** [comment]
Don't think this is still an issue.
