### ISSUE TITLE
Public Gateway - Trouble Setting up

### ISSUE THREAD

**Issue by Cam-B** [OpenBazaar/openbazaar-go#756]
I am trying to set up a public gateway for viewing OB listings. I installed OB2 on a Ubuntu 16 VPS by OVH with no problems. 

Following the instructions for setting up a public gateway did not quite work. 
https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/gateway.md

-1 In the file ~/.openbazaar2.0/config I successfully changed the gateway listening address. 

```
"Gateway": "/ip4/0.0.0.0/tcp/4002",

```

-2 The OB-Api option does not seem to be there as described in the docs. (I can't find it)

> ...turn off OpenBazaar API as you don't want to give public access to this:

```
"OB-API": {
    "Enabled": false,
}
```

After changing the gateway address to 0.0.0.0 I shut down and restarted OB. I can still access OB from localhost but can't or don't know how to access it from another device.  
I thought I would be able to access OB on port 4002 now but that is giving me a 404 page now. http://odat.xyz:4002/

Am I not using the right link? What can I do to troubleshoot?

**Comment by 6025c7** [comment]
Hello, 
at first make sure that your firewall allow connections from 4002/tcp

The second think, you can see 404 page if your request to API server was invalid. Try following link instead:
https://<server_ip>:4002/ob/profile

API details:
https://api.openbazaar.org/#authentication

**Comment by cpacia** [comment]
So the API urls you'd be interested in would be like http://odat.xyz:4002/ob/profile/<peerID>, http://odat.xyz:4002/ob/listings/<listingID>, http://odat.xyz:4002/ob/listings/<peerID>, http://odat.xyz:4002/ipns/<peerID>

Endpoints like that.

**Comment by Cam-B** [comment]
I might have been mistaken at first. I am getting a "403 - Forbidden" error for the Openbazaar links like http://odat.xyz:4002/ob/listings/

the ipns link does not give me a 403
http://odat.xyz:4002/ipns/

I allowed 4002/tcp with
sudo iptables -A INPUT -p tcp --dport 4002 -j ACCEPT

JSON-Api authentication is "false"

what else can I try?

**Comment by Cam-B** [comment]
I am now also realizing that trying to browse to localhost:4002/ob/listings/  from localhost gives me 403 errors as well 

http://localhost:4002/ipns does work.

I was using the server client bundle before. With the server client bundle, the client will connect but I can't use the browser to access OB listings (403 error). 

Now I'm trying to use the Go version  OpenBazaar Server v0.9.4

**Comment by Cam-B** [comment]
I am now also realizing that trying to browse to localhost:4002/ob/listings/  from localhost gives me 403 errors as well 

http://localhost:4002/ipns does work.

I was using the server client bundle before. With the server client bundle, the client will connect but I can't use the browser to access OB listings (403 error). 

Now I'm trying to use the Go version  OpenBazaar Server v0.9.4 but still get 403 errors when trying to browse links like localhost:4002/ob/listings/

**Comment by cpacia** [comment]
Not sure. If you are running the bundled app then it will enable authentication it's and override any other settings. 

Not sure why you would have that issue if you are running a standalone. The config file looks ok to me.
