### ISSUE TITLE
No cookie file

### ISSUE THREAD

**Issue by cliftonts** [OpenBazaar/openbazaar-go#759]
Firstly apologies if I am listing this bug in the wrong place. My OB2 server does not seem to create a .cookie file. I am needing this in order to access through the API. I have searched my entire hard drive for .cookie and *.cookie but got no results back.

I am using Ubuntu 17.10.
![screenshot from 2017-11-03 19-34-03](https://user-images.githubusercontent.com/17416309/32514385-c1ac3830-c3f4-11e7-9730-182944aa8adb.png)

**Comment by cpacia** [comment]
So the cookie file is a hidden file on Linux so you can view it with ctl + h. However, I'm not sure the context you're trying to use it. The bundled app generates a new auth token at start up and passes it into the server so you can't really use the API manually if you're using the bundle. You obviously can if it's a standalone server.

**Comment by cliftonts** [comment]
Thanks for getting back to me. I did discover this for myself last night 
but don't seem to be able to get the api to play nicely. I have the 
cookie added to the header but I simply get errors about maximum 
connections or retries exceeded, something like that. I won't be at my 
pc again until Friday evening so can't pull up the exact message.

Part of the problem is I don't have an example of how this should look 
so I can't be sure my code is correct. The documentation I have shows 
all the documentation with basic authentication rather than cookie and 
that really doesn't help.

**Comment by christroutner** [comment]
Be sure to review the docs in the repo `/docs` directory:
https://github.com/OpenBazaar/openbazaar-go/tree/d65a3f5ba438dbb80e39df43a2cce31d0399d637/docs

Here is a Gist I put together for accessing the API with jQuery:
https://gist.github.com/christroutner/829bf65eec73dfbc7beb44699dddba0a

**Comment by christroutner** [comment]
I think @cliftonts is facing the same issue I was in #761.

My context is that I'm trying to use the API to automate the creation of listings on my OB store. I've followed the directions in [the security doc](https://github.com/OpenBazaar/openbazaar-go/blob/d65a3f5ba438dbb80e39df43a2cce31d0399d637/docs/security.md). I can connect my OB client to the remote server just fine. 

When I couldn't get [Basic Authentication](https://github.com/OpenBazaar/openbazaar-go/blob/d65a3f5ba438dbb80e39df43a2cce31d0399d637/docs/security.md#basic-authentication) to work, I tried the [Authentication Cookie](https://github.com/OpenBazaar/openbazaar-go/blob/d65a3f5ba438dbb80e39df43a2cce31d0399d637/docs/security.md#authentication-cookie). Both resulted in the same issue I was facing in #761.

**Comment by cliftonts** [comment]
Ok, the first problem I encountered was that the instructions state to run openbazaar-go setapicreds to create basic authentication login details but I just got a command not recognised response from the OS. Through trial and error I discovered an openbazaar-go directory containing an executable called openbazaard, this is what I need to run in order to access the server through API. However the cookie method does not work, I got basic authentication working but it complains when I try to run the sample code the response I get is an error:

```
{
    "success": false,
    "reason": "unknown field 'listing' in pb.Listing"
}

```

I have no idea what is going on here but the obvious issue is I now have 2 config files and must swap them round to run either the client or the api.

**Comment by christroutner** [comment]
@cliftonts Can you copy and paste the difference between the two config files? I don't quite understand.

**Comment by cliftonts** [comment]
With cookie authentication:
```
"JSON-API": {
      "AllowedIPs": [],
      "Authenticated": true,
      "CORS": null,
      "Enabled": true,
      "HTTPHeaders": null,
      "Password": "",
      "SSL": false,
      "SSLCert": "",
      "SSLKey": "",
      "Username": ""
   },
```

With basic authentication:
```
"JSON-API": {
    "AllowedIPs": [],
    "Authenticated": true,
    "CORS": null,
    "Enabled": true,
    "HTTPHeaders": null,
    "Password": "bfa6fed4<blah blah blah>",
    "SSL": false,
    "SSLCert": "",
    "SSLKey": "",
    "Username": "<username>"
  },
```

**Comment by christroutner** [comment]
Thanks @cliftonts. After looking at the code in /api/jsonapi.go I realized that you have to have a blank Username and Password in your config file in order to for the Auth-by-Cookie code to get triggered. So your config changes above make more sense now.

**Comment by cliftonts** [comment]
Than you, so the questions are why doesn't the api work by cookie and why is it telling me that the root keyword of the listing is unexpected?

**Comment by cpacia** [comment]
What API call are you making that's returning that error?

**Comment by cliftonts** [comment]
```
import requests

url = "http://ubuntuguy:42263780e@localhost:4002/ob/listing"

payload = "{\n\t\"listing\": {\n\t\t\"slug\": \"godfather\",\n\t\t\"termsAndConditions\": \"\",\n\t\t\"refundPolicy\": \"\",\n\t\t\"item\": {\n\t\t\t\"title\": \"The Godfather\",\n\t\t\t\"description\": \"Yo\",\n\t\t\t\"processingTime\": \"3 days\",\n\t\t\t\"tags\": [],\n\t\t\t\"categories\": [],\n\t\t\t\"sku\": \"favor-001\",\n\t\t\t\"nsfw\": false,\n\t\t\t\"condition\": \"NEW\",\n\t\t\t\"images\": [{\n\t\t\t\t\"filename\": \"godfather.jpg\",\n\t\t\t\t\"tiny\": \"QmStfQBgdKVTfRBaAnWFHAqtrzquy1TEyEjkBHfmCnmh5x\",\n\t\t\t\t\"small\": \"QmesG5vYFKjrEPiABPY4Qk9EnZNN69LLvn2SMLrgqiXtvV\",\n\t\t\t\t\"medium\": \"QmPt31NBFRkmzkKyeQGyZem9SrnZmo2bRhWsLAYTMhcBdj\",\n\t\t\t\t\"large\": \"QmY2qKeu18pDaKsd4nFmxTwAWKhgmcqDKKoW6cN3swvqab\",\n\t\t\t\t\"original\": \"QmeY6Wdjrh79fPjzE7uE45CxFszWkgYoxUKjPQUQsAFLeJ\"\n\t\t\t}],\n\t\t\t\"price\": 20,\n\t\t\t\"options\": []\n\t\t},\n\t\t\"metadata\": {\n\t\t\t\"contractType\": \"PHYSICAL_GOOD\",\n\t\t\t\"format\": \"FIXED_PRICE\",\n\t\t\t\"expiry\": \"2037-12-31T05:00:00.000Z\",\n\t\t\t\"pricingCurrency\": \"USD\"\n\t\t},\n\t\t\"shippingOptions\": [],\n\t\t\"taxes\": [],\n\t\t\"coupons\": [],\n\t\t\"moderators\": []\n\t},\n\t\"inventory\": []\n}"

headers = {
    'content-type': "application/json",
    }

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

As listed on https://api.openbazaar.org/#b14af9a6-8686-5e8b-c92a-3fd8d9f0510e

**Comment by cliftonts** [comment]
Isn't there anybody who can tell me why this API call fails?

**Comment by christroutner** [comment]
The best I can do is give you [this example script](https://gist.github.com/christroutner/829bf65eec73dfbc7beb44699dddba0a). This is an HTML file that I used to query the /ob/config API endpoint. It uses jQuery. 

I recommend avoiding the cookie type of authentication. I don't think it's working correct. Use the Basic Authentication method as illustrated in the Gist.

**Comment by cliftonts** [comment]
Thanks, I'll give it a study and see if a lightbulb goes on.

**Comment by cliftonts** [comment]
Thank you for that. I have managed to make a basic listing. For now I shall create some scripts to reconfigure my setup for either the client or working with the api.
