### ISSUE TITLE
Improving ratings for OB2.0

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#76]
In `OpenBazaar-Server` it looks like the transaction `address` and `amount` are part of a given rating. Why isn't a hash of the transaction (not the `txid` as that can mutate) included? Indeed, the pair (`address`, `amount`) is not always enough to uniquely identify a Bitcoin transaction.

Secondly, it looks like `OpenBazaar-Server` does not actually verify the existence of the Bitcoin transaction. I suspect since OB2.0 has an SPV node, such verification will be done for OB2.0. Is that correct?

Finally, it looks like the `OpenBazaar-Server` rating object doesn't contain a timestamp. Please consider including a timestamp.

**Comment by cpacia** [comment]
We have to do ratings differently in this one. The other counldn't check the address because it was too much load to repeatedly query the libbitcoin server like that just to calculate the rating. 

And SPV mode cannot query for address balances even if it were an acceptable load.
