### ISSUE TITLE
server connection timeout 

### ISSUE THREAD

**Issue by kiahmed** [OpenBazaar/openbazaar-go#762]
Hi,
I really need some help on keeping the connection alive on remote server. After a while the server disconnects the client connected remotely. Is there any way I can change that in the config to keep the connection alive ?

Thanks,
Kazi

**Comment by cpacia** [comment]
The client is saying it lost connection the server?

**Comment by solutionjet** [comment]
yup..it looks like after a while it loses the connection and gets redirected to the server manager screen. Then if I hit connect , it connects again.

**Comment by solutionjet** [comment]
windows 2012 r2, there are plenty of resources 8 gb ram, 4 core . I was wondering if is a network issue then figured that its happening consistently almost at a certain period of time
