### ISSUE TITLE
docker container error and api not accessible

### ISSUE THREAD

**Issue by kiahmed** [OpenBazaar/openbazaar-go#765]
HI,
I tried it running on latest docker on Mac. Got the following error when it starts up..looks like something to do with https? Also tried accessing the api with http://vmip:4002/ob/profile , it didn't work even the same port is mapped with the docker host. Any idea?

18:45:52.178 [fetch] [ERROR] Failed to fetch from https://ticker.openbazaar.org/api Get https://ticker.openbazaar.org/api: dial tcp: lookup ticker.openbazaar.org on 10.0.2.3:53: read udp 172.17.0.2:40874->10.0.2.3:53: i/o timeout
18:45:52.211 [getPointersFromGatewayRoutine] [ERROR] Error retrieving offline message from gateway: Get https://gateway.ob1.io/ipfs/providers/Qmcpq7AULSSFHb1uqoNQBkWGx33rPqDWT535RkLfGsg1Tq: dial tcp: lookup gateway.ob1.io on 10.0.2.3:53: read udp 172.17.0.2:42707->10.0.2.3:53: i/o timeout
18:45:52.213 [func4] [INFO] Starting bitcoin wallet
18:46:12.249 [fetch] [ERROR] Failed to fetch from https://bitpay.com/api/rates Get https://bitpay.com/api/rates: dial tcp: lookup bitpay.com on 10.0.2.3:53: read udp 172.17.0.2:45444->10.0.2.3:53: i/o timeout
18:46:30.657 [Publish] [INFO] Published zdj7WWTT8dF6vgNf775hU3YuJ86J3cER7Wpmrr8GqLU8JM4cM to IPNS
18:46:32.264 [fetch] [ERROR] Failed to fetch from https://blockchain.info/ticker Get https://blockchain.info/ticker: dial tcp: lookup blockchain.info on 10.0.2.3:53: read udp 172.17.0.2:52598->10.0.2.3:53: i/o timeout
18:46:52.321 [fetch] [ERROR] Failed to fetch from https://api.bitcoincharts.com/v1/weighted_prices.json Get https://api.bitcoincharts.com/v1/weighted_prices.json: dial tcp: lookup api.bitcoincharts.com on 10.0.2.3:53: read udp 172.17.0.2:50904->10.0.2.3:53: i/o timeout
18:46:52.322 [fetchCurrentRates] [ERROR] Failed to fetch bitcoin exchange rates

**Comment by christroutner** [comment]
Hi @kiahmed. My pull request was just accepted into the master branch that fixed issue #763. That latest update might help you with accessing the API.

I also had a hard time getting the Docker container to work. I ended up creating my own this morning. You can find it here:
https://github.com/RPiOVN/docker-connextcms-p2pvps/blob/3dcf2487ee94473de76a576e02acc643760ee3e2/openBazaar/Dockerfile

**Comment by kiahmed** [comment]
thanks @christroutner ..will give it a try and let you know

**Comment by christroutner** [comment]
Also, don't forget to set the `"Addresses": {"Gateway": "/ip4/0.0.0.0/tcp/4002"}` in the config file of your Dockerized server. I forgot to do that and have been wresting with my Docker container for the last few hours.

**Comment by kiahmed** [comment]
right..but I got into a chicken/egg problem here. As OB doesn't generate the data dir (where the config lives) , that leaves me to edit the file until the container starts. Then without restarting the container the OB server gateway ip doesn't take effect which gets rid of the existing config. I wonder how you dealt with that? 

I am new into Docker, if I can stop the container getting rid of the data dir when it stops (but not deleted) or other solution might be passing the config file parameter during startup (doubt OB allows it as of now) from a different location or evn variable or something?

**Comment by j005u** [comment]
You need to tell docker to place the volume in a dir you can access better with `-v /full/path/to/desired/dir:/var/lib/openbazaar`

Then you can run the container, stop it, modify the file and start it back up.

Also, if you want to change the username/password you can do `docker run -it -v /full/path/to/desired/dir:/var/lib/openbazaar openbazaar/server /opt/openbazaard setapicreds -d /var/lib/openbazaar`

**Comment by kiahmed** [comment]
no i knew about the volume, but I was using one of your scripts to run the image and dint notice it had -rm switch . so its all good now. Thanks for your help. I am closing it.
