### ISSUE TITLE
http: response.WriteHeader on hijacked connection

### ISSUE THREAD

**Issue by agd-media** [OpenBazaar/openbazaar-go#770]
When I try to connect to the server with my Win client, I see this message on the server and client doesn't connect:

```
http: response.WriteHeader on hijacked connection
http: response.Write on hijacked connection
```

**Comment by hoffmabc** [comment]
Are you trying to connect over SSL to a remote server?

**Comment by agd-media** [comment]
No. I had to switch off SSL, because of some still unknown issue. After that, it has been working for at least one time without SSL. I was able to open the shop with my Windows client and everything.

**Comment by cpacia** [comment]
That error is usually ssl related. Like a client using a regular http connection when the server expects SSL. Something along those lines.

**Comment by agd-media** [comment]
Even when I put SSL=false and disabled SSL in the Windows client? Why should the server expect SSL when it is disabled?

**Comment by arteniioleg** [comment]
I had the same problem. The fix was to set a simpler password (md5), initially it was a very long password (70 chars) with special characters.

**Comment by cpacia** [comment]
Sounds like that might be it.

**Comment by arteniioleg** [comment]
An improved error message is welcome

**Comment by i-am-vivek** [comment]
I'm having the same problem. did anyone find the solution?? can anyone help me out!!?

**Comment by placer14** [comment]
@i-am-vivek Please open a new ticket with a description of your setup in it and we'll troubleshoot from there. Be sure to include version, any custom configuration you're applying, and the method you used to install the software.
