### ISSUE TITLE
AOL SMTP fails

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/openbazaar-go#776]
client 2.0.18, server 0.10.0

> The integration test was not successful: EOF

https://help.aol.com/articles/how-do-i-use-other-email-applications-to-send-and-receive-my-aol-mail?ncid=mbr_comdefeml00000001
says 
> smtp.aol.com SMTP - 465 - SSL

![screen shot 2017-10-27 at 16 08 38](https://user-images.githubusercontent.com/2625857/32128355-d8c58344-bb31-11e7-8f72-ccf701b7927c.jpg)

**Comment by pinheadmz** [comment]
Same issue here, OSX and gmail

**Comment by rmisio** [comment]
@cpacia What does it mean when the server is returning `EOF` as the error?

**Comment by pinheadmz** [comment]
Port 587 worked for me for gmail

**Comment by cpacia** [comment]
I think you just have the wrong port @TheButterZone. Have you tried 587?

**Comment by TheButterZone** [comment]
AOL has the wrong ports listed on https://help.aol.com/articles/how-do-i-use-other-email-applications-to-send-and-receive-my-aol-mail?ncid=mbr_comdefeml00000001

587, which does not appear at all on there, works.
