### ISSUE TITLE
Missing Orders

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#781]
We've had many reports of this issue. This one was filed in the desktop repo, I'm moving it here.

This is from @kiahmed
https://github.com/OpenBazaar/openbazaar-desktop/issues/1134

Brief Description: 

Operating System (OS and version): Windows 10 Pro
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
client 2.0.17, server 0.9.4
Hardware: intel cori 7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Hi,
One OB node ordered an item from my store more than 3 weeks ago and I never got notified and he already paid in full. He tried to get support many times but haven't had any luck then finally brought it to my attention. Here is the screen shot of the product purchase.  My store id QmQfbCEUEfmBr59ZvBDVek7rs71AywrcMkX2APEDwJWGDo
![missed_order](https://user-images.githubusercontent.com/28849607/33679482-e0a0c324-da8c-11e7-802b-9da9ff537c3f.PNG)

I feel horrible saying the customer that I never received any order from him. Is there anything I need to do or configure on OB node?

**Comment by pinheadmz** [comment]
I've had this issue multiple times as well.
OSX client 2.0.18, server 0.10.0
Always happens when "offline" protocol is followed (payment to 1-of-2 P2WSH bech32) In one case, after twice cancelling and ensuring both me and the seller were still online, the seller got my purchase after a long wait. The other two sellers, it failed completely.

**Comment by kiahmed** [comment]
well, so what we do now? Does that mean my OB is incapable of receiving orders? Then whats the point or how others do tx?

**Comment by DominiqueFrancon** [comment]
I'm the purchaser from @kiahmed and this has been such a pain. I'm so glad it was only $3.00. 
I don't run Windows 10, I'm running 8, and now I'm wondering if I have any open orders that I don't know about.

**Comment by jjeffryes** [comment]
When you're running the app, do you typically leave it on for brief or long periods of time? Offline messages should download every time you turn the app on, and then once an hour after that.

Have you tried going into settings/advanced, and clicking the Reload Transactions button?

**Comment by pinheadmz** [comment]
Once an hour? I think that may be far too infrequent. For chat messages, I noticed I get them faster by restarting OB. I do not have port 4001 open yet. In my dialog with the sellers, we both are restarting and rescanning (hitting all the buttons!) And the purchase still doesn't come through. I have some logs posted in this thread with @chrispacia:

http://www.reddit.com/r/OpenBazaar/comments/7gwans/shameless_self_promotion_thread_friday_121/dqv9im5

**Comment by jjeffryes** [comment]
Resyncing can take a while.

Once an hour might be too infrequent to check for offline messages, I'll let @cpacia chime in on that.

**Comment by jjeffryes** [comment]
Hopefully @tyler-smith or @cpacia can help out with this issue, it's very important to us to get it resolved.

**Comment by DominiqueFrancon** [comment]
I have done both leaving the app running for days or shutting it down for a day or two.
Maybe you guys can run a report on all open orders in sellers queues in case there are more people not getting their notifications.

**Comment by kiahmed** [comment]
@jjeffryes  I just did reload ..nothing changed. I wonder since it was btc tx, wouldn't it traceable on blockexplorer ? From the screen shot looks like OB sent the order but was never received by my node

**Comment by jjeffryes** [comment]
> run a report on all open orders in sellers queues

All transactions on OB are private between the buyer, seller, and moderator (if they have one), no one else can see or even know about those transactions. 

That's part of the value of OpenBazaar, but it does mean it's difficult for us to assist when things go wrong.

**Comment by kiahmed** [comment]
it was a brand new order and never been fulfilled and that was the first sale I had on this store. why I need to run report. I still did and same result

**Comment by pinheadmz** [comment]
I don't know if this part of the bug, but once I got a direct, real-time, online connection with my vendor we discovered he was "out of stock" on the item I was trying to purchase. I don't know if that's why my order attempts never showed up in his client, but either way I was not notified he was out of stock until we were both online and I tried the purchase again. Once he adjusted his inventory value, I was able to complete the purchase very quickly!

**Comment by jjeffryes** [comment]
@pinheadmz when a vendor isn't online, we can't tell what the inventory is for their items. They could have had 3 offline orders before yours, and until they come back online and process the orders the inventory is in a state of limbo. 

We know that's inconvenient, but it's not a bug.

**Comment by pinheadmz** [comment]
Gotcha, makes sense. Does the buyer get a notification though? Once the seller comes back online? I didn't know he was out of stock until we were both online.

**Comment by jjeffryes** [comment]
The seller has to choose to accept or reject the order when they come back online. They should be able to adjust the inventory first, then accept it, in which case everything would have worked and you wouldn't have known the inventory was out.

If they reject the order, you are notified of that too.

**Comment by cpacia** [comment]
I've got a PR in to improve the logging. It should tell us some people aren't seeing messages get through.

**Comment by hoffmabc** [comment]
We should get some of these people to upgrade and see what's going on @cpacia

**Comment by jooray** [comment]
Same problem. The buyer is willing to help debug the problem. He ordered and paid in full, I don't see his order at all. My OpenBazaar store is running all the time and I am regularly updating. Also did Reload Transactions.

Order ID: QmahKR9tRXenz8rKXqHoU7ATyDnZcMNZhvEU6Jp7cFPMZm

Can he do something to rebroadcast the transaction? I don't like the fact that the customer has ordered and paid, I don't even know about this transaction. The funds are somewhere in limbo, I cannot see them in my wallet. I wonder how many transactions like this are out there and people are waiting for their products.

Let me know if we can help to debug this, both me and the buyer are capable of a bit of debugging.

**Comment by DominiqueFrancon** [comment]
*So, here's the deal....I'm going to cancel this order, but for the record
I'm posting a screenshot of it here BEFORE I cancel so there's record I
have money sitting in OpenBazaar that needs to be refunded by OpenBazaar in
case there's an even bigger snafu.*

Here's the order, pre-cancellation:
 [image: Inline image 1]

*Here's the cancellation confirmation:*
[image: Inline image 2]

Here's my wallet, post-cancellation (note, zero money returned):
[image: Inline image 3]

And, when I click View Details, blockchain.info has no record of that
transaction.
[image: Inline image 4]
*So, yeah...bigger snafu. I just want my bitcoin back.*

**Comment by jjeffryes** [comment]
@DominiqueFrancon When you funded your transaction, the funds were moved to a bitcoin address, and only one of the parties that control that address can move those funds. The parties that control it are you, the seller, and a moderator if you have one.

OpenBazaar has absolutely zero ability to affect anyone's transactions. We don't have those funds, we can't move the funds, and we don't even know about them unless we're told.

When you cancel the order, you'll pay a bitcoin transaction fee (which may currently be very high) to move the funds back to your wallet. The fee will be subtracted from the funds, if the fee is larger than the funds you're moving, they won't move.

When the buyer receives the offline purchase (the fact they haven't received the purchase is what we're trying to debug) they would pay the fee to move it to their wallet instead.

The transaction isn't appearing on blockchain.info because it's using a format not every Bitcoin company has adopted yet, though this was supposed to be a standard format everyone was compatible with several months ago.

**Comment by pinheadmz** [comment]
@jjeffryes @DominiqueFrancon Blockchain.info does display SegWit transactions, but it does not correctly decode bech32 addresses unless "advanced" mode is on (by clicking "Show scripts & coinbase"). Compare these two views of the same transaction:

https://blockchain.info/tx/bd14fa9db714fb931a5630151f4e5be4e5e15d84ef1f2d5903a37f81cc27f8e7?show_adv=false

https://blockchain.info/tx/bd14fa9db714fb931a5630151f4e5be4e5e15d84ef1f2d5903a37f81cc27f8e7?show_adv=true

 This issue seems to only affect "offline mode" purchases which are sent to a 2-of-2 P2WSH multisig until the seller accepts the purchase.

**Comment by kiahmed** [comment]
@DominiqueFrancon were you able to transact with any other OB sellers? Just curious..

**Comment by jjeffryes** [comment]
@pinheadmz good tip on the show scripts, I didn't know about that.

**Comment by jooray** [comment]
Another buyer with the same problem. Does it make sense to put order IDs here, or what would help to debug this issue?

**Comment by DominiqueFrancon** [comment]
I haven't tried.

**Comment by kiahmed** [comment]
@jjeffryes so any result from your testing might indicate that if that happens for one item for one seller, its gonna happen for all the items?

**Comment by jjeffryes** [comment]
@kiahmed it seems so far from what we've seen that this issue affects offline orders, and there are some computer setups that appear to cause all orders to be treated as offline due to firewalls blocking messages.

**Comment by kiahmed** [comment]
@jjeffryes  I have all the port WS/Swarm 4001,9005 and also gateway 4002 open, but could've been a possibility that the node was offline during the order was placed I am not sure

**Comment by DominiqueFrancon** [comment]
Do we have any progress on this? 

I'd like to air my concerns a bit more:

1. How many other stores might be having this issues and don't even know (including me)?
2. Is OpenBazaar going to refund my 0.00027292 BTC? 
3. Would you like me to set up a fake test product and then turn off my node to see if anyone can still purchase?

**Comment by jjeffryes** [comment]
The latest release has both a potential fix, and more extensive logging so we can investigate further if it doesn't work.

We can't refund any orders, we at no point have any control or even awareness of anyone's payments. 

More testing is always useful, I'll let @cpacia specify what would be most helpful.

**Comment by jooray** [comment]
@jjeffryes I don't know what you mean by latest release, but upgrading to 2.0.20 both on the customer side and merchant side did not help (meaning the old orders did not appear, even after reloading transactions). What can we do to debug it better? Is there a way to republish a missing order (on the customer side)?

**Comment by jenncloud** [comment]
For OB development team: ZD Tickets 860/872/850 are all one account of this issue as well as the individual tickets 863, 846 and 761.

**Comment by jjeffryes** [comment]
@jooray @kiahmed @DominiqueFrancon can you do the following for us?

1. let us know if you're still experiencing the missing order issue. The last release included a fix that should allow vendors to retrieve orders that they were previously missing. 

2. if the answer is yes, tell us what OS you are running OpenBazaar on.

**Comment by kiahmed** [comment]
I updated to latest version and the order was for me. I did reload tx couple times..nothing showed up...running on windows 10

**Comment by jooray** [comment]
No change for me either. Running latest fully updated macOS, openbazaar is fully updated and running through Tor. I had some successful orders since the missing orders, but the missing orders are paid by customers and I cannot still see them. Did reload transactions, tried restarting and waited for a while, nothing.

**Comment by jjeffryes** [comment]
Ok. So we can confirm there are still issues on 2.0.21 with Windows and Mac.

@jooray it's possible Tor is slowing things down enough loading offline transactions is still timing out for you.

@cpacia would it be worth making the timeout settable in the config, so people could experiment with longer timeouts to see if that fixes the issue? Or something they can manually set in settings?

**Comment by jooray** [comment]
How do I find out if it is timing out? Anyway Tor is pretty fast at least from browser, to my surprise.

**Comment by jjeffryes** [comment]
@jooray I don't think pulling the offline messages from the DHT timing out is visible to the user, possibly you could tell by going through the logs.

One of the things we suspect was happening is when nodes were downloading offline messages (data that is sent to a node when it's offline or not able to accept incoming messages due to firewalls or other computer settings that block messages) the download wasn't able to complete before it timed out. 

We increased the timeout to 5 minutes, which seems to have helped, but it's clearly not fixing every instance of missing orders (an order is a message).

**Comment by tnperron** [comment]
Following this thread; I'm a buyer experiencing the same issue.  Seller has reloaded TX and still cannot see the order.  I'm running client 2.0.21 on Ubuntu 17.10, not sure what seller is running.

Anything I can do to help, or information I can provide?

**Comment by morebrownies** [comment]
I've recently experienced this issue again. Probably about the 3rd of 4th time i've run into it. Using a Mac, non-tor, clicked "reloaded transactions" in settings. Order still displays unpaid, buyer said he paid for it.

**Comment by jjeffryes** [comment]
@morebrownies but it does display the order in your sales screen? If so, that's a different issue with the payment not coming through. 

I've started a new issue to track that here: https://github.com/OpenBazaar/openbazaar-go/issues/815

**Comment by kiahmed** [comment]
I dont see any order on my sales screen .and if that's happening now..probably it will happen for other coins zcash, bch you guys working on?

**Comment by morebrownies** [comment]
> @morebrownies but it does display the order in your sales screen? If so, that's a different issue with the payment not coming through.

Correct. The order displays in the Transaction section as "Awaiting Payment"

**Comment by jjeffryes** [comment]
@kiahmed that's correct. This issue most likely affects all crypto currencies.

@tnperron there are logs that might be useful, I'll let @cpacia specify which ones..

**Comment by cpacia** [comment]
@tnperron the ob.log might help. It's more helpful to me if I can get the log from the vendor as well.

**Comment by tnperron** [comment]
Attached is my ob.log; I'll see if I can get the vendor's log as well.





[ob.log](https://github.com/OpenBazaar/openbazaar-go/files/1617018/ob.log)

**Comment by DominiqueFrancon** [comment]
Sorry I didn't check my email the other day, but here's my update:

1. I was the person who PLACED the order with @kiahmed so nothing has
changed for me.
2. I did RECEIVE an order the other night in my store and the process went
just great.
3. I'm running Windows 8.

**Comment by DominiqueFrancon** [comment]
Sorry, another update....

I happened to go look in my Sales queue and sure enough, there's another
sale pending payment in there. I didn't receive any notification for it. It
was made 5 days ago and thankfully they haven't paid or I might have
completely pissed off a customer.

The other thing is, it looks like it might be a test account that made the
"purchase". the buyer is at this
location: ob://QmVnk2XAP7NPaDuc3osoXqoNS8rXHgQH8qS4THPmBso7wq/store

**Comment by MinaZ23** [comment]
You are able to SEE the sale pending payment at least?  I thought I was having the same issue, but perhaps mine is different as the buyer has an order ID AND paid but I cannot see the sale, so I cannot accept it or fulfill it or do anything, yet their BTC is tied up.

1)The buyer has paid (shows on blockchain...I can share if need be but I don't see how that will help)
2)Buyer has order ID (orderId=QmdmzqTdCc3EiqNM8tGf7wn8NHiyifCYWjNKeC61p5ReH6)
3)On my end no notification, no sale...so I cannot accept 

It is a large order and prefer to get it to work vs Cancel, pay a Moderator for nothing, and have the customer repeat the order as was mentioned above (I don't see that as a solution but a workaround).  I know we can do this and we will if need be, but the techy in me is irked by being unable to fix this.

**Comment by kiahmed** [comment]
I was never able to see @DominiqueFrancon s order that was paid, but I see other orders on my other store that was placed but never paid.

**Comment by MinaZ23** [comment]
thank you for clarification, I have the same situation.  I cannot see order either.  I tried cutting and pasting the order (which the provided me) and replacing it with another order ID, but it doesn't work like looking up an HTML page.  Basically, when something is lost to the DHT you are F***D

**Comment by HICPRUSA** [comment]
@MinaZ23 I have the same issue, i am the buyer. The seller does not see order, and i cant start a dispute with mod because, i get error: routing: not found.
Did you solve this issue?

**Comment by cpacia** [comment]
Closing for now as the last couple releases seemed to have squashed this issue.

**Comment by HICPRUSA** [comment]
Hi, yes seems that the update solved this.
I have one more question if the seller does not accept payment what hapens
then?

V sre., 28. mar. 2018 21:51 je oseba Chris Pacia <notifications@github.com>
napisala:
