### ISSUE TITLE
Metrics Collection Ping

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-go#782]
I'm proposing a webhook push to capture specific events on the OpenBazaar network. The server would send out a small bit of information after certain types of events occur that will inform developers of how the network is being used without exposing too much information. 

This information would be helpful to see the health and activity at a high level. 

Scenario:

1. User files dispute
2. Server sends small JSON snippet to gateway or metric server* indicating that someone filed a dispute

`{ 'event': { 'type': 'transaction', 'subtype': 'dispute_open' } }`

3. Collection server aggregates events
4. Collection server provides charts/graphs on activity of the network

**Comment by placer14** [comment]
@hoffmabc @jjeffryes I assume our county setup would satisfy these needs or are we interested in using this for tracking server metrics?

**Comment by jjeffryes** [comment]
I think this issue is closed by our having added Countly.
