### ISSUE TITLE
Wallet not able to be emptied

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-go#789]
When trying to remove all BTC from the wallet it will always leave some proportion (typically a substantial percentage) in the wallet. I don't know if this is related to bad fee estimation but it is easily reproducible; try removing all the funds in your OB wallet.

**Comment by hoffmabc** [comment]
I think we should have a sweep funds ability to just empty the whole damn thing out no matter what.

**Comment by cpacia** [comment]
I think I may have fixed this. There was a requirement that a transaction contain a minimum amount of change. I removed it.
