### ISSUE TITLE
Merkle Blocks Not Downloading

### ISSUE THREAD

**Issue by christroutner** [OpenBazaar/openbazaar-go#793]
## Summary
I just created a new Bitcoin Testnet OB server. I tried to receive some testnet coins from a Bitcoin Testnet Faucet site. To avoid issues with offline servers, I'm using a Digital Ocean Droplet VPS. It's been 6 hours and the OB wallet is still not showing any confirmations, even though blockchain explorer is showing 19 confirmations.

I'm using the latest commit to the master branch: 156b69ba4b15fbd669902b962d93b716ab3994fe

I checked the log files in the OB `.openbazaar2.0-testnet` folder. From the `bitcoin.log` file, it appears that the downloading of the Merkle blocks got hung up. According to Block Explorer, the current block is 1255225. Here is the tail of the bigcoin.log file:

```
trout@OB-Test-Buyer:~/.openbazaar2.0-testnet/logs$ tail bitcoin.log
21:32:40.650 [onMerkleBlock] [DEBUG] Received Merkle Block 0000000000000cb23dc8eab577b3cb44929a3ee44079b17ae2dc566ebfc87bbc at height 1252255
21:32:40.652 [onMerkleBlock] [DEBUG] Received Merkle Block 000000000000083e163be16504fb50817ccdf1e3178fd0f79e17a0b9fce114eb at height 1252256
21:32:40.694 [onMerkleBlock] [DEBUG] Received Merkle Block 00000000000008901d832b98d38c57e2da44c966061f0c598056ad0972114173 at height 1252257
21:32:40.735 [onMerkleBlock] [DEBUG] Received Merkle Block 0000000000000ee06c9cb7a2da6a66c506cae6e429930d0d3a15acf2658b25de at height 1252258
21:32:40.737 [onMerkleBlock] [DEBUG] Received Merkle Block 0000000000000bef4f7335d212e2773d01fa8ff4701767dd9b1f14b962c5e7d5 at height 1252259
21:32:40.747 [onMerkleBlock] [DEBUG] Received Merkle Block 00000000000002d32b964d132df21e3c3fb21ea6c09dab4d8b6e049056e86813 at height 1252260
21:32:40.793 [onMerkleBlock] [DEBUG] Received Merkle Block 0000000000000a27b9d5edb17a9f9d6ecf1a7c7be1021dfea71c6c779acdd9b9 at height 1252261
21:32:40.900 [onMerkleBlock] [DEBUG] Received Merkle Block 0000000000000432be3de2de5e91b6c6e456456d9f02665bd9df4cf546d3acdc at height 1252262
21:32:40.923 [onMerkleBlock] [DEBUG] Received Merkle Block 000000000000070eba1221172d9ee46dfb9d4110ca12adc699fb9cfe6f242e58 at height 1252263
21:32:40.951 [onMerkleBlock] [DEBUG] Received Merkle Block 000000000000068ae11e526a63b4279d26e8ad285d051070d8f683a0eb2a4edf at height 1252264
```

I've seen this issue before on a VM. It fixed itself after about 24 hours. But this is a brand new install, and I'm trying to fund a new wallet. This kind of hang up is a real turn off from a UX perspective. I had hoped to avoid it by using a DO VPS. 

Could the issue be that I'm on the BTC testnet? Connected peers are few and far between.

**Comment by christroutner** [comment]
I rebooted the server and restarted OpenBazaar. The rest of the Merkle blocks downloaded just fine.

Feel free to close this issue. I'm going to leave it open so that I know the devs saw this.

Perhaps the server could restart itself if a period of time goes by without new Merkle blocks being downloaded? Especially if it's a new install and it's downloading the blocks for the first time. Or at least the part that is responsible for the download could be restarted? Seems to me like the OB server stalled and didn't recover until it was rebooted.

**Comment by cpacia** [comment]
Thanks. I think this issue might be better for the spvwallet repo. I have seen this once or twice before. Not sure the cause. It appears like the peer stopped sending blocks. I believe all network messages have a timeout so I'm not sure how that would happen, but I'll have to investigate.

**Comment by christroutner** [comment]
Closing this issue and moving it to [the spvwallet repo](https://github.com/OpenBazaar/spvwallet/issues/30)
