### ISSUE TITLE
Unfollow Fails with Routing Not Found

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#800]
For some old profiles I am following, trying to unfollow them fails with a 500 error and the following response:

```
{
    "success": false,
    "reason": "routing: not found"
}
```

Peer IDs that get this error:
QmSxrDKfmZgJmg9bZYsgiCyAZXkPkmvv7qJxMZBQ1WY7eL
QmbCXXdnduZgCPATvWGY9FUtPCS3UHbYBJ35p4GpHSK4gs
QmSGJTsLnwhuneyhjx7WpJT5BdACQgGy9DbgbEmmgd5hct
QmVfsHYJwV7LMj7bnwfBBuTkFbHfWrPfBCjiqWqdthJYD7
QmeY7wzVsw5Ta7g2jtgTB1Wy9RaUAgRudrbYictqePRjTi
QmUFEMQ4goo8CX9DnypWzx2ftM7QrXnbLCqYdYk3PSbAL9

I was able to load QmUFEMQ4goo8CX9DnypWzx2ftM7QrXnbLCqYdYk3PSbAL9 and QmVfsHYJwV7LMj7bnwfBBuTkFbHfWrPfBCjiqWqdthJYD7, but unfollowing them always returns that error. 

Other nodes were able to be unfollowed and followed normally.

**Comment by cpacia** [comment]
Is it removing them from the db?

**Comment by jjeffryes** [comment]
They aren't being removed. They're all still there even after shutting down the server and starting it again.

**Comment by cpacia** [comment]
pubkeys are now saved in the db so this should not happen
