### ISSUE TITLE
[Linux] Certificates stop working after 1 month

### ISSUE THREAD

**Issue by ekaitz-zarraga** [OpenBazaar/openbazaar-go#801]
Hi,

> I probably opened the issue in the wrong repo but I don't really know if it's related with the client or the server. I think it's related with the server configuration, that's why I opened it here.

I have a Openbazaar-go running in a Debian9 machine and the client running on an Ubuntu machine.

I generated the certs like this:

``` bash
openssl genrsa -out rootCA.key 4096                                                                                                                                                                        
openssl req -x509 -new -nodes -key rootCA.key -days 1024 -out rootCA.crt -subj "/C=DE/ST=Germany/L=Walldorf/O=SAP SE/OU=Tools/CN=rootCA"                                                                   
openssl genrsa -out server.key 4096
openssl req -new -key server.key -out server.csr -subj "/C=DE/ST=Germany/L=Walldorf/O=SAP SE/OU=Tools/CN=${MI_IP}"
openssl x509 -req -in server.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out server.crt
```

It happened twice that the client started to show "insecure-response" error and it stopped working even if the server was running.

I realized it happened **exactly one month after I created the certs**.

I have no idea about certificates and stuff so it will probably be that I misconfigured something but I see `-days 1024` there.

Is there any configuration error or is it related with Openbazaar itself?

I followed this guide:
https://github.com/OpenBazaar/openbazaar-desktop/blob/master/docs/connectionIssues.md
(the link of the trusted certs how-to is broken, btw)

Thank you!

**Comment by cpacia** [comment]
You got it. I think you can either omit that field or set it very high if you want it to last forever.

**Comment by ekaitz-zarraga** [comment]
Done!
Thank you very much!
The certificate creation and stuff is very messy.

**Comment by pinheadmz** [comment]
I'm suddenly having this issue as well... but why would 1024 days -> 1 month? My certificate says it expires in September 2020

**Comment by ekaitz-zarraga** [comment]
Yeah, true I expected it was related with days being a strange parameter or something but I just read the help:

```
req [options] <infile >outfile
where options  are
[...]
 -days          number of days a certificate generated by -x509 is valid for.
```

So... no idea.

This issue should be reopened I think.

**Comment by ekaitz-zarraga** [comment]
It still happens...

This issue should be reopened. It doesn't look like an SSL problem.

**Comment by hoffmabc** [comment]
I don't understand where this is actually related to openbazaar-go code.

**Comment by ekaitz-zarraga** [comment]
It's openbazaar which sends an insecure response... It might be related with the OpenSSL library it uses?
If the certificate is valid it shouldn't send an Insecure Response.

**Comment by hoffmabc** [comment]
Oh also are you requesting that the server cert AND the root CA cert be good for a lot of days or just the CA cert?

In your description up top you only added -days to the CA cert request and not your actual server cert request.

**Comment by ekaitz-zarraga** [comment]
I made it now just to make sure. We'll see what happens.
Thanks again for the help.

**Comment by pinheadmz** [comment]
Well waddaya know, here it is exactly 30 days later and again my cert expired...

**Comment by pinheadmz** [comment]
also @hoffmabc no idea why but the /util/Socket.js file in my application does not match the file on github:

https://pastebin.com/XATHUW7R (/Applications/OpenBazaar2.app/Contents/Resources/app/prod/utils/Socket.js)

vs:

https://github.com/OpenBazaar/openbazaar-desktop/blob/master/js/utils/Socket.js

**Comment by pinheadmz** [comment]
Ok maybe it's the instructions at https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/ssl.md

should the last line have a `days 1024` command?

**Comment by pinheadmz** [comment]
@ekaitz-zarraga  I have solved this problem I think:

the instructions here:
https://github.com/OpenBazaar/openbazaar-go/blob/master/docs/ssl.md

are missing one more `-days 1024` at the very end of the last line, to make the `server.crt` certificate 1024 days until expiry. Otherwise, openssl gives it a default of 30. I'll make a PR.
