### ISSUE TITLE
OB forces launch of zcashd even if it's already running

### ISSUE THREAD

**Issue by rex4539** [OpenBazaar/openbazaar-go#805]
I'm running a Zcash full node and have zcashd running always.

When I launch OB it launches a new zcashd instance.

Can't it use the one already running?

Have a check during launch. If zcashd is already running, use it. Otherwise launch it.

**Comment by cpacia** [comment]
Unfortunately no it needs to be started with --walletnofiy option otherwise it wont receive push notifications of transactions. I suppose if you run it with that option it might work.
