### ISSUE TITLE
Vendor rejected order, reason: Buyer's identity signature on contact failed to verify

### ISSUE THREAD

**Issue by M0Rf30** [OpenBazaar/openbazaar-go#806]
When I click on green Buy button this message appears
`Vendor rejected order, reason: Buyer's identity signature on contact failed to verify`
Why? Looking at the code this message appears when the Ricardian contract struct returns with empty signatures. Am I wrong?

**Comment by cpacia** [comment]
Can you post what version you are using and the vendor's ID as well.

**Comment by M0Rf30** [comment]
client:
` v2.1.0.rc2.r0.g4efc83fc-1`
server:
`v0.11.0.rc2.r1.g8540a8a1-1`
VendorId:
`QmTnTmNjBwmKxoj4B6L1FPF6qjEP3wzqiaX3M66sj1w8H7`

**Comment by cpacia** [comment]
looks like the vendor is 10.0. I'll have to investigate.

**Comment by cpacia** [comment]
Closing because we've had several releases since and have not seen any reports of this error.
