### ISSUE TITLE
Publishing failed

### ISSUE THREAD

**Issue by rex4539** [OpenBazaar/openbazaar-go#807]
OB 2.0.21

Reproducibility: always

Steps:
Launch OB.

What happened:
"Publishing failed" error message.

![screen shot 2017-12-31 at 20 02 40](https://user-images.githubusercontent.com/227442/34463468-b28bd8e2-ee65-11e7-828d-c3a152000832.png)

```
10:50:58.755 [SendRequest] [DEBUG] Sending STORE request to QmY8puEnVx66uEet64gAf4VZRo7oUyMCwG6KdB9KM92EGQ

10:50:58.755 [func1] [ERROR] Error pushing data to peer QmY8puEnVx66uEet64gAf4VZRo7oUyMCwG6KdB9KM92EGQ: failed to find any peer in table

10:50:58.755 [SendRequest] [DEBUG] Sending STORE request to QmPPg2qeF3n2KvTRXRZLaTwHCw8JxzF4uZK93RfMoDvf2o

10:50:58.755 [func1] [ERROR] Error pushing data to peer QmPPg2qeF3n2KvTRXRZLaTwHCw8JxzF4uZK93RfMoDvf2o: failed to find any peer in table

10:50:58.755 [Publish] [ERROR] failed to find any peer in table

10:50:58.755 [publish] [ERROR] failed to find any peer in table
```

[ob.log](https://github.com/OpenBazaar/openbazaar-go/files/1595396/ob.log)

**Comment by hoffmabc** [comment]
This looks more like a connectivity and server issue. @cpacia any ideas?

**Comment by cpacia** [comment]
Is this testnet? Sometimes on testnet the bootstrap fails because there's only two bootstrap peers.

**Comment by rex4539** [comment]
No, it's mainnet.

But it was related to the particular network I was connected at the time.

Now I'm back home and everything works fine.
