### ISSUE TITLE
Missing Payments

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#815]
We have multiple reports of buyers paying for transactions, but the transactions remain in the awaiting payment state for the vendor. This issue is where they should be reported so we can gather information about what might be causing it.

**Comment by morebrownies** [comment]
Yeah this is the issue I have experienced on multiple occasions

**Comment by cpacia** [comment]
@morebrownies can you send me the bitcoin.log for a node that has this issue

**Comment by AncientGuide** [comment]
Dealing with the same issue here.  Buyer says paid and awaiting acceptance...I see awaiting payment, no way to accept.  Have already reloaded.  Order number QmUvvZNUNk4VcCAdnEy6qr5NSMrBVicNFg7Gufk8t3dfdn

This one issue is killing the market for many people.  One time that money vanishes is all we get, so buyers are dropping like flies.

**Comment by hoffmabc** [comment]
Since the last release we haven’t seen to many additional complaints about this. Are you on the latest release? Are they not?

**Comment by jjeffryes** [comment]
This may be an example of errored offline orders that should be ameliorated by the PRs we're working on to show orders in an error state.

I don't know if there's an easy way to tell until that work is done and released. 

@AncientGuide does the buyer have the option to cancel the order when they look at it in their Purchases page?

**Comment by AncientGuide** [comment]
Honestly I'm very not tech.  I'm not sure how to tell what version I'm on,
so i'm going to guess that I'm out of date.  How would I remedy that?

Thanks for the quick response, I know you guys have a ton to do.  I love
OB2, you guys are awesome!

**Comment by AncientGuide** [comment]
Nvm, figured out hot to check for updates.  Using current version already.
Buyer does have cancel option.  Should I have them cancel and order again?

Thank you

**Comment by jjeffryes** [comment]
@AncientGuide you can also open the about section from the navigation menu, it shows the version number.

Your buyer can cancel their order, that will subtract a bitcoin network fee to move the funds back to them, they should be aware of that. It's possible to get into a situation where you cancel an order for $5, but the fee is $6 and nothing comes back.

If you're on the latest version and so is the buyer, the most likely explanation is something is preventing your node from seeing their payment. Normally resyncing will fix that.

**Comment by AncientGuide** [comment]
Thanks for the help and advice.  How would I go about ordering from myself
as a test to make sure payments go thru?
 Thanks again

**Comment by jjeffryes** [comment]
The simplest way to order from yourself is to install OpenBazaar on a 2nd computer or a virtual machine.

There are ways to have two installations on one computer, but they require some command line tinkering and editing config files.

**Comment by AncientGuide** [comment]
10-4.  Thanks for the help.

Have a good one

 As a side note:  Any way to promote OB2 in general?  Free market is
future.

**Comment by AncientGuide** [comment]
Payments still not going thru.  Both are updated.  Can cancel on buyers
side, showing awaiting payment on mine.  Any thoughts?

Thanks

**Comment by AncientGuide** [comment]
Hello again,
I've continued trying to use OB2 and am still running into problems.  I
still cannot accept payments from buyers, and now I attempted to deposit
funds into my wallet and they show, but will not confirm.  Wallet shows
zero confirmations, network shows 37+.
My funds are not touchable to me right now since they wallet wont accept
the payment.

Any help would be great

**Comment by placer14** [comment]
@AncientGuide I'm not sure if you're still interested in assistance, but if so please open a support ticket at https://openbazaar.zendesk.com/ and mention this issue.
