### ISSUE TITLE
Vendor Rejected Order: Different Payment Amount

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#818]
When testing the BCH implementation, I was able to purchase a test listing several times. 

One of the times I attempted to purchase it, the server sent back a 500 error from the purchase API with this message:

```
 "reason": "Vendor rejected order, reason: Calculated a different payment amount"
```

The listing was
ob://QmWqVgN2CtEgWgSXTfWHDoEhXXf26oZdfehPsCCWLZ4BB6/store/test-bch-product

**Comment by jjeffryes** [comment]
After seeing this error, the same error occurred the next 4 times I attempted the purchase.

**Comment by jjeffryes** [comment]
It looks like this affected all purchases. I shut down my server and restarted it, and it stopped showing that error.

**Comment by cpacia** [comment]
I looks like your exchange rates may have been incorrect. That's why when you restarted it worked. Not sure why they would have been off. Unless there was some networking issue affecting the exchange rate API call.
