### ISSUE TITLE
Quasi-DDoS on 2.0.21 OSX

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/openbazaar-go#827]
DD-WRT load averages soon after I had forced a dynamic IP reassignment & launched OB, IIRC: 1.52, 0.8, 0.75 & active IP connections: in the 1000-1100 range, most of them to my OB client/server LAN IP & 4001 TCP (forwarded).

The load averages were persistently higher than below, no matter whether I had turned my store off & quit OB, or had OB open but store off, or had OB open and store on.

Current DD-WRT load averages after I forced a dynamic IP reassignment and have not relaunched OB: 0.01, 0.03, 0.00 | 0.01, 0.02, 0.00 | 0.02, 0.03, 0.00 & active IP connections: 142 (59 of those just from me to my router). 

I wouldn't have known to check my router portal if my tablet wasn't being dropped from WiFi & unable to reacquire at the same time the load averages were that high. The OB desktop client/server is wired-only. I'd also been having wired network services (like IRC, Mumble, HTTP) disconnect and reconnect. I'll update this if wired or wireless starts failing again despite no OB target-painting.

**Comment by placer14** [comment]
Please reopen if issue persists with steps to reproduce.
