### ISSUE TITLE
2018/01/18 15:27:57 http: TLS handshake error from 127.0.0.1:4001: EOF

### ISSUE THREAD

**Issue by aSocialMenace** [OpenBazaar/openbazaar-go#829]
trying to install this for over a week on my google cloud platform VM.... i cant get past this handshake error! This is the error is the error i get if i dont mod the gateway in the config file leaving it like 
"Gateway": "/ip4/127.0.0.1/tcp/4002"
results in
2018/01/18 17:37:16 http: TLS handshake error from 127.0.0.1:4001: EOF
2018/01/18 17:37:41 http: TLS handshake error from 127.0.0.1:56922: EOF

however if i change the gateway ip to the gateway ip to the actually gateway of my VM instance
"Gateway": "/ip4/10.142.01/tcp/4002",
the server crashes instantly with no error message at all... If i change the gateway ip addres to 
"Gateway": "/ip4/0.0.0.0/tcp/4002",
then i get the above handshake error plus a few more... 
2018/01/18 17:16:38 http: TLS handshake error from 127.0.0.1:4001: EOF
2018/01/18 17:16:38 http: TLS handshake error from [::1]:4001: EOF
2018/01/18 17:16:38 http: TLS handshake error from 127.0.0.1:51650: EOF
2018/01/18 17:16:38 http: TLS handshake error from [::1]:55732: EOF
2018/01/18 17:17:40 http: TLS handshake error from 127.0.0.1:52358: EOF
2018/01/18 17:17:40 http: TLS handshake error from [::1]:56440: EOF
2018/01/18 17:17:58 http: TLS handshake error from 127.0.0.1:4001: EOF
2018/01/18 17:17:58 http: TLS handshake error from [::1]:4001: EOF

I am almost positive that my firewall ports are open and after some time i discovered that google cloud platform does not support RSA-4096 so i deleted my ssl crt key and csr files for both the rootCA and server and re made them with the google cloud platform compatible RSA-2048 encryption and i still get the same errors... i have tried everything i can think of and still cant figure out what the heck is going on here... I have tried turning the ssl to false in the config file and when i do the handshake error goes away but this is obviously not ideal and i still cant get my client side to connect even with no handshake error from the server side...  Is this a problem with the google cloud platform service? any help would be greatly appreciated!!

**Comment by cpacia** [comment]
Is the client connecting using SSL?

**Comment by aSocialMenace** [comment]
the handshake error happens as soon as the server boots up... before the client even tries to connect. i can set ssl to false in the config file and the handshake error goes away however my client is still unable to connect. The server says its listening on tcp 4001 and i can ping the ip of the server from the client so i to me it looks like a firewall issure however the google tech guy says it should be configured correctly...

**Comment by aSocialMenace** [comment]
Ok.. i have attempted to install this server on my raspberry pi 3 on the same network as my desktop client and i still get the handshake error.. whats happening here? I have tried connecting to my pi server with the local ip and the public ip with no luck.... also if i turn ssl to false in the config file the server stops haveing the handshake error however i still cant connect to it with my desktop client... I must be doing something wrong here right? i have tried this no less than 50 different times on the google cloud platform server and a dozen times now on my pi and i keep getting the same results ... :(

**Comment by aSocialMenace** [comment]
UPDATE!! i was able to connect to my pi server!!! after changing the gateway address 
"Gateway": "/ip4/0.0.0.0/tcp/4002",
and turning SSL to false and deleting the path to the server.crt and server.key files inside the config file i was able to connect with my desktop clint (running on linux mint btw)!!!!!! 
"JSON-API": {
      "AllowedIPs": [],
      "Authenticated": true,
      "CORS": null,
      "Enabled": true,
      "HTTPHeaders": null,
      "Password": "iknowthisisencryptedanywaysbutistillaintgonnapostitherelol",
      "SSL": false,
      "SSLCert": "",
      "SSLKey": "",
      "Username": "keepingitseceret"
however... when i set the SSL to ture and give it the correct file paths for my server.crt and server.key files i go right back to the handshake errors
"JSON-API": {
      "AllowedIPs": [],
      "Authenticated": true,
      "CORS": null,
      "Enabled": true,
      "HTTPHeaders": null,
      "Password": "iknowthisisencryptedanywaysbutistillaintgonnapostitherelol",
      "SSL": true,
      "SSLCert": "/home/pi/.openbazaar2.0/server.crt",
      "SSLKey": "/home/pi/.openbazaar2.0/server.key",
      "Username": "keepingitseceret"
now i downloaded the openbazaar.crt and installed it however the handshake error happens almost as soon as the server boots up... way before i try to connect with the client.. this has to be a server side error right?

**Comment by aSocialMenace** [comment]
ok guys i figured out what was happening! my first problem was that my gateway address needed to be set to 0.0.0.0 and even tho that still gave me handshake errors before i tried to connect the client. That was a big hang up for me.. I was under  the impression that the server waited for the client to send its hello message so when i seen the handshake error without a client even trying to connect i figured there was a problem... live and learn right lol... Any how that was only part of my problem... My biggest problem was that i was trying to connect from a client that was running linux mint... As it turns out its a bit of a process to get linux accept a cert that is signed from an untrusted source or a self signed cert...  I found some great instructions for how do this here
https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list#90607
