### ISSUE TITLE
Dispute opened, Moderator cannot see dispute

### ISSUE THREAD

**Issue by MinaZ23** [OpenBazaar/openbazaar-go#832]
2/3 parties cannot see the order, only the buyer can and it is paid, so it cannot be disputed to cancel and redo the order and it cannot be fufilled.  Moderator has nothing regarding the dispute!

I have another ticket about me as a seller not getting the sale notification OR seeing it in my sales, so this issue could be related BUT it seems like a separate issue since it doesn't relate to the seller issue.

So after the sale never showed up after a day and every recommended fix (opened port 4001, restarted the server/ob program multiple times, reloading transactions) it never worked.

SO the buyer decided to dispute so he could cancel, as we read that this bug happens but we could cancel and redo the order and that worked for many peple.

WELLLL.....the stuff hit the fan, the moderator is having the same issue as me with the dispute, no notification and nothing showing up under disputes/cases etc.  So the order cannot be cancelled using 2/3 parties because 2 of the parties cannot see the order.  Is there anything the Moderator can do to try and retrieve the transaction?  It seems to be stuck in the DHT or something.

ALSO, do transactions auto cancel or auto finalize or is this coin gone forever unless it somehow appears for the Moderator (or the seller)?

**Comment by jjeffryes** [comment]
@MinaZ23 if we can get the logs from all 3 parties, we may be able to determine where the bug is. I'll let @cpacia explain which logs he needs, and how to get them to him.

**Comment by MinaZ23** [comment]
Ok, I am obtaining the logs (ob.log) from parties
@cpacia do I send them to you here?  via email to you?  or to an OB support email?  Just let me know how to proceed

**Comment by cpacia** [comment]
@MinaZ23  Based on the logs it looks to me like he tried ordering too much inventory and it did not handle it properly. I believe I should be able to write a patch that can force your node to reprocess the message and it should send the funds back to him.

**Comment by MinaZ23** [comment]
that would work great, or if I can see it on my end I can cancel the order, or of the mod can see it then he can.  Whatever works would be great

**Comment by MinaZ23** [comment]
@cpacia So is it resolved with the outcome you suggested?  I was hoping that the sale could be fixed to go through the normal process, but if your solution is the only outcome that is better than funds being lost for the buyer.  We worked out a direct deal, with the buyer sending me half of the funds privately (I know this is not OBs issue) and agreeing to pay the rest when he got his funds back as we were confident there would be a way to recover the funds.  

We wanted to see if the sale could be created and "retry" my server and go through the normal process, or get seen by the moderator and work normally.  That way we still have a paper trail of the transaction and don't have a chance of the transaction vanishing like this, and then the buyer as well once he gets the goods and automatically receives the funds.

**Comment by MinaZ23** [comment]
Oddly enough, another sale is having the same issue.  It is someone from Germany, while I am in USA. I am hoping that perhaps the contract will show up for vendor and/or moderator over a little more time since it my have longer to travel over a peer to peer network....but that seems to be wishful thinking as I know it should have arrived by now.

**Comment by cpacia** [comment]
The last few releases have overhauled the message handling and it seems to be working fairly well right now.
