### ISSUE TITLE
tor controls unavailable 

### ISSUE THREAD

**Issue by aSocialMenace** [OpenBazaar/openbazaar-go#833]
trying to get my server up and running through tor now.. i keep getting this error
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.11.0
[Press Ctrl+C to exit]
2018/01/22 00:19:03 Migrating repo to version 6
Tor control unavailable
exit status 1

anyone have any ideas why this is happening? i running the server on google cloud platform I have not set up a password for tor and i have modified my config file with the prefix of my .onion-key file in .openbazaar2.0 per the instructions in tor.md. I have confirmed that to is up and running and listening on port 9050. one thing i should add... in my config file i had to change the gateway from 127.0.0.1 to 0.0.0.0
"Gateway": "/ip4/0.0.0.0/tcp/4002",
for the life of me i could not get my server to connect with it set at 127.0.0.1.... Could this be part of my problem? do i need to somehow change the torrc file to reflect this??

**Comment by aSocialMenace** [comment]
Ok so here is what i have tried... 
ive gave tor a password and passed the unhashed password in the config file.. i have also changed the control port to 9051 in the torrc file and nothing..
i tough perhaps the gateway address being set up to 0.0.0.0 in the config file might be a factor however i CANNOT for what ever reason get the client to connect with it set to 127.0.0.1 or using the phrase localhost.. however i was able to change it to the local ip address of the linux instance of my server.. this let me connect just fine! but not when i try to enable tor :( i have tried editing the torrc file to SocksListenAddress 127.0.0.1 and i tried ever possible combination above and when that didnt work i tried
SocksListenAddress 0.0.0.0 and again ive tried every possible combination of gateway ip password and tor control address in the config file that applies wand when that didnt work i changed 
SocksListenAddress <my local ip address> and again... ever combination of different settings i could think of... i can confirm that running 
sudo netstat -plnt | fgrep 9050
and its listening to port 9050... am i missing something? what could be the problem here???

**Comment by cpacia** [comment]
what are you using for the tor control port? It should either be 9051 or 9151.

**Comment by aSocialMenace** [comment]
THANK YOU!! That was the problem!!! i found the line where it said ControlPort 9051.. it was still commented out but i deleted the # then jumped over to my config file and passed 'localhost:9051" into the tor config section and im up and running! lol i think i hit about ever snag possible getting this going.. I might do a youtube video cuz I would be very good at telling people what not to do
