### ISSUE TITLE
Transaction ERROR state and rejection message

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#838]
When a vendor node receives an order for an out of date listing, the order should be processed as normal instead of being rejected.

When a vendor node automatically rejects an offline order, that order should have it's state set to ERROR_PENDING, and a reject message should be sent to the buyer, so the buyer node can also set the state to ERROR_PENDING.

The order details API should include the reason the order was rejected, so it can be displayed to the user.

**Comment by cpacia** [comment]
Done
