### ISSUE TITLE
Rebase to the Latest Version of IPFS

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#842]
Rebase the server to use the latest version of IPFS.

**Comment by camelmasa** [comment]
Latest IPFS adds "Core API" https://blog.ipfs.io/34-go-ipfs-0.4.14#ipfs-core-api.

I think we can refactor any [IPFS codes](https://github.com/OpenBazaar/openbazaar-go/tree/master/ipfs) by official Core API way.
