### ISSUE TITLE
Merchant cannot finalize payment when releasing funds from escrow

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#850]
https://github.com/OpenBazaar/openbazaar-go/blob/v0.11.1/core/completion.go#L339 should be corrected to FINALIZE_PAYMENT on the Sale and not the Purchase

**Comment by placer14** [comment]
This might fix #849 as well?

**Comment by rmisio** [comment]
> should be corrected to FINALIZE_PAYMENT on the Sale and not the Purchase

To be clear, the order state for both the vendor and buyer should be set to PAYMENT_FINALIZED.

**Comment by placer14** [comment]
It appears the work has already been completed in f5e6490a8. Have been able to verify that this problem no longer occurs and that the merchant was able to successfully release their funds.
