### ISSUE TITLE
Opt-in proof of transaction

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#86]
For the purposes of generating OpenBazaar statistics, I think it would be useful for buyers to be able to submit an opt-in proof of transaction, similar to leaving a rating (with is both a proof of transaction and a rating). This would effectively be an "empty rating".

**Comment by cpacia** [comment]
Submit it to where?

**Comment by JustinDrake** [comment]
@cpacia To the IPFS network, just like ratings.
