### ISSUE TITLE
Erroneous 'insufficient funds' error

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#864]
Migrating this over from the client repo:
https://github.com/OpenBazaar/openbazaar-desktop/issues/1216

Brief Description: 
I'm using the BCH wallet in release 2.1.0, server version 0.11.0. I just funded my wallet, had 2 confirmations. I tried to send BCH to another address and I get an insufficient fund error:

![image](https://user-images.githubusercontent.com/9870991/35653923-3e95c5ea-069f-11e8-8481-9a24b540657a.png)

Luckily, I had the debug window open in the Electron app and I was able to catch the API request. One thing I noticed is that the amount requested is 136585. Very weird.

![image](https://user-images.githubusercontent.com/9870991/35654000-9b0ea35a-069f-11e8-9ec2-74bd5ca36550.png)

Operating System (OS and version): Windows 10 Home
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: Intel i7 processor. 12GB or RAM.

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by rmisio** [comment]
I'm experiencing this as well. I have 13 tbch in my wallet and getting insufficient funds from the estimatefee and purchase apis when attempting to spend 0.00075297 BCH.

`http://localhost:4102/wallet/estimatefee/?feeLevel=NORMAL&amount=75297`

returns:

```
{
    "success": false,
    "reason": "insuffient funds"
}
```

**Comment by cpacia** [comment]
I think we narrowed this down to people who failed to properly migrate the release candidate.
