### ISSUE TITLE
Publish semi-realtime listing inventory availability for vendor to IPFS

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#875]
We would like to make it possible for buyers to retrieve an available inventory for a listing that is as up to date as is feasible. 

There should be a server API endpoint that will return the latest known available inventory for a listing when sent the listing's peerID and slug.

We discussed various ways the inventory could be stored on IPFS that would not invalidate the root directory caching for less frequently updated data. Possibly we would save a second root directory for the inventory. Ideally this would not require changes to the IPFS code.

### Assumptions
- The inventory will be set in each listing as it is now, and updated when inventory is purchased, with no modifications needed to those APIs. Inventory should not be changeable in any  other way.
- When inventory is retrieved from offline nodes by getting cached data from peers, it represents the most recent available data, and may be inaccurate. 

#### General
- [x] All inventory endpoints should return data if possible even when the node with the inventory is offline or unreachable.
- [x] All inventory endpoints should return a date time in milliseconds for the last time the inventory was updated.
- [x] All inventory endpoints should accept a "useCache" parameter, which specifies whether the server can use cached data or not. This parameter should be a boolean.
- [x] If no inventory data can be retrieved, a human readable error message and an error code for internationalization should be returned.
- [x] For now the inventory APIs should ignore variants inventory. In the future we would want to include something like an array of SKU objects with a name composed from the variant names and a quantity, like "SKU: red-large, quantity: 5".

- [x] There should be an API endpoint to retrieve the last known inventory of a listing.
    - This endpoint URL should include the peerID and slug for the listing.
    - This endpoint should accept a useCache parameter.
    - This endpoint should return a last updated value.
	
Example data sent:
URL: /ob/listingInventory/QmV2xo6De168QB9nkrYYuj6FVJeeczz9KEn1M2YTARLoNb/red-shoes
```
{
  useCache: false
}
```

Example data returned:
```
{
  slug: "red-shoes",
  inventory: 32,
  lastUpdated: 1522248609937
}
```

- [x] There should be an API endpoint to retrieve the last known inventory of all the items in a node.
    - This endpoint should return an array of inventory objects with slugs.
    - This endpoint URL should include the peerID.
    - This endpoint should accept a useCache parameter.
    - This endpoint should return a last updated value.
	
Example data sent:
URL: /ob/inventory/QmV2xo6De168QB9nkrYYuj6FVJeeczz9KEn1M2YTARLoNb/
```
{
  useCache: true
}
```

Example data returned:
```
{
  [
    {
      slug: "red-shoes",
      inventory: 32,
      lastUpdated: 1522248609937
    },
    {
      slug: "green-shoes",
      inventory: 4,
      lastUpdated: 1522258813435
    }
  ]
}
```

**Comment by placer14** [comment]
The thinking @cpacia and I had was to provide another IPFS root which might be used for highly-volatile data (in contrast to the listing data which is, comparatively, less-volatile). For now, just inventory availability per listing, but potentially other things, too (like public state for followers, followings, etc).

An example config structure might look like this:
```
localconfig/
├── blocks
│   └── _README
├── config
├── datastore
│   └── mainnet.db
├── datastore_spec
├── headers.bin
├── keystore
├── logs
│   ├── api.log
│   ├── bitcoin.log
│   ├── ipfs.log
│   └── ob.log
├── outbox
├── peers.json
├── repover
├── root
│   ├── channel
│   ├── feed
│   ├── files
│   ├── followers.json
│   ├── following.json
│   ├── images
│   │   ├── large
│   │   │   └── c18.png
│   │   ├── medium
│   │   │   └── c18.png
│   │   ├── original
│   │   │   └── c18.png
│   │   ├── small
│   │   │   └── c18.png
│   │   └── tiny
│   │       └── c18.png
│   ├── listings
│   │   └── hugs.json
│   ├── listings.json
│   ├── posts
│   ├── profile.json
│   ├── ratings
│   │   └── QmYsgA2ZB1af.json
│   ├── ratings.json
│   └── user_agent
├── highly_volitile_root   # new IPFS root
│   └── inventory.json
└── version
```

**Comment by placer14** [comment]
@jjeffryes I added `slug` to the product inventory return object.

Additionally, could we make the related API requests nested?
`/ob/inventory/` # existing. returns local inventory
`/ob/inventory/:peerID` # returns inventory about peerID
`/ob/inventory/:peerID/:slug` # returns inventory about peerID's slug

**Comment by jjeffryes** [comment]
@placer14 what would we use the call to retrieve your own inventory for?

**Comment by rmisio** [comment]
> what would we use the call to retrieve your own inventory for?

Anytime our node node needs the inventory on listing detail, purchase, etc... we could call the local call and save a super latent ipfs call. My plan would be to abstract that all away in an inventory utility module.

**Comment by jjeffryes** [comment]
> Anytime our node node needs the inventory on listing detail, purchase, etc... we could call the local call and save a super latent ipfs call. My plan would be to abstract that all away in an inventory utility module.

Ok. I was assuming the server would know not to go to IPFS if you were calling your own peerID.

**Comment by jjeffryes** [comment]
@placer14 are you saying to get the inventory of your own (singular) listing, you'd call
`/ob/inventory/:slug`?

**Comment by rmisio** [comment]
> There should be an API endpoint to retrieve the last known inventory of all the items in a node.
> This endpoint should return an array of inventory objects with slugs.

Could it instead return an object keyed by slug? This would make lookups easier and I'm not seeing any benefit from the fact that arrays are ordered.

For example:

```
{
  red-shoes: {
    inventory: 32,
    lastUpdated: 1522248609937
  },
  green-shoes: {
    inventory: 4,
    lastUpdated: 1522258813435  
  },
}
```

**Comment by rmisio** [comment]
> lastUpdated: 1522258813435

I know this is probably just a placeholder, but I assume we'll stick with the ISO time format the server uses everywhere else?

**Comment by rmisio** [comment]
> Ok. I was assuming the server would know not to go to IPFS if you were calling your own peerID.

Yeah, I think that's better and I believe how the server does it with some other calls. @placer14 Can the server abstract the local and ipfs inventory into one call so if you're calling from your own node, it gets it from the db, otherwise from ipfs?

**Comment by rmisio** [comment]
> All inventory endpoints should return data if possible even when the node with the inventory is offline or unreachable.

This may be semantics, but if the node is unreachable and useCache is false, I think the endpoint should return an error.

**Comment by cpacia** [comment]
I think rather than having the inventory file nested inside another root directory I think it would be more efficient to publish the inventory file hash directly at `/ipns/<peerID>/inventory`. That way it saves an IPFS lookup.

**Comment by jjeffryes** [comment]
> Could it instead return an object keyed by slug? 

Sounds fine to me.

> I know this is probably just a placeholder, but I assume we'll stick with the ISO time format the server uses everywhere else (e.g. 2037-12-31T08:00:00.000Z)?

We can do that. I was thinking milliseconds would be convenient, but it's not a big deal either way.

> This may be semantics, but if the node is unreachable and useCache is false, I think the endpoint should return an error.

Good point, that should be specified.

**Comment by rmisio** [comment]
> This may be semantics, but if the node is unreachable and useCache is false, I think the endpoint should return an error.

> Good point, that should be specified.

I think it's just a matter of removing "or unreachable" from that bullet point.

**Comment by placer14** [comment]
> @placer14 are you saying to get the inventory of your own (singular) listing, you'd call
/ob/inventory/:slug?

That endpoint (`/ob/inventory`) already exists. I was just trying to follow the convention we already had in the API.

**Comment by jjeffryes** [comment]
> That endpoint (/ob/inventory) already exists. I was just trying to follow the convention we already had in the API.

We can use a different endpoint to avoid confusion, it seems to me like the functionality here is a little different, and there's not POST option for individual listings.

**Comment by rmisio** [comment]
> We can use a different endpoint to avoid confusion

It would still be nice if the server could abstract the other end point to pull from the db it called from your own node.

> and there's not POST option for individual listings.

I think setting the inventory on an individual listing is done via the listing POST/PUT APIs.

**Comment by jjeffryes** [comment]
> I think setting the inventory on an individual listing is done via the listing POST/PUT APIs.

You can use the POST to /inventory to set the inventory on a single listing (I don't think that's currently used anywhere), but it doesn't follow the pattern above, instead you send the slug and variant in the data.

Should the current inventory call be updated to return data the way we're proposing here? Currently it looks like this:

```
[
  {
    "quantity": 0,
	"slug": "test-inventory",
	"variant": 1
  },
  {
    "quantity": 0,
	"slug": "test-inventory",
	"variant": 7
  }
]
```

**Comment by rmisio** [comment]
> We can do that. I was thinking milliseconds would be convenient, but it's not a big deal either way.

The absolute timestamp would allow you to compare between two fetches to know which one was more recent. And, if you need ms since that date, it can be easily determined.
