### ISSUE TITLE
Listing POST returns nothing on success which is invalid JSON

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#88]
A successful POST to /ob/listing/ returns nothing. This results in an error on the client because an empty response body is not valid json:

![image](https://cloud.githubusercontent.com/assets/794517/17794120/77635da0-6561-11e6-98b3-de801a209500.png)

If the response will not return anything useful (like the created listing, or the listing id / hash), the expectation is that it would at a minimum return an empty object (which is valid json).

**Comment by cpacia** [comment]
Maybe you did a pull immediately after I changed it but before I reverted it. If you do a git reset --hard orgin/master it should fix it
