### ISSUE TITLE
Seller Has Dispute Button Before Fulfilling order

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#881]
The dispute button is present and clickable for the seller when the order is accepted, but not fulfilled. Attempting to start a dispute shows a server error.

The button shouldn't show when it's not usable, should it?

![image](https://user-images.githubusercontent.com/1584275/37290826-a80e6c76-25e3-11e8-9ac8-7638a8f7001b.png)

![image](https://user-images.githubusercontent.com/1584275/37290841-af95ea28-25e3-11e8-8b9a-e418f7d174ea.png)

**Comment by rmisio** [comment]
Should this be in the desktop repo?

**Comment by jjeffryes** [comment]
> Should this be in the desktop repo?

Yep. I'll move it.
