### ISSUE TITLE
Public PGP keys for encrypting shipping information

### ISSUE THREAD

**Issue by aSocialMenace** [OpenBazaar/openbazaar-go#882]
Hey I know I am a noob here and I might be missing it.. But why doesn't OpenBazaar have a method of sending your shipping information more securely? Markets on the dark net use PGP keys so buyers can encrypt their shipping information so that only the sellers can read it. Can OB incorporate a PGP encryption?   Or is it not necessary for some reason?

**Comment by cpacia** [comment]
All messages are automatically encrypted and authenticated using your Peer ID so PGP is a bit redundant. Some people have used PGP to pushed a signed message in their profile saying "my OpenBazaar ID is xxxxx" which has the effect of linking their peer ID to their outside PGP identity so people know both identities are the same person. But that's the most that would be needed.

**Comment by aSocialMenace** [comment]
Awesome! Thanks for clearing that up!!
