### ISSUE TITLE
Investigate invalid IPNS responses being served by gateway

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#883]
I'm seeing some weird behavior where our gateway node is serving a few IPNS records with invalid signatures (or at least they aren't validating). But it's weird because it shouldn't be saving any records to the db where the signature is invalid. If you get some free time can you take a look.

Gateway saves records to the db here: https://github.com/OpenBazaar/openbazaar-go/blob/master/vendor/github.com/ipfs/go-ipfs/namesys/routing.go#L222

Gateway servers records here: https://github.com/OpenBazaar/openbazaar-go/blob/master/api/jsonapi.go#L3565

Clients download and validate record here: https://github.com/OpenBazaar/openbazaar-go/blob/master/core/ipns.go#L50

I believe this record is invalid QmVcptcHa49avLnz78Uf7894pBPWfMEaUEt56ijxwmFEsx.

This is a problem because nodes receiving invalid responses are communicated to the user as if the record was not found/couldn't be retrieved. The gateway is a last resort for retrieving a record after searching the DHT and failing.

**Comment by cpacia** [comment]
We've moved off of using the gateway for records and we now use our new tiered routing infrastructure.
