### ISSUE TITLE
User should be able to post a crypto listing

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#885]
Completes #876 in part...

- [x] Express unique type of `metadata.contractType` to represent crypto listings. (replace `AUCTION` type)
- [x] Express unique type of `metadata.format` to represent that the price should reflect Market Value. (referred to as listing "Market Value" format)
- [x] Express new `metadata` field which indicates the type of coin for sale in the listing. (referred to as the listing coin type)
- [x] When `metadata.contractType` reflects a new crypt listing, the server should not persist values for the following fields:
    - pricingCurrency
    - price
    - condition
    - options
    - shippingOptions
    - coupons
- [x] When `metadata.contractType` reflects a crypto listing, the server should return an error if any of the following objects are sent with a value:
    - pricingCurrency
    - condition
    - options
    - shippingOptions
    - coupons
- [x] When `metadata.contractType` reflects a crypto listing, the server should return an error if the `coinType` is empty
- [x] When `metadata.format` is set to "market value", the server should return an error if `item.price` is not zero. 
 - [x] When `metadata.contractType` reflects a crypto listing, the server should set `format` to `MARKET_PRICE`

Example listing:
```
{
   "termsAndConditions":"test",
   "refundPolicy":"test",
   "item":{
      "title":"ZEC for Sale",
      "description":"I am selling 1.5 ZEC.",
      "tags":[
         "ZEC",
         "Zcash"
      ],
      "categories":[
         "crypto"
      ],
      "nsfw":false,
      "condition":"", // should be blank
      "images":[
         {
            "filename":"cryptoImage.jpg",
            "original":"zb2rhkeGuSRJe9eKdiPAoNXRtc2APEqR8YcKwLaer75bJZrkF",
            "large":"zb2rhkfkVTD1opwgSz3i6oMKm1Uwesqzxn4SHBhb5aFsyxjcY",
            "medium":"zb2rhkJXrP7Vp5oP4EMVDEhVPweZDw8GmBvQjkcw7pKPx1uCL",
            "small":"zb2rhf5SNn6MdZL8BXeg6WcTn8tBrN6PyZS3d2YdaYrPEXo1d",
            "tiny":"zb2rhdZ7MLdpQne12gigyowCzCRBZLtgUJz4zSfnzLkSHES1s"
         }
      ],
      "options":[], // should be empty
      "skus":[
         {
            "quantity": 150000000  // this represents 1.5 ZEC 
         }
      ],
      "price":0 // should be zero
   },
   "metadata":{
      "contractType":"CRYPTO_CURRENCY",
      "format":"MARKET_VALUE",
      "expiry":"2037-12-31T05:00:00.000Z",
      "pricingCurrency":"", // should be blank
      "coinType":"ZEC"
   },
   "shippingOptions":[], // should be empty
   "coupons":[]  // should be empty
}
```

**Comment by jjeffryes** [comment]
> When metadata.contractType reflects a crypto listing, the server should return an error if the coinType is not empty

Should that be "is empty"?

**Comment by placer14** [comment]
Thanks @jjeffryes, corrected.
