### ISSUE TITLE
Multi-Coin API Based Wallet

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#897]
## User Story: 
As a user, I want the option of using an external API for most of my wallet functionality, so I can run a light application on a mobile device, low powered computer, or web site.

As a user, I want to be able to run multiple wallets at the same time, so applications can be built that support multiple crypto currencies in a single user node simultaneously.

### General
- [ ] The API calls made to the server and the data returned from those calls should remain the same as much as possible.
- [ ] Using an external API should reduce the security of the user's data as little as is feasible.

### Setup 
- [ ] It should be possible to set the crypto currencies used by a node and whether it uses a web API for its wallets in the config file.
- [ ] There should be command line options for setting multiple crypto currencies when starting the server.
- [ ] There should be command line options for setting the wallet(s) to SPV or web API.
- [ ] If the node is using more than one crypto currency, the node must use a web API for its wallets.
- [ ] If a node is using a SPV wallet, it should only have one crypto currency.
- [ ] The config should be populated with default urls for the server endpoints that will be used for the web API wallet. If only an SPV wallet is being used, this data is optional.
- [ ] It should be possible to change the server endpoints that will be used for the web API wallet in the config file.
- [ ] If the server endpoints for the web API wallet are returning incorrect data, a human readable, actionable error message should be returned when the web API wallet is in use.

### API Changes
- [ ] If a crypto currency is sent as a parameter to any API and the node does not support it, a human readable, actionable error to that effect should be returned.
#### Wallet
- [ ] If a node has multiple wallets, all wallet APIs will need to accept a parameter for which crypto currency the call is using.
- [ ] If a node has only one wallet, the crypto currency parameter can be optional.
#### Listings
- [ ] The data for each listing should contain all the crypto currencies that can be used to purchase that listing.
- [ ] The listings API should include the crypto currencies that can be used to purchase each listing.
- [ ] It is assumed that in the current client/server implementation the crypto currencies the node supports will also be the currencies listed in that node's listings, and the listings will be updated if the crypto currencies of the node change. This isn't required by the protocol, so we should assume any listing may have a list of accepted currencies that does not match the currencies accepted by that node.
#### Purchase
- [ ] When a purchase is made, the purchase call should include a parameter for what crypto currency is being used for the purchase.
- [ ] The Estimate Fee API should accept a crypto currency as a parameter.
#### Profile
- [ ] Profile.currencies should have all the accepted currencies for that node.
- [ ] Profile.moderatorInfo.acceptedCurrency should have all the accepted currencies for that moderator's node.
- [ ] It is assumed it is possible for Profile.currencies to not be the same as Profile.moderatorInfo.acceptedCurrency, even if the current server implementation always makes them the same.
#### Transactions
- [ ] The purchases, sales and cases APIs should accept an optional crypto currency parameter, and return only orders using that crypto currency. All orders matching the other parameters would be returned if the crypto currency parameter was blank or not sent.
- [ ] The purchases, sales and cases APIs should return the crypto currency used with each returned purchase so the payment data can be displayed correctly if orders with more than one crypto currency are returned.
- [ ] The order API should return the crypto currency used to purchase the order.
- [ ] The case API should return the crypto currency used to purchase the order. If the moderator no longer supports that crypto currency, that will need to be handled somehow. 

### Complications from Dropping Currencies on a Multi-Currency Node
- If a node with multiple currencies drops one, but still has orders in process, it should still be possible to complete those orders. This may mean a node cannot fully drop a currency until all pending orders with that currency are completed. It might be able to remove that currency from it's accepted currencies so no new orders can be made with that currency.
- If a moderator is on an order in progress, they may drop the crypto currency the order uses, and then have a dispute started with that order. That scenario will need to be handled.

**Comment by placer14** [comment]
Closing as dupe.
