### ISSUE TITLE
"Unable to fetch order"

### ISSUE THREAD

**Issue by imaginaryusername** [OpenBazaar/openbazaar-go#902]
I have recently updated my OB from 2.1.0 RC to 2.1.1, on BCH server and migrated my wallet using [this tool](https://gist.github.com/cpacia/751589a9c70399713774a0ac5c954c15). Now my purchase history is no longer available - the list is still viewable, but when I click into an individual order it shows

```Unable to fetch order. sql: no rows in result set```

With a "retry" button doing nothing. This applies even to current in-progress orders that are not completed yes, so vendor is at risk of losing money since it's a 2-of-3 moderated order.

**Comment by cpacia** [comment]
Was this before or after you ran the command to update the store from the RC?

**Comment by cpacia** [comment]
Also going to close because I think this was an issue upgrading from the RC not an actual bug in the code. We are willing to help get it straightened out in slack.

**Comment by imaginaryusername** [comment]
This was after updating the store/wallet. I guess I'll need to download Slack finally...
