### ISSUE TITLE
Add -d option to start in daemon mode

### ISSUE THREAD

**Issue by arteniioleg** [OpenBazaar/openbazaar-go#903]
I downloaded the server binary from the [Releases](https://github.com/OpenBazaar/openbazaar-go/releases) page on my VPS.

I start it manually in backgroud like this:

```
openbazaar start &
disown $(pidof openbazaar)
exit
```

I wan't it to start automatically after VPS reboot but adding it to cronjobs doesn't start it:

```
crontab -l

...
@reboot openbazaar start
```

----

For example [Resilio](https://www.resilio.com/individuals/) is starting by default in background and adding it to cronjobs as described above works fine.

**Comment by cpacia** [comment]
I've tried finding libraries to do this in the past and couldn't get them working. Other than writing a bunch of code to do the unix double fork I've found the easiest way is to just use `nohup`.

**Comment by arteniioleg** [comment]
I've heard about `nohup` and `disown` but I am newbie in this unix internals stuff.

If you would add in README "The recommended way to start the server in background" that will be enough for me (I will just copy paste the solution).

**Comment by cpacia** [comment]
`nohup ./openbazaar-go start [options] &` should work.

**Comment by arteniioleg** [comment]
I just found out that in crontab you must use absolute patsh (`PATH` variable seems to be missing)

So these work (tested)

```
@reboot ~/soft/bin/openbazaar start
@reboot /usr/bin/nohup ~/soft/bin/openbazaar start &
```
