### ISSUE TITLE
Include remaining inventory and err-code in error response if purchase fails due to insufficient inventory

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#904]
for example:

```
{
  reason: "not enough inventory",
  code: "ERR_INSUFFICIENT_INVENTORY", // allows us to show a translatable message
  remainingInventory: "100", // allows us to update the UI so the user can't enter a value above 100 just to have it fail on the server
}
``` 

![image](https://user-images.githubusercontent.com/794517/39216538-fa27c502-47d0-11e8-8f86-71c6a11827be.png)

The main idea is for the UI to be able to make a more useful message than that ^^^. 1.) We could translate it into different langs 2.) We could convert the quantity from base units, since otherwise the user won't be able to make sense of it.

**Comment by cpacia** [comment]
So this should really only apply to online nodes. If we have to fetch the inventory for offline nodes on each offline purchase, it will double the amount of time it will take to complete an offline purchase... which is already takes upwards of 30 seconds to fetch the peerinfo from the DHT and attempt connection on each address.

**Comment by rmisio** [comment]
> So this should really only apply to online nodes.

ok, I don't have a strong opinion on that. But, I think it should apply any time you are failing the purchase because of insufficient inventory. If that's only on online orders, so be it.
