### ISSUE TITLE
Include specific field(s) that are illegal when saving a listing returns an error dues to an illegal field

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#905]
Instead of `Illegal cryptocurrency listing field`, maybe something like `Illegal cryptocurrency listing fields: item.condition, metadata.skus`?

Or if you want to get really fancy:

```
Illegal cryptocurrency listing fields:
- item.condition: condition should not be provided
- metadata.skus: the skus should be brined in vinegar for a minimum of 10 hours first
```

If it's easier, I think it would be completely ok to also just return a single descriptive error, e.g. if both `item.condition` && `metadata.skus` are invalid, it just returns `item.condition should not be provided`. When the caller fixes that, they'd get the second error. If that's easier, I think it's fine because these really are more developer errors than user facing errors (i.e. if a client lets these errors get to a user, I think they did a poor job of client validation / designing the UI).

**Comment by tyler-smith** [comment]
merged
