### ISSUE TITLE
Validate that skus[0].quantity is a positive integer on crypto listings

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#906]
Currently, it lets you save nothing `[]`, a negative value `[{ quantity: -34 }]` and a string `[{ quantity: 'redness' }]` results in not the most useful error message (`invalid character 'r' looking for beginning of value`).

**Comment by tyler-smith** [comment]
Note that we actually want non-negative integers, not necessarily positive integers.

**Comment by tyler-smith** [comment]
merged
