### ISSUE TITLE
Add coinType to the listings api for cryptocurrency listing.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#907]
title says it all.

**Comment by tyler-smith** [comment]
@rmisio by search api you mean in the OB1 search? If so, that should be a separate issue in https://github.com/OpenBazaar/obips/issues I think.

**Comment by rmisio** [comment]
> by search api you mean in the OB1 search? If so, that should be a separate issue in https://github.com/OpenBazaar/obips/issues I think.

done:

https://github.com/OpenBazaar/obips/issues/33

**Comment by tyler-smith** [comment]
merged
