### ISSUE TITLE
There is not well-functioning update Listing API.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#91]
Currently, there is only a POST API available to create / update a listing. It is in-adequate in regards to updating a listing for a couple of reasons:

1.) There is no way for the API consumer to express their intention on whether they want to update an existing listing vs. create a new one. For example, if your intention is to create a new listing, and you send a POST with a slug that, unbeknownst to you, is already associated with an existing listing, you will be overwriting the existing listing.

Expected result:
In this case, the expectation would be that the API returns an error like 'Slug already exists'.

2.) If you attempt to change the slug of an existing listing, the old listing still remains and a "copy" of the new one is created with a new slug (and any other fields you updated). The listing is essentially forked.

Expected result:
When you change the slug of an existing listing, the slug is updated "in place" so that only the one listing remains, but with an updated slug.

**Comment by cpacia** [comment]
Let me know if we need to make any more changes
