### ISSUE TITLE
Impose a max length validation on the paymentAddress field in purchase

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#915]
We have no idea what format all the different payment addresses will be for different coins, so we can't make too small of a limit, but something reasonable should be put in to prevent something ridiculous like 10k chars in there.

**Comment by tyler-smith** [comment]
Using 256 bytes == 4096 bits.

**Comment by rmisio** [comment]
Does this work the same way as these max lengths?

https://github.com/OpenBazaar/openbazaar-go/blob/53451771b1b0d7771120fad770e09dba3a072606/core/listings.go#L28

I assumed those go by character count and not bytes? Was I wrong in that assumption?

**Comment by tyler-smith** [comment]
(discussed offline)

yes it's by character.

merged
