### ISSUE TITLE
https://docs.openbazaar.org/ certificate expired

### ISSUE THREAD

**Issue by Rushit** [OpenBazaar/openbazaar-go#927]
certificate on docs.openbazzar.org expired.

**Comment by Rushit** [comment]
<img width="1485" alt="screen shot 2018-04-22 at 9 29 05 am" src="https://user-images.githubusercontent.com/1387607/39097341-e2803050-460f-11e8-8d83-3f76ba371b27.png">

**Comment by BazaarDog** [comment]
Just a heads up @Rushit , the OpenBazaar 2.0 Docs are located at: https://api.openbazaar.org
