### ISSUE TITLE
Add Sweep Wallet API

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#929]
Currently is it very difficult to move all funds from the internal wallet to another address. To facilitate this, there should be an API to move all funds.

Suggestion:

Add a wallet/spendall endpoint that works similarly to the spend endpoint, but moves all funds, minus a fee, to the supplied address.

Data Sent:
```
{
  "feeLevel": "NORMAL",
  "memo": "move to personal wallet",
  "address": "tb1q2gzlqfs27al4087h56gg9pgza2l7fp0v7tl0llgd9agfhx6us8qs5ht6fw",
}
```

Data Received
```
{
  "amount": 27106,
  "confirmedBalance": 0,
  "memo": "move to personal wallet",
  "timestamp": "2018-04-19T15:16:18-04:00",
  "txid": "ee4f0bb4b405f17eeeb3e84aaf6bb02a13763cf87a71375f7d59ca5fe916a47d",
  "unconfirmedBalance": 0
}
```

The above is the same as the spend endpoint, but does not send an amount (since the amount is always all available funds).

**Comment by christroutner** [comment]
Love this idea.
