### ISSUE TITLE
Add Country Code to ShippingAddress 

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#93]
To determine if a user has an address that matches the countries a listing can ship to, we need to have the country code for each saved address of the user. 

Can we add a countryCode field (with a string type) to the ShippingAddress data?

**Comment by rmisio** [comment]
We also need to display a verbose country name, so since the existing country field is used for that, that's why we need a specific countryCode field.

**Comment by cpacia** [comment]
I'm not following. In the contract the country is displayed as a a string "UNITED_STATES". What would a country code field be used for?

**Comment by jjeffryes** [comment]
That's what I meant by country code. The string the server uses.

I'll close this, it's better if we store the server country code in the existing field, and then find the display name in the client so we can translate it.
