### ISSUE TITLE
Review not showing for Vendor if submitted after payment was finalized.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#955]
1. make a purchase
2. let the escrow timeout expire
3. have vendor claim funds
4. have buyer leave a review

Observed:
When the vendor fetches the order, it still has a PAYMENT_FINALIZED state and does not include the review.

Expected:
The state updates to COMPLETED and the contract is updated with a `buyerOrderCompletion` entry containing the review.

**Comment by cpacia** [comment]
Fixed in branch
