### ISSUE TITLE
buyerDisputeTimeout notifications should be ordered differently if they have the same timestamp

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#959]
The user periodically gets buyerDisputeTimeout notifications informing them of time remaining to dispute an order. If they are not online for a while they may come back and have multiple notifications created with the same timestamp. If the timestamps are the same, please sort those in ascending order based on the expiresIn field. (it's probably just a matter of switching the order they are inserted in the db in this case)

This is the current order:

```
    "notifications": [
        {
            "notification": {
                "expiresIn": 240,
                "notificationId": "QmcAwgpFhnfRJ4J41mtA1X7N2PdRC7vkQU3rEmQbwC9t95",
                "orderId": "QmfJ7fkUJEvxWkYizciNfHFBEqiu9wWFRZK8t3XiPVxD6E",
                "thumbnail": {
                    "small": "zb2rhX9dB3XnzMXcbTkzCHVerz1g1tTDu8veMTod3gKBv98RB",
                    "tiny": "zb2rhedegZXnGsbXLjB3WgKa6M2SquEdcxZ9jKXX7CBvw6BTB"
                },
                "type": "buyerDisputeTimeout"
            },
            "read": true,
            "timestamp": "2018-05-24T14:48:04-05:00",
            "type": "buyerDisputeTimeout"
        },
        {
            "notification": {
                "expiresIn": 120,
                "notificationId": "QmVLxmU6GCVnoSHCGGhuahbskJk33GWzNf9HBdAuzQxyHj",
                "orderId": "QmfJ7fkUJEvxWkYizciNfHFBEqiu9wWFRZK8t3XiPVxD6E",
                "thumbnail": {
                    "small": "zb2rhX9dB3XnzMXcbTkzCHVerz1g1tTDu8veMTod3gKBv98RB",
                    "tiny": "zb2rhedegZXnGsbXLjB3WgKa6M2SquEdcxZ9jKXX7CBvw6BTB"
                },
                "type": "buyerDisputeTimeout"
            },
            "read": true,
            "timestamp": "2018-05-24T14:48:04-05:00",
            "type": "buyerDisputeTimeout"
        },
        {
            "notification": {
                "expiresIn": 60,
                "notificationId": "QmfPxhP1h9yRyhfBxARiSBTCbUVt8cEu9Xi4uMMkggyxs8",
                "orderId": "QmfJ7fkUJEvxWkYizciNfHFBEqiu9wWFRZK8t3XiPVxD6E",
                "thumbnail": {
                    "small": "zb2rhX9dB3XnzMXcbTkzCHVerz1g1tTDu8veMTod3gKBv98RB",
                    "tiny": "zb2rhedegZXnGsbXLjB3WgKa6M2SquEdcxZ9jKXX7CBvw6BTB"
                },
                "type": "buyerDisputeTimeout"
            },
            "read": true,
            "timestamp": "2018-05-24T14:48:04-05:00",
            "type": "buyerDisputeTimeout"
        },
        {
            "notification": {
                "expiresIn": 0,
                "notificationId": "QmYFwNjnVDs6TN3ppNzydmvLkiuvLfbTR1q44zcQvoQ9J3",
                "orderId": "QmfJ7fkUJEvxWkYizciNfHFBEqiu9wWFRZK8t3XiPVxD6E",
                "thumbnail": {
                    "small": "zb2rhX9dB3XnzMXcbTkzCHVerz1g1tTDu8veMTod3gKBv98RB",
                    "tiny": "zb2rhedegZXnGsbXLjB3WgKa6M2SquEdcxZ9jKXX7CBvw6BTB"
                },
                "type": "buyerDisputeTimeout"
            },
            "read": true,
            "timestamp": "2018-05-24T14:48:04-05:00",
            "type": "buyerDisputeTimeout"
        },
```

Which is awkward because it results in your notification list looking like below, which doesn't match the sequence of the notifications if you were online when they came. In other words '4 minutes left' should have come before '2 minutes left' which should have come before 'a minute left', etc...

![image](https://user-images.githubusercontent.com/794517/40547954-f166200e-5ff8-11e8-801c-adf8ad6e9fe5.png)

**Comment by rmisio** [comment]
Actually, I've discovered what the issue is. The notifications are in insertion order in the database, but since they all have the exact same timestamp the query which fetches them sorted by timestamp does not return them in insertion order. It returns them in reverse insertion order which is contrary to how all the other notifications are returned and it messes up pagination via the offsetId parameter.

Would it be possible to make those timestamp unique (even by a fraction of a millisecond) and ensure they are returned in insertion order (e.g. expiresIn: 0, expiresIn: 60, expiresIn: 120, expiresIn: 240)?

**Comment by placer14** [comment]
I'd actually like to assert the order in the SQL query rather than depending on the sort order of a read or a write operation (and that order possibly changing since it's not guaranteed by any of the libraries we're using). At least SQL can guarantee a certain order. I'll get this done today.

**Comment by placer14** [comment]
@rmisio Please confirm this is fixed in your test branch.

**Comment by placer14** [comment]
@jjeffryes Yes, this is in master and should be fixed? Let me know if you still see problems.
