### ISSUE TITLE
Support Crypto Listing Markups

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#962]
## User Story
Support cryptocurrency listings having prices above or below the market rate.

### Listing API
- [x] Add a field for a price modifier ("priceModifier").
    - This field is only used for listings with type CRYPTOCURRENCY.
    - This field should have values between -99.99 and 1000.00, with two decimal places.
    - The actual value should be an integer. It represents a percentage between negative 99.99% (a discount) and 1000%.
    - The value should be validated to prevent discounts of 100% or more, or increases above 1000%.
    - The upper limit of 1000% is an arbitrary number, we can change it, presumably no one would successfully sell anything at a 10x markup.

### Listings API
- [x] Add in the acceptedCurrencies array so the client can determine what coin you are paying in (i.e. which coin you're trading for the coinType coin). (search already does this)
- [x] For cryptocurrency listings, add in the priceModifier field so the client can determine how to style the price.

### Sales, Purchases, and Cases APIs
- [x] Add the CoinType (the coin being sold) to these APIs so it can be displayed in the client.
- [x] Add the payment coin to these APIs as well. EDIT: remove incorrect note

**Comment by rmisio** [comment]
> The actual value should be an integer. It represents a percentage between negative 99.99% (a discount) and 1000%.

This is not correct. If we follow suit with other percentage fields, e.g. the ones used for coupons, it should be a float.

**Comment by rmisio** [comment]
> It's only strictly needed for the Cases API right now, but it would be best to add it to all three, so it's in place when we support multicoin wallets.

@jjeffryes Well for Sales it would be needed. For purchases, I suppose it could be inferred from the `cryptoCurrency` the current nodes wallet supports, but I totally agree with "it would be best to add it to all three, so it's in place when we support multicoin wallets".

**Comment by BazaarDog** [comment]
This can be accommodated by the existing price object. 

A 5% markup on coin ABC is is just 1 ABC for 1.05 ABC. The markup an UI and logic can be contained in the client.

**Comment by jjeffryes** [comment]
> This is not correct. If we follow suit with other percentage fields, e.g. like the ones used for coupons, it should be a float.

@cpacia @tyler-smith @mg would it be safe here to use a float like we do with coupons?

**Comment by placer14** [comment]
@jjeffryes IMO, keeping floats away when accuracy of value is important (like with prices) is a good policy in general since limits and edge cases are hard to reason about.

**Comment by jjeffryes** [comment]
> Well, for Sales it would be needed as well.

I thought it was already in the payments data, I should have double checked that. I've updated the issue.

**Comment by placer14** [comment]
@tyler-smith All done here?
