### ISSUE TITLE
Stuck funds when vendor is unresponsive and opened dispute is resolved 100% to buyer

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#973]
From reddit:
> I found a huge BUG. If you place an order and the vendor is inactive and he never accepts the order and you dispute it with a moderator and the moderator rules in your favor and returns your funds they will be stuck forever. On the "Summary" tab you are asked to write a review but if you do it produces an error because you never purchased the item. So your funds are stuck until you write a review. Please fix.

Source: https://www.reddit.com/r/OpenBazaar/comments/8g2ao4/openbazaar_20_megathread_post_bugs/e0iwqr0

**Comment by jjeffryes** [comment]
I have confirmed this issue, and can reproduce it on my own nodes.

**Comment by jjeffryes** [comment]
This is the scenario I see:
1. Buyer makes a purchase when the seller is offline.
2. Buyer disputes the purchase.
3. The moderator resolves the dispute 100% in favor of the buyer.
4. The buyer accepts the resolution.
5. When the buyer attempts to complete the order, the server returns a 500 error with `"Cannot leave review because the vendor never accepted this order"`

**Comment by hoffmabc** [comment]
Ok guys this one is getting stale. Let's at least make a decision about how we'll address this. I think personally it makes most sense to do as @placer14 suggested in Slack, which is to allow the moderator reward the present party 100% and then proceed as normal. Any other distribution should be impossible since the other contract is not present.

**Comment by placer14** [comment]
This is more to do with the completion of the "decided dispute". I'm not familiar enough to know why a completion is necessary after the dispute is awarded and accepted by the buyer.

**Comment by rmisio** [comment]
@jjeffryes Trying to figure out if this bug is an issue of just the completion failing or also of stuck funds. The latter would be much more severe.

> 4. The buyer accepts the resolution.

That should have been enough to get them the funds. Do you know if it was?

**Comment by rmisio** [comment]
> When the buyer attempts to complete the order, the server returns a 500 error with "Cannot leave review because the vendor never accepted this order"

If that's the only bug, it seems like it's working as the server dev intended. Now if we want a different UX there - if it's critical that the buyer be able to leave a review, then I guess we could prioritize.

**Comment by hoffmabc** [comment]
@cpacia can you please help @placer14 come up with an approach for solving this since offline messages are inconsistent on local instances for him?

**Comment by placer14** [comment]
So here's the fallout. The buyer DOES get their funds as soon as they accept the resolution from the moderator. Unfortunately, the buyer will NEVER be able to close the order as the vendor never sends the contract. Presumably (speculation) because the order has progressed past the state where the vendor node would normally transmit it's copy of the contract and never has the opportunity to.

Not sure what actionable there is from this but my thoughts are:
- Could the frontend prevent the case showing the review screen if the buyer's order is unreviewable due to the missing vendor contract?
- Should the server progress the order to Complete after the funds are accepted but a vendor contract is missing?
- Should the vendor transmit the contract to the other parties despite being in the wrong state yet it detects a Dispute present on the Order?

This is definitely a lower priority as we're only dealing with stuck orders and funds are moving as expected. Thoughts on how to proceed based on this knowledge?

**Comment by placer14** [comment]
A short discussion with the team later, @cpacia and @rmisio agree that given that no ones funds are actually confirmed to be stuck and it's just a matter of some orders remaining in a weird state.

Some observations:
- the vendor does not transmit their contract to the other parties as a result of this flow
- the buyer does not get a formal indicator that the funds were returned to their internal wallet when accepting the resolution and processing to the order completion view (to leave a review and complete).
- the state of the order for the buyer and vendor are both inconsistent in state on the UI.
