### ISSUE TITLE
Encrypt outgoing online messages (two-layer encryption)

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#98]
(This issue was discussed with @cpacia during the OpenBazaar Partners Call on Thursday August 25.)

Duo Search wants to proxy OpenBazaar orders (and other similar p2p messages) from a buyer visiting www.duosear.ch to a vendor's node, without Duo Search knowing the contents of the message (to preserve privacy). At the moment there is a single TLS-like layer of encryption between two nodes for outgoing online messages, as shown in Diagram 1:

```
Diagram 1
*********

         TLS
 Buyer <-----> Vendor
(node)         (node)
```

To allow for proxying of p2p messages while preserving privacy, we suggest adding a second layer of AES encryption similar to what already exists for offline messages (see [`SendOfflineMessage`](https://github.com/OpenBazaar/openbazaar-go/blob/a6b7a36706786aa5d8a9beec193c7583dc935480/core/net.go#L22)): 

```
ciphertext, cerr := n.EncryptMessage(p, messageBytes)
```

(As stated in [a comment](https://github.com/OpenBazaar/openbazaar-go/blob/a6b7a36706786aa5d8a9beec193c7583dc935480/core/core.go#L104) for the function `EncryptMessage`: `encrypt outgoing offline messages with the long lived identity key`. We suggest generalising that encryption to online messages.)

The second layer of AES encryption for outgoing online messages allows for the setup as shown in Diagram 2:

```
Diagram 2
*********

                     AES
      <------------------------------>
           TLS                TLS
  Buyer  <-----> Duo Search <-----> Vendor
(browser)          (node)           (node)
```

As can be seen in Diagram 2, the AES encryption is _end-to-end_, overarching the whole path from buyer to vendor, including the two TLS hops. In this setup, the AES encryption (and decryption) is _client-side_ in the buyer's browser using JavaScript, similar to what Blockchain.info does for its wallet. Here the Duo Search node is a dumb proxy of AES encrypted messages.

(Incidentally, having AES for both outgoing online and offline messages makes the code neater and more consistent.)

Comments and questions welcome; cc @hoffmabc @tyler-smith

**Comment by duosearch** [comment]
I'm curious as to what version of TLS is used, as there is a JavaScript library that supports TLS 1.0 and TLS 1.1 but not TLS 1.2.

https://github.com/digitalbazaar/forge/issues/404

**Comment by cpacia** [comment]
I don't think it's actually but a custom tls-like protocol. As far as i know the code is in the libp2p package. They do plan to have a javascript version but I'm not sure the state of it.

**Comment by JustinDrake** [comment]
(For future reference, this is the libp2p JavaScript library for the custom TLS-like protocol https://github.com/libp2p/js-libp2p-secio/tree/master/src.)

**Comment by JustinDrake** [comment]
I'd like to discuss this during the technical hangout tomorrow.

**Comment by JustinDrake** [comment]
#243 does it
