### ISSUE TITLE
Validate that vendor listing's `escrowTimeoutHours` >= buyer's locally expected `escrowTimeoutHours`

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#984]
- As a buyer, I want to ensure that `escrowTimeoutHours` is an acceptable value by having the node validate the value as part of the Listing's regular validation items and should return an error when the value is less than expected.

Implementation details are to be determined.

**Comment by placer14** [comment]
We do have some protections around this value. We currently check to make sure the value equals what is locally expected. On the buyer side, this check is performed at the time we estimate the order total for fees and again at the time of purchase contract is sent. On the vendor side, this check is performed at the time the listing is signed. Is this sufficient?

The actual check: https://github.com/OpenBazaar/openbazaar-go/blob/5f4b9776dc172dd87b5985661b3c1f49285018d7/core/listings.go#L859

Verification on the Buyer side:
https://github.com/OpenBazaar/openbazaar-go/blob/5f4b9776dc172dd87b5985661b3c1f49285018d7/core/order.go#L558

Verification on the Vendor side:
https://github.com/OpenBazaar/openbazaar-go/blob/5f4b9776dc172dd87b5985661b3c1f49285018d7/core/listings.go#L143

**Comment by tyler-smith** [comment]
Those checks look sufficient to me.

**Comment by placer14** [comment]
Thanks. @tyler-smith
