### ISSUE TITLE
Tor integration

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#99]
As of August 26, the `openbazaar-go` codebase doesn't seem to have code for Tor integration. The intent of this issue is to push forward discussion about Tor integration, as this one of the most requested features for OpenBazaar. I'll start with a couple questions:
1. Is Tor integration planned for the OB2.0 initial release?
2. I tried to find a Tor library in Go but couldn't find anything satisfactory. Which Tor library is planned to be used for the integration?

**Comment by tyler-smith** [comment]
TOR support will come from a TOR transport for IPFS which needs to be written. There is an issue for it here: https://github.com/ipfs/notes/issues/37

There's not much happening with it. If anybody was interested in working on one it would be a great way to contribute to OB IMO.

**Comment by cpacia** [comment]
It should probably:
1) Detect if tor is running by querying the control port
2) If it's running and tor hasn't been set in the config
      2a) stop initialization and ask them if they want to use tor.
      2b) if so, configure tor and proceed with startup. 

It should also have the option to run in onion only mode or dual stack mode.

**Comment by cpacia** [comment]
Here's a guid to implementing another transport https://github.com/ipfs/examples/blob/bdfef47c851cdb5c41a32af80ec4d7cd0587fa49/examples/transport/readme.md

**Comment by cpacia** [comment]
Ideally we should be able to make it also use the socks proxy to connect to clearnet nodes via Tor. That might be more complicated as I think we'd have to modify the libp2p dialer. On the other hand, I'm not sure if that functionality will be desired. Connection only to onion or dual-stack nodes from Tor is probably sufficient.

**Comment by cpacia** [comment]
Another requirement for this should be a full node wallet implementation. The spv wallet likely leaks more private data than a Tor user would find acceptable. This would require a wallet implementation that either connects to bitcoind or packages btcd as an alternative.

**Comment by OstrichEgg** [comment]
I just created a $100 (USD) bounty for the solving of this issue (i.e. integration of Tor into openbazaar-go).
https://www.bountysource.com/issues/37322830-tor-integration

**Comment by cpacia** [comment]
I have it roughly working here https://github.com/cpacia/openbazaar-go/tree/tor 

But i'm waiting for IPFS 0.4.5 because I integrate it because there were tons of dependency issues that I had to manually fix that will probably be fixed in 0.4.5

**Comment by OstrichEgg** [comment]
@cpacia , Glad to hear it! I think Bountysource automatically dispenses the bounty when its bots detect that the open issue has been officially marked as Resolved to the dev whose pull request resulted in the completion of the issue.

**Comment by cpacia** [comment]
PR #342

**Comment by OstrichEgg** [comment]
cpacia, once your PR is accepted and issue is closed, follow my earlier link to claim the bounty.
